### ISSUE TITLE
Include flow-typed for native dependencies in ./app

### ISSUE THREAD

**Issue by gabriel** [electron-react-boilerplate/electron-react-boilerplate#1407]
The flow-typed install doesn't include native dependencies in ./app.

Would it be possible to add a flow-typed script to `app/package.json` and run it via `npm install`?

```json
{
  "name": "electron-react-boilerplate",
  "productName": "electron-react-boilerplate",
  "version": "1.0.0",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
  "main": "./main.prod.js",
  "author": {
    "name": "C. T. Lin",
    "email": "chentsulin@gmail.com",
    "url": "https://github.com/chentsulin"
  },
  "scripts": {
    "electron-rebuild": "node -r babel-register ../internals/scripts/ElectronRebuild.js",
    "flow-typed": "rimraf flow-typed/npm && flow-typed install --overwrite || true",
    "postinstall": "npm run flow-typed && npm run electron-rebuild"
  },
  "license": "MIT",
  "devDependencies": {
    "flow-bin": "^0.64.0",
    "flow-typed": "^2.3.0"
  },
  "dependencies": {
    "grpc": "^1.8.4",
    "react-native": "^0.52.1"
  }
}
```

If I `npm run flow-typed` here from app directory it puts the native dependency flow definitions in ../flow-typed, but am not sure about the proper way to call this from the root package.json.

**Comment by gabriel** [comment]
Also, should we add `<PROJECT_ROOT>/app/node_modules/*` to `./flowconfig` `[ignore]`, otherwise flow is trying to evaluate app/node_modules.

Maybe should include a native module (something simple?) in the boilerplate to test this all?

**Comment by amilajack** [comment]
I'd love a PR for that 😄
