### ISSUE TITLE
Better way to package and distribute boilerplate

### ISSUE THREAD

**Issue by yeskunall** [electron-react-boilerplate/electron-react-boilerplate#1421]
I love the work done so far to build and maintain this boilerplate. git (v >= 1.9) complains when cloning a shallow copy of this repo, then changing the remote URL and then proceeding to push to the updated remote. This means if I were to use this boilerplate for my own project I would

- either need to keep the commit history of this repo and build on top of it
- remove the `.git` folder and `git init` myself and push the new changes
- ZIP download the contents, and then go a similar route as the one above

... I don't really like either 😅

I was wondering if there is a way to package and distribute this boilerplate, much like an `npm` package?

Thanks for all the hard work! 💖

**Comment by amilajack** [comment]
That would definitely be a *huge* migration and I'm not sure if I have the time to make those kind of changes now. I think a good solution for now would be fixing the shallow cloning issue. Maybe in the future we can focus on distributing ERB as an npm module

**Comment by yeskunall** [comment]
I fully understand that 😅thanks for being open to the idea &mdash; even if it's not viable in the near future! @amilajack

**Comment by talha131** [comment]
@yeskunall 

You probably already know it. 

> then changing the remote URL and then proceeding to push to the updated remote.

What I do is to have at least two remotes.

1. Boilerplate upstream
1. My project upstream

I keep merging changes from boilerplate upstream time to time. If need be, I reduce commit pollution by squashing all upstream changes into one commit.

If you maintain two or more remotes, and squash commits, then you don't need to

> remove the .git folder and git init myself and push the new changes

**Comment by davidwinter** [comment]
@talha131 could you please share your workflow for the two remotes, where you squash the incoming commits, so you're then able to push?

I originally did a shallow clone of this repo, then started working on my app. Then attempted to push to Github and encountered the error about shallow clones. So I then fetched all of the commits from this repo using the `--unshallow`, so now a `git log` will display all commits. I _could_ push to Github now but I want to try and keep my history clean with only my commits, while still being able to squash and merge in future changes from this repo in the future.

Can anyone advise how I could squash the commits from this repo that now exist before the work and commits I have made?

And also, how I could squash and merge commits from this repo in the future? I have an `origin` remote for Github where I'd like to push to my repo, and another called `bootstrap` which is a reference to this repo.

**Comment by syddo** [comment]
I'm not sure if this will be an acceptable alternative but in my case I did:

```bash
git remote remove origin
git rev-parse --verify master >> .git/info/grafts
git filter-branch -- --all
rm .git/shallow
git remote add origin <new-git-repo-url>
git push origin master
```

It worked okay and started a new git project.
