### ISSUE TITLE
jest cannot test files that import native modules

### ISSUE THREAD

**Issue by asmallfurrywombat** [electron-react-boilerplate/electron-react-boilerplate#1465]
I'm integrating some unit tests which use a native module called 'instauuid'. The boilerplate directed me to register it in app/package.json. When i run 'npm test', I get the following error:
```
    ● Test suite failed to run
        Cannot find module './build/Release/generator' from 'index.js'
          at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:194:17)
          at Object.<anonymous> (app/node_modules/instauuid/index.js:4:17)
```
At <rootNode>/app/node_modules/instauuid/index.js(4):
```
    var generator = require('./build/Release/generator');
```
<rootNode>/app/node_modules/instauuid/build/Release/generator.node is the only file in the directory which appears to look like it might be a 'generator'.

I think a jest moduleNameMapper entry in package.json might work, but so far it's resisting my efforts. Any ideas appreciated!

**Comment by joelgetaction** [comment]
I'm also seeing this.  I'm trying to test a file that imports `NativeModules` and uses some constants defined on the native side but I get `TypeError: Cannot read property 'foo' of undefined` which is just wrong since the same code works perfectly fine in an RN app running on device and on simulator.  And these aren't some constants that depend on iOS hardware, they're just strings ...

**Comment by HyperSprite** [comment]
I use `fs-extra` all over the place and don't have any issues. 

Meanwhile, my stuff is a fork from ERB v13 and way off in the weeds at this point but this might help someone ....

I needed to run tests on native modules for SQLite/Sequelize with a dynamic db file and ran into issues. I ended up moving the jest config into a `jest.config.js` file and moving my `.spec.js` files to live with what they are testing.
Also added a package to the main `package.json` file called @jest-runner/electron/environment

jest.config.js
```js
module.exports = {
  projects: [
    {
      displayName: 'client',
      testMatch: ['<rootDir>/app/client/**/*.spec.js'],
      setupFiles: ['./.enzyme'],
    },
    {
      displayName: 'db',
      runner: '@jest-runner/electron',
      testEnvironment: '@jest-runner/electron/environment',
      testMatch: ['<rootDir>/app/db/**/*.spec.js'],
    },
    {
      displayName: 'e2e',
      testMatch: ['<rootDir>/test/e2e/**/*.spec.js'],
    },
  ],
  testURL: 'http://localhost/',
  moduleNameMapper: {
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/internals/mocks/fileMock.js',
    '\\.(css|less|sass|scss)$': 'identity-obj-proxy',
  },
  moduleFileExtensions: ['js'],
  moduleDirectories: ['node_modules', 'app/node_modules'],
  transform: {
    '^.+\\.js$': 'babel-jest',
  },
  collectCoverage: true,
};
```
