### ISSUE TITLE
add support for jest + enzyme + snapshot testing

### ISSUE THREAD

**Issue by goldylucks** [electron-react-boilerplate/electron-react-boilerplate#1519]
I have this working on my project, should I prepare a PR with the setup running and docs?

**Comment by talmukund** [comment]
@goldylucks I believe same is already implemented in Master branch. 
`import { spy } from 'sinon';
import React from 'react';
import Enzyme, { shallow } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { BrowserRouter as Router } from 'react-router-dom';
import renderer from 'react-test-renderer';
import Counter from '../../app/components/Counter';

Enzyme.configure({ adapter: new Adapter() });

function setup() {
  const actions = {
    increment: spy(),
    incrementIfOdd: spy(),
    incrementAsync: spy(),
    decrement: spy()
  };
  const component = shallow(<Counter counter={1} {...actions} />);
  return {
    component,
    actions,
    buttons: component.find('button'),
    p: component.find('.counter')
  };
}
`

**Comment by goldylucks** [comment]
Indeed.

In our project we implemented the following:

``` 
// package.json.jest
"setupTestFrameworkScriptFile": "./test/jestSetup.js",
"snapshotSerializers": ["enzyme-to-json/serializer"],

// ./test/jestSetup.js
import Enzyme from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'

Enzyme.configure({ adapter: new Adapter() })

// Loading.spec.js
import React from 'react'
import { mount } from 'enzyme'

import Loading from './Loading'
import { load } from './LoadingUtil'

jest.mock('./LoadingUtil', () => ({
  load: jest.fn(),
}))


describe('Loading', () => {
  const component = mount(<Loading />)
  it('should render Loading', () => {
    expect(true).toBe(true)
    expect(load).toHaveBeenCalled() // no need to use sinon, use jest mocking
    expect(component).toMatchSnapshot() // No need to call .toJSON(), handled by enzyme-to-json/serializer
  })
})

```

Thoughts on this?

Also, we are storing the tests inside the folder with the related code itself, altho that's our convention/style, matter of preference. But I had to make some changes to `RunTests.js` and `package.json` to make it work.

**Comment by amilajack** [comment]
👍 yup, please send a PR that
