### ISSUE TITLE
PR: Crash Reporting Support

### ISSUE THREAD

**Issue by goldylucks** [electron-react-boilerplate/electron-react-boilerplate#1593]
how about adding a `utils/crashReporting.js` file, something like ..

```
import pjson from '../../package.json'

export defulat init

function init() {
  crashReporter.start({
    productName: 'PRODUCT_NAME_HERE',
    companyName: 'COMPANY_NAME_HERE',
    submitURL: 'SERVER_ENDPOINT_HERE,
    uploadToServer: true,
    extra: {
      NODE_ENV: process.env.NODE_ENV,
      appVersion: pjson.version,
    },
  })
}
```

and then in the docs some reference on how to use it and maybe links to popular crash SAASs.

Can even use affiliate links and maybe make some :moneybag: ;)

I can prepare a PR

**Comment by amilajack** [comment]
A PR for this would be awesome

**Comment by goldylucks** [comment]
@amilajack do you have any experience implementing error reporting in electron app?

I'm going thru it now, I have a flow working, with support for the user to opt in and out of reporting errors to the server.

I can submit my progress so far, but, I haven't found any A-Z good tutorial for handling electron errors. Do you have any recommendations?

I'm trying out [backtrace](https://backtrace.io/) as a service at the moment btw.

**Comment by amilajack** [comment]
Unfortunately I don't. A PR for that would be awesome

**Comment by talha131** [comment]
> A PR for handling errors in a general way would be awesome.

Or a walk through or guideline in the wiki, if a general way is not possible.

**Comment by goldylucks** [comment]
@amilajack news on this?

**Comment by amilajack** [comment]
let's move this to the docs and create a guide out of this
