### ISSUE TITLE
release script

### ISSUE THREAD

**Issue by goldylucks** [electron-react-boilerplate/electron-react-boilerplate#1642]
since we have two `package.json` and `app/package.json` files, we can't use a ready made solution.

@amilajack do you use any script for your projects? Ideally we could something like ...
```
$ npm run release
# or
$ npm run release --minor # or --major or --patch
```

and that will:
1. bump versions on both package files
1. maybe also run npm install to update the package-lock.json files?
1. make a commit
1. make git tag
1. push commit and tags
1. travis will then start a release

Also might consider having support for github releases, draft/production/pre-release

Thoughts?

**Comment by amilajack** [comment]
Something like that would be awesome. Unfortunately  I dont even have anything like that for my personal projects. If I had more time i would implement something like that. I'd base it off of [np](https://github.com/sindresorhus/np)

**Comment by amilajack** [comment]
lets move this to the `erb-cli` repo. Please create an RFC there
