### ISSUE TITLE
How can you enable debugging for main process - for a built app.?

### ISSUE THREAD

**Issue by yanivkalfa** [electron-react-boilerplate/electron-react-boilerplate#1648]
I've been using this boilerplate for 2 projects so far, lately i am running into errors in main process only in the built app.
when running `npm run dev` it works fine.
My question is: how can i enabled debugging for main process on a built app.

Update: 
For now i am just logging to file to debug - but there should be a real solution.

**Comment by jsrhome** [comment]
I haven't tried this myself, but the electron site has this advice:

[https://electronjs.org/docs/tutorial/debugging-main-process](url)

**Comment by yanivkalfa** [comment]
I've also tried that, couldnt run electron from this bootstrap without the dist folder.

I ended up just logging into a file.

**Comment by davidwinter** [comment]
I added Sentry to the production build of my applications to report exceptions, for both the main process and the renderer.

**Comment by yanivkalfa** [comment]
@davidwinter How do you use it ?

**Comment by yanivkalfa** [comment]
@davidwinter yea, i am familiar with such tools winstone and logger also does the same thing i thought there's something simpler in electron.

I have my own solution that will not send requests with the error to a 3rd part - i simply log the error/info to a file

**Comment by basiclaser** [comment]
> @yanivkalfa I added `@sentry/electron` to my `app/package.json` file - it had to be this one or I'd receive errors from the root `package.json` file.
> 
> Then in my `main.dev.js` and `index.js` files, have something like this as close to the top of each file as possible, so that it can catch exceptions as early on as possible:
> 
> ```
> import * as sentry from '@sentry/electron';
> 
> if (process.env.NODE_ENV === 'production') {
>   sentry.init({
>     dsn: 'https://abcdefg1234@sentry.io/1234567'
>   });
> }
> ```
> 
> Obviously updating the `dsn` value with your own.
> 
> Then if exceptions happen, they appear in the Sentry web app.

is that still working for you? im trying to piece this together but not sure what goes where. im not sure how to install the sentry package. did you run `yarn add @sentry/electron`in the build/app folder?

**Comment by jgresham** [comment]
`@sentry/electron` in the next release should work with ERB. See https://github.com/getsentry/sentry-electron/issues/445/
