### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by vikr01** [electron-react-boilerplate/electron-react-boilerplate#1689]
Using ERB in a subdirectory will cause problems when its `node_modules` are hoisted. (#1639) The current workaround is to [avoid hoisting its dependencies](https://yarnpkg.com/blog/2018/02/15/nohoist/), but this isn't ideal in the long run.

Areas causing problems:
- [x] `CheckNativeDep.js` checking node_modules in [current working directory](https://github.com/chentsulin/electron-react-boilerplate/blob/master/internals/scripts/CheckNativeDep.js#L12)
  - Fixed in #1854
- [x] Certain scripts in `package.json` expecting `node_modules` to be in the current working directory (i.e. [`./node_modules/webpack/bin/webpack`](https://github.com/chentsulin/electron-react-boilerplate/blob/master/package.json#L8)).
  - Fixed build scripts in #1827 
  - Fixed lint script in #1746

Possible solutions:
- `webpack.config.*.babel.js`
- `require.resolve`
- `npm root`

**Comment by rntjr** [comment]
project supports monorepo in release 1.3.0?
