### ISSUE TITLE
electron build with flash  by  electron-builder problem    mac  mac  mac

### ISSUE THREAD

**Issue by spcBackToLife** [electron-react-boilerplate/electron-react-boilerplate#1696]
I wrote an app with this, it's a browser. when i used `npm run dev`, it can show the flash in website well, but when i builded this, it didn't work. I had to fix it, including reading the guide of electron-builder,and visiting the stackoverflow,but it still couldn't be solved. I really need your help!!!!!!!!!  
   here is my file and package.json
![image](https://user-images.githubusercontent.com/20703494/44019276-dd12466c-9f10-11e8-9abc-274b5555625e.png)
![image](https://user-images.githubusercontent.com/20703494/44019335-01535afc-9f11-11e8-93ee-6300a5484b8b.png)
the second picture means 'cannot load this plugin'
so is there anyone can tell me how to solve this 0.0.

**Comment by amilajack** [comment]
Adding flash is not recommended. You'll find it very hard to find good documentation for this. What is your reason for using flash?

**Comment by spcBackToLife** [comment]
@amilajack  i want to write a browser which is depended on electron, and I want it to support flash. It feels not so good when users need to install flash in addition.  so is there any good way to solve this problem(flash has been installed and can work after app was builded)?

**Comment by spcBackToLife** [comment]
@amilajack  i solved this problem ,because of the path of publicPath in render.prod.js,just like this
```
  output: {
    path: path.join(__dirname, 'app'),
    publicPath: './',
    filename: 'renderer.prod.js'
  },
```

**Comment by amilajack** [comment]
Find something other than flash. it's slow and insecure
