### ISSUE TITLE
how to combine redux-persist ?

### ISSUE THREAD

**Issue by tiennguyen9988** [electron-react-boilerplate/electron-react-boilerplate#1725]
I want save lastest status of redux state when close app and reuse it when reopen app. In react-native app i was using redux-persist for this issue. So with react - electron can i using redux-persist or everything else?
Thank you!

**Comment by kingpalethe** [comment]
I'm finding this to be exceptionally challenging, too. Here is a rejected pull request on that, but the code is out of date with the current version of redux-persist:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1116/files

This issue also provides some hints

https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1392

But that code is also out of date with the latest version of redux-persist.

There are some docs on redux-persist including how to integrate with Hot Module Reloading...

https://github.com/rt2zz/redux-persist/tree/master/docs

But it's out of my league. Has anyone recently successfully found a persistence strategy for use with electron-react-boilerplate?

**Comment by amilajack** [comment]
I have created an example here: https://github.com/amilajack/erb-redux-persist-example

**Comment by amilajack** [comment]
Ahh right. I'll start adding examples under there and migrating my examples there. Good call
