### ISSUE TITLE
When adding dependency using commit hash "ERROR in dll renderer: Module not found "

### ISSUE THREAD

**Issue by fc** [electron-react-boilerplate/electron-react-boilerplate#1752]
Run the following commands:
```
git clone https://github.com/chentsulin/electron-react-boilerplate.git
cd electron-react-boilerplate
yarn
yarn add react-map-gl@git+https://github.com/fc/react-map-gl.git#95e1623af9abd90eb148474a63436305a972b3b4
```

Then, it results in the following output:
```
ERROR in dll renderer
Module not found: Error: Can't resolve 'react-map-gl' in '/some/folder/here'
 @ dll renderer renderer[9]
```

**Comment by dbvrac** [comment]
Did you ever figure this out? I'm pretty new to a lot of these tools, but I'm experiencing the same issue. The package does appear in `node_modules/`, but the install script just stops at this error and `app/node_modules` doesn't build. [This thread](https://github.com/webpack/webpack/issues/6858) suggests it's a path issue with Webpack, but I'm still digesting it.

**Comment by fc** [comment]
@dbvrac I found a way to achieve what I wanted without using the commit hash... so, nope.

**Comment by dbvrac** [comment]
@fc How did you do it?
I've tried it a few ways without using the commit hash, to no avail.
I'm still using v0.13.3 though. I'm working on refactoring for v0.14.0 right now.

**Comment by fc** [comment]
I should have clarified: I did not actually solve it.  I used a different library that would require me to not use a hash at all.

But I just poked into it again (still did not fix it).

The boiler plate creates a dll at `configs/webpack.config.renderer.dev.dll.js`and in the `dll` folder it appears to create these 2 files:
```
renderer.dev.dll.js
renderer.json
```

Anyway... I just found hints of what I think the problem is but no resolution but maybe that is enough for you to follow the trail to figure out what is happening?

`configs/webpack.config.renderer.dev.dll.js` uses dependecies from package.json to create the dependencies for the renderer.  Here is a trace statement of the `dependencies` variable
```
$ cross-env NODE_ENV=development node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config ./configs/webpack.config.renderer.dev.dll.js --colors
{ '@fortawesome/fontawesome-free': '^5.2.0',
  devtron: '^1.4.0',
  'electron-debug': '^2.0.0',
  history: '^4.7.2',
  react: '^16.4.1',
  'react-dom': '^16.4.1',
  'react-hot-loader': '^4.3.4',
  'react-map-gl':   'fc/react-map-gl.git#95e1623af9abd90eb148474a63436305a972b3b4',
  'react-redux': '^5.0.7',
  'react-router': '^4.3.1',
  'react-router-dom': '^4.3.1',
  redux: '^4.0.0',
  'redux-thunk': '^2.3.0',
  'source-map-support': '^0.5.6' }
```

So it does get react-map-gl but there is a problem with webpack.config.renderer.dev.dll.js or maybe webpack.config.renderer.dev.js.

It might be helpful to read up on the docs of the webpack DLL plugin (maybe related to that?).

These are just stabs in the dark but maybe in the right direction

**Comment by scopsy** [comment]
Removing node_modules and re-installing again fixed the issue o.0

**Comment by shunmian** [comment]
experience the same error when using module with `https://github.com/username/onerepo#v0.0.42`
