### ISSUE TITLE
image in main process create a crash when in production 

### ISSUE THREAD

**Issue by nanjixiong218** [electron-react-boilerplate/electron-react-boilerplate#1753]
node : 10.9.0
os: mac

I have new Tray in main process, it worked well in development, bug after packaged,  it did not work, just silent。

i think it is the problem of image, i have read the related issue of #612, #250 ,#129,  but it does not work for me.

this is my project : https://github.com/nanjixiong218/MyHost/blob/master/app/main.dev.js#L112 , please have a look ,thank you !

**Comment by vikr01** [comment]
Not necessarily an error but you should use `require.resolve` instead of `path`. This will throw an error if the file is not found -- `path` will not.

```javascript
require.resolve('../resources/host16x16.png')
```

**Comment by amilajack** [comment]
Please use the issue template

**Comment by Noitidart** [comment]
Were you able to solve this @nanjixiong218 I'm having same problem.

**Comment by dugiwarc** [comment]
Have you guys sorted this one out?
