### ISSUE TITLE
Failed to pack Win32

### ISSUE THREAD

**Issue by uuswyf** [electron-react-boilerplate/electron-react-boilerplate#1768]
• electron-builder version=20.28.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.8 appOutDir=release\win-unpacked
  • cannot unpack electron zip file, will be re-downloaded error=zip: not a valid zip file
  ⨯ zip: not a valid zip file

**Comment by amilajack** [comment]
Is this a fresh clone of the boilerplate?
