### ISSUE TITLE
Error: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by andreperegrina** [electron-react-boilerplate/electron-react-boilerplate#1782]
I'm getting this error. 
```
Uncaught TypeError: Super expression must either be null or a function, not undefined
    at renderer.prod.js:71
    at renderer.prod.js:71
    at renderer.prod.js:71
    at Object../node_modules/react-dates/lib/components/CalendarDay.js (renderer.prod.js:63)
    at n (renderer.prod.js:1)
    at Object../node_modules/react-dates/lib/index.js (renderer.prod.js:63)
    at n (renderer.prod.js:1)
    at Object../node_modules/react-dates/index.js (renderer.prod.js:63)
```
It seems to be react-dates the problem, but all the app it's not working, it's just a blank page.
This just happen when I run the `yarn package`

Did anyone have the same problem?

**Comment by danjumamilhaus** [comment]
@amilajack Has this been solved? Also having this issue in a production environment.

**Comment by amilajack** [comment]
I closed it because it was a react-dates specific problem. If you think this is an issue that is not related to the bolierplate then please create an issue following the issue template and i will investigate
