### ISSUE TITLE
"DEBUG_PROD=true" error

### ISSUE THREAD

**Issue by itbeckham7** [electron-react-boilerplate/electron-react-boilerplate#1783]
I have some problem with yarn package.
i am using latest electron-react-boilerplate version on windows10.
this is my error

PS M:\alden> DEBUG_PROD=true yarn package
DEBUG_PROD=true : The term 'DEBUG_PROD=true' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ DEBUG_PROD=true yarn package
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (DEBUG_PROD=true:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Please help me. how can i solve it?

**Comment by vikr01** [comment]
Your OS probably doesn’t set environment variables that way. Try `yarn cross-env DEBUG_PROD=true yarn run package`

**Comment by itbeckham7** [comment]
hello, vikro1. thanks for your quick response.
there are no errors with your command.
btw, i am going to use debug window with production exe file.
after packaging and running exe file. i can't see debug window(F12). 
how can i use it?

**Comment by johisco** [comment]
Solved my issue with package, installed in the top level package.json and then it worked. Still interested to know how to work with DEBUG_PROD tho.
