### ISSUE TITLE
WARNING: Textured window <EventDispatchingWindow: 0x7fcc938537d0> is getting an implicitly transparent titlebar.

### ISSUE THREAD

**Issue by dbvrac** [electron-react-boilerplate/electron-react-boilerplate#1794]
Fresh clone of the project
MacOS 10.13.6
yarn 1.9.4 (installed with npm i -g yarn)
npm 6.2.0
node 10.8.0
`yarn install` Seems to work ok, with two warnings:
`warning " > eslint-config-airbnb@17.0.0" has incorrect peer dependency "eslint@^4.19.1".`
`warning "eslint-config-airbnb > eslint-config-airbnb-base@13.0.0" has incorrect peer dependency "eslint@^4.19.1".`

`yarn dev` starts the project, and everything seems to work, but DevTools opens in an external window.
Terminal output:
`2018-09-19 20:25:47.060 Electron[3579:70141] *** WARNING: Textured window <EventDispatchingWindow: 0x7feec6930560> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`
`2018-09-19 20:25:47.780 Electron Helper[3584:70230] Couldn't set selectedTextBackgroundColor from default ()`

Same output with `UPGRADE_EXTENSIONS=1 yarn run dev`
`yarn run electron-rebuild` doesn't seem to change anything, either.
`DEBUG_PROD=true yarn run start` behaves the same way.

Here's the strange part - it seems that all of my projects based on this boilerplate are now misbehaving in different ways, and I can't reproduce this on another machine (Mac or Linux). I'm getting the same behavior from my IDE (WebStorm) and the Mac Terminal.

**Comment by suyanzhi** [comment]
Have you solved this problem?Electron[3579:70141] *** WARNING: Textured window <EventDispatchingWindow: 0x7feec6930560> is getting an...

**Comment by amilajack** [comment]
This is on electron's side. Not an issue with the boilerplate

**Comment by cmontois** [comment]
Has anyone figured out a solution to this problem ?

**Comment by aguynamedben** [comment]
Ahhh, no but have not tried. Super annoying message every time I start my app! Looks like the "best" error in Electron is this one: https://github.com/electron/electron/issues/11150. It was closed as fixed but many people are still reporting it happening.
