### ISSUE TITLE
Vscode. Debug react code

### ISSUE THREAD

**Issue by xahon** [electron-react-boilerplate/electron-react-boilerplate#1807]
What `launch.json` config can I use to debug react code?

**Comment by amilajack** [comment]
See
https://github.com/chentsulin/electron-react-boilerplate/issues/528
https://github.com/chentsulin/electron-react-boilerplate/issues/428

**Comment by amilajack** [comment]
Will reopen if these solutions don't work for you

**Comment by Unforgiven-wanda** [comment]
Hello @amilajack
Both the issues you linked deal with debugging the main process, as where I believe his question (and mine actually) is about the renderer process. What's more I haven't had any luck myself with any of the suggested solutions.
Is there no way at the moment to debug the renderer process of this boilerplate through VSCode?

**Comment by amilajack** [comment]
I don't think so. I will need to investigate this again

**Comment by PitterL** [comment]
Why not offer the launch.json in project? We used the default launch.json of electron-quick-start, it's not worked for current project. And the discussed  in ticket #528 #428 also not working. Any help will be appreciated.
