### ISSUE TITLE
Sqlite file in production

### ISSUE THREAD

**Issue by cvalenzuela** [electron-react-boilerplate/electron-react-boilerplate#1820]
I've looked into #1410, #1316,  #1115, and all issues in https://github.com/amilajack/erb-sqlite-example/, but I can't seem to find the solution to package the app with a sqlite3 file.

This works in dev:

```javascript
const dbPath = path.join(__dirname, 'db/database.db');
const db = new sqlite3.Database(dbPath);
```

I can read and write, but when packaging, I get `Error: SQLITE_CANTOPEN: unable to open database file`. Because the file `.db` file does not get packed into the final app. Any ideas? 

Adding:

```javascript
"extraFiles": [
    "app/db/database.db"
]
```
in `package.json` adds the file to `Contents/app/db/database.db` when its packed, but I'm still unable to read it. Not sure what's the best solution

thanks!

**Comment by cvalenzuela** [comment]
great, thanks for letting me know. I'll try to see what I can do as well.

**Comment by HyperSprite** [comment]
Two things come to mind when reading this:

1. asar files are read only. I would probably copy the file out of the asar to one of the user writable locations, app.getPath('userData'), as @andrerpena says is a good place for that kind of thing. I actually use that location for both prod and non-prod configuration files and add a `dev` subdirectory to keep thing seperate. 

2. Pathing in Electron with Webpack can be tricky. Files move around and the path in dev may not be the path in prod if you are not requiring the file, as in this case. Also, `__dirname` is relative to where you are calling it. You could start with a simple console.log(__dirname) to see where Electron thinks it is. If that seems right, you could try something like this

```js 
import fs from 'fs';
// then where you have your dbPath const line add this right below it

fs.readdir(path.join(__dirname), (err, items) => {
  if (err) {
    console.log('db dir err', err);
  } else {
    console.log('db dir items', items);
  }
});
```

> Start with `__dirname` and it should output an array of all of the folders/files it can see. If you can't see a `db` folder then you are in the wrong place. Once you can see the `db` folder in your results, then change the readdir path to path.join(__dirname, 'db') and it should output an array of files in that dir. If you get a big nasty error, it can't see 'db'.

If you are calling this from renderer, you may see the console log output in both main and renderer consoles and they may not be the same.

Hope that helps

**Comment by salimdriai** [comment]
here what i did and it worked super fine, 
put your database file under resources by adding it to extraResources like : 

in `package.json` under `"build "`

```
 "extraResources": [
      "./assets/**",
      "./database/**"
  ],
```
note: my database directory is in the root 

then you just access the file from different modes like : 

 ```
const isDevelopment =
  process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true';

connect() {
    const dbPath = isDevelopment
      ? path.join(webpackPaths.srcPath, '../database/database.db')
      : path.join(process.resourcesPath, 'database/database.db');

    return new Database(dbPath, { verbose: console.log, fileMustExist: true });
  }
```
