### ISSUE TITLE
Move examples into monorepo

### ISSUE THREAD

**Issue by vikr01** [electron-react-boilerplate/electron-react-boilerplate#1823]
We have quite a few ERB examples, such as [erb-serialport-example](/amilajack/erb-serialport-example) and others listed in [the wiki](../wiki/Notable-Forks).

They should move to [the `examples` repo in the `electron-react-boilerplate` organization](/electron-react-boilerplate/examples) as subpackages.

**Comment by edykim** [comment]
I'm happy to take this issue if no one assigns yet.

**Comment by RajatArora08** [comment]
@vikr01 If you can confirm this process is okay, I can work on including others as well.
https://github.com/electron-react-boilerplate/examples/pull/1
