### ISSUE TITLE
Clean run project dev throws errors

### ISSUE THREAD

**Issue by 10SPD** [electron-react-boilerplate/electron-react-boilerplate#1855]
Having issues with a vanilla install and running yarn dev.

- Node version: 9.10.1
- Version or Branch used : master
- Operating System and version : OSx High Sierra 10.13.6

## Expected Behavior
Expect to see the counter demo

## Current Behavior
Blank blue screen displays with errors in the console. 
Throws errors:

renderer.dev.js:41955 Uncaught TypeError: Cannot read property 'state' of undefined
    at unliftState (<anonymous>:2:31678)
    at Object.getState (<anonymous>:2:31745)
    at Object.runComponentSelector [as run] (http://localhost:1212/dist/renderer.dev.js:41740:46)
    at ProxyComponent.initSelector (http://localhost:1212/dist/renderer.dev.js:41892:23)
    at ProxyComponent.initSelector (http://localhost:1212/dist/renderer.dev.js:40214:25)
    at new Connect (http://localhost:1212/dist/renderer.dev.js:41833:15)
    at new Connect(ConnectedRouter) (eval at ./node_modules/react-hot-loader/dist/react-hot-loader.development.js (http://localhost:1212/dist/renderer.dev.js:39859:54), <anonymous>:5:7)
    at constructClassInstance (http://localhost:1212/dist/renderer.dev.js:33594:18)
    at updateClassComponent (http://localhost:1212/dist/renderer.dev.js:35291:7)
    at beginWork (http://localhost:1212/dist/renderer.dev.js:35971:14)
unliftState @ VM110:2
getState @ VM110:2
runComponentSelector @ renderer.dev.js:41740
initSelector @ renderer.dev.js:41892
initSelector @ renderer.dev.js:40214
Connect(ConnectedRouter) @ renderer.dev.js:41833
Connect(ConnectedRouter)
constructClassInstance @ renderer.dev.js:33594
updateClassComponent @ renderer.dev.js:35291
beginWork @ renderer.dev.js:35971
performUnitOfWork @ renderer.dev.js:38010
workLoop @ renderer.dev.js:38049
callCallback @ renderer.dev.js:22247
invokeGuardedCallbackDev @ renderer.dev.js:22285
invokeGuardedCallback @ renderer.dev.js:22334
replayUnitOfWork @ renderer.dev.js:37457
renderRoot @ renderer.dev.js:38109
performWorkOnRoot @ renderer.dev.js:38707
performWork @ renderer.dev.js:38629
performSyncWork @ renderer.dev.js:38601
requestWork @ renderer.dev.js:38501
scheduleWork$1 @ renderer.dev.js:38365
scheduleRootUpdate @ renderer.dev.js:38932
updateContainerAtExpirationTime @ renderer.dev.js:38959
updateContainer @ renderer.dev.js:38986
module.exports../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ renderer.dev.js:39269
(anonymous) @ renderer.dev.js:39409
unbatchedUpdates @ renderer.dev.js:38826
legacyRenderSubtreeIntoContainer @ renderer.dev.js:39405
render @ renderer.dev.js:39464
(anonymous) @ renderer.dev.js:1848
./app/index.js @ renderer.dev.js:1880
__webpack_require__ @ renderer.dev.js:726
fn @ renderer.dev.js:103
0 @ renderer.dev.js:55189
__webpack_require__ @ renderer.dev.js:726
module.exports../app/Routes.js.Object.defineProperty.value @ renderer.dev.js:793
(anonymous) @ renderer.dev.js:796
renderer.dev.js:36373 The above error occurred in the <Connect(ConnectedRouter)> component:
    in Connect(ConnectedRouter) (created by Root)
    in Provider (created by Root)
    in Root
    in AppContainer

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ renderer.dev.js:36373
logError @ renderer.dev.js:36412
callback @ renderer.dev.js:37094
callCallback @ renderer.dev.js:33025
commitUpdateQueue @ renderer.dev.js:33069
commitLifeCycles @ renderer.dev.js:36524
commitAllLifeCycles @ renderer.dev.js:37609
callCallback @ renderer.dev.js:22247
invokeGuardedCallbackDev @ renderer.dev.js:22285
invokeGuardedCallback @ renderer.dev.js:22334
commitRoot @ renderer.dev.js:37750
completeRoot @ renderer.dev.js:38765
performWorkOnRoot @ renderer.dev.js:38710
performWork @ renderer.dev.js:38629
performSyncWork @ renderer.dev.js:38601
requestWork @ renderer.dev.js:38501
scheduleWork$1 @ renderer.dev.js:38365
scheduleRootUpdate @ renderer.dev.js:38932
updateContainerAtExpirationTime @ renderer.dev.js:38959
updateContainer @ renderer.dev.js:38986
module.exports../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ renderer.dev.js:39269
(anonymous) @ renderer.dev.js:39409
unbatchedUpdates @ renderer.dev.js:38826
legacyRenderSubtreeIntoContainer @ renderer.dev.js:39405
render @ renderer.dev.js:39464
(anonymous) @ renderer.dev.js:1848
./app/index.js @ renderer.dev.js:1880
__webpack_require__ @ renderer.dev.js:726
fn @ renderer.dev.js:103
0 @ renderer.dev.js:55189
__webpack_require__ @ renderer.dev.js:726
module.exports../app/Routes.js.Object.defineProperty.value @ renderer.dev.js:793
(anonymous) @ renderer.dev.js:796
renderer.dev.js:39822 TypeError: Cannot read property 'state' of undefined
    at unliftState (<anonymous>:2:31678)
    at Object.getState (<anonymous>:2:31745)
    at Object.runComponentSelector [as run] (http://localhost:1212/dist/renderer.dev.js:41740:46)
    at ProxyComponent.initSelector (http://localhost:1212/dist/renderer.dev.js:41892:23)
    at ProxyComponent.initSelector (http://localhost:1212/dist/renderer.dev.js:40214:25)
    at new Connect (http://localhost:1212/dist/renderer.dev.js:41833:15)
    at new Connect(ConnectedRouter) (eval at ./node_modules/react-hot-loader/dist/react-hot-loader.development.js (http://localhost:1212/dist/renderer.dev.js:39859:54), <anonymous>:5:7)
    at constructClassInstance (http://localhost:1212/dist/renderer.dev.js:33594:18)
    at updateClassComponent (http://localhost:1212/dist/renderer.dev.js:35291:7)
    at beginWork (http://localhost:1212/dist/renderer.dev.js:35971:14)
error @ renderer.dev.js:39822
componentDidCatch @ renderer.dev.js:41201
componentDidCatch @ renderer.dev.js:40214
callback @ renderer.dev.js:37095
callCallback @ renderer.dev.js:33025
commitUpdateQueue @ renderer.dev.js:33069
commitLifeCycles @ renderer.dev.js:36524
commitAllLifeCycles @ renderer.dev.js:37609
callCallback @ renderer.dev.js:22247
invokeGuardedCallbackDev @ renderer.dev.js:22285
invokeGuardedCallback @ renderer.dev.js:22334
commitRoot @ renderer.dev.js:37750
completeRoot @ renderer.dev.js:38765
performWorkOnRoot @ renderer.dev.js:38710
performWork @ renderer.dev.js:38629
performSyncWork @ renderer.dev.js:38601
requestWork @ renderer.dev.js:38501
scheduleWork$1 @ renderer.dev.js:38365
scheduleRootUpdate @ renderer.dev.js:38932
updateContainerAtExpirationTime @ renderer.dev.js:38959
updateContainer @ renderer.dev.js:38986
module.exports../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ renderer.dev.js:39269
(anonymous) @ renderer.dev.js:39409
unbatchedUpdates @ renderer.dev.js:38826
legacyRenderSubtreeIntoContainer @ renderer.dev.js:39405
render @ renderer.dev.js:39464
(anonymous) @ renderer.dev.js:1848
./app/index.js @ renderer.dev.js:1880
__webpack_require__ @ renderer.dev.js:726
fn @ renderer.dev.js:103
0 @ renderer.dev.js:55189
__webpack_require__ @ renderer.dev.js:726
module.exports../app/Routes.js.Object.defineProperty.value @ renderer.dev.js:793
(anonymous) @ renderer.dev.js:796
renderer.dev.js:41955 Uncaught TypeError: Cannot read property 'state' of undefined
    at unliftState (<anonymous>:2:31678)
    at Object.getState (<anonymous>:2:31745)
    at Object.runComponentSelector [as run] (http://localhost:1212/dist/renderer.dev.js:41740:46)
    at ProxyComponent.initSelector (http://localhost:1212/dist/renderer.dev.js:41892:23)
    at ProxyComponent.initSelector (http://localhost:1212/dist/renderer.dev.js:40214:25)
    at new Connect (http://localhost:1212/dist/renderer.dev.js:41833:15)
    at new Connect(ConnectedRouter) (eval at ./node_modules/react-hot-loader/dist/react-hot-loader.development.js (http://localhost:1212/dist/renderer.dev.js:39859:54), <anonymous>:5:7)
    at constructClassInstance (http://localhost:1212/dist/renderer.dev.js:33594:18)
    at updateClassComponent (http://localhost:1212/dist/renderer.dev.js:35291:7)
    at beginWork (http://localhost:1212/dist/renderer.dev.js:35971:14)
unliftState @ VM110:2
getState @ VM110:2
runComponentSelector @ renderer.dev.js:41740
initSelector @ renderer.dev.js:41892
initSelector @ renderer.dev.js:40214
Connect(ConnectedRouter) @ renderer.dev.js:41833
Connect(ConnectedRouter)
constructClassInstance @ renderer.dev.js:33594
updateClassComponent @ renderer.dev.js:35291
beginWork @ renderer.dev.js:35971
performUnitOfWork @ renderer.dev.js:38010
workLoop @ renderer.dev.js:38049
callCallback @ renderer.dev.js:22247
invokeGuardedCallbackDev @ renderer.dev.js:22285
invokeGuardedCallback @ renderer.dev.js:22334
replayUnitOfWork @ renderer.dev.js:37457
renderRoot @ renderer.dev.js:38109
performWorkOnRoot @ renderer.dev.js:38707
performWork @ renderer.dev.js:38629
performSyncWork @ renderer.dev.js:38601
requestWork @ renderer.dev.js:38501
scheduleWork$1 @ renderer.dev.js:38365
scheduleRootUpdate @ renderer.dev.js:38932
updateContainerAtExpirationTime @ renderer.dev.js:38959
updateContainer @ renderer.dev.js:38986
module.exports../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ renderer.dev.js:39269
(anonymous) @ renderer.dev.js:39409
unbatchedUpdates @ renderer.dev.js:38826
legacyRenderSubtreeIntoContainer @ renderer.dev.js:39405
render @ renderer.dev.js:39464
(anonymous) @ renderer.dev.js:1848
./app/index.js @ renderer.dev.js:1880
__webpack_require__ @ renderer.dev.js:726
fn @ renderer.dev.js:103
0 @ renderer.dev.js:55189
__webpack_require__ @ renderer.dev.js:726
module.exports../app/Routes.js.Object.defineProperty.value @ renderer.dev.js:793
(anonymous) @ renderer.dev.js:796
renderer.dev.js:36373 The above error occurred in the <Connect(ConnectedRouter)> component:
    in Connect(ConnectedRouter) (created by Root)
    in Provider (created by Root)
    in Root
    in AppContainer

**Comment by 10SPD** [comment]
Update: if we comment out the function `await installExtensions();` then it will work.

Any idea why this would be the case?

**Comment by amilajack** [comment]
Try running the commands here: https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools#devtools-extension

**Comment by barbalex** [comment]
@amilajack thanks, `set UPGRADE_EXTENSIONS=1 && yarn run dev` did the trick for me

**Comment by Gaafar** [comment]
for mac os, running `UPGRADE_EXTENSIONS=1 yarn run dev` seems to fix it
