### ISSUE TITLE
Add Typescript Support

### ISSUE THREAD

**Issue by Fihtangolz** [electron-react-boilerplate/electron-react-boilerplate#1857]
Is the project planning support?

**Comment by amilajack** [comment]
Yes, this is planned. We need to get babel@7 pr merged first

**Comment by YikaJ** [comment]
THANKS LOTS, I CAN'T WAIT FOR IT!!!
I almost forget how to write code without typescript, lol .

**Comment by gorilla-devs** [comment]
Do you have any ETA for this? I'm really hyped!

**Comment by vikr01** [comment]
Issue is resolved as of #1899. [`babel` 7 supports typescript](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/). See @Microsoft's [TypeScript-Babel-Starter repo](https://github.com/Microsoft/TypeScript-Babel-Starter) if you need an example configuration.

**Comment by danmo** [comment]
What's the status on this one?

**Comment by gorilla-devs** [comment]
Afaik it's resolved. Babel now supports typescript so it is enough to configure it and you're ready to go
