### ISSUE TITLE
Have you considered developing a command line tool to create template projects?

### ISSUE THREAD

**Issue by hengkx** [electron-react-boilerplate/electron-react-boilerplate#1858]
1. use `js` or `ts`
2. whether `flow` is used
3. redux middleware use `redux-thunk` or `redux-saga`
4. use `less` or `sass`
5. etc

**Comment by amilajack** [comment]
Yes, there is a repo for that. You can submit an RFC there. https://github.com/electron-react-boilerplate/erb-cli
