### ISSUE TITLE
Investigate using flags instead of environment variables

### ISSUE THREAD

**Issue by vikr01** [electron-react-boilerplate/electron-react-boilerplate#1861]
We're using environment variables like flags a lot here. However, setting environment variables is different between systems and can cause people errors (#1783). This makes things confusing when people are trying to figure out why their script isn't working, only for it to work for someone else using a different OS.

For webpack configs, the easy solution is to use [function configs](https://webpack.js.org/configuration/configuration-types/#exporting-a-function) (#1745). Webpack itself will parse the args into a parameter `argv`. For example, if you ran the script `webpack --hot=true` then `argv.hot` will be `"true"`.

For in app use, the answer is [dotenv](https://github.com/motdotla/dotenv). Although I don't think we're using any environment variables in the sample counter app given.

Example of a proposed change:

```bash
# with environment variable
START_MINIMIZED=true yarn dev

# with flag
yarn dev --start-minimized
```

**Comment by amilajack** [comment]
Lets move this to `erb-cli` repo
