### ISSUE TITLE
[Question] Electron v3

### ISSUE THREAD

**Issue by ljubic** [electron-react-boilerplate/electron-react-boilerplate#1862]
Hello,

I am using some node libraries which are supported with the node version 10 and above. Do you have any plans in upgrading electron to version 3, because the current electron v2 is using node v8?

**Comment by Slapbox** [comment]
Have you tried simply changing the version in dependencies to 3.x? I'm not aware of any breaking changes for the boilerplate with Electron 3.x, although there may be some I've overlooked.

If you find yourself hitting some bug with 3.x, just let me know and I'll be happy to try and help you get it working.

**Comment by VikramTiwari** [comment]
It works fine. Why not update the boilerplate as well?

**Comment by clem91** [comment]
Same here electron V3 works fine!

**Comment by ljubic** [comment]
Works fine :)

**Comment by vikr01** [comment]
@VikramTiwari 
1. PRs are welcome. 
1. Works fine ≠ No breaking changes

**Comment by ljubic** [comment]
Actually, I got the problem after installing a new module.

The electron-rebuild is using the node-abi version ^2.0.0, and that version of node-abi is incompatible with electron v3. 

I installed node-abi@^2.45 (which is compatible with electron v3) into package.json, but the electron-rebuild still pulls node-abi from it's node_modules directory.

I don't know whether this is relevant to this repo, but maybe someone could give me advice on how to make electron-rebuild to use latest node-abi.

I tried running **yarn add node-abi@2.4.5 --deep** but with no success.

**Comment by Slapbox** [comment]
@ljubic - Change your inner `package.json` postinstall script to the following and let us know how it goes:

`"postinstall": "npm rebuild --runtime=electron --target=3.0.6 --disturl=https://atom.io/download/atom-shell",`

**Comment by Slapbox** [comment]
PS: Always, always always - `yarn package` after upgrading Electron to a new major version. Sometimes you may find a problem in production builds which was not present in development, and it's much better to find them early.

**Comment by ljubic** [comment]
Solved it, the **ffi** module is not building because it's no longer maintained andd doesn't support ABI 64. The solution was to install manually **ffi-napi** which has the same API and require it in active-win module instead of ffi. Also the ffi is optional dependencies in active-win, and doesn't get installed by default using yarn.

**Comment by Slapbox** [comment]
@ljubic thanks for posting your solution!

**Comment by nagama-wal** [comment]
I updated the electron version. After `yarn` and `yarn package`. The application started working properly. Couldn't notice any broken code. Should we focus on it and look forward to upgrading electron version.

**Comment by aguynamedben** [comment]
Electron 3.0.6 + custom compiled node-sqlite3 with SQLCipher has been working fine for us. The upgrade was super easy because there weren't many big API changes between Electron 2 and Electron 3 ("breaking API changes" [here](https://electronjs.org/blog/electron-3-0)).
