### ISSUE TITLE
On MacOS, after closing the window, it does not reopen from the dock

### ISSUE THREAD

**Issue by euangordon** [electron-react-boilerplate/electron-react-boilerplate#1863]
In my project, I have found that once the app is closed on MacOS, it won't reopen from the dock. I have resolved it with the following changes in main.dev.js:

Add:
```
app.on('activate', () => { mainWindow.show() })
app.on('before-quit', () => app.quitting = true)
```

Edit:
```
  mainWindow.on('close', (event) => {
    if (app.quitting) {
      mainWindow = null
    } else {
      event.preventDefault()
      mainWindow.hide()
    }
  });
```

**Comment by AmauriAires** [comment]
Can I work on this?

**Comment by amilajack** [comment]
@AmauriAires sure

**Comment by AmauriAires** [comment]
@euangordon, your solution seems to work. Are you going to make a PR?

**Comment by AmauriAires** [comment]
I reviewed PR #2122 and made a few changes on it. It is working properly now.

**Comment by adamchenwei** [comment]
@AmauriAires I still have the same problem, when click on the electron icon in the doc, it won't reopen.... does an app can only be reopened when its compiled into a distributed app icon for Mac? Thanks
