### ISSUE TITLE
Add support for checking if global build requirements exist

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#1866]
Can add this to the `postinstall` script. This can help with [`node-gyp` installation issues](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400#issue-177964472)

**Comment by hengkx** [comment]
This check is to determine if the global installation does not install `node-gyp` and then go to install?

**Comment by amilajack** [comment]
@hengkx yup, that's correct
