### ISSUE TITLE
Create StackOverflow tag `electron-react-boilerplate`

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#1886]

**Comment by co16353sidak** [comment]
@amilajack I would like to work on this as my first issue on this repo, please give me the go ahead to proceed.

**Comment by amilajack** [comment]
@co16353sidak would love if you could create this tag! Thanks!

**Comment by co16353sidak** [comment]
Hey @amilajack how about something like this?
[![StackOverflow](http://img.shields.io/badge/stackoverflow-electron_react_boilerplate-blue.svg)]( http://stackoverflow.com/questions/tagged/electron-react-boilerplate )

**Comment by amilajack** [comment]
That would be awesome!

**Comment by co16353sidak** [comment]
Okay, please wait on the PR
