### ISSUE TITLE
PR: Lazy load routes using React.lazy

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#1888]
https://twitter.com/TheLarkInn/status/1056729742437543936
https://github.com/reactjs/rfcs/blob/gaearon-patch-2/text/0000-lazy.md

**Comment by vikr01** [comment]
Related #1136

**Comment by gorilla-devs** [comment]
Would this really speedup startup times?

**Comment by amilajack** [comment]
It depends on how large your app is. I've reduced ERB apps from 20 second startup time to 2 seconds by using lazy loading and route based code splitting

**Comment by fxnoob** [comment]
@amilajack Where should I place the example files of React.lazy?

**Comment by amilajack** [comment]
Lazy loading routes seems like the best option. Also instead of adding examples elsewhere, I think we should add the examples to this repo.
