### ISSUE TITLE
PR: Add `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#1892]
The goal with this is to make it easier for new contributors to PR to ERB. We should denote our conventions:
* PR'ing to the `next` branch
* Using `yarn`
* Use descriptive messages for PR headings and commit messages
* Denote the standards for RFCs. We can model this after [Rust's RFCs](https://github.com/rust-lang/rfcs)
* Update `CHANGELOG.md`

**Comment by vikr01** [comment]
- Document `[skip ci]` for README changes.

This is supported [by appveyor](https://www.appveyor.com/docs/how-to/filtering-commits/#commit-message) and [by travis](https://docs.travis-ci.com/user/customizing-the-build/).
