### ISSUE TITLE
Migrating to parcelJS instead of webpack

### ISSUE THREAD

**Issue by gorilla-devs** [electron-react-boilerplate/electron-react-boilerplate#1909]
Would it be possible to switch to parcelJS instead of webpack? I think it would bring faster loading times and a lot simpler configuration. What do you think?

**Comment by amilajack** [comment]
See https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1430. I think it would be better to wait for the parcel community to mature before migrating (if we decide to)

**Comment by vikr01** [comment]
I'm not interested in switching to `parcel` at all. The whole point of a boilerplate to me is extensibility, getting to customize the configurations to your liking.

Switching to an "all in one" builder for *everyone* could cause confusion, i.e. "How do I rename ___?", "How do I add support for ___?", "Why doesn't hot reloading work?".

People are welcome to switch to `parcel` if it works for them, but making the entire boilerplate default to it is unnecessary.
