### ISSUE TITLE
Question about filtering dependencies from DLL

### ISSUE THREAD

**Issue by Slapbox** [electron-react-boilerplate/electron-react-boilerplate#1928]
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.renderer.dev.dll.js#L34-L38

How does this work?

**Comment by amilajack** [comment]
We filter out packages that have issues with being packaged in the dll. Font awesome was one of those packages

**Comment by Slapbox** [comment]
Right but can you let me know anything about _how_ that works? As best as I can tell the code just returns a key index to ignore, not a package name, if I recall correctly. Is this right?

I guess my question is, what is the final input for DLL creation? If I wanted to filter out additional packages, how would I do it? I thought it would be simple, but it wasn't, and webpack configs aren't the easiest things to debug.

**Comment by amilajack** [comment]
That is correct, you give it the name of the dep that you want to ignore. The final output of dll creation is a huge bundle of mappings to js files. DLL's are not necessary so you can remove them. They're there for performance reasons in dev

**Comment by Slapbox** [comment]
@amilajack could you provide an example of how you'd go about listing dependencies to exclude from the DLL creation? I'm using `lerna` and have local packages that are changed pretty frequently which I want to exclude from DLL creation, but I also have far too many packages to possibly go without DLL altogether.

Thanks for any advice you might have!

**Comment by Slapbox** [comment]
@amilajack - do you have any thoughts on how to do this? I'm trying to work with a monorepo, but as things stand now the more of my code I move into packages in the monorepo, the more often I need to rebuild the DLL which is a major inconvenience.

Any thoughts?
