### ISSUE TITLE
SASS for app.global.css broken

### ISSUE THREAD

**Issue by thanhquang1988** [electron-react-boilerplate/electron-react-boilerplate#1950]
## Steps to Reproduce (for bugs)

1. rename app.global.css to app.global.scss

2. change to app.global.scss https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/app/index.js#L6

3. Add an icon to Home page, example `<i className="fa fa-apple"/>`

4. yarn package

5. run release app

## Context
The fontawesome icon showing as []
<img width="1136" alt="screen shot 2018-11-02 at 10 48 58 am" src="https://user-images.githubusercontent.com/4501044/47892960-0dea1600-de8d-11e8-9f44-366227b2b25c.png">

## Your Environment

- Node version : 10.13.0
- Version or Branch used : master
- Operating System and version : MacOS 10.14

**Comment by clem91** [comment]
I'm using [react-fontawesome](https://github.com/FortAwesome/react-fontawesome) and I don't have any problem
