### ISSUE TITLE
How to disable Eslint Pre-commit Hook?

### ISSUE THREAD

**Issue by nyxynyx** [electron-react-boilerplate/electron-react-boilerplate#1953]
How can we disable the Eslint pre-commit hook in git?

When I commit my files in git, I am getting many errors such as the following, which I assume are due to eslint rules.

```
cross-env NODE_ENV=development eslint --cache --format=pretty [failed]
→ 
Running tasks for *.{js,jsx} [failed]
→ 


[?25h× "cross-env NODE_ENV=development eslint --cache --format=pretty" found some errors. Please fix them and try committing again.
  
app\actions\animals\types.js:1:56
×    1:56   Expected linebreaks to be LF but found CRLF.                                                                                                                            linebreak-style
```

Alternatively, how can we edit the Eslint rules to allow this? Is this recommended, or should we actually fix the CRLF/LF issue?

**Comment by vikr01** [comment]
You can disable it on pre-commit by removing [this line](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/package.json#L40).

Though, I don't recommend doing that. Instead you can set `"linebreak-style": "off"` in `.eslintrc` to disable that specific rule. Not sure why it isn't being auto-fixed, though.
