### ISSUE TITLE
Transpiling external packages in node_modules broken.

### ISSUE THREAD

**Issue by rostislav-simonik** [electron-react-boilerplate/electron-react-boilerplate#1955]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs) 

## Expected Behavior

Babel should transpile external es6 dependencies located in node_modules 

## Current Behavior

Throws error: 
https://gist.github.com/rostislav-simonik/077e847fd09963b57c2c6ed75f48aee7

## Steps to Reproduce (for bugs)

1. in configs/webpack.config.renderer.dev.babel.js disable exclusion for node_modules (js/jsx)
2. yarn dev 

I've also tried to exclude everything except concerning module, but it doesn't work, it breaks on the first "import" statement. It's somehow related to new babel 7. 

## Context
I'm trying to enable babel transpiling for packages in node modules. 

## Your Environment

- Node version :v11.0.0
- Version or Branch used : 0.17.0
- Operating System and version : MacOS Mojave

**Comment by vikr01** [comment]
It’s not related to the `babel` 7 upgrade. It’s because [we exclude `node_modules` from `babel-loader` in `webpack`](
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.base.js#L16).

**Comment by rostislav-simonik** [comment]
@vikr01 Yes, I've narrowed issue. I'm doing incremental upgrade of my project from 0.13.3 (That's where it worked after i removed exclude for node_modules. 
1) I'm observing that issue raises at 0.16.0 it's somehow related to moving/updating webpack configs. I'll investigate more, to get exact plate of issue.  
2) After babel 7 (0.17.0) there is another issue, so removal of exclusion must be changed to exclusion for everything except packages i want to transpile.

**Comment by vikr01** [comment]
@rostislav-simonik Are you trying to run a node script, or use the electron application?

If it's the former, it could be related to `@babel/register` (I believe it ignores `node_modules` by default, and you need to configure it to not).

If it's the latter -- using `import` with `module.exports` will break with the latest versions of `@babel/preset-env` and `babel-loader` ([link](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940)).

Also, how are you referencing the `node_modules` you want to transpiled? If you're using a relative path (i.e. `require('../node-modules/foo')`), `babel` might not run on it.

There were many issues we were running into when using the old 2-package.json structure with `babel` 7. If you're still using that, you'll need to configure your `babel` configs more.

**Comment by rostislav-simonik** [comment]
> @rostislav-simonik Are you trying to run a node script, or use the electron application?
@vikr01 not sure whether i follow, but I'm executing yarn dev of given boilerplate when error occurs. 

I need to investigate more, I'll let you know then. Thx for pointing me out.

**Comment by vikr01** [comment]
@rostislav-simonik Is the error in your terminal, or in the electron application?

**Comment by rostislav-simonik** [comment]
Aiv

**Comment by rostislav-simonik** [comment]
@vikr01 ok, I've found out. 

It was related to changes presented in 0.17.0. 

So in case somebody wants to enable transpiling for packages located in node_modules, following must be done. 

1) Add packages exception in node_modules exclusion (particular libraries or reg exp group match, whatever you need)

**configs/webpack.config.renderer.dev.babel.js**
**configs/webpack.config.renderer.prod.babel.js** 
```
rules: [
      {
        test: /\.jsx?$/,
        // exclude: /node_modules/,
        exclude: /^((?!node_modules\/my_package1|node_modules\/my_package2).)*$/,  
        use: {
```

that solves issue which has been present in gist above. 

2. But real cause was due following code has been removed, when I put it back it started to work again. 

**configs/webpack.config.base.js**
```
/ Find all the dependencies without a `main` property and add them as webpack externals
function filterDepWithoutEntryPoints(dep: string): boolean {
  // Return true if we want to add a dependency to externals
  try {
    // If the root of the dependency has an index.js, return true
    if (
      fs.existsSync(path.join(__dirname, '..', `node_modules/${dep}/index.js`))
    ) {
      return false;
    }
    const pgkString = fs
      .readFileSync(require.resolve(`${dep}/package.json`))
      .toString();
    const pkg = JSON.parse(pgkString);
    const fields = ['main', 'module', 'jsnext:main', 'browser'];
    return !fields.some(field => field in pkg);
  } catch (e) {
    console.log(e);
    return true;
  }
}

export default {
  externals: [
    ...Object.keys(dependencies || {}).filter(filterDepWithoutEntryPoints)
  ],
```

**Comment by vikr01** [comment]
I can't give a "proper solution" when I don't have enough of a background (which is what I was attempting to figure out). I'm still not clear on where the error was even occurring.

I'm not entirely sure why that function was removed (cc @HyperSprite). Though, it will become outdated if we integrate `yarn`'s `plug'n'play`.

I'm glad something worked for you. Closing this as it seems issue has been resolved.

**Comment by rostislav-simonik** [comment]
Ah sorry, 
issue occurred in electron application 
```
Uncaught SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.tsx-redux (http://localhost:1212/dist/renderer.dev.js:23343:18)
```

content of given tsx-redux package 
*node_modules/tsx-redux/index.js* simplified version: 
```
import type {
  AbstractRedux,
} from './Model/Types'
import {
  createRedux,
} from './Redux/Model/Redux'


export {
  createRedux,
}

export type {
  AbstractRedux,
}
```

**Comment by HyperSprite** [comment]
Looking that this, `filterDepWithoutEntryPoints`, probably needs to go back in. I read what it did and didn't quite grasp all the implications.

**Comment by vikr01** [comment]
Reopening since this needs to be fixed. (Though we should use `require.resolve` instead of `path`.)

**Comment by Aid19801** [comment]
@W1M0R ^^ this fixed a 2 hour problem for me, thanks man, sincerely. x
