### ISSUE TITLE
Bundle size significantly increased in latest version

### ISSUE THREAD

**Issue by gorilla-devs** [electron-react-boilerplate/electron-react-boilerplate#1961]
As of [this commit](https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/9f4381aeaed82acfff2e1cd59f781bcf5669f595), the app.asar on windows weights 6mb. In the latest commit it weights 46mb. Since my application is much bigger, the size went from 16mb to 122mb, quite an increase. I noticed that now it bundles the node_modules folder inside the app.asar, it didn't do that before. Any idea on how to solve this?

To reproduce this it's enough to do yarn and yarn package on both commits and go look inside release/win-unpacked/resources/app.asar, extract it with [this](https://github.com/electron/asar) et voila

**Comment by aguynamedben** [comment]
The commit you point to is a simple README change... did you mean to paste another commit?

**Comment by gorilla-devs** [comment]
I know. That is the last commit with a small bundle size. The commits after that ([from this commit](https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/d5416958865bca241f001807cb5e1f62a0cd1ba2)) weights a lot. I need to fix this asap

**Comment by vikr01** [comment]
This sounds like it’s related to the webpack config changes.

**Comment by thecorsair** [comment]
same issue. 
In the last version(0.16.0), the dist folder size is very small and not contains [node_modules].

**Comment by thecorsair** [comment]
> same issue.
> In the last version(0.16.0), the dist folder size is very small and not contains [node_modules].

It's not like 0.16.0, maybe 0.15.0

**Comment by gorilla-devs** [comment]
Anyone got a fix? I tried but i couldn't figure out the problem

**Comment by vikr01** [comment]
@gorilla-devs If you discard the `node_modules` folder entirely after building, does your app still run fine? If that's the case, that may actually be better behavior since your bundle size should be smaller than `node_modules` + your bundled app due to `webpack`'s tree-shaking.

**Comment by gorilla-devs** [comment]
I just tried unpacking app.asar using the asar utility, deleting node_modules and repacking it. It crashes saying it cannot find one of the modules (electron-log). There is surely something wrong in the configs of webpack

**Comment by gorilla-devs** [comment]
If anyone needs, our fantastic @amilajack found a solution (even if it's temporary afaik).
[#1986](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1986)
