### ISSUE TITLE
General Question: How is DLL working?

### ISSUE THREAD

**Issue by twigs67** [electron-react-boilerplate/electron-react-boilerplate#1962]
I'm new to React, so I apologize, as I know this isn't the correct place to ask this. However, I'm trying to launch a new React window upon a keyboard shortcut and I can't figure out how DLL is playing into React being rendered. 

"app.html" loads "renderer.dev.js" & "renderer.dev.dll.js", but "renderer.dev.dll.js" is rather meaty so I can't figure out what's going on here. I'm assuming from here it loads index.js, but I can't figure out how or where Home.js is actually loaded?

Can you provide any insight into this? 

Thanks

**Comment by amilajack** [comment]
What do you mean by react window?
