### ISSUE TITLE
How to set app icon in development mode?

### ISSUE THREAD

**Issue by BeAce** [electron-react-boilerplate/electron-react-boilerplate#1964]
How to set app icon in development mode?

## Prerequisites

- [ ] Using yarn
- [ ] Using an up-to-date master branch
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

I want to use the same app icon in production environment and development environment.

## Current Behavior

I have replaced icons and `.icn`  in `resources` and `app`. 

Icon is correctly replaced under production environment, but development mode also keep react icon.

**Comment by talha131** [comment]
This is the expected behavior. There is no easy way around it. Please see [this issue](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1710#issuecomment-414199480) for details.

**Comment by BeAce** [comment]
> This is the expected behavior. There is no easy way around it. Please see [this issue](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1710#issuecomment-414199480) for details.

Thanks a lot.
