### ISSUE TITLE
Yarn run start broken in last version

### ISSUE THREAD

**Issue by clem91** [electron-react-boilerplate/electron-react-boilerplate#1967]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

yarn run start should run the application in production mode without packaging it

## Current Behavior

electron can't read import instruction in index.js

## Possible Solution

Maybe add some transpiling before ?

## Steps to Reproduce (for bugs)
1.yarn run start or yarn start

2. 💔

**Comment by damianfijorek** [comment]
I have the same issue. Restoring the `package.json` with `"main": "./main.prod.js"` in `app` fixed that. It seems that the `"main": "./app/main.prod.js"` in root `package.json` is disregarded.

**Comment by amilajack** [comment]
Interesting. I cannot reproduce this with a fresh clone

**Comment by vikr01** [comment]
For future reference -- please note that if you don't provide a stacktrace or a repo to reproduce then someone has to attempt to reproduce the issue themselves, which means your issue may take some time to get to (and could be closed if it's not being occurring for anyone else).

I tested this on a fresh clone and got the same bug, here's the stacktrace:

```shell
$ cross-env NODE_ENV=production electron ./app/
App threw an error during load
<path-to-boilerplate>/app/index.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import React from 'react';
                                                                                                                                                           ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:606:28)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (<path-to-boilerplate>/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (<path-to-boilerplate>/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (<path-to-boilerplate>/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:365:3)
```

Steps to reproduce:

1. clean out build files
1. `yarn build`
2. `yarn start`

**Comment by amilajack** [comment]
start script should be changed to `"start": "cross-env NODE_ENV=production electron ./app/main.prod.js",`

**Comment by clem91** [comment]
the fix work! Thanks @amilajack
