### ISSUE TITLE
Question: How to add data in a json file in the app/

### ISSUE THREAD

**Issue by mariorodeghiero** [electron-react-boilerplate/electron-react-boilerplate#1970]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Current Behavior

I'm trying to use a ** "db.json" ** file stored in the ** app / ** folder as the following data below. I can read the file using fetch (./ db.json), but I can not add data to it. How can I do this?

```
{
  "favorite": [
    {
      "id": "1",
      "url": "url1"
    },
    {
      "id": "2",
      "url": "url2"
    }
  ]
}
```

## Possible Solution

I would like to make a Post add the following data to the file ** "db.json" **

```
{
      "id": "3",
      "url": "url3"
    }
```

## Steps to Reproduce (for bugs)

1.` yarn dev`

2.

3.

4.

## Your Environment

- Node version : v10.12.0
- Version or Branch used : master
- Operating System and version : mac OS 10.14 
- Link to your project :

**Comment by vikr01** [comment]
This is not related to `electron-react-boilerplate`.

Please post your question in an appriate place like StackOverflow or [the fetch polyfill](
https://github.com/github/fetch).
