### ISSUE TITLE
Module not installing into node_modules folder

### ISSUE THREAD

**Issue by panpansh** [electron-react-boilerplate/electron-react-boilerplate#1975]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
\* = name of the typeface
on yarn add typeface-*
"typeface-*": "version" => package.json
**(exist)** ./flow-typed/npm/typeface-*_vversion.js 
**(exist)** ./node_modules/typeface-*

## Current Behavior
\* = name of the typeface
on yarn add typeface-*
"typeface-*": "version" => package.json
**(exist)** ./flow-typed/npm/typeface-*_vversion.js 
**(not exist)** ./node_modules/typeface-*

## Possible Solution
use npm instead yarn
or
remove node_modules folder and 'yarn install'

## Steps to Reproduce (for bugs)
\* = name of the typeface
yarn add typeface-*

## Your Environment

- Node version : v10.13.0
- NPM version : 6.4.1
- Yarn version : 1.12.1
- Operating System and version : win 10

**Comment by vikr01** [comment]
I'm not sure I'm following. Please be more descriptive about your issue.

To my understanding:

1. You added a module starting with `typeface-` with `yarn add`
    - `yarn add typeface-roboto`
1. You then see that that module is correctly placed in your `package.json`
    - ```jsonc
        "dependencies": {
          // ... other dependencies
          "typeface-roboto": "^0.0.54"
          // ... other dependencies
        }
       ```
1. You also notice the module has a typing creating in `flow-typed`
    - `./flow-typed/npm/typface-roboto-v0.0.54.js`
1. However, the module does not exist in your `node_modules` folder:
    - `./node_modules/typeface-roboto` does not exist

If this is the case, you should run a script:
```bash
console.log(require.resolve('typeface-roboto/package.json')); // or whatever typeface-* you're using
```

If this passes without error, you should know which directory the `package.json` for the module is in.

If it's not, then you should probably run `yarn install`.

**Comment by panpansh** [comment]
yes exactly :)
and on index.js I need to specify the index.css like that 
`import 'typeface-*/index.css';`
instead of automatic
`import 'typeface-*';`

did you know where is the file to specify to get index.['js','?','css'] like try index.css if no (index.js or index.?) exist ?

**Comment by vikr01** [comment]
Oh I think what you're asking is how to make `<folder>` fallback to `<folder>/index.css` if `<folder>/index.js` does not exist.

In that case, you change [this line](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.base.js#L37) to:

```javascript
resolve: {
  extensions: ['.js', '.jsx', '.json', '.css']
},
```

In this case, the resolution will check `.js` first and `.css` last. If you want to change the resolution order, re-arrange that array accordingly.

**Comment by vikr01** [comment]
@panpansh Is your issue resolved now?

**Comment by panpansh** [comment]
yes first it's a report for a "quantum" bug :)
last for extensions is extra :)
