### ISSUE TITLE
Yarn Dev after following readme instructions results in error - Windows 10

### ISSUE THREAD

**Issue by robbylucia** [electron-react-boilerplate/electron-react-boilerplate#1977]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

I expect it to work-- not sure what that entails, as I've never seen it work :(

## Current Behavior

After following the instructions in the readme for the quickstart, I get the following error on Windows 10:
`error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory`

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

1. Follow instructions for quickstart

2. Yarn Dev

## Context

I did nothing but follow the tutorial.

## Your Environment

Windows 10, Node 10.13, Master Branch

**Comment by amilajack** [comment]
Try the solutions in https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400

**Comment by robbylucia** [comment]
Not sure what fixed the issue for me. I did upgrade Webpack, Electron, and pretty much everything else. Sorry it's not more informative.
