### ISSUE TITLE
cnpm  run dev    Failure

### ISSUE THREAD

**Issue by jimGitHub123** [electron-react-boilerplate/electron-react-boilerplate#1988]
tom@tom-virtual-machine:~/DDN/tools/coin2$ cnpm  run dev

> electron-react-boilerplate@0.17.0 dev /home/tom/DDN/tools/coin2
> cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-react-boilerplate@0.17.0 dev: `cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-react-boilerplate@0.17.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tom/.npm/_logs/2018-11-09T11_32_10_004Z-debug.log
tom@tom-virtual-machine:~/DDN/tools/coin2$

**Comment by amilajack** [comment]
Follow issue template template and use yarn
