### ISSUE TITLE
stuck on starting main process..

### ISSUE THREAD

**Issue by Saccarab** [electron-react-boilerplate/electron-react-boilerplate#1998]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#1635](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1635)

## Expected Behavior

Electron client won't initiate as it should.

Identical to the issue described in [#1635](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1635)

## Current Behavior

> Starting Main Process...

> electron-react-boilerplate@0.17.0 start-main-dev C:\Users\Projects\test
> cross-env HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js

the terminal will just hang at this point

## Steps to Reproduce (for bugs)

1. Follow quickstart instructions

2. Yarn dev

## Context

I had no issues with the boilerplate few days ago and it randomly started hanging like this in the terminal. I've added multiple modules following the two package.json structure. When I encountered the issue for the first time I've cloned the project as it is and it worked out for some time but ended up with the same issue after few hours of development. 

Currently not even a fresh clone of the boilerplate's master branch initiates an electron client.

I've tried multiple node and yarn versions. Tried out the debugging solutions you have listed [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400) 

I've cloned & built the project on another system and it works fine. So the problem is in my machine (most likely due to chrome debugger on electron and breakpoints) but I couldn't really find a fix through.

## Your Environment

- Node version : v10.13
- Version or Branch used : Master
- Operating System and version : Windows 10

**Comment by contractormario** [comment]
Try clearing Electron's cache (on Win: c:\Users\XXXX\AppData\Roaming\Electron\Cache\)

**Comment by Saccarab** [comment]
That didn't help, I've main.dev.js code for now, to force show electron client before the web contents are loaded

**Comment by sanzhardanybayev** [comment]
Cleaning cache did not help, but removing the whole Electron directory inside AppData/Roadming & AppData/Local did help

**Comment by markjhvonk** [comment]
I tried all of the above but disabling/removing the `await installExtensions();` function in the app/main.dev.js file (line 55) did the trick for me for me for now!
Also sort of mentioned in this issue:
#2360

**Comment by XxLittleCxX** [comment]
> I tried all of the above but disabling/removing the `await installExtensions();` function in the app/main.dev.js file (line 55) did the trick for me for me for now!
> Also sort of mentioned in this issue: #2360

You did not provide a screenshot, I don't know if you have the same problem as me, take a look at this

https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2360#issuecomment-576077653

**Comment by markjhvonk** [comment]
> > I tried all of the above but disabling/removing the `await installExtensions();` function in the app/main.dev.js file (line 55) did the trick for me for me for now!
> > Also sort of mentioned in this issue: #2360
> 
> You did not provide a screenshot, I don't know if you have the same problem as me, take a look at this
> 
> [#2360 (comment)](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2360#issuecomment-576077653)

Yes, switching back to windows light mode also worked for me as mentioned in your issue!

**Comment by nathanredblur** [comment]
I get this problem in windows 19041.264 and I solve it updating the electron version.
