### ISSUE TITLE
Importing SVG as React Component

### ISSUE THREAD

**Issue by arvinsalvador** [electron-react-boilerplate/electron-react-boilerplate#2015]
Hello,

I am trying to import SVG as a React Component in my component. I have the following code:

```
import React, { Component } from 'react';
import Mysvg from './mysvg.svg';

class Home extends Component {
  render() {
    return (
       <Mysvg />
    );
  }
}

export default Home;
```

When I run the above code, it shows error in console:

`Warning: <data:image/svg+xml;base64,ZnVuY3Rpb24gX29iamVjdFdpdGhvdXRQcm9wZXJ0aWVzKG9iaiwga2V5cykgeyB2YXIgdGFyZ2V0ID0ge307IGZvciAodmFyIGkgaW4gb2JqKSB7IGlmIChrZXlzLmluZGV4T2YoaSkgPj0gMCkgY29udGludWU7IGlmICghT2JqZWN0LnByb3RvdHlwZS5oYXNPd25Qcm9wZXJ0eS5jYWxsKG9iaiwgaSkpIGNvbnRpbnVlOyB0YXJnZXRbaV0gPSBvYmpbaV07IH0gcmV0dXJuIHRhcmdldDsgfQoKaW1wb3J0IFJlYWN0IGZyb20gInJlYWN0IjsKZXhwb3J0IGRlZmF1bHQgKChfcmVmKSA9PiB7CiAgbGV0IHsKICAgIHN0eWxlcyA9IHt9CiAgfSA9IF9yZWYsCiAgICAgIHByb3BzID0gX29iamVjdFdpdGhvdXRQcm9wZXJ0aWVzKF9yZWYsIFsic3R5bGVzIl0pOwoKICByZXR1cm4gPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0IiBmaWxsPSIjOGM4YThhIiB7Li4ucHJvcHN9PjxwYXRoIGZpbGw9Im5vbmUiIGQ9Ik0wIDBoMjR2MjRIMFYweiIgLz48cGF0aCBkPSJNMTkgMTNoLTZ2NmgtMnYtNkg1di0yaDZWNWgydjZoNnYyeiIgLz48L3N2Zz47Cn0pOw== /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.`

And if I update my code and do it like this:

```
import React, { Component } from 'react';
import { ReactComponent as Mysvg } from './mysvg.svg';

class Home extends Component {
  render() {
    return (
       <Mysvg />
    );
  }
}

export default Home;
```

It throws an error:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

What should I do to make my SVG as a React Component with this boilerplate?

**Comment by vikr01** [comment]
Please *always* use the issue template for bug reports. If you delete it, your issue will be closed.

This issue has nothing to do with `electron-react-boilerplate` anyway, so I'm going to close it. I recommend posting your issue in [the `react` repository](https://github.com/facebook/react/issues).
