### ISSUE TITLE
Warning in production caused by babel react optimisation

### ISSUE THREAD

**Issue by clementAC** [electron-react-boilerplate/electron-react-boilerplate#2037]
I'm running an erb  app packaged in an appImage and it seems that react is not running in production mode because it showing warning about unique key prop. 
![46846520_316213875459604_8759571953217437696_n](https://user-images.githubusercontent.com/10882592/49150096-2a526480-f30c-11e8-8f46-71d29f495c08.jpg)
Normally this type of message don't show up in production mode. 

I'm not able to reproduce the same behavior with the command `DEBUG_PROD=true yarn build && yarn start`. I have several pages my app and some of it shout this type of message.

After investigating a little it seems this "[issue](https://github.com/facebook/react/issues/11222)" with babel transforms is related 
 
## Prerequisites

- [ x] Using yarn
- [ x] Using an up-to-date master branch
- [x ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ x] Link to stacktrace in a Gist (for bugs)
- [ x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Don't show react warning in packaged app

## Current Behavior

react warnings are showns in react packaged app

## Your Environment

- Node version :
- Version or Branch used : master
- Operating System and version : ubuntu 18.04

**Comment by clem91** [comment]
After some testing, I can confirm that this react optimisation package   
`require('@babel/plugin-transform-react-inline-elements')`
is causing the key warning.

**Comment by amilajack** [comment]
Please file a bug for that repo

**Comment by nickensoul** [comment]
any changes? what do we need to know about this issue?
trying to clean up the main problem.
also, I've noticed that React throws an error about dead eliminated code in production build.

**Comment by amilajack** [comment]
It was fixed

**Comment by nickensoul** [comment]
@amilajack yep, I see, thank you!
As I've understand, for now this boilerplate uses two package.json configuration.
The trouble was that `react`, `react-dom` was in the `externals` dependencies too.
So, for now trying to find native dependencies to use only native as an `externals`.
Again, thank you!
