### ISSUE TITLE
importing 'aws-amplify-react', ERROR: Uncaught SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by robbylucia** [electron-react-boilerplate/electron-react-boilerplate#2040]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date master branch
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Have module be imported and have my component/react app working and displaying.

## Current Behavior
Does not work, blank screen instead of component, browser console error:
`vm.js:74 Uncaught SyntaxError: Unexpected token :
    at new Script (vm.js:74)
    at createScript (vm.js:246)
    at Object.runInThisContext (vm.js:298)
    at Module._compile (internal/modules/cjs/loader.js:678)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)`

## Possible Solution

Not sure. I don't use Typescript or Flowtype, but it seems to be complaining a lot. Looks like Typescript in .js files? Flowtype doesn't like that I think. Not sure if it's related but it sure is confusing for me.

## Steps to Reproduce (for bugs)

1. Install everything, everything works fine.

2. Import 'aws-amplify-react' in a component.

3. yarn dev

4. Electron app starts but page breaks. Blank page and browser error.

## Context
I am trying to use aws-amplify in react/electron, but for some reason importing aws-amplify-react isn't working.

## Your Environment

- Node version : v11.1.0
- Version or Branch used : Master
- Operating System and version : Windows 10
- Link to your project : --

**Comment by amilajack** [comment]
This is definitely a library specific issue and doesn't have to do with the boilerplate. I would recommend filing an issue in the `aws-amplify-react` project. They may be importing some CSS using require or something similar to that. That's my guess.

**Comment by robbylucia** [comment]
Thanks, I opened a ticket here:
[https://github.com/aws-amplify/amplify-js/issues/2230](https://github.com/aws-amplify/amplify-js/issues/2230) in case anyone stumbles upon this.

You may have been right about the CSS guess, we'll see! Thanks!
