### ISSUE TITLE
yarn package isn't working for me :(

### ISSUE THREAD

**Issue by mentaman** [electron-react-boilerplate/electron-react-boilerplate#2056]
## Expected Behavior

yarn package without any errors

## Current Behavior

yarn dev works well.
but yarn package throws an error.
some "app-builder-lib" errors are thrown

here is the full error log
https://gist.github.com/mentaman/da99c5d8974be21d1411409e5e0ef373

## Steps to Reproduce (for bugs)

1. clone

2. yarn

3. yarn package

## Your Environment

- Windows 10 x64

- Node 10.13.0

- npm 6.4.1

- yarn 1.12.3

- Version or Branch used : master

- Link to your project : even tried to clone the boilertape as is and yarn package it again. but it still doesn't work.. so no need for my project.

- (I ran as adminstrator)

Thanks

**Comment by vikr01** [comment]
I'm not able to reproduce this, though I am using macOS. It seems that some kind of [infinite loop is occurring with the `node_modules`](https://gist.github.com/mentaman/da99c5d8974be21d1411409e5e0ef373#file-electron-react-boilerplate-error-L99) due to `electron-builder`. Hopefully someone with Windows is able to comment.

**Comment by amilajack** [comment]
This is an `electron-builder` issue. Please file an issue there. They will be able to help you out more since we cannot reproduce this.

https://github.com/electron-userland/electron-builder

**Comment by pbwei** [comment]
yarn package isn't working for me
Your Environment
macos 10.12.6

Node 8.9.1

npm 6.5.0

yarn 1.12.3

Version or Branch used : master

**Comment by vikr01** [comment]
@pbwei Please file a separate issue ticket and fill out all required details. You should also be using Node 10.x.
