### ISSUE TITLE
when package-all cannot find L"C:\\....

### ISSUE THREAD

**Issue by spcBackToLife** [electron-react-boilerplate/electron-react-boilerplate#2077]
Error: Exit code: 255. Command failed: /Users/xiaofan/Library/Caches/electron-builder/wine/wine-3.0.3-mac-10.13/bin/wine Z:\Users\xiaofan\Library\Caches\electron-builder\wix\wix-4.0.0.5512.2\candle.exe -arch x64 -dappDir=Z:\Users\xiaofan\Documents\program\new_browser\browser_for_package\xigua_browser_20181218\release\win-unpacked -pedantic -wx project.wxs
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
002d:err:display:macdrv_ChangeDisplaySettingsEx No matching mode found 1680x1050x32 @60!
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.

**Comment by vikr01** [comment]
Please use the issue template.
