### ISSUE TITLE
Unknow plugin add-module-exports defined in the file .babelrc

### ISSUE THREAD

**Issue by medaamarnadh** [electron-react-boilerplate/electron-react-boilerplate#2081]
I am using Windows 10
Nodejs version : 10.13 
When I am trying `npm install`
I am getting below error.

D:\CL\cl-fe\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "add-module-exports" specified in "D:\\CL\\cl-fe\\.babelrc" at 0, attempted to resolve relative to "D:\\CL\\cl-fe"
    at D:\CL\cl-fe\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)

**Comment by vikr01** [comment]
Please use the issue template.

**Comment by medaamarnadh** [comment]
@vikr01 Can you tell me one specific reason to close this issue ?

**Comment by amilajack** [comment]
@medaamarnadh You're supposed to use the issue template. It helps us help you.

**Comment by vikr01** [comment]
@medaamarnadh You intentionally erased everything that was pre-filled in the template. We state in our bug report issue template:

> [Please use the following issue template or your issue will be closed.](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blame/next/.github/ISSUE_TEMPLATE/1-Bug_report.md#L6)

Please file a new issue and select the "Bug report" option and fill out the template accordingly.
