### ISSUE TITLE
Invalid Host/Origin Header

### ISSUE THREAD

**Issue by giorgi-m** [electron-react-boilerplate/electron-react-boilerplate#2094]
Since this issue seems fairly easy to reproduce I will attempt to open this issue with the current info I have. 
I simply downloaded the project and did `yarn` and `yarn dev `and get the warnings in the image. Why?

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Current Behavior

I am seeing these warnings:
![screenshot from 2018-12-24 11-37-22](https://user-images.githubusercontent.com/41240312/50396250-4ec22500-0782-11e9-9757-6cf10678fc31.png)

## Steps to Reproduce (for bugs)

1. Download project

2. `yarn`

3. `yarn dev`

## Your Environment

- Node version : 10.14.2
- Version or Branch used :
- Operating System and version : Ubuntu 18.04.1 LTS
- Link to your project :

**Comment by unStone** [comment]
[how to fix](https://github.com/webpack/webpack-dev-server/issues/1604)

I set module webpack-dev-server 3.1.10

`"webpack-dev-server": "3.1.10",`

**Comment by giorgi-m** [comment]
@unStone inside `devDependencies`, right? ok I will try it bit later.
