### ISSUE TITLE
Is there any way to run sequelize migrations after installing electronjs application.

### ISSUE THREAD

**Issue by amaranadh-wal** [electron-react-boilerplate/electron-react-boilerplate#2096]
Hi Team,

Thanks for giving support to this electron-react-boilerplate. We are using this boilerplate for our enterprise project. We are using sqlite with sequelize ORM in our electron(electron-react-boilerplate) application. So, here the problem is how to execute sequelize migrations after installation completion and before application launching.  Can you guys please tell me the best way to do this ?

Regards,
Amar.

**Comment by amilajack** [comment]
In `main.dev.js`, create a state for if the migrations have been run or not. Store the state using some kind of state persistence solution such as one of the following:
* https://github.com/sindresorhus/electron-store
* https://github.com/electron-userland/electron-json-storage
```js
// main.dev.js
if (!store.get('migrationsHaveRun')) {
  runMigrations();
  store.set('migrationsHaveRun', true);
}
```

**Comment by amilajack** [comment]
Also if you are using this boilerplate for an enterprise, we kindly request that you make a contribution to our [boilerplate's opencollective](https://opencollective.com/electron-react-boilerplate-594). This project is in desperate need of having sustainable funding. Thank you.

**Comment by aguynamedben** [comment]
@amaranadh-wal We ran into some issues trying to manage SQLite/Sequelize migrations with umzug and its CLI because I believe umzug tries to dynamically `require` your migration files. That runs into Webpack's overriding of `require` (I think).

I still haven't been able to fully work it out, but generally: ERB uses webpack to perform most includes/requires at *compile time*. Many node libraries assume `require` will run at *run time*. Webpack does magic to override `require` so that at *compile time* code can be fetched.

It's similar to this issue: https://github.com/tj/node-migrate/issues/126

We ended up rolling our own fairly simple migrations system. We have to explicitly reference code for each migration so that Webpack finds it at *compile time*.

Please report back here if you find a cleaner way to do this with Sequelize/umzug. I'd love to not have to roll-my-own for this, but I think umzug and node-migrate assume *run time* access to `require`. I'd love to be proven wrong on this.

---

**app/backend/models/Migration.js**

We have our own Migration model. We manage migrations in SQLite, similar to how Rails keeps migration status in a Migrations table.

```js
import Sequelize from 'sequelize';

export default function (sequelize) {
  const Migration = sequelize.define('Migration', {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
    },
    executedAt: Sequelize.DATE,
  });

  return Migration;
}
```

**app/backend/models/index.js**

We organize all of our models (including Migration) in a models module. (Note that some of this code is also for SQLCipher encryption, which requires custom building node-sqlite3 and a bunch of other rabbit-hole tasks.)

```js
import path from 'path';
import Sequelize from 'sequelize';
import log from 'electron-log';

import createDocModel from './Doc';
import createMigrationModel from './Migration';

const { app } = require('electron').remote;


/* eslint-disable import/no-mutable-exports */
let sequelize;
let Doc;
let Migration;
/* eslint-enable import/no-mutable-exports */


export function updateModelsWithKey(sqlCipherKey) {
  if (process.type !== 'renderer') {
    throw new Error('trying to connect to database in main process');
  }

  const dbPath = path.join(app.getPath('userData'), 'ce.db');
  log.info(`Using SQLite database at ${dbPath}`);

  sequelize = new Sequelize('myapp', 'username', sqlCipherKey, {
    dialect: 'sqlite',
    storage: dbPath,
    logging: (_sql, _settings) => {
      // log.info(_sql.substring(0, 120));
      // log.info(_sql);
      // log.info(_settings);
    },
  });

  // Load each model file
  Doc = createDocModel(sequelize);
  Migration = createMigrationModel(sequelize);
}

export { sequelize, Doc, Migration };
```

**app/backend/migrations/ensureMigrationsTable.js**

Helper function to ensure migrations table is created. We await this function somewhere as our app starts.

```js
import Sequelize from 'sequelize';
import log from 'electron-log';

import { sequelize } from '../models';


export default async function ensureMigrationsTable() {
  log.info('Ensuring migrations table exists');
  await sequelize.queryInterface.createTable('Migrations', {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
    },
    executedAt: {
      allowNull: false,
      type: Sequelize.DATE,
    },
    createdAt: {
      allowNull: false,
      type: Sequelize.DATE,
    },
    updatedAt: {
      allowNull: false,
      type: Sequelize.DATE,
    },
  });
}
```

**Each migration has its own file**

There are files for each migration, like app/backend/migrations/1-create-docs-table.js, app/backend/migrations/2-do-other-thing.js.

Example:

```js
import Sequelize from 'sequelize';

import { sequelize } from '../models';

export default async function up() {
  await sequelize.queryInterface.addColumn('Docs', 'preview', {
    type: Sequelize.STRING,
  });

  await sequelize.queryInterface.addColumn('Docs', 'accountId', {
    type: Sequelize.STRING,
  });
}
```

**app/backend/migrations/migrate.js**

This provides methods that let you see what the current migration number is or run all the pending migrations.

```js
/**
 * Migrate SQLite database and manage Migrations table.
 * Eventually this probably should run in a separate process.
 *
 * For now we run migraitons from the renderer process since we show a static
 * migration screen with no buttons to click anyways.
 */

import log from 'electron-log';

import ensureMigrationsTable from './ensureMigrationsTable';
import up1 from './1-create-docs-table';
import up2 from './2-do-other-thing';

import { Doc, Migration } from '../models';

// Migrations (`up`) should be functions that return a Promise.
const migrations = {
  1: up1,
  2: up2,
};

export async function pendingMigrations() {
  await ensureMigrationsTable();

  const maxMigration = await Migration.findOne({ order: [['id', 'DESC']] });
  const maxMigrationNumber = maxMigration ? maxMigration.id : 0;
  log.info(`SQLite - Max migration is ${maxMigrationNumber}`);
  const pendingMigrationNumbers = Object.keys(migrations)
    .filter(migrationNumber => migrationNumber > maxMigrationNumber);

  return pendingMigrationNumbers;
}

export async function migrateDatabase() {
  await ensureMigrationsTable();

  const pendingMigrationNumbers = await pendingMigrations();
  if (pendingMigrationNumbers.length === 0) {
    log.info(`SQLite - No migrations to run, all up to date`);
    return;
  }

  // Use for-of loop to await in sequence
  // https://blog.lavrton.com/javascript-loops-how-to-handle-async-await-6252dd3c795
  // https://codeburst.io/foreach-vs-for-of-vs-for-in-tug-of-for-d8f93539664
  for (const migrationNumber of pendingMigrationNumbers) {
    log.info(`SQLite - Running migration ${migrationNumber}`);
    const up = migrations[migrationNumber];
    await up();
    await Migration.create({ id: migrationNumber, executedAt: new Date() });
    log.info(`SQLite - Migration ${migrationNumber} succeeded`);
  }

  const count = await Doc.count();
  log.info(`SQLite - There are now ${count} docs in the database`);
}
```

**Comment by amaranadh-wal** [comment]
I am using umzug module. It seems working but getting issue with relative paths.

**Comment by aguynamedben** [comment]
Yeah, that's the issue I ran into. Let me know if you figure out how to deploy is as [extraFiles](https://www.electron.build/configuration/contents#extrafiles) or [extraResources](https://www.electron.build/configuration/contents#extraresources). Last time I tried that I couldn't get Umzug to `require` the migration files correctly.

**Comment by narutosanjiv** [comment]
@aguynamedben Migration works on Dev mode perfectly but it fail in Production Mode.

**Comment by amaranadh-wal** [comment]
> @amaranadh-wal We ran into some issues trying to manage SQLite/Sequelize migrations with umzug and its CLI because I believe umzug tries to dynamically `require` your migration files. That runs into Webpack's overriding of `require` (I think).
> 
> I still haven't been able to fully work it out, but generally: ERB uses webpack to perform most includes/requires at _compile time_. Many node libraries assume `require` will run at _run time_. Webpack does magic to override `require` so that at _compile time_ code can be fetched.
> 
> It's similar to this issue: [tj/node-migrate#126](https://github.com/tj/node-migrate/issues/126)
> 
> We ended up rolling our own fairly simple migrations system. We have to explicitly reference code for each migration so that Webpack finds it at _compile time_.
> 
> Please report back here if you find a cleaner way to do this with Sequelize/umzug. I'd love to not have to roll-my-own for this, but I think umzug and node-migrate assume _run time_ access to `require`. I'd love to be proven wrong on this.
> 
> **app/backend/models/Migration.js**
> 
> We have our own Migration model. We manage migrations in SQLite, similar to how Rails keeps migration status in a Migrations table.
> 
> ```js
> import Sequelize from 'sequelize';
> 
> export default function (sequelize) {
>   const Migration = sequelize.define('Migration', {
>     id: {
>       type: Sequelize.INTEGER,
>       primaryKey: true,
>     },
>     executedAt: Sequelize.DATE,
>   });
> 
>   return Migration;
> }
> ```
> 
> **app/backend/models/index.js**
> 
> We organize all of our models (including Migration) in a models module. (Note that some of this code is also for SQLCipher encryption, which requires custom building node-sqlite3 and a bunch of other rabbit-hole tasks.)
> 
> ```js
> import path from 'path';
> import Sequelize from 'sequelize';
> import log from 'electron-log';
> 
> import createDocModel from './Doc';
> import createMigrationModel from './Migration';
> 
> const { app } = require('electron').remote;
> 
> 
> /* eslint-disable import/no-mutable-exports */
> let sequelize;
> let Doc;
> let Migration;
> /* eslint-enable import/no-mutable-exports */
> 
> 
> export function updateModelsWithKey(sqlCipherKey) {
>   if (process.type !== 'renderer') {
>     throw new Error('trying to connect to database in main process');
>   }
> 
>   const dbPath = path.join(app.getPath('userData'), 'ce.db');
>   log.info(`Using SQLite database at ${dbPath}`);
> 
>   sequelize = new Sequelize('myapp', 'username', sqlCipherKey, {
>     dialect: 'sqlite',
>     storage: dbPath,
>     logging: (_sql, _settings) => {
>       // log.info(_sql.substring(0, 120));
>       // log.info(_sql);
>       // log.info(_settings);
>     },
>   });
> 
>   // Load each model file
>   Doc = createDocModel(sequelize);
>   Migration = createMigrationModel(sequelize);
> }
> 
> export { sequelize, Doc, Migration };
> ```
> 
> **app/backend/migrations/ensureMigrationsTable.js**
> 
> Helper function to ensure migrations table is created. We await this function somewhere as our app starts.
> 
> ```js
> import Sequelize from 'sequelize';
> import log from 'electron-log';
> 
> import { sequelize } from '../models';
> 
> 
> export default async function ensureMigrationsTable() {
>   log.info('Ensuring migrations table exists');
>   await sequelize.queryInterface.createTable('Migrations', {
>     id: {
>       type: Sequelize.INTEGER,
>       primaryKey: true,
>     },
>     executedAt: {
>       allowNull: false,
>       type: Sequelize.DATE,
>     },
>     createdAt: {
>       allowNull: false,
>       type: Sequelize.DATE,
>     },
>     updatedAt: {
>       allowNull: false,
>       type: Sequelize.DATE,
>     },
>   });
> }
> ```
> 
> **Each migration has its own file**
> 
> There are files for each migration, like app/backend/migrations/1-create-docs-table.js, app/backend/migrations/2-do-other-thing.js.
> 
> Example:
> 
> ```js
> import Sequelize from 'sequelize';
> 
> import { sequelize } from '../models';
> 
> export default async function up() {
>   await sequelize.queryInterface.addColumn('Docs', 'preview', {
>     type: Sequelize.STRING,
>   });
> 
>   await sequelize.queryInterface.addColumn('Docs', 'accountId', {
>     type: Sequelize.STRING,
>   });
> }
> ```
> 
> **app/backend/migrations/migrate.js**
> 
> This provides methods that let you see what the current migration number is or run all the pending migrations.
> 
> ```js
> /**
>  * Migrate SQLite database and manage Migrations table.
>  * Eventually this probably should run in a separate process.
>  *
>  * For now we run migraitons from the renderer process since we show a static
>  * migration screen with no buttons to click anyways.
>  */
> 
> import log from 'electron-log';
> 
> import ensureMigrationsTable from './ensureMigrationsTable';
> import up1 from './1-create-docs-table';
> import up2 from './2-do-other-thing';
> 
> import { Doc, Migration } from '../models';
> 
> // Migrations (`up`) should be functions that return a Promise.
> const migrations = {
>   1: up1,
>   2: up2,
> };
> 
> export async function pendingMigrations() {
>   await ensureMigrationsTable();
> 
>   const maxMigration = await Migration.findOne({ order: [['id', 'DESC']] });
>   const maxMigrationNumber = maxMigration ? maxMigration.id : 0;
>   log.info(`SQLite - Max migration is ${maxMigrationNumber}`);
>   const pendingMigrationNumbers = Object.keys(migrations)
>     .filter(migrationNumber => migrationNumber > maxMigrationNumber);
> 
>   return pendingMigrationNumbers;
> }
> 
> export async function migrateDatabase() {
>   await ensureMigrationsTable();
> 
>   const pendingMigrationNumbers = await pendingMigrations();
>   if (pendingMigrationNumbers.length === 0) {
>     log.info(`SQLite - No migrations to run, all up to date`);
>     return;
>   }
> 
>   // Use for-of loop to await in sequence
>   // https://blog.lavrton.com/javascript-loops-how-to-handle-async-await-6252dd3c795
>   // https://codeburst.io/foreach-vs-for-of-vs-for-in-tug-of-for-d8f93539664
>   for (const migrationNumber of pendingMigrationNumbers) {
>     log.info(`SQLite - Running migration ${migrationNumber}`);
>     const up = migrations[migrationNumber];
>     await up();
>     await Migration.create({ id: migrationNumber, executedAt: new Date() });
>     log.info(`SQLite - Migration ${migrationNumber} succeeded`);
>   }
> 
>   const count = await Doc.count();
>   log.info(`SQLite - There are now ${count} docs in the database`);
> }
> ```

I am getting module not found issue in production environment in this approach. I found one more thing, webpack is executing all these files at the time of build. I do not want to do that. In my case I want to check migrations and seeds in app ready mode.

**Comment by amaranadh-wal** [comment]
@aguynamedben  Thank you so much. I have implemented a similar kind of module. Now, I have resolved the problem.

**Comment by amaranadh-wal** [comment]
Yes. I did in a similar way. What I did is 

- I have added migrations and seeders to extra files. Then they will go to the installation folder. 
- In the app ready event, I have written the migration and seeders execution function. 
- In case if there are no pending migrations and seeders then It will not execute any migration functions. 
- My next step is to add the auto-updater module. So, It has to fetch new migration files to the installation directory and they will execute automatically. This is my actual plan. 

If you would like to suggest something that would be great. 
@aguynamedben 
CC: @narutosanjiv

**Comment by AkhmedovSH** [comment]
> Yes. I did in a similar way. What I did is
> 
> * I have added migrations and seeders to extra files. Then they will go to the installation folder.
> * In the app ready event, I have written the migration and seeders execution function.
> * In case if there are no pending migrations and seeders then It will not execute any migration functions.
> * My next step is to add the auto-updater module. So, It has to fetch new migration files to the installation directory and they will execute automatically. This is my actual plan.
> 
> If you would like to suggest something that would be great.
> @aguynamedben
> CC: @narutosanjiv

Hi can you share the solution need same functionality

**Comment by AkhmedovSH** [comment]
> @aguynamedben Migration works on Dev mode perfectly but it fail in Production Mode.

any solution? same problem(
