### ISSUE TITLE
Cannot read property 'displayName' of null

### ISSUE THREAD

**Issue by blksheep93** [electron-react-boilerplate/electron-react-boilerplate#2101]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
Been having issues with a project I was working on for a bit based off of ERB. After a certain point, I wasn't able to use React DevTools anymore. It would return an error to the console of 'Uncaught TypeError: Cannot read property 'displayName' of null'.

Uncaught TypeError: Cannot read property 'displayName' of null .  backend.js:9159 
    at getDisplayName (backend.js:9159)
    at getDataFiber (backend.js:9888)
    at enqueueMount (backend.js:10158)
    at mountFiber (backend.js:10246)
    at backend.js:10306
    at Set.forEach (<anonymous>)
    at Object.walkTree (backend.js:10304)
    at backend.js:8534
    at <anonymous>:52:32
    at Array.map (<anonymous>)

## Current Behavior
Decided to run a clean install of ERB to troubleshoot and the same error is coming up. 

## Possible Solution
I would assume it would have something to do with my machine, but I want to validate my suspicion first since I have no clue as to what would be interfering with it. 

## Steps to Reproduce (for bugs)

1. Install

2. Run

3. Test React DevTools

4. Error

## Context

Straight clone of Boilerplate.

## Your Environment

- Node version : '6.4.1' 
- Chrome version: Version 71.0.3578.98 (Official Build) (64-bit)
- React DevTools: 3.4.3
- Version or Branch used : #2098 
- Operating System and version : macOS Mojave Vers. 10.14.2
- Link to your project :

The original project: https://github.com/blksheep93/trade-mgr/tree/fork
The test case project: Was a direct clone.

**Comment by vikr01** [comment]
> Using an up-to-date master branch
> Version or Branch used : #2098

Please use `master`, not `next` if you're a user.

> Using node 10.x
> Node version : '6.4.1'

Please use a correct version of `node` (10.x).

From your stacktrace, I'm not able to find a `backend.js` file in your repo so I don't know what code is causing it to occur.

`displayName` is injected from `babel` by [`@babel/plugin-transform-react-display-name`](https://babeljs.io/docs/en/babel-plugin-transform-react-display-name) if your component has a variable name. For example, using `class FooComponent extends Component...` will add a `displayName` `"FooComponent"`, while `class extends Component` will not have one.

**Comment by blksheep93** [comment]
I looked through all of my components and all of them look like they're labeled correctly. I'll try rolling back to master and I'll post an update when I can. 

I thought I responded to this before, but my version of node is 10.x. Again, I'll update when I can.

**Comment by blksheep93** [comment]
1. Cloned electron-react-boilerplate from master.
2. Unshallowed the repo
3. Changed remote to my repository

Should be a 1-to-1 copy of the boilerplate, and I'm still getting the error.

Here goes a link tot he repo: https://github.com/blksheep93/tmr2

Getting this warning when starting the main process, though I'm not sure if it's relevant.
`npm WARN lifecycle The node binary used for scripts is /var/folders/3n/2tdg2zy15gsdgjk5v4kkd31w0000gn/T/yarn--1546267682938-0.6620774973526982/node but npm is using /Users/tiko/.asdf/installs/nodejs/10.6.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.`

And here is the full stacktrace
```
 
Uncaught TypeError: Cannot read property 'displayName' of null
    at getDisplayName (backend.js:9159)
    at getDataFiber (backend.js:9888)
    at enqueueMount (backend.js:10158)
    at mountFiber (backend.js:10246)
    at backend.js:10306
    at Set.forEach (<anonymous>)
    at Object.walkTree (backend.js:10304)
    at backend.js:8534
    at <anonymous>:52:32
    at Array.map (<anonymous>)
    

getDisplayName | @ | backend.js:9159
-- | -- | --
  | getDataFiber | @ | backend.js:9888
  | enqueueMount | @ | backend.js:10158
  | mountFiber | @ | backend.js:10246
  | (anonymous) | @ | backend.js:10306
  | walkTree | @ | backend.js:10304
  | (anonymous) | @ | backend.js:8534
  | (anonymous) | @ | VM109:52
  | emit | @ | VM109:51
  | setupBackend | @ | backend.js:8621
  | module.exports | @ | backend.js:8567
  | (anonymous) | @ | backend.js:116
  | g | @ | backend.js:981
  | EventEmitter.emit | @ | backend.js:894
  | (anonymous) | @ | backend.js:302
  | (anonymous) | @ | backend.js:7619
  | (anonymous) | @ | backend.js:7618
  | _handleMessage | @ | backend.js:7611
  | listener | @ | backend.js:92
  | postMessage (async) |   |  
  | handleMessageFromDevtools | @ | VM229 contentScript.js:20
  | emit | @ | /Users/<user>/Docs/Pro…ensions/event.js:19
  | Port.ipcRenderer.on | @ | /Users/<user>/Docs/Pro…er/chrome-api.js:37
  | emit | @ | events.js:182



```

**Comment by amilajack** [comment]
It is very difficult to debug this because we don't know what the `backend.js` file looks like. Here's how you can help us help you:

* Update your repo to have the `backend.js`
* Follow the **exact** same steps of the installation and confirm if that works. Then run `yarn dev`. If that does not work then we know there's an issue with your environment. Please share if these things have worked for you.

**Comment by blksheep93** [comment]
Working down the list. 

1. I just pushed a copy of the backend.js file into my repo. It's a file from React-DevTools, and this one is just a copy, but at least you can read it now.
https://github.com/blksheep93/tmr2/blob/master/app/backend.js

2. I'll make another clean clone of the boilerplate in a second.

**Comment by blksheep93** [comment]
Just did a fresh install of the repo off using the instruction in the master branch and something is still interrupting React-DevTools. 

Can you explain how I might troubleshoot my environment to determine what the issue is?

**Comment by amilajack** [comment]
For Devtools issues, try this <https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools#devtools-extension> for the fresh clone

**Comment by blksheep93** [comment]
This looks like it worked. I can load the React-DevTools without getting the error.

**Comment by blksheep93** [comment]
And it's working on my other project as well. I guess the DevTool extensions needed to be updated? Thanks for the help troubleshooting.

**Comment by amilajack** [comment]
The updating only happens locally. The state for devtools is not shipped with the boilerplate. Its stored locally on your machine

**Comment by pjebs** [comment]
I have the same issue. Use to work and just stopped.
