### ISSUE TITLE
Creating a second window (using 0.17.1 config)

### ISSUE THREAD

**Issue by tomrbowden** [electron-react-boilerplate/electron-react-boilerplate#2108]
I've noticed that this issue has been brought up before: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1095
This thread is very helpful for anyone trying to add a second window, using a previous version of `electron-react-boilerplate`.

However, the new `electron-react-boilerplate` now has a different (and quite complex) config setup. Could anyone please outline the process with the new configuration?

**Comment by jp887** [comment]
I've just set this up in the app I'm working on. Basically I wanted a second window with the same webpack config as the first, and the code for the two windows separated into different folders under the /app directory. In the end it was fairly straight forward and the steps are not all that different from what has been described before. 

If it would be useful, I'd be happy to fork the boilerplate and set up an example repo for a 2 window app. The commit history would show the the steps required to create the second window.

**Comment by jp887** [comment]
@tomrbowden sorry this has taken a while. I've made an example repo here: https://github.com/jp887/electron-react-boilerplate/
