### ISSUE TITLE
Uncaught TypeError: Class constructor <ComponentName> cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Rafi993** [electron-react-boilerplate/electron-react-boilerplate#2109]
I cloned the repo and created a class component. But then when I change the state I get the error Uncaught TypeError: Class constructor <ComponentName> cannot be invoked without 'new'.
I did some dig through it seems that new babel preset compiles to es6 classes which may cause this error.

## Prerequisites

-  Using yarn 1.12.3
-  Using node v11.6.0
-  Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)

## Possible Solution

We can restrict the target that babel compiles to older version.

## Steps to Reproduce (for bugs)

1. I cloned the repo did  yarn 
2. Created a class component
3. App crashes when state changes

## Your Environment

- Node version : 11.6.0
- Version or Branch used : master
- Operating System and version : Linux (Debian)

**Comment by vikr01** [comment]
Did you attempt to run it with `node` 10 at all? We've had issues with `node` 11, which is why we specifically ask for you to check with version 10 in [the bug report template](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/new?labels=bug&template=1-Bug_report.md).

**Comment by Rafi993** [comment]
I was using node 8 I had that issue which is why I upgraded to node 11

**Comment by Rafi993** [comment]
I tried node 10.15 and it was resolved.
