### ISSUE TITLE
not mangled after set terserOptions: {               mangle: true             }

### ISSUE THREAD

**Issue by hugetiny** [electron-react-boilerplate/electron-react-boilerplate#2111]
* Operating System:MacOS 10.13.6
* Node Version:10.13.0
* NPM Version: latest
* webpack Version:4 ( latest )
* terser-webpack-plugin Version:1( latest )

### Expected Behavior

mangled

### Actual Behavior

not mangled

### Code

```js
optimization: {
    minimizer: process.env.E2E_BUILD
      ? []
      : [
          new TerserPlugin({
            parallel: true,
            sourceMap: false,
            cache: true,
            terserOptions: {
              mangle: true
            }
          }),
          new OptimizeCSSAssetsPlugin({
            cssProcessorOptions: {
              map: {
                inline: false,
                annotation: true
              }
            }
          })
        ]
  },
```

### How Do We Reproduce?

https://github.com/electron-react-boilerplate/electron-react-boilerplate.git
replace the webpack prod configs with code above

**Comment by vikr01** [comment]
We didn't make the `terser-webpack-plugin`, I think your issue ticket webpack-contrib/terser-webpack-plugin#51 is more appropriate.
