### ISSUE TITLE
One more shortcut when i click close on Windows 

### ISSUE THREAD

**Issue by jianfenkezhan** [electron-react-boilerplate/electron-react-boilerplate#2115]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
App is turned off normally.

## Current Behavior
After closing the desktop more than a shortcut, its name is ElectronReact, click to open after the default program of this repo. Very strange, anything about this repo was deleted.  how can I fix it?
![image](https://user-images.githubusercontent.com/6964781/50628858-dffc7d00-0f74-11e9-8865-fb55b3fbe4c4.png)

**Comment by vitalyliber** [comment]
I have the same issue. @jianfenkezhan do you have any solution? =)

**Comment by vitalyliber** [comment]
I replaced auto-update settings in packages.json. It works now.

**Comment by PeterEB** [comment]
Hi @vitalyliber , I have the same issue. How do you replaced packages.json?
