### ISSUE TITLE
How to add some directories to the installation directory.

### ISSUE THREAD

**Issue by amaranadh-wal** [electron-react-boilerplate/electron-react-boilerplate#2116]
## Prerequisites
Hi, 
I am using sqlite3 with sequelize module. So, I want to move one folder called migrations to the installed directory.
How to do that ?
I have added directories in package.json like 
`
 {
   "build":{
       "files":[
           "migrations/"
       ]
    }
 }
`
But, it is going to inside the app.asar folder. 
`__dirname` is pointing to the installed directory but not to the app.asar file.

- [-] Using yarn
- [ -] Using node 10.x
- [ -] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ -] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
The expected behavior is additional files has to go installed directory instead of app.asar file.

## Current Behavior
Right now, they are going to app.asar file.

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Context
I have added migration process code by using [Umzug](https://github.com/sequelize/umzug) in the app.on('ready') event.

## Your Environment

Installed directory is: 
C:\Users\WAL\AppData\Local\Programs\electron-react-boilerplate

- Node version : 10.13
- Version or Branch used :
- Operating System and version : Windows 10
- Link to your project : NA

**Comment by wangsijie** [comment]
In run time, `app.asar` is somehow extracted, which means files inside can be directly accessed or executed, have you tried that?

**Comment by amaranadh-wal** [comment]
I got a solution for this. We can add `extraFiles`

**Comment by loganknecht** [comment]
@amaranadh-wal Can you elaborate on the `extraFiles` solution? I'm experiencing the same issue. When I package my executable I am getting this file path for it.

`/Users/lknecht/Repositories/FAUST_Nextflow_Desktop/electron_faust_nextflow_desktop/release/mac/ElectronReact.app/Contents/Resources/app.asar/binaries/r/r-mac/R`

**Comment by amaranadh-wal** [comment]
We can give like below in the package.json @loganknecht 
`"build": {
    "productName": "xxxxxxxxxx",
    "appId": "xxxx.xxxx..xxxxxxxxxx",
    "extraFiles": [
      {
        "from": "app/migrations",
        "to": "app/migrations"
      }]
}`

**Comment by loganknecht** [comment]
Thank you @amaranadh-wal!

I managed to get this worked out and will be updating my post in #2420 to explain the solution! Your answer is very much the correct solution, however in production it requires accounting for the fact that the `app.asar` that it's bundled into is not a directory. So you have to create helper functions to access from the app directory for resources. By doing that you need to slip in a `..` in production so that you can correctly link to the directory needed.

Thank you again @amaranadh-wal !

**Comment by amaranadh-wal** [comment]
> Thank you @amaranadh-wal!
> 
> I managed to get this worked out and will be updating my post in #2420 to explain the solution! Your answer is very much the correct solution, however in production it requires accounting for the fact that the `app.asar` that it's bundled into is not a directory. So you have to create helper functions to access from the app directory for resources. By doing that you need to slip in a `..` in production so that you can correctly link to the directory needed.
> 
> Thank you again @amaranadh-wal !

Yes. Your point is correct regarding the production environment. I did the same for my project
