### ISSUE TITLE
Install and run MSI with admin previledges Windows

### ISSUE THREAD

**Issue by eddiebeazer** [electron-react-boilerplate/electron-react-boilerplate#2130]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>

Hey everyone, I just wanted to check and see if anyone has successfully created a msi installer that installs their app as an administrator and then runs as admin without UAC popping up on application start.

**Comment by MrSharpp** [comment]
any solution?
