### ISSUE TITLE
Typescript example

### ISSUE THREAD

**Issue by gorilla-devs** [electron-react-boilerplate/electron-react-boilerplate#2134]
I found [this](https://github.com/electron-react-boilerplate/examples/tree/master/examples/typescript) typescript boilerplate example in your "example" repo. Is it safe to use or has any bug or WIP? I tried it and looks pretty stable but i wanted to be sure before committing too much to it

**Comment by amilajack** [comment]
@gorilla-devs it's stable and good to use
