### ISSUE TITLE
rxjs source not stoping after unsubscribing

### ISSUE THREAD

**Issue by paulluap** [electron-react-boilerplate/electron-react-boilerplate#2138]
a call to unsubscribe of the rxjs subscription does not stop the source.

The subscription is created as follows: 
```
+      const Rx = require('rxjs')
+      const { tap } = require('rxjs/operators')
+      const subscription = Rx.interval(500).pipe(
+          tap( v=>console.log('tap ' + v))
+          ).subscribe(v=>console.log('subscribed: ' + v))
+      Rx.timer(2000).subscribe(()=>{
+          console.log('unsubscribing ... ')
+          subscription.unsubscribe()
+      })
```
which is unsubscribed after 2 seconds. 
But the tap operations still runs.  

This does not happen in 
 - my chrome (Version 71.0.3578.98) https://jsfiddle.net/paullu/crdbu34x/3/
 - electron quick start https://github.com/electron/electron-quick-start (by adding the same js code in the script section in index.html)
 - a react app : https://codesandbox.io/s/01j935q7m0
 - nodejs 

## Prerequisites

- [x] Using yarn
- [x] Using node v11.6.0
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
The console should print : 
```
tap 0
subscribed: 0
...
unsubscribing ...
//and no more "tap ..."
```

## Current Behavior
The console prints : 
```
tap 0
subscribed: 0
...
unsubscribing ...
tap 4
tap 5
...
```
and the source stream never stops...

## Steps to Reproduce (for bugs)

```
git clone --depth 1 --single-branch --branch master https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
```
Then install rxjs and add the lines of experiment code in HomePage.js to reproduce the issue.
```
yarn add rxjs
```

Complete diff: 
```diff
diff --git a/app/containers/HomePage.js b/app/containers/HomePage.js
index 3822674..9815263 100644
--- a/app/containers/HomePage.js
+++ b/app/containers/HomePage.js
@@ -4,6 +4,16 @@ import Home from '../components/Home';

 type Props = {};

+      const Rx = require('rxjs')
+      const { tap } = require('rxjs/operators')
+      const subscription = Rx.interval(500).pipe(
+          tap( v=>console.log('tap ' + v))
+          ).subscribe(v=>console.log('subscribed: ' + v))
+      Rx.timer(2000).subscribe(()=>{
+          console.log('unsubscribing ... ')
+          subscription.unsubscribe()
+      })
+
 export default class HomePage extends Component<Props> {
   props: Props;

diff --git a/package.json b/package.json
index 48a6a86..4dec245 100644
--- a/package.json
+++ b/package.json
@@ -269,6 +269,7 @@
     "react-router-dom": "^4.3.1",
     "redux": "^4.0.1",
     "redux-thunk": "^2.3.0",
+    "rxjs": "^6.3.3",
     "source-map-support": "^0.5.9"
   },
```
## Context

I'm using rxjs to construct repeatedly running jobs, and intend to start/stop them by simply subscribing and unsubscribing. 

## Your Environment

- Node version : v11.6.0
- Version or Branch used : commit 3ac2a766a6e30f8353c39b2f6810d61828be5c1d (grafted, HEAD -> master, tag: v0.17.1, origin/master)
- Operating System and version : MacOS Mojave Version 10.14.2 (18C54)

**Comment by Noitidart** [comment]
Oh my gosh. I'm having this same exact problem. And I can't replicate it anywhere else outside of electron. Can it be electron?

Were you able to find a solution? People on stackoverflow are confused as well - https://stackoverflow.com/q/55970104/1828637

**Comment by Noitidart** [comment]
I tested my code and your code in a fresh electron app, following this guide here - https://electronjs.org/docs/tutorial/first-app - and it worked! It must be electron-react-boilerplate doing something.

**Comment by Noitidart** [comment]
Its weird, i copied and pasted your code, but its not reproducing in my electron-react-boilerplate renderer. Its unsubscribing and stopping the timer.
