### ISSUE TITLE
Hot reload main process

### ISSUE THREAD

**Issue by kenhuang** [electron-react-boilerplate/electron-react-boilerplate#2141]
The current `dev` process launch `start-renderer-dev`first, then spawn a [process](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/configs/webpack.config.renderer.dev.babel.js#L263) to start `start-main-dev` [process](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/package.json#L30), is there a way to apply webpack config to the main process in dev mode? I think in production mode it does.

Related launch step:
```
"start-main-dev": "cross-env HOT=1 NODE_ENV=development electron -r @babel/register ./app/main.dev.js",
```

saw possiable solution from other project here:
https://github.com/input-output-hk/daedalus/blob/develop/gulpfile.js#L44

**Comment by theogravity** [comment]
Confused how this isn't a thing - is it normal for devs using this project to have to kill the main process and re-build each time they want to make a change to the main process code?

**Comment by ahmad-invozone** [comment]
@jeremyong Can you please describe little bit more how did you get this working locally using web-pack?

Though hot reload must be a built-in feature of this boilerplate. It's very annoying to kill the main process each time and re-build to see changes.

**Comment by ahmad-invozone** [comment]
@amilajack Can we get this feature in v3.0.0, any chances?

**Comment by theogravity** [comment]
I think at this point you're better off using 

https://www.electronforge.io

It's an all-in-one package like react create app that also includes hot reloading.

**Comment by MrRobz** [comment]
some like this would be nice. taken from electron-forge docs
"For the main process reloading, just type `rs` in the console you launched electron-forge`
 
![image](https://user-images.githubusercontent.com/21201812/129476631-a982d57a-b6fc-44cc-b581-4507fd42afcd.png)

**Comment by Jimmy-JS** [comment]
Hi @amilajack , is it working in ver 4.0.0 ? I tried to change something (global shortcut) in `src/main/main.js` but it doesn't hot reload the main process. and I also notice it's get removed from the changes list as well:

<img width="325" alt="2021-10-03 at 18 51 50@2x" src="https://user-images.githubusercontent.com/9798426/135752390-83c29409-8616-4b6b-8bb1-023f8bc2a007.png">

**Comment by amilajack** [comment]
Accidentally closed this. Thanks for the heads up!

**Comment by SergiiMarkin** [comment]
Hi @amilajack , 
It is very annoying to kill the main process every time I made a change in main process.
This is essential function for this boilerplate project.
😉

**Comment by amilajack** [comment]
Agreed. Coming soon

**Comment by theogravity** [comment]
I also recommend this as an alternative to electron-forge as it uses vite to do extremely fast compiles and no rs command is required for reloading

https://github.com/cawa-93/vite-electron-builder

**Comment by SergiiMarkin** [comment]
> Hi @amilajack , It is very annoying to kill the main process every time I made a change in main process. This is essential function for this boilerplate project. 😉

We can use electronmon to reload main process

**Comment by jgresham** [comment]
Just tested with `"electronmon": "^2.0.2"` and latest ERB version and it looks like it works. 

Steps to add:
`npm i --save-dev electronmon`
Change `electron` to `electronmon` in the `start:main` command in `package.json`

Because `electronmon`'s last release was about a year ago and the README says only up to electron 11 is supported (curr version is 16), I'm thinking it would be a good idea to create another command instead of modifying `start`. Ex. create a `npm run start-hot-reload` which is uses `electronmon`

**Comment by nanu2000** [comment]
@jgresham Thanks for finding something that works, I haven't had the time to dig around. This will save me from so much time and pain.

`electronmon` works without a problem on my application.

**Comment by jgresham** [comment]
If anyone can test or review my PR, please take a look. #3180

**Comment by amilajack** [comment]
Fixed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3180
