### ISSUE TITLE
Windows surface tab not opening virtual keyboard

### ISSUE THREAD

**Issue by amaranadh-wal** [electron-react-boilerplate/electron-react-boilerplate#2143]
## Prerequisites

-  Using yarn
-  Using node 10.x
- Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)

## Expected Behavior

I have installed my application in windows surface tab. When you focus on a text box it should open a virtual keyboard to type text in the textbox

## Current Behavior
It's not opening any virtual key board when focus on a text box.

## Steps to Reproduce (for bugs)

1. Generate a Electron-react-boilerplate installable application which contains a form. Install it on windows surface tab. 

2. Open the application and focus on any form the form field where you need to fill some information.

## Context
It is a major issue on Windows surface tablet. Becuase, we could not proceed to the step1 atleast in our application.

## Your Environment

- Node version : 10.15
- Version or Branch used :  N/A
- Operating System and version : Windows 10
- Link to your project : N/A

**Comment by amaranadh-wal** [comment]
@narutosanjiv I am adding as a follower to this issue.

**Comment by amaranadh-wal** [comment]
@aguynamedben Can you suggest some solution to this issue?

**Comment by aguynamedben** [comment]
I do not use Windows, sorry.

**Comment by amaranadh-wal** [comment]
> I do not use Windows, sorry.

No issue. Thanks for the quick response.
