### ISSUE TITLE
Viewing Electron Content In Browser for Testing

### ISSUE THREAD

**Issue by redstubble** [electron-react-boilerplate/electron-react-boilerplate#2146]
New to Electron. Is it possible to view the electron app content (app.html) in the browser e.g. localhost:1212? 
I am trying to get a callback working for oauth, but I am getting a blank screen within the electron app,

I have tried following this tutorial (https://blog.ecliptic.io/google-auth-in-electron-a47b773940ae). After login the redirect listener (below) doesnt trigger and I am left with an empty window. Not sure how best to troubleshoot.

```
authWindow.webContents.on('did-get-redirect-request', (event, oldUrl, newUrl) => {
      handleNavigation(newUrl)
    })
```

 Any hints and tips would be greatly appreciated. Not sure if this is related to webpack or react router.

**Comment by amilajack** [comment]
What do your logs say?

**Comment by redstubble** [comment]
When I load localhost:1212 I get the following browser error:
`Cannot GET /`
In the terminal I get 
`Rewriting GET / to /index.html`
I found this blog post. Is this related? https://tylermcginnis.com/react-router-cannot-get-url-refresh/

**Comment by redstubble** [comment]
This issue outlines the problem with rendering pages in the browser but it doesn't resolve how I can use this application to make a callback in electron. 
#1488 
As I outlined earlier using a file callback points the window at a static app.html without process.env modules etc. and just renders a blank page as above.
