### ISSUE TITLE
How do I specify a file path for the preload attribute of the webview component?

### ISSUE THREAD

**Issue by sfDev001** [electron-react-boilerplate/electron-react-boilerplate#2154]
I want to specify a file path for the preload attribute of the webview component. Although it works normally in the development build, in the product build, it becomes an error "Error: Can not find module".

`<webview src="https://www.github.com/" preload="./test.js"></webview>`

> Specifies a script that will be loaded before other scripts run in the guest page. The protocol of script's URL must be either file: or asar:, because it will be loaded by require in guest page under the hood.

[https://electronjs.org/docs/api/webview-tag#preload](https://electronjs.org/docs/api/webview-tag#preload)

**Comment by barretron** [comment]
Depending on where the file is, you may need to specify it in `package.json`

```json
{
  "build": {
    "files": [
      "app/dist/",
      "app/app.html",
      "app/main.prod.js",
      "app/main.prod.js.map",
      "app/test.js",
      "package.json"
    ]
  }
}
```

**Comment by sfDev001** [comment]
Thank you for your help.
