### ISSUE TITLE
migrate to azure pipelines

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#2155]
hopefully this will help us avoid windows issues. Also I've had great experiences with it so far and so have others. Would be worthwhile to investigate migrating ERB to it.

**Comment by nazarsh** [comment]
Definitely +1 on Azure pipelines! On that note, would Actions be plausible for ERB?
```
Linux, macOS, Windows, ARM, and containers
Hosted runners for every major OS make it easy to build and test all your projects.
Run directly on a VM or inside a container. Use your own VMs, in the cloud or on-prem, 
with self-hosted runners.
```

**Comment by amilajack** [comment]
I would actually prefer Actions over Azure! But a PR for either would be fine.

**Comment by nazarsh** [comment]
I will give it a go in the next few days and might ping you with questions as I am porting things over

**Comment by amilajack** [comment]
Awesome! Would be ideal if we can get it working for Windows as well but thats not a requirement for now.

**Comment by amilajack** [comment]
I've found a [working azure config](https://github.com/shamofu/electron-react-parcel-boilerplate/blob/master/azure-pipelines.yml) we can use as a reference.

**Comment by nazarsh** [comment]
Awesome thanks! I left off on the testcafe step and looks like what you are
linking should work - will take a look in a bit.

**Comment by amilajack** [comment]
Added this in `v1.0.0`
