### ISSUE TITLE
Update dev tools link in #issues template leads to blank page

### ISSUE THREAD

**Issue by ahtee** [electron-react-boilerplate/electron-react-boilerplate#2156]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Clicking the  See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools) above in the checkboxes should direct to the Wiki page with Updating DevTools information.

## Current Behavior

Clicking link wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools) opens a new wiki page ready for editing.

## Possible Solution

Create devtools wiki, or remove the checkbox from `bug` issue template.
default branch for this is `next`, should it be `master`?
`yarn dev` fails but `yarn start` works as expected, may need to update this info in the `README.md`. Happy to help with that 💯  

## Steps to Reproduce (for bugs)

1. Remove project directory from local machine, if already cloned. Clone the repo and `cd electron-react-boilerplate`

2. run `yarn install` then `yarn dev`

3. Terminal shows output:

```
yarn run v1.13.0
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

4. run `yarn start`. electron window opens with boilerplate application.

## Context

Trying to get started with electron-based react development for a work project and came across this boilerplate.

No changes were made.

## Your Environment

- Node version : `v10.15.0`
- Version or Branch used : default branch is `next`
- Operating System and version : macOS Mojave
- Link to your project : Have not pushed to my local repo.

**Comment by amilajack** [comment]
@ahtee is this still an issue?

**Comment by ahtee** [comment]
Im on yarn 1.16.0 now so im not sure but i dont have a current electron project. I'll close
