### ISSUE TITLE
eslint shutdown issue

### ISSUE THREAD

**Issue by supersudh** [electron-react-boilerplate/electron-react-boilerplate#2157]
I am using the **.eslintrc.json**  file that came with the boilerplate. The eslint server stops running and I get the below error logs in my VSCODE console's eslint output.

```
[Info  - 10:36:36 PM] ESLint server stopped.
[Info  - 10:36:36 PM] ESLint server running in node v10.2.0
[Info  - 10:36:36 PM] ESLint server is running.
"process.env.NODE_ENV" must be "development" to use this webpack config
[Error - 10:38:09 PM] Server process exited with code undefined. This usually indicates a misconfigured ESLint setup.
[Error - 10:38:10 PM] Connection to server got closed. Server will not be restarted.
[Info  - 10:38:10 PM] ESLint server stopped.
``` 

Not sure why it says nodev10.2.0 when I don't have that version installed. I only have 10.15.1 installed.

## Prerequisites

- [ :green_heart:] Using yarn
- [ :green_heart:] Using node 10.x
- [:green_heart: ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [:green_heart: ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [:green_heart: ] Link to stacktrace in a Gist (for bugs)
- [:green_heart: ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [:green_heart: ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
eslint server must work properly.

## Current Behavior
Its crashing

## Your Environment

- Node version : 10.15.1
- Version or Branch used :
- Operating System and version : osx mojave latest version
- Link to your project : -

**Comment by vikr01** [comment]
What matters is if it works with the actual `eslint` CLI. If `yarn lint` does not crash for you, then you need to file a bug for [the plugin](https://github.com/Microsoft/vscode-eslint).

**Comment by supersudh** [comment]
Seems like this is an eslint issue. I am not facing the shutdown anymore if I try the below solution.

Add **process.env.NODE_ENV = 'development';** in _./node_modules/eslint/lib/api.js_

**Comment by vikr01** [comment]
That's not a "solution".

Please run the `yarn lint` command and post the output here.

**Comment by supersudh** [comment]
yarn lint succeeds. Intended output is displayed.

**Comment by vikr01** [comment]
If you notice [we set `NODE_ENV=development` before running `eslint` in our script](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/package.json#L15). So the issue is neither with the boilerplate nor `eslint`, it's with [`vscode-eslint`](https://github.com/Microsoft/vscode-eslint) and setting the environment variable.

**Comment by Skriptach** [comment]
@vikr01 

>  it's with vscode-eslint and setting the environment variable.

So how to set that env to

**Comment by p4rse** [comment]
https://github.com/Microsoft/vscode-eslint/issues/590#issuecomment-448943357

It's `internals/scripts/CheckNodeEnv.js` that calls `process.exit(2)`which makes ESLint server shutdown.

I just commented that `process.exit(2)` line and all is good.
Another solution is set `process.env.NODE_ENV` to `"development"`.

**Comment by Skriptach** [comment]
Hello @p4rse
How can I set `process.env.NODE_ENV` in VS Code **only** for ESLint?

**Comment by p4rse** [comment]
That's something I think is not doable!

If you are here because of the same issue that ESlint shutdowns, just follow my comment above and it will help you.

**Comment by mustafahafidi** [comment]
@Skriptach if you're using this boilerplate then, eslint configuration uses webpack renderer configuration file. So to fix this issue is enough to set `process.env.NODE_ENV = 'development'` only in webpack.config.eslint.js before webpack conf is exported, like this:

```
process.env.NODE_ENV = 'development';
module.exports = require('./webpack.config.renderer.dev.babel').default;
```
this way nodeenv `development` is restricted to eslint (vscode extension included).

Also, it's not safe to modify CheckNodeEnv.js, since you might end up running dev scripts in production in the future and not realize it.
