### ISSUE TITLE
Can't use css Id or class to style react component

### ISSUE THREAD

**Issue by tufailra97** [electron-react-boilerplate/electron-react-boilerplate#2161]
## Prerequisites
- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
Apply css styling to react component
## Current Behavior
No css styles is applied. However if I import css file `import Sidebar from './Sidebar.css'` and apply add the class to the element like `<div id = {Sidebar.sidebar}></div>` then it works.
## Steps to Reproduce (for bugs)
1. Create react component
```
import React, { Component } from 'react';
import './Sidebar.scss';
export class Sidebar extends Component {

  render() {
    return (
      <div id = 'sidebar'>
        <h1>Sidebar</h1>
      </div>
    )
  }
}

export default Sidebar;

```

2. Create css styling for the component 
```
#sidebar, .sidebar {
  width: 30%;
  background-color: navy;
}
```

## Context
Trying to learn how to build cross platform application using React and Electron.
## Environment

- Node version : v10.15.2
- Version or Branch used : master
- Operating System and version : Windows 10
- Link to your project :

**Comment by vikr01** [comment]
You need to use `className`, not `id`.

**Comment by tufailra97** [comment]
Even using className nothing happens.

**Comment by reZach** [comment]
I have the same bug.

**Comment by reZach** [comment]
@tufailra97 Based on this answer, https://stackoverflow.com/a/36844502/1837080, your app is looking for css files in the `app` directory. This is why in **app/index.js**, the call `import './app.global.css'` works but not in a custom component.

What I think will work for you is using this code in your component: `import styles from './Sidebar.scss';` and then when you want to use the style in the component,... `<div id={styles.sidebar}>...</div>`. If you need to intermix css classes, look to this answer: https://stackoverflow.com/a/43552631/1837080.

**Comment by amilajack** [comment]
Seems like this is resolved

**Comment by reZach** [comment]
@larissa-n there isn't a way to do both? I'm trying to use an external library that relies on the second option you presented, while the rest of my code is using modules at the moment.

**Comment by reZach** [comment]
@tufailra97 and @larissa-n , you can load both css modules and entire css files like this: https://stackoverflow.com/questions/59450588/webpack-module-parse-failed-you-may-need-an-appropriate-loader-to-handle-this

**Comment by alirezakay** [comment]
I had a similar problem in `react-electron-boilerplate v2.3.0` as shown below:

```
export 'default' (imported as 'styles') was not found in './styles.css'
```

At first, I used this approach to include CSS files:

``` 
import styles from './Index.css';
```

But after probing the **.erb/configs** folder and the **webpack.config.renderer.dev.babel.js** file, I realised that there are at least two approaches to include css/scss files:

1. One is using the postfix: **.global**. for example, a file named `style.global.css`. using this way, you just include the file like `import 'style.global.css';`
2. The second approach is using module-based importing. just like the above way the community answered before: `import styles from './Index.css';`

Although the second approach was practical in **dev** mode, in the `production` **packaging**, I got problems and experienced console errors after running the executable app after building and packaging!

So I took a quick look at the **webpack.config.renderer.prod.babel.js** (the production config) and noticed that this config is pretty different from the dev configurations. and probably it doesn't support the module-based CSS importing!!!
I think this could be a flaw in the configs and the **electron-react-boilerplate** team should pay more attention to this side of the project someday!

Finally, the easiest way I found was changing the prod file: **webpack.config.renderer.prod.babel.js** 

The rules section for CSS part:

```
{
        test: /\.global\.s?css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              // `./dist` can't be inerhited for publicPath for styles. Otherwise generated paths will be ./dist/dist
              publicPath: './',
            },
          },
          'css-loader',
          'sass-loader',
        ],
      },
      {
        test: /^((?!\.global).)*\.css$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: '[name]__[local]__[hash:base64:5]',
              },
              sourceMap: true,
              importLoaders: 1,
            },
          },
        ],
      },
```
