### ISSUE TITLE
Include @wranggle/rpc?

### ISSUE THREAD

**Issue by ferbs** [electron-react-boilerplate/electron-react-boilerplate#2162]
Communicating between main and renderer processes is common to most all Electron apps and [@wranggle/rpc](https://github.com/wranggle/rpc) makes these interactions much easier and cleaner than hand-coded messaging. I'm the author and would be happy to drop it into electron-react-boilerplate if you'd like to include it.

**Comment by amilajack** [comment]
We already have a PR open for this: https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1921
