### ISSUE TITLE
on mac and pack for mac, username/password prompt show up 21 time? 

### ISSUE THREAD

**Issue by code-brewer** [electron-react-boilerplate/electron-react-boilerplate#2163]
It is terrible, on my MacBook, the packing process for Mac prompt me to input username/password 21 times.
Is this normal ? or something wrong happen?

I have try pack three time, so i input about 60 times  username/password.

**Comment by dbvrac** [comment]
Sounds like something was installed as root (or using sudo) in your project node_modules folder, in /usr/local/bin, or your home directory depending on your setup. Were you prompted for password when you ran `yarn install`?

**Comment by code-brewer** [comment]
Having retry by remove node_modules and use daily use account ( non-root ) to run 'yarn install' command, then run 'yarn package --mac',  again the user/password dialog pops endless while the logs says: 
`
  • electron-builder version=20.34.0

  • loaded configuration file=package.json ("build" field)

  • writing effective config file=release/builder-effective-config.yaml

  • no native production dependencies

  • packaging       platform=darwin arch=x64 electron=3.0.10 appOutDir=release/mac

  • signing         file=release/mac/ElectronReact.app identityName=my-gdb-apple-cert identityHash=0E02F8132A5CAAECBEEA624D210E8408B1745A19 provisioningProfile=none
`

**Comment by dbvrac** [comment]
I don't know anything about code signing, so I can't help you with that.

**Comment by code-brewer** [comment]
@dbvrac 
Thanks for your help and times cost. 

After hours struggle i found the solution, just add  ` "identity": null ` to build.mac section work。

`"mac": {
  "category": "myTestApp",
  "identity": null
},`

Current i do not register apple personal developer account and i just want to create a DMG without code signing.

**Comment by dbvrac** [comment]
No problem, though I didn't do much. 
Best of luck on your project.
