### ISSUE TITLE
why not place react package to devDependencies? and so for others that used by render process.

### ISSUE THREAD

**Issue by code-brewer** [electron-react-boilerplate/electron-react-boilerplate#2167]
I'm puzzle why not put packages like react/react-dom etc under devDependencies category?

I regard that react and related packages have been bundler into one bundle.js by webpack, so they don't need to be packed into installer.

What more, i think, if bundled by webpack, all package used by render process can be move to devDependencies to avoid be wrapped into installer.

 Do i right?  

All my purpose is to reduce the installer file size.

**Comment by vikr01** [comment]
You're right, this was mentioned in a discussion in [#2005](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2005#issuecomment-439207882). I can't remember if there was a reason why we didn't end up making these changes.
