### ISSUE TITLE
React Hooks support

### ISSUE THREAD

**Issue by suchcodemuchwow** [electron-react-boilerplate/electron-react-boilerplate#2170]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
Is it possible to use react hooks by upgrading react packages. Are there anyone who has tried that and experienced versioning issues.

**Comment by amilajack** [comment]
Yes, this is possible

**Comment by clytras** [comment]
@amilajack unfortunately react hooks, although **do work in production** release, they **don't work on development with HMR**. I have also added a `resolve` to `@hot-loader/react-dom` inside `webpack.config.renderer.dev.babel.js` like this:

```
resolve: {
  alias: {
    'react-dom': '@hot-loader/react-dom'
  }
},
```
but it didn't do nothing for dev and hmr.
Should I create a new issue or we can open this one?

**Comment by kas** [comment]
Even after updating react, react-do, and react-hot-loader, I am getting this error in the console:

![image](https://user-images.githubusercontent.com/7661552/62750215-2c7ccf00-ba14-11e9-9ce0-f2675e2d7cad.png)
