### ISSUE TITLE
Including external js file works only on dev

### ISSUE THREAD

**Issue by stefanmaco** [electron-react-boilerplate/electron-react-boilerplate#2181]
## Prerequisites

- [x ] Using yarn
- [ ] Using node 10.x
- [x ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Module to be load in production. It's workign only if I add DEBUG_PROD=true in order to catch the error.

## Current Behavior

If I package the app with DEBUG_PROD=true the module is loaded, but without this flag it's missing.

## Steps to Reproduce (for bugs)

1. Added 
var azScript = document.createElement('script');
azScript.src = 'https://app.appzi.io/bootstrap/bundle.js?token=<token>';
azScript.async = true;
document.head.appendChild(azScript);
in index.js after render. That's what their support team asked me tot do. 
2. Working on dev, not in production.
## Context

I'm trying to include Appzi module (https://www.appzi.com/) in my app and it's working well on dev and when I have DEBUG_PROD=true. But for production the widget it's missing and I can't find the error.

## Your Environment

- Node version : 9.10.0
- Version or Branch used :
- Operating System and version : macOS Mojave 10.14.1
- Link to your project :

**Comment by stefanmaco** [comment]
OK, now I'm really confused. Tried to set an interval and it works after some iterations. 
setInterval(function() {
  if (!window.appzi) {
    var azScript = document.createElement('script');
    azScript.src = 'https://app.appzi.io/bootstrap/bundle.js?token=my_token';
    azScript.async = true;
    document.head.appendChild(azScript);
  }
}, 3000);

**Comment by kronenbourg** [comment]
I'm encountering the same issue as well. Wondering if anyone managed to find a solution, Appzi is able to send the feedback correctly but the snapshot captured does not have any styles applied to it

**Comment by stefanmaco** [comment]
@kronenbourg Try to set an interval like I've did above. And about the snapshot it's impossible to generate it from an electron app as the css is bundled locally.  Appzi and other capturing apps like hotjar renders the page on their server with something like phantomjs or even using an borderless electron for example. And they use the css files from the target page(which hosted somewhere, it's not locally). 
If you really need the snapshot you can use desktopCapturer (check electron api) and store this in your server with a identifier of the conversation. Check this example: https://ourcodeworld.com/articles/read/280/creating-screenshots-of-your-app-or-the-screen-in-electron-framework
