### ISSUE TITLE
How to disable devtools in dev

### ISSUE THREAD

**Issue by kubilaysalih** [electron-react-boilerplate/electron-react-boilerplate#2196]
I just want to open the devtools panel whenever I want. How can we close the devtools in the development environment by default? 

In addition, how can we set the default position of this devtools because I don't want a separate window for devtools.

What am I missing?

**Comment by andhapp** [comment]
Hello @kubilaysalih,

Just to clarify your questions.

> I just want to open the devtools panel whenever I want. How can we close the devtools in the development environment by default?
> 

I have to open devtools window manually. Does it open for you automatically every time you run up the app in dev?

Might be worth looking at [configureStore.dev.js](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/app/store/configureStore.dev.js#L44) file.
