### ISSUE TITLE
virtual keyboard not opening when focus on text box 

### ISSUE THREAD

**Issue by amaranadh-wal** [electron-react-boilerplate/electron-react-boilerplate#2198]
I am using electron-react-boilerplate. I am running my application in windows surface tablet. 
The main problem I am facing is, virtual keyboard not opening when focus on a text box.

## Prerequisites

- [.] Using yarn
- [.] Using node 10.x
- [ .] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ .] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ .] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Virtual keyboard need to be open to type in the input type text form component.

## Current Behavior
It's not opening the virtual keyboard.

## Steps to Reproduce (for bugs)

1.Build the ElecronJs application and install the file in the surface tablet. Then click on the text box to enter data

## Context
Production issue

## Your Environment

- Node version :   10.5
- Version or Branch used : master 
- Operating System and version : Windows 10 Home
- Link to your project :

**Comment by keshav0016** [comment]
@amaranadh-wal 
I guess upgrading the electron to version 4 would work.
They have added functionality for the touch events in the version 4 of electron.
That should probably solve the issue.

Thank you
