### ISSUE TITLE
React-Hot-Loader: react-🔥-dom patch is not detected

### ISSUE THREAD

**Issue by suprageek** [electron-react-boilerplate/electron-react-boilerplate#2200]
## Expected Behavior

On the Home Page, when i click on the link `to Counter` i should be redirect to Counter Page

## Current Behavior

When i click on the link, nothing happens
But when i'm on counter page, redux is working fine
i just can't switch between components

## Possible Solution
i tried solution given here but still not working
https://medium.com/@antonkorzunov/react-hot-loader-4-6-41f3ce76fb08

## Steps to Reproduce (for bugs)

1. Changed the redux structure to have something like :
redux
--counter
----actions.js
----reducer.js
----actionTypes.js
--user
---- action.js
----reducer.js
----actionTypes.js

2. Loading the routes dynamically :
     routes.map(route => <Route .... />);

3. yarn dev

4. When the app start, i got in the console :
React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.

## Context

I've made many changes in `app` folder structure
i want to build an app with authentication process so i have public route and protected route

## Your Environment

- Node version : 10.15.3
- Version or Branch used : master
- Operating System and version : Mac OSX Mojave
- Link to your project :

**Comment by tomkdgun** [comment]
@suprageek How did you solve this issue ? I've added @hot-loader/react-dom + alias in webpack config (DEV), but I'm seeing now "React-Hot-Loader: Hot Module Replacement is not enabled"
