### ISSUE TITLE
Not work "yarn" if Node version 12+

### ISSUE THREAD

**Issue by XeHeSi** [electron-react-boilerplate/electron-react-boilerplate#2202]
## Prerequisites
- [x] Using yarn
- [x] Using node 12.x

## Expected Behavior

Then i using the latest version of Node.js (now it is 12.1.0), there is a mistake at installation of dependences (node-sass):

```bash
yarn
```

It happens because of the old version of node-sass (in the project: ^4.10.0, but for work with Node.js v 12, the version of node-sass 4.12 is necessary).

## Possible Solution

Therefore it is necessary to update manually node-sass to the latest version, before execution of the command of **yarn**:
```bash
node i node-sass
```

## Steps to Reproduce (for bugs)

1. Install latest Node.js version (12.x)

2. **git clone ...** in folder

3. yarn

4. Result: Error (can't install node-sass)

## Your Environment

- Node version : 12.1.0
- Operating System and version : Windows 10

---

P.s.: Maybe I know not enough how work **yarn**, but it caused in me a problem.

**Comment by Tuistmessiah** [comment]
I have the same problem!

**Comment by forvenus** [comment]
Thanks @XeHeSi , same problem!

**Comment by fdterr** [comment]
Same problem here for me as well, using Node v12.6.0

**Comment by sbaum23** [comment]
Same problem for me. Updating `node-sass` in  `package.json` to use version `^4.12.0` fixed the problem for me.

**Comment by pedrocarlos-ti** [comment]
> Same problem for me. Updating `node-sass` in `package.json` to use version `^4.12.0` fixed the problem for me.

Thanks, works for me too!

**Comment by MBetters** [comment]
Updating `node-sass` to `4.12.0` fixed it for me as well.

**Comment by kingcocomango** [comment]
```
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/4] ⠄ electron
[-/4] ⠄ waiting...
[3/4] ⠄ node-sass
error /home/mango/Documents/mahgar/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /home/mango/Documents/mahgar/node_modules/electron
```

I believe I have the same issue. Updating node-sass in package.json and running npm i node-sass both did not resolve the issue
