### ISSUE TITLE
How to use typeface-lateef font?

### ISSUE THREAD

**Issue by Bouncue** [electron-react-boilerplate/electron-react-boilerplate#2211]
I've tried to add :

`@import "~typeface-lateef/index.css";`

in `app.global.css`

also I tried this: `@import "~typeface-lateef";`

and set style to the component: style={{font-family: "Lateef", cursive}}

but the font doesn't change at all.

but it works if I use CDN from [fonts.google.com](https://fonts.google.com/?subset=arabic&selection.family=Lateef)

I've read these issues:

[#966](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/966)
[#1157](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1157)
[#1495](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1495)

I've followed the instruction on that issues and it seems some configs have changed now, unfortunately none of it solve my problem.

any help would be appreciate

**Comment by astralmedia** [comment]
Was there any resolution to this? I can't seem to get google fonts I use to package either.
