### ISSUE TITLE
ESLint:Cannot start language service process

### ISSUE THREAD

**Issue by anonymous-qsh** [electron-react-boilerplate/electron-react-boilerplate#2217]
I am using WebStorm to write my program, and when I use "workerize-loader" in my project, but the eslint does work in the used workerize-loader pages. WebStorm hit as the title. The codes are as follows.

```js
// worker.js
// eslint-disable-next-line
import worker from "workerize-loader!./handleFiles.js";

export default worker;
```

## Prerequisites

- [x ] Using yarn
- [x ] Using node 10.x
- [ x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

I think eslint shoud work in this files but it does not work.

## Current Behavior

Webstorm Hint ESLint:Cannot start language service process and when using `worker.js` files all eslint does not work.

## Steps to Reproduce (for bugs)

1. yarn add workerize-loader and currectly using it.

2. create a file in /app/worker named worker.js

3. writing code 

```js
// eslint-disable-next-line
import worker from "workerize-loader!./handleFiles.js";

export default worker;
```

4. using worker in any other files.

## Your Environment

- Node version : 11.7.0
- Version or Branch used : next
- Operating System and version : MacOs v 10.14
- Link to your project :

**Comment by jessechhabra** [comment]
Did you find a solution to this error?

**Comment by mlgzzz** [comment]
You can try this
`.eslintrc.js`
```
{
  "extends": "erb",
  "settings": {
    "import/resolver": {
      "webpack": {
        "config": require.resolve('./configs/webpack.config.eslint.js')
      }
    }
  }
}

// -> 
{
  "extends": "erb",
  "settings": {
    "import/resolver": {
      node: {},
      "webpack": {
        "config": require.resolve('./configs/webpack.config.eslint.js')
      }
    }
  }
}
```
