### ISSUE TITLE
How to use it with material-ui?

### ISSUE THREAD

**Issue by piya23300** [electron-react-boilerplate/electron-react-boilerplate#2222]
I need to use [material-ui](https://material-ui.com/getting-started/installation/).

I installed material-ui and then I try to use `Button` of material-ui. It doesn't work for me.

at /app/components/Home.js
```
// @flow
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import Button from '@material-ui/core/Button'

import routes from '../constants/routes';
import styles from './Home.css';

type Props = {};

export default class Home extends Component<Props> {
  props: Props;

  render() {
    return (
      <div>
        <Button>TEST</Button>
        <h2>Home</h2>
        <Link to={routes.COUNTER}>to Counter</Link>
      </div>
    );
  }
}
```

it doesn't work. it has errors.
![Screen Shot 2019-07-10 at 5 49 17 PM](https://user-images.githubusercontent.com/4598861/60963487-1f988d00-a33b-11e9-9b7b-06b9478a2269.png)

Could you suggest to me?

**Comment by piya23300** [comment]
I found that it doesn't work with material-ui above 4.0.0

it works with 3.9.1

**Comment by mtsamis2** [comment]
I had the same issue. Downgrading worked for me, but would love for this boilerplate to support the latest version of material-ui/core

**Comment by Alpha2J** [comment]
change the react-hot-loader version from 4.3.12 to the latest version in package.json, problem solved.
