### ISSUE TITLE
Production environment needs to disable soureMap

### ISSUE THREAD

**Issue by citrusjunoss** [electron-react-boilerplate/electron-react-boilerplate#2225]
The source code of the program can be obtained by decompiling. If the soureMap is enabled.
![image](https://user-images.githubusercontent.com/18432488/62343376-4ce0f100-b51d-11e9-8341-67543efcdb48.png)
decompression app.asar

**Comment by citrusjunoss** [comment]
I tried modifying the webpack devtool option, but it doesn't work
![image](https://user-images.githubusercontent.com/18432488/62343817-21aad180-b51e-11e9-989b-8868957b5be6.png)
![image](https://user-images.githubusercontent.com/18432488/62343829-312a1a80-b51e-11e9-9bac-efa7317a5556.png)

**Comment by amilajack** [comment]
Fixed in `v1.0.0`
