### ISSUE TITLE
Size of dmg file is too big

### ISSUE THREAD

**Issue by binhndicts** [electron-react-boilerplate/electron-react-boilerplate#2226]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
I'm using `yarn package` to make production build without any changes in any config files.
However, size of dmg file is over 80MB.

Is this normally? Am I wrong somewhere?

**Comment by praisethemoon** [comment]
I wonder so meself, my app size is about `800mb`

**Comment by dbvrac** [comment]
800mb? Lots of video?

Right now my project is 87MB DMG, 283MB app size.

Does `yarn run package` kick out everything that isn't needed? My projects have evolved so much, I have components and other files that I'm not using, and I probably have some installed packages in package.json that are left over.

**Comment by praisethemoon** [comment]
@dbvrac clean your package.json
