### ISSUE TITLE
Context instead of Redux

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2233]
Since Context is really perfect and out of the box I think this Boilerplate needs to get rid of Redux and publish the same Boilerplate with Context example.

Advantages
1.  Less third party packages.
2.  We can do the same thing with Context.
3. Ready for the Future

If (I hope) a Context version comes or even better the current version gets rid of Redux and adds Context please use this Folder Structure. I have it from Traversy Media and it is very clean and nice, Instead of adding multiple folders regarding to context in the root, like in the current version with Redux add in the root a folder called 'context' and in there comes everything for context, for the example the Counter, So a counter folder in context folder that holds the context.

.
├── context
|├── ├── counter
|├── ├── ├──counterContext
|├── ├── ├──counterReducer
|├── ├── └── counterState

**Comment by larissa-n** [comment]
I'm sure there'll still be a place for Redux, but would love to see a version with context (and hooks).

**Comment by akmittal** [comment]
Created a fork which removes Redux and uses React Hooks api https://github.com/akmittal/electron-react-boilerplate
