### ISSUE TITLE
Using production version in non-production environment.

### ISSUE THREAD

**Issue by ghost** [electron-react-boilerplate/electron-react-boilerplate#2266]
I get this after clean git clone && yarn && yarn dev:

/Users/ddyok/Code/13/fuck/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js:1 React-Hot-Loader: misconfiguration detected, using production version in non-production environment.
AppContainer @ /Users/ddyok/Code/13/fuck/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js:1
/Users/ddyok/Code/13/fuck/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js:1 React-Hot-Loader: Hot Module Replacement is not enabled.
AppContainer @ /Users/ddyok/Code/13/fuck/node_modules/react-hot-loader/dist/react-hot-loader.production.min.js:1
redux

**Comment by JeffDerk** [comment]
same

**Comment by hadnet** [comment]
Same thing here.

**Comment by dfa1234** [comment]
same

**Comment by amilajack** [comment]
Fixed in #2325
