### ISSUE TITLE
Can't find Image path

### ISSUE THREAD

**Issue by sundowatch** [electron-react-boilerplate/electron-react-boilerplate#2278]
I'm trying to show an image on an electron app. I've included it via `extraResources `in `package.json` like that:

```
"extraResources": [
  {
    "from": "app/assets/images",
    "to": "../app/assets/images",
    "filter": [
      "**/*"
    ]
  }
]
```
I'm calling it from JavaScript like that:

`./app/assets/images/a.jpg`

But it's calling wrong path which is: `file:///D:/Program%20Files/nodejs/Nodejs_Projects/paletten4/release/win-unpacked/resources/app.asar/app/app/assets/images/a.jpg`

How can I attach external folders and use them?

**Comment by hcuffy** [comment]
@sundowatch 

What exactly are you attempting to do with the image? Display it within the application/page or use it as the app icon?

You can always reference the image like:
 `file://${__dirname}/<PATH_TO_IMAGE>`

So it will look something like => `<img src={ file://${__dirname}/<PATH_TO_IMAGE>/>`

Or place it in an assets folder and `import` then.

**Comment by lacymorrow** [comment]
How should I go about loading local images without using the `file://` protocol?
