### ISSUE TITLE
Where you write Node logic?

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2283]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
Hello, where you write you Node.js logic? For example if your app need to interact with the filesystem `fs` module. Do you write it directly in the React Components or somewhere else? Thanks

**Comment by tkoriginal** [comment]
You write it in main.dev.js in app, though depends on how you are writing the app.
