### ISSUE TITLE
How to disable linting on development?

### ISSUE THREAD

**Issue by nicwhitts** [electron-react-boilerplate/electron-react-boilerplate#2285]
Iv extending the linting to display listing problems within viscose and also on pre-commit. So i find that the listing problems slow my development down (i know il fix things before committing)

Is there an easy way to turn off the linting for development only? 

Thanks!

**Comment by amilajack** [comment]
Can you please clarify your question

**Comment by nicwhitts** [comment]
Example:
For rapid development id like to just quickly change things even though not completely correct. e.g:

```
      TS6133: 'SomeComponent' is declared but its value is never read.

```

So while in development i would like it NOT stop the execution because this won't effect anything.
Then i have precommit which will prevent any problems like this from getting into the repo.

Im not sure how i would do this though?

**Comment by nicwhitts** [comment]
I can't find anywhere where web pack or babel configures eslint so that i can disable it in development mode? 
Where can i find this?

**Comment by amilajack** [comment]
If you dont want linting issues in development then dont use viscose. Linter errors shouldnt slow down development. electron-react-boilerplate also [already lints files on pre-commit](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/package.json#L39-L43).
