### ISSUE TITLE
Boilerplate not starting in Windows 10 + Ubuntu 18.04

### ISSUE THREAD

**Issue by HuuPhuoc97** [electron-react-boilerplate/electron-react-boilerplate#2286]
![image](https://user-images.githubusercontent.com/46307771/67465740-f2fd4c80-f66f-11e9-8a46-4878c8ac4c42.png)
![image](https://user-images.githubusercontent.com/46307771/67465744-f4c71000-f66f-11e9-8532-42d3c627a60d.png)

## Prerequisites

- [ ] Using yarn
- [ ] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version :
- Version or Branch used :
- Operating System and version :
- Link to your project :

**Comment by amilajack** [comment]
Please try the solutions in #400
