### ISSUE TITLE
Importing Bootstrap CSS partial loading?

### ISSUE THREAD

**Issue by twigs67** [electron-react-boilerplate/electron-react-boilerplate#2299]
Hello,

I'm not sure if this is a bug or I'm just doing something wrong, but I'm not sure how I could be messing this up. 

I'm trying to import Bootstrap in ```app/index.js``` with:
```
import 'bootstrap/dist/css/bootstrap.css';
```

It is including it in the build, but it's not all of the css properties are being added. For instance,
```
<button type="button" class="btn btn-primary">Primary</button>
```
Only grabs the padding, but not anything else. I've tried React Bootstrap and the same thing. The only way to get it to work is to load it in ```app.html```. 

Has anyone run into this? Or can anyone offer any suggestions on how to fix this?

Thanks

**Comment by hcuffy** [comment]
@twigs67 

I not too certain on your project structure but you can import bootstrap like `@import '~bootstrap/dist/css/bootstrap.min.css';` within the app.global.css. 

Then import the CSS accordingly like for example within the app/index.js  like `import './app.global.css;`

Hope that helps.

**Comment by twigs67** [comment]
Thanks @hcuffy - I'll give that a try.
