### ISSUE TITLE
Multiple Entry Points

### ISSUE THREAD

**Issue by twigs67** [electron-react-boilerplate/electron-react-boilerplate#2300]
Hello,

I'm just trying to understand how webpack is building the dll files, as I'm looking to create multiple entry points into this electron app. 

Right now, it appears that ```app.html``` runs ```../dll/renderer.dev.dll.js```, which appears to be built by webpack. What I'm failing to see is how this dll file is created and how I can create multiple entry points. 

For instance, I'd like two entry points, the already included ```app.html``` and a new entry point, ```newEntry.html```. Can anyone give any insight into how I might be able to do this?

Any help would be appreciated.

**Comment by VladimirPal** [comment]
If you will use multiple entry points, you will have multiple output files, ```output.filename = '[name].js'``` files with entry names.
So use these files to load needful entry.

Regarding dll, i think it useless  https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2313
