### ISSUE TITLE
Failure in travis build

### ISSUE THREAD

**Issue by baymac** [electron-react-boilerplate/electron-react-boilerplate#2306]
<!-- 
  Is this a bug report?
  If so, go back and select the "Bug report" option or your issue WILL be closed.
--!>
The default travis ci config fails to build the electron boiler plate. The build logs can be found here: [](https://travis-ci.org/baymac/cypherock-live-desktop/jobs/606373227). I want to build the app for all platforms and make releases for tagged commit. Can someone help?

**Comment by amilajack** [comment]
See this as an example:
https://github.com/amilajack/popcorn-time-desktop
