### ISSUE TITLE
New BrowserWindow isn't loading in prod

### ISSUE THREAD

**Issue by Chagrilled** [electron-react-boilerplate/electron-react-boilerplate#2307]
I'm trying to open a new BrowserWindow, it works fine in `yarn dev`, but in full release it just comes up as a white window that never does anything. I've tried using #/paths with the default router, and the solution here using react-router-dom with search props: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/623

Presumably some Webpack config issue, which I have very little experience with, or I'm just flat out loading the wrong file path because of prod bundle wizardry.

## Prerequisites

- [x ] Using yarn
- [x ] Using node 10.x
- [x ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start` - no output is given

## Expected Behavior

Opening a new BrowserWindow from within a component in prod should work properly, as it does in dev.

## Current Behavior

New BrowserWindow opens, but seems not to load any renderer process. Debug prod output shows console logs firing the event, but no logs from the process afterwards.

## Possible Solution

Some prod Webpack config alterations I guess :man_shrugging: 

## Steps to Reproduce (for bugs)

The code suggested here for the router:
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/623#issuecomment-333750155

Being called from a component like; `this.windowObject = window.open(`file://${__dirname}/app.html?gallery`);`

Works in yarn dev, but not yarn start.

Alternatively, with no changes to the original router
`window.open(`file://${__dirname}/app.html#/counter`);`
would also have the same effect.

Output of that file path in dev is: `file://E:\Github\xx\app/app.html?counter`
Vs in prod: `file:////app.html?counter`

If that would effect anything when bundled.

## Context

Trying to open a new child window from a component, ended up here. This still launches a whole new React app which seems undesirable, but oh well.
No intelligent changes to the core boilerplate.

## Your Environment

- Node version : v10.15.2
- Version or Branch used : master/latest
- Operating System and version : Windows 7

**Comment by Chagrilled** [comment]
I fixed this myself - by updating to Electron 7, BrowserWindow now emits errors unlike Electron 3, which directed me through a few things. 

New BrowserWindows can't be opened in a renderer process, but via remote and ipcRenderer to do it from the main process.

**Comment by dbvrac** [comment]
What details were involved with upgrading to Electron 7? I updated to the most recent `next` branch and all seems well with my 2-window app.

**Comment by Chagrilled** [comment]
I just bumped some packages, installed electron@latest, changed window options to include `webPreferences: { nodeIntegration: true }`, and `add corejs: 3` to babel's preset-env, and installed core-js 3, of course. 

Any native modules will need to be `electron-rebuild`'d, this is where most of my strife came from.

**Comment by leohxj** [comment]
when after build, __dirname is `/`, whatever I set nodeIntegration:true...

**Comment by tolmekian1453** [comment]
The default is Electron 8 now, but I have the same issue. I'm doing the same thing as originally mentioned with `file://${__dirname}/app.html#/routename`, works in dev but not prod.

**Comment by tolmekian1453** [comment]
The default is Electron 8 now, but I have the same issue. I'm doing the same thing as originally mentioned with `file://${__dirname}/app.html#/routename`, works in dev but not prod.

**Comment by hot-gril** [comment]
The default is Electron 8 now, but I have the same issue. I'm doing the same thing as originally mentioned with file://${__dirname}/app.html#/routename, works in dev but not prod. Console says "Not allowed to load local resource."
