### ISSUE TITLE
💚💚 PLEASE DONATE 💚💚 (see backers and sponsors section in readme)

### ISSUE THREAD

**Issue by austinnichols101** [electron-react-boilerplate/electron-react-boilerplate#2308]
Respectfully, I would like to ask "Is this project still active?  

- No support for the current versions of Electron
- A year since the last release
- Seeing very few commits
- A growing list of issues

Would like to understand if there's any effort underway to move forward...

This project is still listed on https://electronjs.org/docs/tutorial/boilerplates-and-clis, but things are so far out-of-date that it's probably not a good idea to recommend in the current state.

**Comment by amilajack** [comment]
I am currently very busy at the moment because I'm interviewing for companies full time now. I will start contributing again in the next week or so.

**Comment by dbvrac** [comment]
I use this project quite a bit. The docs could use a refresh but the `next` branch isn't so far behind. I'd contribute code if I had the time and better skills, but in the mean time: [https://opencollective.com/electron-react-boilerplate-594](https://opencollective.com/electron-react-boilerplate-594)

**Comment by reZach** [comment]
@austinnichols101, not to dissuade you from using this template, as it is a great template that can really build great apps.

I too, after using this template found it was lacking in more [secure practices](https://electronjs.org/docs/tutorial/security) recommended by the community (to no dis-service to the authors/maintainers of this app - the electron team updates the framework _very_ frequently and we can't expect free updates all the time =)). I began to set out and build a more secure/updated template with the newest version of electron. I ended up creating [`secure-electron-template`](https://github.com/reZach/secure-electron-template).

_I realized I didn't ask in advance, but if you'd like me to take this comment down please let me know!_
