### ISSUE TITLE
Switch Redux logic setup to use Redux Toolkit

### ISSUE THREAD

**Issue by markerikson** [electron-react-boilerplate/electron-react-boilerplate#2312]
Hi, I'm a Redux maintainer. I'd like to offer a couple suggestions.

### Problem

The current Redux example implementation shows use of reducers with "hand-written" immutable update logic, and has a somewhat complex store configuration. In addition, the project currently uses a "folder-by-type" folder structure.

### Proposed Solution

The project should switch to using the official [Redux Toolkit package](https://redux-toolkit.js.org) to implement the Redux logic.

The project should also consider switching to a "feature-folder" or "ducks" folder structure, rather than a "folder-by-type" structure.

### Additional Details

Redux Toolkit is our new official, opinionated, batteries-included toolset for efficient Redux development.  It includes utilities to simplify several common Redux use cases, including store setup, defining reducers, immutable update logic, and even creating entire "slices" of state at once without writing any action creators or action types by hand.

We are recommending RTK as the default standard way to write Redux logic.  Partly related to that, we are also recommending that developers should prefer to use "feature folders" or "ducks" rather than "folder-by-type".  (Reference: the work-in-progress [Redux "Style Guide" docs page](https://deploy-preview-3626--redux-docs.netlify.com/style-guide/style-guide).)

Since many developers will be starting their projects using `electron-react-boilerplate`, it would be beneficial if Redux Toolkit was included as part of the default project setup, as it will greatly simplify the application code they write.

**Comment by johncantrell97** [comment]
I'll take a stab at this.  Do we want to also switch to the "feature-folder" structure as part of it or do that separately?

**Comment by reZach** [comment]
@johncantrell97 I'd imagine that would be apart of this

**Comment by gregorychen3** [comment]
I'm greatly looking forward to trying out this feature. Any idea when it will be officially released? Any help needed doing so?
