### ISSUE TITLE
should not use all dependencies  as externals for the webpack config of renderer build

### ISSUE THREAD

**Issue by laketea** [electron-react-boilerplate/electron-react-boilerplate#2324]
should not use the dependencies keys in package.json as externals value for the webpack config of renderer build, this will lead webpack not bundle any dependencies packages, and then,  when electron browser loading renderer bundle js, the dependency package file will be loaded by nodejs module require, and this will lead huge performance problem .

```
// webpack.config.base.js
import { dependencies } from '../package.json';

export default {
  externals: [...Object.keys(dependencies || {})],
 ...
}
```

for renderer build, only use third-party nodejs package key as externals, not all dependencies in package.json

some screenshot s of performance tab in developer tools:

![image](https://user-images.githubusercontent.com/3827390/69162927-5754e400-0b28-11ea-829b-7876b0add2a6.png)

if used @material-ui/icons in component, loading @material-ui/icons take 2s:

![image](https://user-images.githubusercontent.com/3827390/69163197-c0d4f280-0b28-11ea-8c99-704d7fc0764c.png)

if we set externals to empty, the whole scripting only take 300ms:

![image](https://user-images.githubusercontent.com/3827390/69163956-12ca4800-0b2a-11ea-9306-755ecdb8a53d.png)

**Comment by VladimirPal** [comment]
You are right, here is my issue with the same points
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2313

**Comment by amilajack** [comment]
This was caused by some changes when migrating to a single package.json architecture (https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/1854). I'm currently working on reverting that transition because it makes it harder to integrate native modules into apps.
