### ISSUE TITLE
Global styles keep overriding css modules

### ISSUE THREAD

**Issue by RoeelCohen** [electron-react-boilerplate/electron-react-boilerplate#2328]
Hey, I started using electron react boilerplate with an existing react project I had.
I used to load both scss global styles and scss modules.

I did all the required steps to use scss.

When Moving to the current boilerplate I fixed the styling to match the current webpack config.
i.e:
1. global styles are stored in index.global.scss 
2. I import global styles only once in index.js

## Expected Behavior:
Global styles should load first and only then the local/css modules

## Current Behavior:
Global styles loads/imported last and that breaks my ui since my local styles won't override the global styles.

## Unwanted Working Solution:
Import global styles manually where I use both global and local styles:
```
import '../../index.global.js'  // importing global styles here would fix the problem 
import s from './MenuItem.scss';
```

## Another Unwanted Possible Solution:
Increase css specificity on some of the objects

## Desired Solution:
Make the global styles load first, how can I achieve it?

## Webpack Dev Config
```
// SASS support - compile all .global.scss files and pipe it to style.css
      {
        test: /\.global\.(scss|sass)$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'sass-loader'
          }
        ]
      },
      // SASS support - compile all other .scss files and pipe it to style.css
      {
        test: /^((?!\.global).)*\.(scss|sass)$/,
        use: [
          {
            loader: 'style-loader'
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]__[hash:base64:5]'
            }
          },
          {
            loader: 'sass-loader'
          }
        ]
      },
```

**Comment by reZach** [comment]
@RoeelCohen have you looked at configuring the loaders?
https://github.com/webpack-contrib/style-loader
