### ISSUE TITLE
After build the app to .pkg, it crashes

### ISSUE THREAD

**Issue by nguyen-tam** [electron-react-boilerplate/electron-react-boilerplate#2330]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

The built .pkg is runnable

## Current Behavior

After specify built target as pkg, the built pkg file is not runnable

"mac": {
      "icon": "resources/icon.icns",
      "target": [
        "pkg"
      ]
    },

## Steps to Reproduce (for bugs)

1.

2.

3.

4.

## Your Environment

- Node version : 10.15.3
- Version or Branch used : 0.18
- Operating System and version : MacOS 10.15
- Link to your project :

**Comment by amilajack** [comment]
Please try a fresh clone and solutions in #400. Also this is likely an issue with electron-builder. Comment if this doesnt work for you and I can reopen
