### ISSUE TITLE
The platform "linux" is incompatible with this module

### ISSUE THREAD

**Issue by Mad-hu** [electron-react-boilerplate/electron-react-boilerplate#2331]
Ubuntu 14.04.5
"name": "electron-react-boilerplate",
"productName": "ElectronReact",
"version": "0.18.0",
git clone -> yarn install
![image](https://user-images.githubusercontent.com/13977755/69845035-f5c01280-12a9-11ea-9037-8315ae51b512.png)

**Comment by dbvrac** [comment]
This isn't an error. FSEvents is specifically for MacOS: https://www.npmjs.com/package/fsevents
The real error you are seeing is your version of Node, which you can remedy by changing the version you are running (nvm is handy for this) or changing the requirement stated in package.json.

**Comment by Mad-hu** [comment]
I didn't add anything module,you can try install this project on linux.  
execute command: 
1、git clone https://github.com/electron-react-boilerplate/electron-react-boilerplate.git
2、yarn install
the error again!

**Comment by dbvrac** [comment]
FSEvents is only relevant to MacOS and gets installed automatically for use with another package listed in package.json. It's ignored in Linux. This is not an error.
I just now installed it just fine, no errors:
- Ubuntu 18 (I don't have a machine running 14 handy)
- Node 11.15.0 (newer version than yours - update this)

In my previous message I mentioned the node version listed in package.json. That wasn't quite right. Some other package is enforcing that restriction, but that's the problem you appear to be having.

**Comment by dbvrac** [comment]
@Mad-hu Did you get everything working properly? If so, please close this issue.

**Comment by amilajack** [comment]
It's actually ESLint that's incompatible with your node version. Please upgrade to the latest node version.
