### ISSUE TITLE
App is not restarting when we close the the app manually.

### ISSUE THREAD

**Issue by muhzi4u** [electron-react-boilerplate/electron-react-boilerplate#2345]
### Prerequisites
- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date master branch
- [x]  Using latest version of dev tools.

### Environment
Node version : v11.15.0
Version or Branch used: master (0.18.1)
Operating System and version : Mac OS Catalina

### Expected Behaviour

The app should restart after we close the app manually.

### Current Behaviour

The app is opening initially. If we close the app manually and it is not opening when we try to restart the app by clicking the app icon.

![issue](https://user-images.githubusercontent.com/12408980/70882468-e94fef80-1ff5-11ea-9773-54d81e1f1af2.gif)

**Comment by muhzi4u** [comment]
@amilajack Any thoughts on this issue?

**Comment by amilajack** [comment]
This is not a bug. This functionality needs to be configured with electron. See https://github.com/electron/electron/issues/1550#issuecomment-98966134

**Comment by amilajack** [comment]
Here's how Hyper is doing this: https://github.com/zeit/hyper/blob/canary/app/index.js#L178-L185. I'd also love if you could PR this change. I think a lot of users would benefit from this.

**Comment by muhzi4u** [comment]
@amilajack I will work on this issue.
