### ISSUE TITLE
Chrome developer tools does not work in windows 10 Pro, 

### ISSUE THREAD

**Issue by ethanoic** [electron-react-boilerplate/electron-react-boilerplate#2349]
## Prerequisites

- [x] Using yarn
- [] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

When toggling the developer tools from the boilerplate menu dropdown, chrome developer tools should appear

## Current Behavior

Nothing happens

## Steps to Reproduce (for bugs)

1. clone the master branch

2. launch the application

3. click on dropdown menu and select "toggle developer tools"

## Context

I was trying to get familiar with the build and modify for my own components but I was getting errors that I was unable to see.

## Your Environment

- Node version : 12.14.0
- Version or Branch used : master
- Operating System and version : Windows 10 Pro

**Comment by amilajack** [comment]
Try this: https://electron-react-boilerplate.js.org/docs/dev-tools/#devtools-extension

**Comment by thanksgiver** [comment]
The same issue, please help!
