### ISSUE TITLE
Proper way to install dependencies?

### ISSUE THREAD

**Issue by tytech3** [electron-react-boilerplate/electron-react-boilerplate#2350]
I recently tried to install material UI and completely broke the boilerplate. I didn't add anything to the code other than another react component. I ran a yarn add and an npm install on the mui package. And then an additional npm install in my directory. I was just fiddling around trying stuff because I couldn't get the mui package to compile with the boilerplate.  This eventually broke the entire boilerplate with an error saying 'couldn't find variable 'history' in (wherever the redux store is in the file structure)'. So to cleanse my paranoia of installing things with this build, what is the proper way to do so? Yarn add? Npm install? Is there a difference? Does running just a raw 'npm install' break anything?

**Comment by sdjhoanborges** [comment]
I actually wonder the same.

**Comment by amilajack** [comment]
Here are the docs:
https://electron-react-boilerplate.js.org/docs/adding-dependencies/
