### ISSUE TITLE
VS Code not auto-refactoring imports in this repo when I move files

### ISSUE THREAD

**Issue by azlant** [electron-react-boilerplate/electron-react-boilerplate#2353]
## Prerequisites

- [X] Using yarn
- [13.5.0 ] Using node 10.x
- [X] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [X] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [N/A ] Link to stacktrace in a Gist (for bugs)
- [N/A] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Visual Studio Code is supposed to automatically refactor `import` statements in other files that reference moved or renamed files. If I move a file in this repo to another directory, Code should automatically refactor other files that `import` it.

## Current Behavior

Refactoring of `import` statements does not occur. I get a `Cannot resolve module {module}` error in the linter.

## Possible Solution

Not sure if this might be related to Flow setup, or some override in VSCode settings.

## Steps to Reproduce (for bugs)

1. Open repo in VSCode

2. Create new folder, i.e. `app/test`

3. Move a file that is referenced by another file's `import` into that folder, i.e. `app/reducers/types.js`

4. Observe the issue in a file that references the moved file, i.e. `app/actions/counter.js`

## Context

I'm attempting to rearrange the repo so that I can keep to something like the Ducks paradigm, where I have action and reducer logic for objects bundled together.

I recognize that this could also be a bug in VSCode, but I tried with another repo and no issue.

## Your Environment

- Node version : 13.5.0
- Version or Branch used : master
- Operating System and version : OS X Catalina 10.15.2
- Link to your project : none yet, in progress

**Comment by reZach** [comment]
@azlant This seems like a VSCode bug, and not specific to here.
