### ISSUE TITLE
Electron window does not appear in Windows 10 Dark Mode(May be due to the bug in electron)

### ISSUE THREAD

**Issue by XxLittleCxX** [electron-react-boilerplate/electron-react-boilerplate#2360]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

> This starts the renderer process in hot-module-replacement mode and starts a webpack dev server that sends hot updates to the renderer process:

## Current Behavior

Electron window does not appear after "yarn dev" or "yarn start", without any error log
The electron process has started and can be seen in the task manager.

![image](https://user-images.githubusercontent.com/26459759/71760654-e3b23f00-2efb-11ea-8fee-9d4cfcbe3b42.png)

## Steps to Reproduce (for bugs)

All operations follow README.md

[Useless Video](https://youtu.be/efILCwinEIk)

## Your Environment

- Node version : v11.11.0
- Version or Branch used : master c273ba4 Create CODE_OF_CONDUCT.md
- Operating System and version : Windows 10 1909

**Comment by reZach** [comment]
@XxLittleCxX  I've seen this hang before when webpack has an error and never finishes the process, but that might be a red herring if you need ideas to try to debug.

**Comment by NikitaVr** [comment]
I have the same issue. Found a similar issue also, but the mentioned steps did not help https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1998

**Comment by raodong** [comment]
If this only happens when 'yarn dev', try to wait a minute to see if there are console logs saying 
"Failed to fetch extension, trying 4 more times",
if this message is shown, then it might be a network connections problem that makes installing devtool extensions failed, thus no windows is shown, cause in development mode, this step is executed at first startup and will block window rendering

**Comment by markbmullins** [comment]
I am also having this issue. @XxLittleCxX Did you ever find a solution to this?

**Comment by XxLittleCxX** [comment]
> I am also having this issue. @XxLittleCxX Did you ever find a solution to this?

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/c273ba447a4300dc699500206ac282b744f3d0e1/app/main.dev.js#L51-L56

After I deleted the following code and I cleared the cache located at `C:\Users\<username>\AppData\Roaming\Electron\Extensions`, the window can be displayed normally. I think this may be one of the reasons why the window is not displayed.

(I guess the reason may be that the devtools extension is not downloaded properly or is not loaded properly)

There is a similar situation in the `electron-devtools-installer` issue:
https://github.com/MarshallOfSound/electron-devtools-installer/issues/122

**Comment by XxLittleCxX** [comment]
> I am also having this issue. @XxLittleCxX Did you ever find a solution to this?

Hello, I cloned the code of `electron-devtools-installer` and debugged, and found that this line of code caused electron blocking,

https://github.com/MarshallOfSound/electron-devtools-installer/blob/3e37415fe3b4c9dc4f669d643c455f28a8338c21/src/index.js#L52

and then found these two issues in the electron repository. 
https://github.com/electron/electron/issues/19978
https://github.com/electron/electron/issues/19468

After I try to switch the system to light mode, the window can be displayed normally, this might help you.

**Comment by markbmullins** [comment]
> > I am also having this issue. @XxLittleCxX Did you ever find a solution to this?
> 
> Hello, I cloned the code of `electron-devtools-installer` and debugged, and found that this line of code caused electron blocking,
> 
> https://github.com/MarshallOfSound/electron-devtools-installer/blob/3e37415fe3b4c9dc4f669d643c455f28a8338c21/src/index.js#L52
> 
> and then found these two issues in the electron repository.
> [electron/electron#19978](https://github.com/electron/electron/issues/19978)
> [electron/electron#19468](https://github.com/electron/electron/issues/19468)
> 
> After I try to switch the system to light mode, the window can be displayed normally, this might help you.

This was it! To future visitors: witching to light mode resolved the issue for me. 

This line was never printed to the console before:

>Skip checkForUpdatesAndNotify becatesAndNotify because application
use application is not packed

**Comment by ivanjeremic** [comment]
Same here, I even installed Windows new today because I could not figure out how to get my window running again! LoL :(

**Comment by alexandermckay** [comment]
That is classic. I spent ages wondering what I had messed up. Who knew it could be as simple as changing back to Light Mode.

**Comment by specialgee** [comment]
> Same here, I even installed Windows new today because I could not figure out how to get my window running again! LoL :( After switching to Light Mode in Windows everything is fine, but please ERB Team fix this because it's not an Electron problem fresh Electron install runs in dark and light mode so it has something to do with ERB What I have learned today is go to GitHub issues first before waisting 6 hours.

not sure it's related to ERB  as related Electron issue is still opened
https://github.com/electron/electron/issues/19468

except bypassing `installExtensions()` there's some workarounds mentioned in the ` vue-cli-plugin-electron-builder` repo https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/378#issuecomment-572386609

**Comment by matthewbrown1234** [comment]
I was able to get this working on Windows 10 in dark mode by moving the block of code in main.dev.js to call the installExtensions() method bellow the "did-finish-load" event handler:

```
  mainWindow.webContents.on('did-finish-load', () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    if (process.env.START_MINIMIZED) {
      mainWindow.minimize();
    } else {
      mainWindow.show();
      mainWindow.focus();
    }
  });

  if (
    process.env.NODE_ENV === 'development' ||
    process.env.DEBUG_PROD === 'true'
  ) {
    await installExtensions();
  }
```

I am not sure why it works there, but maybe this helps.

**Comment by Sensiblemnd** [comment]
Better fix

Set package Json electron packages to 

Current:
"electron": "7.1.13",
    "electron-builder": "^22.2.0",

Fix"
"electron": "8.0.2",
    "electron-builder": "^22.3.2",

**Comment by ivanjeremic** [comment]
We have still the same issue in the newest version of ERB can we use the versions above?
