### ISSUE TITLE
macOS Catalina doesn't support 32-bit executables and as result Wine cannot run Windows 32-bit applications too

### ISSUE THREAD

**Issue by arnaudambro** [electron-react-boilerplate/electron-react-boilerplate#2362]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs): https://gist.github.com/arnaudambro/1e026d23f55f5851b0c28a7d0a285c7f

## Expected Behavior
`yarn package-all` does not end with `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE`

## Current Behavior
`yarn package-all` end `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` (cf full stacktrace [here](https://gist.github.com/arnaudambro/1e026d23f55f5851b0c28a7d0a285c7f)
The dmg and zip packages are created but the app inside is not working. But the ./release/mac/ElectronReact.app is working.
I couldn't test for Windows.

## Context - Your Environment

I don't know if it happens in all Catalina's mac, but I would think so.

**Comment by njho** [comment]
I have the same error. 

Due to lack of time, I had to keep my MacOS on Sierra in order to support my current client :/

**Comment by amilajack** [comment]
This is not an issue with the boilerplate. This is electron-builder telling you that you can't target 32 bit arch on catalina.

**Comment by arnaudambro** [comment]
so what is the solution ? put this issue on electron-builder's lib instead ?

**Comment by amilajack** [comment]
No. One solution is to downgrade the macOS version that you're using in CI. [Apple is officially has officially dropped support for 32 bit executables](https://support.apple.com/en-us/HT208436).

**Comment by yanlee26** [comment]
⨯ macOS Catalina doesn't support 32-bit executables and as result Wine cannot run Windows 32-bit applications too

**Comment by mikedatsko** [comment]
I have the same when trying to build win x64:

> ⨯ macOS Catalina doesn't support 32-bit executables and as result Wine cannot run Windows 32-bit applications too

@amilajack do you know any solution except downgrading?

**Comment by mitjans** [comment]
Same here! Leaving a comment

**Comment by einsteinx2** [comment]
@mikedatsko @mitjans We ended up using Docker and it works great (also matches our CI configuration which is nice). Just install Docker for Mac like normal and then you can build windows binaries and even deploy them since Wine is running on Linux inside the Docker container. The container is called `electronuserland/builder:wine`. Full info on Docker Hub: https://hub.docker.com/r/electronuserland/builder/

Not as simple as a native solution, but beats downgrading and it works just fine. We added a bash script to our repo with the following so in the end it's still just typing a single command:

```
# Run Docker and build the release
docker run --rm -ti \
    --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
    -v ${PWD}:/project \
    -v ~/.cache/electron:/root/.cache/electron \
    -v ~/.cache/electron-builder:/root/.cache/electron-builder \
    electronuserland/builder:wine \
    bash -c "yarn run whatever-command-you-want-here"
```

**Comment by ndtreviv** [comment]
> @mikedatsko @mitjans We ended up using Docker and it works great (also matches our CI configuration which is nice). Just install Docker for Mac like normal and then you can build windows binaries and even deploy them since Wine is running on Linux inside the Docker container. The container is called `electronuserland/builder:wine`. Full info on Docker Hub: https://hub.docker.com/r/electronuserland/builder/
> 
> Not as simple as a native solution, but beats downgrading and it works just fine. We added a bash script to our repo with the following so in the end it's still just typing a single command:
> 
> ```
> # Run Docker and build the release
> docker run --rm -ti \
>     --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
>     -v ${PWD}:/project \
>     -v ~/.cache/electron:/root/.cache/electron \
>     -v ~/.cache/electron-builder:/root/.cache/electron-builder \
>     electronuserland/builder:wine \
>     bash -c "yarn run whatever-command-you-want-here"
> ```

Does this work for signing with an EV Code Signing cert locked on a security token as well?

**Comment by LucasAndrad** [comment]
I solved this by changing the windows build config on `package.json`:

```
  "win": {
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64"
          ]
        }
      ]
    },
```

**Comment by ndtreviv** [comment]
> > @mikedatsko @mitjans We ended up using Docker and it works great (also matches our CI configuration which is nice). Just install Docker for Mac like normal and then you can build windows binaries and even deploy them since Wine is running on Linux inside the Docker container. The container is called `electronuserland/builder:wine`. Full info on Docker Hub: https://hub.docker.com/r/electronuserland/builder/
> > Not as simple as a native solution, but beats downgrading and it works just fine. We added a bash script to our repo with the following so in the end it's still just typing a single command:
> > ```
> > # Run Docker and build the release
> > docker run --rm -ti \
> >     --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') \
> >     -v ${PWD}:/project \
> >     -v ~/.cache/electron:/root/.cache/electron \
> >     -v ~/.cache/electron-builder:/root/.cache/electron-builder \
> >     electronuserland/builder:wine \
> >     bash -c "yarn run whatever-command-you-want-here"
> > ```
> 
> Does this work for signing with an EV Code Signing cert locked on a security token as well? How does the docker environment see that token?

FYI for anyone coming here - it would never work on docker, because you can't mount the USB device into a docker container.

**Comment by ndtreviv** [comment]
> I solved this by changing the windows build config on `package.json`:
> 
> ```
>   "win": {
>       "target": [
>         {
>           "target": "nsis",
>           "arch": [
>             "x64"
>           ]
>         }
>       ]
>     },
> ```

This works for creating a self extracting exe (nsis package), but not for msi-s.

After lots of heartache on this, I can categorically say that the only way to build an MSI is on a windows box. I opted for a VirtualBox. You can also mount the USB drive, which works well for using eTokens with EV certs on to sign your code.
