### ISSUE TITLE
VS Code debugging out of the box

### ISSUE THREAD

**Issue by eric-burel** [electron-react-boilerplate/electron-react-boilerplate#2366]
Hi guys,

I've been working on VS Code debugging, and eventually manage to run the debugger for the main process. 

I wanted to share my progress so they could be included in the boilerplate out of the box. The project is running a rather old version so I can't directly PR but I hope it will help.

Basically, we need:
- to build the ES6 `main` file, so that it's readable directly in Node
- you need to use the `outFiles` option to tell where this built file is too
- if you run `electron .`, it will look for the path to your `main.js` using the `package.json` main prop. It's equivalent to specify a `program` in `launch.json` but cleaner.
- **Very important:** we need valid sourcemaps for our `main.js`! otherwise VS Code can't match the build file and your sources. This meant creating an additionnal Webpack config `main.dev`, as we do for the renderer, with `  devtool: 'inline-source-map',  mode: 'development'`. The prod config with `source-map` did not work for me, VS code can't find the source-map. It probably doesn't know how to resolve the source file or maybe the naming is not conventional.
- the Webpack dev server for the renderer must also run. It will serve your renderer bundle on `localhost:3000`. For that you need a background task. They are a total mess to setup, because you need to teach VS Code how to tell if your bg process is ok. I provided a working `problemMatcher`  config below.

It's quite similar to calling `START_HOT=1 npm run hot-server` which basically run the Webpack dev server for the renderer + build the main and run electron (by detecting the START_HOT env variable, explore the renderer's Webpack config to understand better). For debugging, we just remove the "run" part so that VS code can do it itself and enable debugging.

There might be simpler alternatives. Maybe just running `yarn dev` would be enough though I doubt it. I suppose that internally VS Code do some stuff before running Electron to enable interactive debugging.

**Launch.json**
```
{
  "version": "0.2.0",
  "isShellCommand": true,
  "showOutput": "always",
  "args": ["-c"],
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "stopOnEntry": false,
      "cwd": "${workspaceRoot}",
      "env": {
        "NODE_ENV": "development",
        "HOT": "1"
      },
      "console": "internalConsole",
      "program": "${workspaceRoot}/app/main.js",
      "sourceMaps": true,
      "outFiles": ["${workspaceRoot}/app/main.js"],
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "args": ["."],
      // simulate what npm run dev does, but do not run the main server
      "preLaunchTask": "build-main-and-run-renderer-hot-server",
      "postDebugTask": "kill-renderer-hot-server"
    }
  ]
}
```

**Tasks.json**

```
{
  "version": "2.0.0",
  "command": "bash",
  "type": "shell",
  "args": ["-c"],
  "tasks": [
    // needed as a post debug task to kill the server
    {
      "label": "kill-renderer-hot-server",
      "type": "shell",
      "args": ["kill -9 `lsof -t -i:3000`"]
    },
    {
      "label": "build-main-and-run-renderer-hot-server",
      "type": "shell",
      "args": ["yarn build-main-development && yarn hot-server"],
      "isBackground": true,
      "problemMatcher": {
        "pattern": [
          {
            "regexp": ".",
            "file": 1,
            "location": 2,
            "message": 3
          }
        ],
        "background": {
          "activeOnStart": true,
          "beginsPattern": ".",
          "endsPattern": "^Done.*"
        }
      }
    }
  ]
}
```

**Comment by amilajack** [comment]
Awesome! I'd love if you can PR your final changes.

**Comment by eric-burel** [comment]
Thanks, I'll try to (might take a while for me to test it correctly but I'll do my best)
