### ISSUE TITLE
Remove State Management from ERB! Don't kill me:(

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2367]
Hello, Why would I love to remove Redux from this ERB? Please don't kill me read fist. ;)
 
So, first of all, I have 2 nice YouTube videos that inspired me to open up this discussion please watch it, each video ~20min 
1: [https://www.youtube.com/watch?v=jFULzAMS-jI](https://www.youtube.com/watch?v=jFULzAMS-jI) 
2: [https://www.youtube.com/watch?v=Q54YDGC_t3Y](https://www.youtube.com/watch?v=Q54YDGC_t3Y), 

Many things changed in the React world and also how we fetch data and manage state I use in most of my Apps GraphQL/Apollo but I don't want for example to have it in ERB out of the box I want to add it if my current App needs this setup, same with my other projects some of the Apps use Redux some of them only Context and some small Apps no state management library at all. Why is this important? 

I think we need to give the users of ERB freedom of choice! In the second video, the guys explain very well 90% of the time we don't need redux. It is not hard to add a state management library and ERB would become much more flexible if we stop forcing a state management library on the users, Also watch the first video carefully and maybe I can some of the head maintainers bring the idea closer and maybe we will have in the future a much more flexible ERB setup that goes with the new trends in React.

By the way same for Flow/TypeScript I heard there are plans on the Roadmap to move to TypeScript nothing against it nice idea! But I would love to have a pure JS version also and to be able to choose. 

Or maybe a CLI in the future where we can do,

 `create-erb-app myapp`  or `create-erb-app myapp --typescript`

Thanks

**Comment by vikr01** [comment]
I think it's high time this project focused on moving to a CLI like `create-react-app` and stopped being a boilerplate. I feel like redux, flow, all the configs, scripts, and whatever else really bloat the project up too much and make it harder for newcomers to understand the boilerplate.

With that being said, my time is very limited right now. Anyone could attempt making this at any time, it doesn't necessarily need to be done by this project's maintainers.

**Comment by amilajack** [comment]
@ivanjeremic no one's going to kill you 😂 I actually 100% agree with you on this. Personally, I would love to get rid of Redux and TypeScript. React is probably the only piece of the stack I would personally keep. But removing them will hurt users who receive updates from the boilerplate. I agree with @vikr01 on how we do need something like create-react-app. The only thing stopping me from implementing this is time.

**Comment by ivanjeremic** [comment]
> But removing them will hurt users who receive updates from the boilerplate.

If this is the reason you can safely remove it,  everyone at this time who works with redux knows how to maintain it and he can still use this boilerplte for updates by only updating the other parts. I believe in your power :))))

**Comment by amilajack** [comment]
Let's merge this conversation into #2233
