### ISSUE TITLE
prevent navigation for a route

### ISSUE THREAD

**Issue by muscaiu** [electron-react-boilerplate/electron-react-boilerplate#2379]
I'm looking for a way to **prompt the user with a confirmation dialog** when trying to navigate from a route. And very important, **the prompt needs to be styled**.

**Question**:  What is the goto library or method in this case? What are you guys using?

I tried using https://github.com/ZacharyRSmith/react-router-navigation-prompt , it works fine, but i have an issue that i'm not able to fix.

**Comment by amilajack** [comment]
Show a div on navigation change. I don't think there is a goto library to do this.
