### ISSUE TITLE
Importing/requiring modules into main.(dev/prod).js error

### ISSUE THREAD

**Issue by HaveAGitGat** [electron-react-boilerplate/electron-react-boilerplate#2380]
I'm trying to split my code in main.dev.js into multiple files. For example, in a folder called 'modules/versionManager' (next to main.dev.js) I have a file called versionManager.js.

This is required in main.dev.js as follows:

`var versionManager = require('./modules/versionManager/versionManager.js')`

This works fine in dev but when the app is packaged I get the following error:

```
[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
ReferenceError: versionManager is not defined
    at Module.<anonymous> (C:\Users\H\Documents\GitHub\TL\release\win-unpacked\resources\app.asar\main.prod.js:2:7744)
```

I have added 'modules' folder to the build arguments:

```
    "files": [
      "dist/",
      "node_modules/",
      "modules/",
      "app.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
```

What is the correct way to import/require files in main.dev.js so it works when packaged?

Likewise, what is the correct way to import/require files from main.(dev/prod).js from a file (semi-cyclic). For example, in 'versionManager.js' I have used:

```

if (process.env.NODE_ENV === 'production') {
   var updateMainWindow = require('../../main.prod.js')
}else{
    var updateMainWindow = require('../../main.dev.js')
}
```

The above has worked fine in dev but not sure if it will work when packaged as I have not been able to get that far due to the previous error.

## Prerequisites

- [ x] Using yarn
- [x ] Using node 10.x
- [ x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Import/require should work the same in dev as when packaged.

## Current Behavior

Error when using import/require in prod/package.

## Context

I'm trying to split my code up for readability.

## Your Environment

- Node version:10.19
- Version or Branch used :
- Operating System and version :Win
- Link to your project :

**Comment by jaykch** [comment]
I am trying to do the same thing as my main.dev.ts is huge now.
Any updates?

**Comment by HaveAGitGat** [comment]
@jaykch  I put things on hold - I couldn’t find a way to do it with various methods I tried (e.g. using absolute path) as the files are put into app.asar

So you’d probably need to use hacky method of extracting the files from app.asar and constructing the file path to import the extracted files.

**Comment by jaykch** [comment]
@HaveAGitGat I have put it on hold for now, let's see if the devs reply. If I find a solution I will post here.

**Comment by steveetm** [comment]
Can you guys please share me a repo to reproduce this?

**Comment by jaykch** [comment]
> Can you guys please share me a repo to reproduce this?

My work project is private so I cannot share.
But move any code from main.dev.ts to a separate folder and import it as a node.js module.

It will work in development but the pathing won't work in build.

**Comment by steveetm** [comment]
That file already contains a few import on my side and this is working fine for me, this is why asking a minimal example repo where it is broken for you.

**Comment by steveetm** [comment]
> Likewise, what is the correct way to import/require files from main.(dev/prod).js from a file (semi-cyclic). For example, in 'versionManager.js' I have used:

If you have to do that, then rethink and refactor, cyclic deps are usually wrong:) I don't really see why you should ever need to import `main.prod.js` anywhere. If you have some kind of config in that file which is used elsewhere then move that part into a common file and require that. But again, if you can too can share a minimal repo where you experience this issue I am happy to look into that.
