### ISSUE TITLE
How to use local js files after package

### ISSUE THREAD

**Issue by Vaye1** [electron-react-boilerplate/electron-react-boilerplate#2381]
I wanted to make a tool that would allow the user to import his or her scripts。
So how do I import js files dynamically

**Comment by HaveAGitGat** [comment]
What do you mean by dynamically?

If you have the absolute path to the script, you can use:

`var example = require('full/path/to/script.js)`

Use importFresh if the script is being changed while your app is running to prevent a cached version being used:

https://www.npmjs.com/package/import-fresh

**Comment by amilajack** [comment]
@Vaye1 can you please provide more details about what you're trying to do. That would really help answer your question.

**Comment by Vaye1** [comment]
> @ Vaye1您能否提供有关您要执行的操作的更多详细信息。那确实可以帮助您回答问题。

I want to use 'dialog.showOpenDialog' to get the corresponding folder address after the application is packaged, and then use the js file in the folder.

**Comment by amilajack** [comment]
See https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1043#issuecomment-312514802
