### ISSUE TITLE
More Docs about code signing

### ISSUE THREAD

**Issue by Aid19801** [electron-react-boilerplate/electron-react-boilerplate#2385]
First off, LOVE the boilerplate. Thank you so much for  building it. 

As i come to the end of coding the actual React app, I'm fnding myself frustrated by the lack of docs on **code signing**. 

It's not clear to me from ERB docs or `electron-builder` or `electron-osx-sign` docs how I should approach signing this.

You use `electron-builder` to package the app, and seems it's configured to provide app.asar minimising risk of anyone tampering with my app/src etc.

But when it comes to Provisioning Profiles, Code Signing Identities, Notarization, Mac vs Mas vs Xcode whether to open it there or how to sign via CLI, i seem to get lost in a world of keychain passwords, entitlements files, P12 files and other stuff.

I think a clear, concise tutorial, documentation or video would really benefit the community and build on the already sterling work you've done with this project. 

Big love.

![image](https://user-images.githubusercontent.com/15033409/75088632-d7d01a00-5547-11ea-8c32-519ec7233872.png)

**Comment by amilajack** [comment]
Code signing is definitely one of the most confusing parts of electron. Your best bet is to read the [docs for it](https://www.electron.build/code-signing). If you have any questions you should ask questions in the electron-builder repo. Sorry for the lack of guidance on this.

**Comment by Aid19801** [comment]
@amilajack agreed & understood, buddy. I ended up paying a dude off upWork to fix it all for me 😂

**Comment by ivanjeremic** [comment]
> @amilajack agreed & understood, buddy. I ended up paying a dude off upWork to fix it all for me

Can you send me his UpWork link?

**Comment by swyxio** [comment]
mfw all the docs i can find about signing and notarizing are by people who got it solved elsewhere https://xkcd.com/979/

**Comment by brijesh-ajna** [comment]
> @amilajack agreed & understood, buddy. I ended up paying a dude off upWork to fix it all for me 😂

@amilajack agreed & understood, buddy. I ended up paying a dude off upWork to fix it all for me

Can you send me Upwork profile of that fellow?
