### ISSUE TITLE
node child_process not working after packaging

### ISSUE THREAD

**Issue by jaykch** [electron-react-boilerplate/electron-react-boilerplate#2396]
I have this bit I am trying to run which works perfectly fine in development but when I package it doesnt work. I don't get any error either which is strange. Its like nothing happens.

```js
const userDataPath = (electron.app || electron.remote.app).getPath('userData');
const ptpPath = userDataPath + "/Print/ptp.exe";
const command = `${ptpPath} Invoice.pdf`;
const exec = require('child_process').exec;


function execute(command, callback) {
  exec(command, (error, stdout, stderr) => {
    callback(stdout);
  });
};

execute(command, (output) => {
  console.log(output);
});
```

**Comment by ahmedakmal525** [comment]
@jaykch Hi, did you resolve this issue?

**Comment by jaykch** [comment]
@ahmedakmal525 No, a way around this is creating html templates and and printing them from electron.
Another way is using a pdf viewer to load the entire pdf in a new window. You can then use the chromes print functions to print it, it opens like any pdf that opens in chrome. This way you can't silently print it.

**Comment by amilajack** [comment]
See https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1043#issuecomment-312514802
