### ISSUE TITLE
app.getVersion() returning electron version instead of package.json version

### ISSUE THREAD

**Issue by WilsonCazarre** [electron-react-boilerplate/electron-react-boilerplate#2397]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

`require('electron').remote.app.getVersion();` should return current version from package.json

## Current Behavior

It is returning electron version instead.

## Steps to Reproduce (for bugs)

1. In `app/components/Home.tsx`, call remote.app.getVersion() and show it in the Home screen.

```
/* eslint-disable react/jsx-one-expression-per-line */
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import routes from '../constants/routes.json';
import styles from './Home.css';

const appVersion = require('electron').remote.app.getVersion();

export default function Home() {
  return (
    <div className={styles.container} data-tid="container">
      <h2>Home {appVersion}</h2>
      <Link to={routes.COUNTER}>to Counter</Link>
    </div>
  );
}

```
2. run `yarn dev` or `yarn start`  

## Context

I started a project using this boilerplate as a template.
Turns out that I can't get the current app version from the `package.json` file. Instead, it returning my current electron version.
This leads me to the problem the `checkforupdates()` from `electron-updater` is also not working because it thinks that my app version is 7.1.13 instead of 1.0.0 (which is declared in package.json).

All files are exactly as in the boilerplate.

I tried to call `remote.app.getVersion()`, same result.
I tried to call it from main.dev.ts and pass it via `ipc`, same result.

## Your Environment

- Node version : 12.14.1
- Version or Branch used : master
- Operating System and version : Windows 10 Education

**Comment by steveetm** [comment]
This is due electron strange behaviour how it reads version which varies by how someone starts electron. As `yarn dev` basically calls `electron app/main.dev.ts` it can't really read any version from that js file. However, it will work once you package your application.
[details](https://github.com/electron/electron/issues/7085)
