### ISSUE TITLE
Not displaying error on missing imports

### ISSUE THREAD

**Issue by Jfelix61** [electron-react-boilerplate/electron-react-boilerplate#2398]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)

## Expected Behavior

Display red squiggly lines on Typescript missing import errors.

## Current Behavior

When there is a missing import, ERB files just show `any` instead of red squiggly lines for error.

## Steps to Reproduce (for bugs)

1. Create file

2. try to run a function which is not defined such as `foo()`

## Context

No changes were made to the boilerplate.

## Your Environment

- Node version : 12.14.1
- Version or Branch used : master
- Operating System and version : Mac Os Catalina

**Comment by Jfelix61** [comment]
So after different approaches, was able to solve it by removing `"typescript.validate.enable": false` from this [file](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/.vscode/settings.json).

**Comment by p4rse** [comment]
@Jfelix61 just did the same and wanted to post the same thing.

Shouldn't it be set to `true` since 1.0.0 which uses TS rather than Flow type checking?

**Comment by amilajack** [comment]
Yes, this is correct. I'll close this in a PR soon.
