### ISSUE TITLE
Where is the typings of `app/constants/routes.json`?

### ISSUE THREAD

**Issue by qtisan** [electron-react-boilerplate/electron-react-boilerplate#2400]
I followed the instructions and installed, it works fine.
But i found something not comfortable, as:

I add a route in `app/constants/routes.json` like below.

```
{
  "HOME": "/",
  "COUNTER": "/counter",
  "RECUR": "/recur"
}
```

In another file, i cannot get the tips of the new property(`RECUR`) in routes.

![image](https://user-images.githubusercontent.com/8434908/75967098-45942280-5f06-11ea-8520-c98ecb406391.png)

And then i removed all keys in `app/constants/routes.json`, nothing changed in code intellegence, as above.

I guess it may miss some typings in typescript, i added `routes.json.d.ts`, and make the typings of `RECUR`, it works fine.

*So, how can i update the typings of `routes.json` when it changed?*

**Comment by amilajack** [comment]
I'd recommend changing the `routes.json` to a `routes.js` and write a type annotation for the routes.
