### ISSUE TITLE
ESLint not working

### ISSUE THREAD

**Issue by kevincastejon** [electron-react-boilerplate/electron-react-boilerplate#2407]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Cloning the repo and inserting error into the code will display this error through ESLint.
## Current Behavior

Cloning the repo and inserting error into the code will not display this error through ESLint.

## Steps to Reproduce (for bugs)

Clone the repo and insert error into the code.

## Context

- Did you make any changes to the boilerplate after cloning it?
No
- Providing context helps us come up with a solution that is most useful in the real world
I'm using this boilerplate on node v10.19.0 Windows 10, I tried with Atom and Visual Studio (both with lint extension installed). No errors linted at all, although it works on any regular node project.

## Your Environment

- Node version : 10.19.0
- Version or Branch used : the version suggested on the README install doc (--depth 1 --single-branch --branch master)
- Operating System and version : Windows10
- Link to your project :

**Comment by ivanjeremic** [comment]
I have no linter feedback for the new typescript version of ERB, is this issue also referring to typescript? If so I have the same issue, this is probably also the reason why when I package the window is empty and all elements are missing I added.

**Comment by amilajack** [comment]
What's the latest hash of ERB that you're on? Try applying https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/9bc93bfe3fa77517b5fe6423f5f2d83afba697b8

**Comment by amilajack** [comment]
Fixed by https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/9bc93bfe3fa77517b5fe6423f5f2d83afba697b8

**Comment by kevincastejon** [comment]
do you have any fix for Atom users?

**Comment by amilajack** [comment]
This issue should only be present on vscode. What plugins are you using for atom?

**Comment by kevincastejon** [comment]
the ones recommended on the "editor configuration" section:
`apm install editorconfig es6-javascript atom-ternjs javascript-snippets linter linter-eslint language-babel autocomplete-modules file-icons`

**Comment by amilajack** [comment]
Ahh good catch! I forgot to update those. Here are the updated plugins you should install:
```bash
apm install editorconfig linter linter-eslint language-babel atom-typescript
```
