### ISSUE TITLE
Why is the new release v0.18.1 when we already have v1.0.0 ?

### ISSUE THREAD

**Issue by GerardKetuma** [electron-react-boilerplate/electron-react-boilerplate#2408]
Can we get some clarity to the different releases. I thought we had moved to v1.0.0 but now see new changes being pushed to v0.18.1. Not sure if there are two parallel branches being worked on and are the changes in 0.18.1 also in v1.0.0?

**Comment by amilajack** [comment]
Ignore the 0.18.1` release. it was pushed by accident because of the automated release process.
