### ISSUE TITLE
Adding dependencies should be part of README.md

### ISSUE THREAD

**Issue by akoskm** [electron-react-boilerplate/electron-react-boilerplate#2413]
Because this is a boilerplate app, adding some other dependencies to the project is a fairly frequent use case. However, there are certain rules you have to follow when doing so and those rules - given how important they are - basically hidden.

Here's the page that contains this crucial information:
https://electron-react-boilerplate.js.org/docs/adding-dependencies/

But, it's not in the sidebar
![image](https://user-images.githubusercontent.com/3111627/76698641-dc4ea500-66a5-11ea-8b0b-e949003b935a.png)

Later I found it through this issue:
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2350

IMO after https://github.com/electron-react-boilerplate/electron-react-boilerplate#starting-development should be the title **Adding Dependencies** and at least make the rule of thumb part of the readme.

**Comment by amilajack** [comment]
This was fixed a while ago
