### ISSUE TITLE
GIF demo is outdated

### ISSUE THREAD

**Issue by AddictArts** [electron-react-boilerplate/electron-react-boilerplate#2417]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

The animating gif shows the boilerplate running, but it also shows some additional things. For example it shows a code editor? It also shows moving the redux dev tools around. This must be old, redux dev tools are in the chrome tools area. The editor is a bit of a curiosity and there are no instructions on replicating what you see.

## Current Behavior

I am able to see the redux and react dev tools with a `yarn dev` after I updated extensions, which the README doesn't mention. I cannot replicated the code editor.

## Possible Solution

Update the animating gif to show the current project or add docs on how to do what it is showing.

## Steps to Reproduce (for bugs)

1. `yarn dev`

2. Observe visually, no code editor and redux dev tools hot keys don't work in main window.

## Context

Investigating the project and wanted to duplicate what I was seeing.

## Your Environment

- Node version : 12.11.0
- Version or Branch used : latest
- Operating System and version : MacOS Mojave
- Link to your project : git clone of this project following README

**Comment by amilajack** [comment]
These are old features of redux devtools, the GIF need to be updated
