### ISSUE TITLE
Setting up the Auto-Updater

### ISSUE THREAD

**Issue by frederikpietzko** [electron-react-boilerplate/electron-react-boilerplate#2418]
I am currently struggling with setting up an update server for my application.

Can anyone give me like a brief overview or maybe an example how i can make it work?

**Comment by oddjob23** [comment]
Check out the docs. It's pretty much everything you need and in the repo of auto updater you will find the rest of the answers. Hope it helps!

https://www.electron.build/auto-update

**Comment by OwenMelbz** [comment]
@frederikpietzko don't worry, the auto-update docs are not very clear for most people new to electron, I gave up trying to understand them

**Comment by oddjob23** [comment]
> @frederikpietzko don't worry, the auto-update docs are not very clear for most people new to electron, I gave up trying to understand them

I can only agree to this and I had plenty of issues while setting up and after 2-3 days of trying and consulting with other devs this is the easiest config that I found it does the job.

"publish": {
      "provider": "s3",
      "bucket": "bucket-name",
      "ßendpoint": "http://s3.amazonaws.com/bucket-name/"
    }

This works almost the same way for github releases. Please note, I managed to make it work with public access to s3 bucket and github releases.

**Comment by frederikpietzko** [comment]
@oddjob23 Thank you very much! Will try it out! 
@OwenMelbz The unclear docs are one Problem but the real problem for me is, that i can't seem to find good examples or some kind of proper tutorial on it. It's like nobody shared any knowledge on that.

**Comment by oddjob23** [comment]
@frederikpietzko Check these two examples:
- https://github.com/iffy/electron-updater-example
- https://github.com/electron-userland/electron-builder/blob/docs/encapsulated%20manual%20update%20via%20menu.js
