### ISSUE TITLE
Updating Electron to 8.2

### ISSUE THREAD

**Issue by OwenMelbz** [electron-react-boilerplate/electron-react-boilerplate#2419]
Is it possible to update ERB to use Electron 8.2? If so is there a process that should be followed?

**Comment by FishOrBear** [comment]
I use 
`yarn upgrade`
And found no problem

**Comment by amilajack** [comment]
Blocked on https://github.com/DevExpress/testcafe-browser-provider-electron/issues/64

**Comment by null-none** [comment]
@OwenMelbz Upgraded electron 9.0.0. Use my pull request https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2469
