### ISSUE TITLE
react-virtualized is rendered incorrectly

### ISSUE THREAD

**Issue by yaronlevi** [electron-react-boilerplate/electron-react-boilerplate#2421]
Hi (-:

I am trying to draw a basic table using react-virtualized, but it gets rendered incorrectly.
I've cloned the electron-react-boilerplate, installed react-virtualized, and added some basic code to show a table:
```
import React from 'react';
import { Column, Table } from 'react-virtualized';

const list = [
  { name: 'brian', description: 'dog' },
  { name: 'garfield', description: 'cat' }
];

export default function Home() {
  return (
    <div>
      <Table
        width={500}
        height={500}
        headerHeight={50}
        rowHeight={50}
        rowCount={list.length}
        rowGetter={({ index }) => list[index]}>
        <Column label="Name" dataKey="name" width={200} />
        <Column width={200} label="Description" dataKey="description" />
      </Table>
    </div>
  );
}
```

The resulting table looks like this:

<img width="624" alt="Screen Shot 2020-03-28 at 19 24 05" src="https://user-images.githubusercontent.com/5398977/77827998-26b23600-712a-11ea-82d5-e32f45e54e38.png">

Just to make sure, I've also removed any CSS from the boilerplate that might cause this.

I've created a [repo](https://github.com/yaronlevi/electron-with-react-virtualized) to easily show the bug.

Just clone it, hit "yarn" and then "yarn dev"

Any help on issue would much appreciated 🙏

**Comment by steveetm** [comment]
You forgot to add react-virtualized's main css file, you can import it in `app.global.css` with `@import '~react-virtualized/style.css` or similarly in `index.tsx` it is up to you. Please refer to react-virtualized's documentation.

**Comment by yaronlevi** [comment]
Thank You!
