### ISSUE TITLE
Webpack loading libraries as browser (despite setting mainFields in config)

### ISSUE THREAD

**Issue by hammadzz** [electron-react-boilerplate/electron-react-boilerplate#2423]
Trying to use aws-sdk but it is loaded as web sdk. I tried adding add mainFields to webpack.config.base.js as:
`mainFields: ['module', 'main']`

Under `resolve` and under `rules` key

But it seems to still load broswer from the package.json of the package instead of main.
```json
  "main": "lib/aws.js",
  "browser": {
    "lib/aws.js": "./lib/browser.js",
    "fs": false,
    "./global.js": "./browser.js",
    "./lib/node_loader.js": "./lib/browser_loader.js"
  },
```

Related:
https://github.com/webpack/webpack/issues/7953

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

For it to load main and module

## Current Behavior
Loads browser

## Possible Solution
Finding a workaround in webpack config

## Your Environment

- Node version : v10.15.3
- Version or Branch used : master
- Operating System and version : OSX 10.15.4
- Link to your project :

**Comment by steveetm** [comment]
I think it is quite normal to use the browser field when the target is `electron-renderer` in webpack config. I guess if you `require('aws-sdk')` in the main process it will use `lib/aws.js`.

Anyway, if you really would like to use `lib/aws.js` in renderer process, you should write a resolver plugin(I don't think you can trick this with rule's resolve config, but don't really have any experience on that).

And may I ask you why it is important that aws-sdk loaded through lib/browser.js?

**Comment by hammadzz** [comment]
@steveetm I actually don't want the `lib/browser.js` as it is limited and using credentials from the system ~/.aws/credentials does not work.

I will look into how to use it in the main process. Still new to electron but know that there is a main and render process. I only needed to use the aws-sdk to connect with aws to retrieve data and render it in the UI.
