### ISSUE TITLE
set proxy  not work

### ISSUE THREAD

**Issue by cornwang** [electron-react-boilerplate/electron-react-boilerplate#2430]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Current Behavior 

1. ##  webpack.config.renderer.dev.babel.js 

![image](https://user-images.githubusercontent.com/27324050/78108812-aaba3580-742a-11ea-932f-fec08f3bad4d.png)

2. ## api Fetch
![image](https://user-images.githubusercontent.com/27324050/78109089-274d1400-742b-11ea-88e2-02faa5bdd14b.png)

3. ## run
![image](https://user-images.githubusercontent.com/27324050/78109237-6da27300-742b-11ea-9ffd-7fef20288c1d.png)
Is there something wrong with my configuration？

## Expected Behavior

i need this api request is  http://xxx.xxx.xx.xx:xx/api/xxxxxx

**Comment by steveetm** [comment]
You fetched a `file://` url and set the proxy in webpack-dev-server, I really do think this is not what you want. You can check if the webpack-dev-server proxy working if go to `http://localhost:1212/api`, it should redirect your target(with default configurations).

**Comment by cornwang** [comment]
@steveetm  thx,When I type localhost: 1212 in my browser,it's will error  (Cannot GET /),what happened?

**Comment by steveetm** [comment]
Thats normal, it means webpack-dev-server is working, but it is for development. I don't really know what are you trying to achieve, but I doubt you need that kind of proxy setup in `devServer`.
If you want to catch and manipulate every requests from your app you may wanna experiment with service workers. Or if you run some kind of server in your main electron process simply `fetch('http://localhost:yourport/api/login/getCert')`. But again, I have no idea about your setup or goals, but honestly, I see no bug there.
