### ISSUE TITLE
Error when adding firebase-admin package -  Can't resolve '@firebase/app'

### ISSUE THREAD

**Issue by suregi** [electron-react-boilerplate/electron-react-boilerplate#2435]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [x] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

yarn add firebase-admin
-> no error

## Current Behavior

I get this error when issuing: yarn add firebase-admin

ERROR in ./node_modules/@firebase/database/dist/index.cjs.js
Module not found: Error: Can't resolve '@firebase/app' in 'C:\Users\hk\wk\electron-react-boilerplate-master\node_modules\@firebase\database\dist'

package.json is updated with:
    "firebase-admin": "^8.10.0",

Get the same error when running with "yarn dev"

## Possible Solution
In a skeleton Node app, "yarn add firebase-admin" worked fine.

## Steps to Reproduce (for bugs)

1. freshly download electron-react-boilerplate

2. yarn dev -> counter app works fine

3. yarn add firebase-admin -> get following error:
ERROR in ./node_modules/@firebase/database/dist/index.cjs.js
Module not found: Error: Can't resolve '@firebase/app' in 'C:\Users\hk\wk\electron-react-boilerplate-master\node_modules\@firebase\database\dist'

4.

## Context

I am trying to make firebase admin dashboard and firebase-admin is the Google's official module.
https://github.com/firebase/firebase-admin-node

As described in the steps above, no changes has been made to the boilerplate in build script or source.

In a plain Node app, adding firebase-admin worked fine:
- npm init
- yarn add firebase-admin -> works fine

## Your Environment

Tested in both macOS (Mojave) and Win10
- Node version : 11.10.1 (macOS) 12.16.1 (Win10)
- Version or Branch used : master as of 2020-04-07
- Operating System and version : macOS & Win10
- Link to your project :
- firebase-admin version:  "^8.10.0"

**Comment by dbvrac** [comment]
I had a similar struggle. I believe it has to do with Electron not getting along with the firebase-admin package. I got around it by adding firebase (not -admin) to my inner package.json and building up from there.
You'll notice in this project they are not adding `firebase-admin` to their package.json, just `firebase`: [https://www.electronjs.org/apps/firebase-admin](https://www.electronjs.org/apps/firebase-admin)
