### ISSUE TITLE
How to import less file globally with TSX file

### ISSUE THREAD

**Issue by huangshuwei** [electron-react-boilerplate/electron-react-boilerplate#2439]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Import ant.design styles globally and  [customize ui theme](https://3x.ant.design/docs/react/customize-theme)
> I'm using ant.design UI

## Current Behavior

Cannot import ant design less file globally

## Steps to Reproduce (for bugs)

1.Install related packages:
```
yarn add antd@3.26.15 less less-loader
```

2.less loader setting:
```
// webpack.config.renderer.prod.babel.js
        {
                test: /\.less$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: {
                                localIdentName:
                                    '[name]__[local]__[hash:base64:5]'
                            },
                            importLoaders: 1,
                            sourceMap: true
                        }
                    },
                    {
                        loader: 'less-loader',
                        options: {
                            sourceMap: true,
                            javascriptEnabled: true
                        }
                    }
                ]
            }
```
```
// webpack.config.renderer.dev.babel.js
        {
                test: /\.less$/,
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            modules: {
                                localIdentName:
                                    '[name]__[local]__[hash:base64:5]'
                            },
                            sourceMap: true,
                            importLoaders: 1
                        }
                    },
                    {
                        loader: 'less-loader',
                        options: {
                            sourceMap: true,
                            javascriptEnabled: true
                        }
                    }
                ]
            }
```
3.import antd theme from entrance file:
```
import 'antd/dist/antd.less';
```

4.Global import is not effective

## Your Environment

- Node version :v10.16.3
- Version or Branch used :v1.10
- Operating System and version :win10
- Link to your project :

**Comment by huangshuwei** [comment]
I know that styles can be imported globally through `. global.css `.But css and less cannot be mixed

**Comment by steveetm** [comment]
You don't need `MiniCssExtractPlugin.loader` in you development config.
You also mentioned global import but you are using css-modules. Which could work but not sure if that is what you really want.

**Comment by huangshuwei** [comment]
yes,it was my mistake.
> @steveetm You don't need MiniCssExtractPlugin.loader in you development config.

I don't understand why it doesn't work,when import less file globally with TSX file.
There is no error on the console...

**Comment by huangshuwei** [comment]
@amilajack 
need your help

**Comment by steveetm** [comment]
Actually it is working for me, but if you use css modules, class names are replaced with hashed names and you must import the css file into a variable and assign class names that variable. This is why I said this could be undesired for a global import, as usually you don't want this when less/scss/css is global.
Either try
```
import styles from './yourLessStyle.less`;
[...]
return (
<div className={styles.classFromYourStyle}></div>
)
```

or remove `modules: {
                                localIdentName:
                                    '[name]__[local]__[hash:base64:5]'
                            },`
from your loader config.

**Comment by huangshuwei** [comment]
@steveetm 
thx. I'll try it later

**Comment by huangshuwei** [comment]
@steveetm 
thx. it's works when I remove css module config from less loader
> or remove modules: { localIdentName: '[name]__[local]__[hash:base64:5]' },
from your loader config.
