### ISSUE TITLE
Microsoft Defender detected "Trojan:Win32/Wacatac.B!ml" in dependency

### ISSUE THREAD

**Issue by galaxyAbstractor** [electron-react-boilerplate/electron-react-boilerplate#2440]
Just FYI,

I just cloned master on Windows 10 and installed the dependencies, and Windows Defender detects "Trojan:Win32/Wacatac.B!ml" in one of the dependencies (app-builder, I think? Doesn't seem to be a direct dependency), see below:

![defender](https://i.imgur.com/xIdKWr3.png)

It might just be a false positive, but it might be worthwhile to check for outdated dependencies?

**Comment by Stylobik** [comment]
[https://github.com/electron-userland/electron-builder/issues/4878#issuecomment-614587486](https://github.com/electron-userland/electron-builder/issues/4878#issuecomment-614587486)

**Comment by sahababd4** [comment]
[Picture](https://prnt.sc/12bg47r)
windows Defender showing this application as a trojan virus. maybe someone added trojan code in that application and your problem also the same
