### ISSUE TITLE
Unable to load preload script:  'renderer.prod.js'

### ISSUE THREAD

**Issue by saifeiLee** [electron-react-boilerplate/electron-react-boilerplate#2441]
I have the problem `Unable to load preload script: /Users/waltermitty/Code/cvte/electron-easi-camera/app/dist/renderer.prod.js`. If I add `nodeIntegration: true,`, My project can work. But the console error is still. My questions are: 
1. what's its effect and why we need `renderer.prod.js` in production build,  even though everything works right without it?
2. How can I require('fs') properly in harmony with `preload.renderer.js`. I do not want to modify the original `main.dev.ts`.

**Error screenshot**
![image](https://user-images.githubusercontent.com/28710808/79623629-ed308180-814f-11ea-8ad3-5fdbbd96d06d.png)

If you need any further info, plz let me know and I will append as soon as possible.

**Update**
I found the reason caused the error: I require node native `fs` module in my react component. Because I want to implement saving file function. When I remove the `require('fs')`, error gone.Here is my code snippet:
```javascript
const fs = require('electron').remote.require('fs');
fs.writeFile(`${url}/${name}`, buf, (err: Error) => {
      if (err) {
        logger.error(err);
      } else {
        logger.log('save file successfully!');
      }
    });
```

**Comment by amilajack** [comment]
Seems like you solve the issue so I'll close this.

**Comment by saifeiLee** [comment]
> Seems like you solve the issue so I'll close this.

I should close this issue earlier. My bad. Sorry.

**Comment by kingpalethe** [comment]
Having this exact same issue here.

**Comment by kingpalethe** [comment]
currently I am using `fs` like this, which works well in development: `import fs from 'fs';`

**Comment by kingpalethe** [comment]
In development everything works well, but when I run `yarn cross-env DEBUG_PROD=true yarn build && yarn cross-env DEBUG_PROD=true yarn start` I see the exact  same errors that @saifeiLee reported

**Comment by kingpalethe** [comment]
```
Unable to load preload script: C:\Users\USERNAME\workspace\voxclient\app\dist\renderer.prod.js
(anonymous) @ init.ts:206
init.ts:209 TypeError: Cannot read property 'style' of null
    at C:\Users\USERNAME\workspace\voxclient\app\node_modules\fabric\dist\fabric.js:2575
    at C:\Users\USERNAME\workspace\voxclient\app\node_modules\fabric\dist\fabric.js:2626
    at Object.<anonymous> (C:\Users\USERNAME\workspace\voxclient\app\node_modules\fabric\dist\fabric.js:2694)
    at Object.<anonymous> (C:\Users\USERNAME\workspace\voxclient\app\node_modules\fabric\dist\fabric.js:29676)
    at Module._compile (internal/modules/cjs/loader.js:967)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004)
    at Module.load (internal/modules/cjs/loader.js:815)
    at Module._load (internal/modules/cjs/loader.js:727)
    at Function.Module._load (electron/js2c/asar.js:738)
    at Module.require (internal/modules/cjs/loader.js:852)
```

**Comment by kingpalethe** [comment]
If I try @saifeiLee solution, which is to replace `import fs from 'fs';` with `const fs = require('electron').remote.require('fs');` ... then `yarn dev` won't boot the development application, it fails with this error:

```
const fs = require('electron').remote.require('fs');
TypeError: Cannot read property 'require' of undefined
```

**Comment by kingpalethe** [comment]
this fixed this issue for me! https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2503/commits/1d97ac110321288b0068c55ca458e3563b751551

**Comment by sanzhardanybayev** [comment]
@kingpalethe By default, **electron** doesn't let you to access **remote module**. In order to get access to it, you need to enable it by setting **enableRemoteModule** to **true** in **webPreferences** property when instantiating **BrowserWindow** . Here's an official solution:
```
 const mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('logo.png'),
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
    },
  });
  ````
