### ISSUE TITLE
Application window doesn't show up

### ISSUE THREAD

**Issue by kmgalanakis** [electron-react-boilerplate/electron-react-boilerplate#2445]
This is the first time I try this boilerplate, so maybe I'm missing something.

I follow all the documentation and install the boilerplate properly (I think) but when I hit `yarn dev` webpack starts to do its magic but that' all. This is all I get 

![image](https://user-images.githubusercontent.com/1268089/80465024-516af680-8943-11ea-9486-b50e89d55a92.png)

After that, I would expect to see an app window pop up somewhere in my system with the app, or at least this is my understanding.

Is this the case and I'm having an issue or am I missing something?

**Comment by amirkabiri** [comment]
I have this problem too

**Comment by s0b3ar** [comment]
Same problem too

**Comment by s0b3ar** [comment]
I solved this problem for myself. Switch to default Windows Theme in Settings.

**Comment by kmgalanakis** [comment]
@s0b3ar how did you figure this out? it doesn't make any sense. When you say `Switch to default Windows Theme in Settings.` Which theme are you talking about?

**Comment by s0b3ar** [comment]
![511BBA36A80C](https://user-images.githubusercontent.com/346469/80608248-ebb86080-8a4f-11ea-8466-dca044fd868b.png)
this one

[article](https://www.simplehow.tips/a/62/how-to-change-theme-in-windows10)

this version chromium does not work with dark theme in windows (probably)

**Comment by kmgalanakis** [comment]
This is confusing. Is there anything we can do about it in order not to actually change the theme?

**Comment by ThinkDualBrain** [comment]
Thought this suggestion was lunacy, but it also worked for me. @s0b3ar just saved me a ton of time. Thanks!

**Comment by kmgalanakis** [comment]
@amilajack IMHO I don't think that this qualifies as `won't fix`. I know that there is a workaround that actually works, but for devs with dark themes in Windows, you cannot really tell them to change their theme if they want to work with this boilerplate.

For me, that wouldn't be an option.

**Comment by amilajack** [comment]
This is an issue electron, not the boilerplate
