### ISSUE TITLE
Issue Viewing Devtools when Running ERBP as Admin

### ISSUE THREAD

**Issue by justinkuntz** [electron-react-boilerplate/electron-react-boilerplate#2446]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

When running "yarn dev" in an elevated command prompt to start the Electron app, I should be able to view Redux, React, and Devtron browser extensions to properly test and debug my code.

## Current Behavior

When running "yarn dev" in an elevated command prompt to start the Electron app, my dev console does not appear; if I attempt to click "Toggle Developer Tools" under the "View" tab, nothing appears. A workaround our team has found is adding an extra line of code in the main.dev.js file to forcibly open a console window when the app starts. However, the devtools still fail to show up.

Please note that this behavior persisted even when installing a clean version of Electron React BoilerPlate without any additional node modules or code modifications.

## Possible Solution

We are stumped, so possible solutions come to mind...

## Steps to Reproduce (for bugs)

1. Open an elevated command shell inside the Electron React BoilerPlate folder.

2. Run yarn dev

3. Attempt to open developer tools (nothing should open).

## Context

The application being developed requires the use of DLL files to communicate with system hardware. Since the DLLs require admin privileges to access said hardware, we are forced to run the app as administrator to alleviate this issue. However, running the Electron app as admin has result in major development issues.

## Your Environment

- Node version : 12.16.1
- Version or Branch used : Current version of master branch
- Operating System and version : Windows 10 Pro, Version 10.0.18363
- Link to your project : Unfortunately this is a private repository

**Comment by NemoDream** [comment]
I had the same problem,but i don`t know how to solve it

**Comment by bryantb2** [comment]
Same here, running in Admin results in weird behavior for the debugging tools AND the debug window doesn't appear. Browser bug, perhaps?

**Comment by NemoDream** [comment]
I solved the problem today.I turned off the dark mode for Windows 10,and turn on the light mode,the electron window was successfully created.
This is probably related to this issue [electron/electron#19468](https://github.com/electron/electron/issues/19468)
