### ISSUE TITLE
I want to use javascript instead of typescript

### ISSUE THREAD

**Issue by fabioalxk** [electron-react-boilerplate/electron-react-boilerplate#2451]
Is it already implemented?
Is there any workaround?

**Comment by amilajack** [comment]
See this release: https://github.com/electron-react-boilerplate/electron-react-boilerplate/releases/tag/v0.18.0

It's the most recent release that was written in JS

**Comment by besserwisser** [comment]
Thank you! I was also surprised to find TS instead of JS.

**Comment by dominicdev** [comment]
hi Im trying to use JavaScript version also cause im having hard time with typescript, is there any tutorial how to setup?

**Comment by js-art** [comment]
Hi, why it's in typescript? typescript takes time without a big advantage.
