### ISSUE TITLE
How do I use the JavaScript version

### ISSUE THREAD

**Issue by tym3515** [electron-react-boilerplate/electron-react-boilerplate#2455]
How do I use the JavaScript version
Because some packages don't have TS version

**Comment by osdamv** [comment]
As far I can tell you have to clone an old version, v0.9.0 for example ...

**Comment by jooohhn** [comment]
#2451 should send you towards the right path

**Comment by dominicdev** [comment]
hi Im trying to use JavaScript version also cause im having hard time with typescript, is there any tutorial how to setup?
