### ISSUE TITLE
css border is not showing while print previewing its moving aside 

### ISSUE THREAD

**Issue by shivammakwan** [electron-react-boilerplate/electron-react-boilerplate#2456]
css border is not showing while printing and previewing its moving aside 
![screenshot](https://user-images.githubusercontent.com/47806980/80916322-96dd5880-8d75-11ea-9314-d5164fcd2640.png)

**Home.js**
`     
        type Props = {};

        export default class Home extends Component<Props> {
          printSlip() {
            window.print();
          }
          state = {
            code: 'IGHD645'
          };

          props: Props;

          render() {
            return (
              <div className={styles.container} data-tid="container">
                <h2>Home</h2>
                <Link to={routes.COUNTER}>to Counter</Link>
          <br/>
          <span className={styles.td_block}>{this.state.code[0]}</span>
          <span className={styles.td_block}>{this.state.code[1]}</span>
          <span className={styles.td_block}>{this.state.code[2]}</span>
          <span className={styles.td_block}>{this.state.code[3]}</span>
          <span className={styles.td_block}>{this.state.code[4]}</span>
          <br/><br/>
          <button onClick={() => this.printSlip()}>print</button>
        </div>
        );
        }
        }
`
**Home.css**

`.td_block {
  border: 1px solid #0000008c !important;
  height: 18px;
  width: 29px;
  text-align: center;
  font-size: 13px;
  font-weight: bolder;
}`

**Comment by amilajack** [comment]
please follow issue template
