### ISSUE TITLE
"Unable to create basic Accelerated OpenGL renderer"

### ISSUE THREAD

**Issue by specter78** [electron-react-boilerplate/electron-react-boilerplate#2457]
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.

## Prerequisites

- [x] Using yarn
- [ ] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Don't know. Trying for the first time.

## Your Environment

- Node version : 14.1.0
- Version or Branch used : Master
- Operating System and version : macOS 10.15.4

**Comment by amilajack** [comment]
This is not an issue with the boilerplate. See https://github.com/electron/electron/issues/20944
