### ISSUE TITLE
Migrate all components to use hooks

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#2461]
Two things that need to do this:

* Migrate all components to hooks
* ESLint plugin: `yarn add eslint-plugin-react-hooks --dev`. ESlint extend the defaults (`"plugin:react-hooks/recommended"`).  Update the config in [erb's eslint config](https://github.com/electron-react-boilerplate/eslint-config-erb).

**Comment by ivanjeremic** [comment]
Hey @amilajack , I tried today to get dependency warning for my useEffects to work but it seems to install eslint-plugin-react-hooks  manually and doesn't work, any info on when the erb-eslint will support it natively? I would appreciate a workaround that works until then.

**Comment by amilajack** [comment]
Feel free to contribute the change. I outline the work that needs to be done so that the community can contribute this.

**Comment by ivanjeremic** [comment]
> Feel free to contribute the change. I outline the work that needs to be done so that the community can contribute this.

The documentation says adding `"plugin:react-hooks/recommended"` to eslint settings does the  trick, I checked erb's eslint config and this is already in there, also I checked if I have latest version of erb's eslint config and yes I do, so technically it should already work but it does not give me dependency errors on useEffect.

**Comment by amilajack** [comment]
Try using [this config](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/.eslintrc.js) with `next` npm release tag for eslint-config-erb

**Comment by reZach** [comment]
@amilajack There was good discussion I read on here as well about using hooks: https://news.ycombinator.com/item?id=22995928. Just wanted to present both sides as using hooks doesn't solve all problems.

**Comment by ivanjeremic** [comment]
> @amilajack There was good discussion I read on here as well about using hooks: https://news.ycombinator.com/item?id=22995928. Just wanted to present both sides as using hooks doesn't solve all problems.

It is the direction React moves, so I think it is smart to follow what the React team is doing.

**Comment by reZach** [comment]
@ivanjeremic They are supporting both, yes. I just want to echo a comment by a user in the HackerNews thread:

> Hooks have unlocked so much power in React but still deserve critiquing. However I think the author only hinted at the major complaint I have about hooks, which is that **it's no longer Javascript**. It's not a function, it's sort of like type system magic. **Hooks can't be nested, order matters, can't be conditionally called, and you have to understand trickier memoization to avoid bugs.** It also isn't portable knowledge to other systems, like vanilla Javascript is. React is great because it's vanilla Javascript, expressions all the way down, and lifecycle methods, which everyone is used to. Hooks are a new non-vanilla-javascript paradigm with special and sometimes tricky rules. Other than, there's no reason to write React unless you're using hooks, and I wonder what the next major paradigm shift will be. I look back on all our HOCs and function as children and shudder compared to how easy it is with hooks.

Not that you haven't researched it yourself, I'm just thinking that these are subtle things the framework will need to understand for this template. Hooks in general can confuse beginners in general and are not transferable knowledge, but this is simply preference I just wanted to share in case you didn't consider before.

**Comment by gcangussu** [comment]
@amilajack I can help on this. Would be better to make multiple smaller PRs or just a single big PR?

**Comment by gcangussu** [comment]
@amilajack You probably can close this. I've checked the code, you are using hooks everywhere you can already. Let me know if I missed anything.

**Comment by amilajack** [comment]
@gcangussu thanks for the heads up on this!
