### ISSUE TITLE
When I generate a dmg it works only on my system

### ISSUE THREAD

**Issue by exogenesys** [electron-react-boilerplate/electron-react-boilerplate#2462]
The app I've made and compiled into an `.dmg` or `.app` using the command `yarn package-mac` works on my system but shows the error 'The application ApplicationName can't be opened' on all the other macOs systems.

I understand that Gatekeeper doesn't let apps by unidentified developers run and I understand that there are process which you should do before distributing your app:

1. Sign the app 
2. Notarise

I get the same error after signing the app using Apple's Developer ID. 
Notarization is only allowed to people who has the Apple's $99 membership.

I just want to share the app I've made to my friend for feedback. Is there no way I can do that, other getting to package the app with the source code on their own? This is just seems a very strange thing to me.

Have I reached the right conclusions? Is there absolutely know way, my friends can run the app, without cloning and compiling it?

Thanks!

**Comment by amilajack** [comment]
What you can do is prevent `electron-builder` from signing the app. I'm not sure how to do this but I'd recommend asking that question in the [electron-builder repo](https://github.com/electron-userland/electron-builder)

**Comment by amilajack** [comment]
[This doc answers](https://www.electron.build/code-signing#how-to-disable-code-signing-during-the-build-process-on-macos) your question. You need to that the ENV variable to your `package-mac` npm script.
