### ISSUE TITLE
Changing file structure braeaks imports

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2463]
Changing the file structure or moving folders around breaks all imports in the files, it adds a `'./node_modules/...';` in front of every import like this `'./node_modules/react';`

Google says changing the vscode editor workbench settings to use locally installed typescript will fix this but it does not.

Editor; VSCODE,
After some research, it has something to do with TS and how it is used in the project/ide.
 
Maybe there is a solution ERB can use in the boilerplate to fix this?

**Comment by amilajack** [comment]
This is not an issue with ERB. More like an issue with VSCode or TS language server.
