### ISSUE TITLE
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

### ISSUE THREAD

**Issue by yadav-saurabh** [electron-react-boilerplate/electron-react-boilerplate#2466]
I just cloned the repo and thought of using scss instead of css and everything was working fine until I did a commented the css property for the `a:hover` in that file and got this error:
(was using yarn run dev command to run the project)
```
CssSyntaxError: /app/app.global.scss:47:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

  45 | //   text-decoration: none;
  46 | //   cursor: pointer;
> 47 | // }

```

## Prerequisites

- [x] Using yarn
- [ ] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior
Use of single-line comments in scss even if the comment has single quotes/ brackets or semi-colon.
`// single-line comments with 'single quotes' `

## Current Behavior
Not able to use single-line comments in scss. 

## Possible Solution

I don't know tried searching online and solving it but got confused.

## Steps to Reproduce (for bugs)

1. Just change the file `app.global.css` to `app.global.scss`

2.  Do a single line comment for any property like `a` or `li`  must also include `{` `}`

3. Or just add a single line comment and include `'` or `{`

4. ex `// hello this is an error comment because of using ' or {`

## Context

Single line comments work for some reason if you include a single quote or curly brackets or a semi-colon it throws an error.

## Your Environment

- Node version: 12.16.3
- Version or Branch used:  master
- Operating System and version: Ubuntu 18.04
-  Yarn version: 1.22.4

**Comment by aFrontendDev** [comment]
Hey, so I've also had this problem and after some trial and error and much frustration I think i've found the problem. I'm still to investigate further to see if there's a fix for this but essentially removing the 'TypedCssModulesPlugin' in the webpack renderer config removed the problem and the scss compiled as it should.

So in the plugins section if you remove TypedCssModulesPlugin you should no longer have this problem, this is a temp fix for me at this point, hopefully I'll be able to find a better fix later.

`
plugins: [

    /*new TypedCssModulesPlugin({
      globPattern: 'app/**/*.{css,scss,sass}'
    }),*/


`

**Comment by aFrontendDev** [comment]
hmm looks like it's a known issue - https://github.com/dropbox/typed-css-modules-webpack-plugin/issues/11

**Comment by yadav-saurabh** [comment]
Thanks @aFrontendDev.

removing TypedCssModulesPlugin works. 
Also until the bug is fixed will need to define the types manually.

**Comment by code-matt** [comment]
import precss from 'precss'

```
    new TypedCssModulesPlugin({
      globPattern: 'app/**/*.{css,scss,sass}',
      postCssPlugins: defaultPlugins => [
        require('postcss')([
          precss()
        ]),
        ...defaultPlugins,
      ],
    })
```

adding this let me parse nested scss styles automatically

**Comment by syddo** [comment]
I encountered the same error when I tried to use styled-elements. good to know that this workaround.

**Comment by dugiwarc** [comment]
@code-matt Where did you add this?

**Comment by amilajack** [comment]
We're no longer using `typed-css-modules-webpack-plugin`. Please use latest version of ERB

**Comment by codingedgar** [comment]
> Thanks @aFrontendDev.
> 
> removing TypedCssModulesPlugin works.
> Also until the bug is fixed will need to define the types manually.

is there any workaround to type automatically?
