### ISSUE TITLE
Ability to easily add assets 

### ISSUE THREAD

**Issue by MJomaa** [electron-react-boilerplate/electron-react-boilerplate#2467]
### Scenario
I have custom .draft, .xml and .obj files I need to fetch during run-time depending on user input.

### Proposal
An `assets` folder that will get copied into the dist folder, then later bundled in to the asar archive and is accessible through `./assets/` would be enough.

**Comment by schrufygroovy** [comment]
how can I achieve this currently? How do I need to change the webpack configurations? Could you maybe give me some kind of hint for this?

**Comment by MJomaa** [comment]
@schrufygroovy 
One easy solution is to use the `CopyWebpackPlugin`.

1. Install `copy-webpack-plugin` via yarn.
2. Add the plugin with configured path patterns to `webpack.config.renderer.dev.dll.babel.js` and `webpack.config.renderer.prod.dll.babel.js`
3. Optionally add a `clean` command so you can `yarn clean` before `yarn dev` or `yarn package`. One way to clean is to run rimraf concurrently.

**Comment by Hazuki124** [comment]
Workaround without any webpack solutions:
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/250#issuecomment-651186831

**Comment by amilajack** [comment]
Moving discussion to #250
