### ISSUE TITLE
Unable to build ReactJS Components

### ISSUE THREAD

**Issue by ifitzsimmons** [electron-react-boilerplate/electron-react-boilerplate#2468]
I am trying to import a React app into this boilerplate. 

My components are written in jsx. When I run `yarn build-renderer` or `yarn dev` I get this error
```
ERROR in ./app/components/AllProducts/AllProducts.jsx 83:4
Module parse failed: Unexpected token (83:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   // );
|   return (
>     <div className={styles.myContainer}>
|       Hello
|     </div>
```

If I change this file to tsx, all is well. I'd eventually like to get this project into TypeScript, but I'll do that incrementally and need it to build with jsx AND tsx components. 

Admittedly, I am awful with webpack configuration so I imagine this is an easy fix, but could someone let me know how to fix this?

**Comment by rocket1** [comment]
I am having a similar issue, with the TYpeScript (latest) version and older versions of electron-react-boilerplate.

In my case, 'yarn dev' works fine, but compiling to a package I get the 'loader' error above. 

All I'm attempting to do is import a file into main.dev.js(ts).  This file simply has:

`class TestClass {
  _foo;

  _bar;

  doStuff = () => {
    const baz = 'zap';
  };
}

export default TestClass;
`

and in main.dev.js I have:

`import TestClass from './test-class';

const myTestClass = new TestClass();
myTestClass.doStuff();`

Under 'yarn dev'... no problems. When doing 'yarn package-mac', though, I get:

 ERROR in ./app/test-class.js 2:6
[0] Module parse failed: Unexpected token (2:6)
[0] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[0] | class TestClass {
[0] >   _foo;
[0] | 
[0] |   _bar;
[0]  @ ./app/main.dev.ts 16:0-37 17:24-33


Any help appreciated!

**Comment by Antg-io** [comment]
if you change line 15 in `app/Clara/configs/webpack.config.base.js` to

`test: /\.ts|\.tsx|\.jsx|\.js?$/,`

it will work

**Comment by rocket1** [comment]
I see this is closed...

So, the fix from Antg-io fixed the issues on the TypeScript-based boilerplate, but not the preveious .js/.jsx only boilerplate.

module: {
    rules: [
      {
        test: /\.ts|\.tsx|\.jsx|\.js?$/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true
          }
        },
....

Any idea what sort of change I can make to the webpack config to compile these ES6 files for production only?  My boilerplate is virtually unchanged.
