### ISSUE TITLE
yarn dev hangs and doesn't create electron window on Windows 10

### ISSUE THREAD

**Issue by koszti** [electron-react-boilerplate/electron-react-boilerplate#2474]
`yarn dev` hangs and doesn't create the electron window on Windows 10.

```
D:\dev\electron-react-boilerplate>yarn dev
yarn run v1.22.4
$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
Starting Main Process...

> electron-react-boilerplate@1.1.0 start-main-dev D:\dev\electron-react-boilerplate
> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts
```

No error message but it starts hanging after this output and the electron window doesn't pop up.
It's only on Windows 10, Ubuntu and Mac working fine.

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

`yarn dev` should create an electron window.

## Current Behavior

`yarn dev` starting the Main Process but the electron window doesn't show up. Task Manager shows 4 running electron processes but no electron window displayed on screen.

`yarn start` opens the electron window correctly

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

```
$ git clone https://github.com/electron-react-boilerplate/electron-react-boilerplate.git
$ yarn
$ yarn dev
```

## Context

Cannot develop on Windows 10. No changes made in the repo and it's working fine on Mac and Ubuntu.

## Your Environment

- Node version : 10.20.1 and 12.17.0 both same issue
- Version or Branch used : master, v1.0.0 and v1.1.0
- Operating System and version : Windows 10 v2004
- Link to your project :

**Comment by koszti** [comment]
turns out it's somehow related to `electron-devtools-installer` and it's hanging when trying to install `REACT_DEVELOPER_TOOLS` and `REDUX_DEVTOOLS` devtool extensions [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/2a72fc874de6318df56093d4715e84a350cf73e0/app/main.dev.ts#L39)

If I comment out trying to download the extensions then it will start but obviously without React DevTools that I miss. Some other workaround reported at https://stackoverflow.com/a/58030907

**Comment by NemoDream** [comment]
According to your suggestion, I have solved the problem.
I turned off the dark mode for Windows 10,and turn on the light mode,the electron window was successfully created.
This is probably related to this issue [electron/electron#19468](https://github.com/electron/electron/issues/19468)

**Comment by koszti** [comment]
just to confirm, switching from dark mode to light mode in windows 10 solves the problem. Funky fix, hopefully electron will provide a proper fix soon.

**Comment by LucasZNK** [comment]
Same here, solved the problem using light mode!

**Comment by amilajack** [comment]
Blocked on https://github.com/electron/electron/issues/19468
