### ISSUE TITLE
auto-updater with custom server

### ISSUE THREAD

**Issue by muscaiu** [electron-react-boilerplate/electron-react-boilerplate#2481]
Hello, i'm using this boilerplate and i'm looking for a solution for the auto-updater using a custom server like `http-server` for example.

I tried this [example ](https://gist.github.com/iffy/0ff845e8e3f59dbe7eaf2bf24443f104)and i can't make it work., basically the `http-server` is not being queried at all.

Any known tutorials or examples would be really apreciated.

Thanks in advance!

**Comment by amilajack** [comment]
Out of scope for this project
