### ISSUE TITLE
Cannot package Electron application

### ISSUE THREAD

**Issue by rafi-isakh** [electron-react-boilerplate/electron-react-boilerplate#2482]
Hi, I am new to electron and currently trying to package an Electron application. 
I have tried to package the app when I copy this repository for the first time and it is working well.
Now, I have added some changes and I want to package it. 

I run `yarn  package-win` to do that
The packaging process generate an installer successfully, but when I install the app it only shows blank page. 

Do I miss something here? Could anyone of you tell me what can I do to debug this error?

**Comment by 117sparta** [comment]
I meet the same problem after I run `yarn run package-mac` to get a `dmg`. The package works fine on my computer but fail on other computer. It is strange. I guess i need a guidance too.

**Comment by syddo** [comment]
@rafi-isakh which platform are you packaging from?

**Comment by rafi-isakh** [comment]
@syddo I'm trying to create the package from Windows platform

**Comment by amilajack** [comment]
Are you using any native dependencies?

**Comment by rafi-isakh** [comment]
@amilajack I don't think so. I only add `material-ui` and `material-table` dependencies to the boilerplate

**Comment by syddo** [comment]
> @amilajack I don't think so. I only add `material-ui` and `material-table` dependencies to the boilerplate

Okay. I’m also having packaging issues for Linux on a macOS Catalina. I only added Material-ui also.
I’ve even tried the boilerplate as is and package but only works on:
windows - for windows packaging
mac - for a dmg package.
rpm generated on mac cannot install in CentOS7.

**Comment by st-zelenin** [comment]
hello. in my case I installed `react-image-crop` inside the `app` folder.

in `development` mode and with `yarn start` everything was working fine.
within package - no.
after forcing `electron-debug` to open within the package there was `electron cannot find module 'react'` error.
moving `react-image-crop` dependency to upper `package.json` fixed the issue.

**Comment by amilajack** [comment]
@rafi-isakh What's your stacktrace? Try running this command: https://electron-react-boilerplate.js.org/docs/installation-debugging-solutions/#debugging-release-builds

**Comment by rafi-isakh** [comment]
Thanks @st-zelenin . I tried your solution and it is working
