### ISSUE TITLE
Knowing about dependencies and dev dependencies

### ISSUE THREAD

**Issue by sdc224** [electron-react-boilerplate/electron-react-boilerplate#2490]
Hi
First of all I want to thank you to all of the contributors for this repository. I am regularly following this repo for near about 4-5 months, now some questions arise in my mind.

Please tell me the requirement of adding (dev dependencies)
1. ```@types/tapable```
2. ```@types/webpack```
3. ```@types/vfile-message```
4. ```babel-core```
5. ```cross-spawn```

I searched the whole project and couldn't get any details regarding above packages.

I thought maybe the type definitions for webpack is needed to get better intellisense(VSCode) in webpack.config.js files, but for me it is not working, and hopefully it is the expected behavior.

It is not an issue, just a quick discussion(maybe convert into issue later if any). If you want me to ask this doubts somewhere else, please ping me the website😅

**Comment by jooohhn** [comment]
They might be unused. I'll check to see if that's the case

**Comment by sdc224** [comment]
There are some other as well, which can be moved from dependencies to dev. Also we can remove core-js, as polyfills are not necessary in electron, in fact we should not use polyfills in electron.

I can create a pull request if you want

**Comment by amilajack** [comment]
Why do you think poly fills aren’t necessary in electron?

**Comment by saulwiggin** [comment]
You've got me? Perhaps because is created fully in the latest ESVersion.
Babel not required.

**Comment by sdc224** [comment]
> Why do you think poly fills aren’t necessary in electron?

Electron actually ships with the latest (almost) chromium version, where no such polyfills are needed.
See [this](https://www.electronjs.org/docs/tutorial/performance#5-unnecessary-polyfills) for a better view, mentioned in electron docs.

**Comment by amilajack** [comment]
Polyfill are required for supporting esnext transpilation. We can't assume all ES APIs are polyfilled in latest electron version.
