### ISSUE TITLE
Fresh install gives errors related to chrome extensions

### ISSUE THREAD

**Issue by sebastiancarlsson** [electron-react-boilerplate/electron-react-boilerplate#2494]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Chrome extensions should install and work without errors.

## Current Behavior

Getting errors in the console when I run `yarn dev`

https://gist.github.com/sebastiancarlsson/5fb66eb1f31a4c1a705c8a03a92a4ad8

## Possible Solution

I poked around a bit in the `electron-devtools-installer` package in my `node_modules` and successfully got rid of this error (by doing what it says): `(electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.`

However the other errors remain and the redux dev tools that I need to use is still not working. It's possible that it's this package that is the source of all the errors but I currently don't have time to try to figure out how everything works.

## Steps to Reproduce (for bugs)

1. Clone the repo following the install instructions
2. Run `yarn dev`

## Context

As stated above I literally just cloned the repo so there's not a lot of context to give.

## Your Environment

- Node version : 12.18.1
- Version or Branch used : latest master
- Operating System and version : MacOS 10.14.6
- Link to your project : n/a

**Comment by sebastiancarlsson** [comment]
https://github.com/MarshallOfSound/electron-devtools-installer/pull/131

**Comment by amilajack** [comment]
Blocked on https://github.com/MarshallOfSound/electron-devtools-installer/pull/131
