### ISSUE TITLE
Module not found: Error: Can't resolve 'flag-icon-css' in  '/Users/xxxxx/workspace/electron_ts'  @ dll renderer renderer[12]

### ISSUE THREAD

**Issue by wlfcss** [electron-react-boilerplate/electron-react-boilerplate#2497]
In my project, I need to use a component about the national flag, and I follow the tutorial to install it using `lipis/flag-icon-css`, But it didn't work, I don't understand at all what I did wrong？Hope to get some tips and help，thx

## Prerequisites

- Normally initialize the electron-react-boilerplate according to the tutorial

## Expected Behavior

- error，I can't add `lipis/flag-icon-css` by yarn or npm，
- i hope it works

## Possible Solution

none

## Steps to Reproduce (for bugs)

![image](https://user-images.githubusercontent.com/12138285/85914576-b8d4f200-b871-11ea-8c01-6ece3a0c50be.png)

## Context

- I hope to use yarn to add components normally

## Your Environment

- yarn
- node 12.16.1
- electron-react-boilerplate：1.2.0
- osx

**Comment by mustafaKamal-fe** [comment]
hi 
i had the same issue with a different module (it was @types/mongoose)
i had to install it again as a devDependency since it was installed first as a Dependency 
this has fixed that issue for me.
