### ISSUE TITLE
Minimal build template

### ISSUE THREAD

**Issue by prescottbreeden** [electron-react-boilerplate/electron-react-boilerplate#2512]
This is really great work that y'all have built here.  Would love a significantly reduced version that isn't pre-opinionated about style sheets, redux, and routing -- it is surprisingly tricky to customize this repo out of the box.

**Comment by amilajack** [comment]
@prescottbreeden There's a lot of interests in dropping support for redux and this is something we'll be looking at in the near future. I was wondering what your thoughts were on why you consider styling and routing opinionated

**Comment by manutero** [comment]
Same here. The work here is astonishing.

In my case, I wanted to remove React-Redux from the equation. Got it but took me a while (and I'm not 100% sure I've left any unused dependency behind).

Now I'm considering even publishing it as a fork "electron-react-boilerplate-no-redux"  xD

**Comment by tudiantuan** [comment]
+1

**Comment by jooohhn** [comment]
General idea is accepted and is being continued in #2553
