### ISSUE TITLE
Redux DevTools not working, showing "No store found. Make sure to follow the instructions."

### ISSUE THREAD

**Issue by dabo248** [electron-react-boilerplate/electron-react-boilerplate#2517]
## Prerequisites

- [X] Using yarn
- [X] Using node 10.x
- [X] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [X] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Expected Redux DevTools to be usable out of the box.

## Current Behavior

When I select the Redux tab in the dev console, I see one sentence stating "No store found. Make sure to follow the instructions."

## Possible Solution

This issue might be related to these:

https://github.com/electron/electron/issues/23662
https://github.com/electron/electron/issues/24011

## Steps to Reproduce (for bugs)

1. Clone and install project like instructed here: https://github.com/electron-react-boilerplate/electron-react-boilerplate#install

2. Run `yarn dev`

3. Click on the Redux tab in the dev console

4. You should see a grey background with the message: "No store found. Make sure to follow the instructions."

## Context

I'm trying to track and understand my application state with Redux DevTools. 

Redux DevTools is usable with electron-react-boilerplate version 1.1.0, so I'm not quite sure if the recent switch to Redux-Toolkit or the switch to Electron version 9 broke it. 

## Your Environment

- Node version : 10.17.0 and 12.18.0
- Version or Branch used : 1.2.0 and master
- Operating System and version : macOS Catalina (10.15.5)
- Link to your project : Happens with the plain boilerplate project (https://github.com/electron-react-boilerplate/electron-react-boilerplate)

**Comment by ChALkeR** [comment]
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/app/main.dev.ts#L73 -- this is probably breaking on 9.x due to electron/electron#24011.

**Comment by pranshuchittora** [comment]
I also tried passing the `devTools: true` flag explicitly to the `configureStore` of the `@reduxjs/toolkit` unfortunately no progress. @ChALkeR you are right I think the problem is with the electron.

**Comment by nikandlv** [comment]
Same issue on a fresh generated project

**Comment by amilajack** [comment]
@nikandlv This shouldn't be happening for you on fresh clone. Latest ERB does not use electron@9

**Comment by Slapbox** [comment]
This has happened to me since forever ago and I have _never_ found a solution despite literally entire days of searching. The issue first began for me when I started using a preload script. Nothing, nothing, nothing resolves it. 

If anyone figures this out, please share!

**Comment by misakisaysyes** [comment]
In macos, I run 'npm start' in the terminal of Vscode, the Redux DevTool fail to start. While I run 'npm start' in local terminal, the Redux DevTool works well...So werid

**Comment by rendomnet** [comment]
@dabo248 did you resolved this issue? I have same problem

**Comment by dabo248** [comment]
Nope, sorry, I hadn't a look at this since a couple of months.

**Comment by DoWhileGeek** [comment]
Also stuck on this

**Comment by leohxj** [comment]
electron@112.3 doesn't support yet.

**Comment by Slapbox** [comment]
I don't think that's true @leohxj. We're using the devtools in our app which uses that version of Electron.

**Comment by ChALkeR** [comment]
@Slapbox perhaps your setup doesn't load html pages over `file://` protocol?

Either way, electron@11.3.0 contains a fix for this issue, but the loading code should be modified to include the `allowFileAccess: true` option.

**Comment by leohxj** [comment]
> I don't think that's true @leohxj. We're using the devtools in our app which uses that version of Electron.

which protocol you use? I am using `file://` to load my index.html...

**Comment by Slapbox** [comment]
@ChALkeR you are correct. It doesn't appear to load for us in `PROD` where we load over a registered `app://` protocol.

**Comment by radicalloop** [comment]
@ChALkeR 

Could you please suggest how can we enable `allowFileAccess: true` option to `true` ?
