### ISSUE TITLE
Error trying to create new BrowserWindow

### ISSUE THREAD

**Issue by AndreoliBR** [electron-react-boilerplate/electron-react-boilerplate#2520]
## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)

## Expected Behavior

I'm trying to open a new BrowserWindow from component when the app fully loads. The component that tries to load the BrowserWindow is aimed to be like Discord Splash (when you open the app and it waits until the app is updated and fully loaded).

## Current Behavior

The splash component is loading normally and then I call the `useEffect` hook to create and load the new window. But when the hook is called and the new BrowserWindow is called, the window turns blank and the following log shows up on cmd: `[13760:0714/113839.895:ERROR:CONSOLE(216)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js (216)`. I have already changed Routes.tsx and routes.json to add the new window component, and the dir I used in the func `newWindow.loadURL()` is `file://${__dirname}/app.html/setup`, as described in routes.json, `"SETUPASSISTANT": "/setup"`

## Possible Solution

This issue might be related to [this issue](https://github.com/electron/electron/issues/24011)

## Your Environment

- Node version : 12.18.0
- Version or Branch used : 1.2.0
- Operating System and version : Windows 10 1909
- Link to your project : https://github.com/AndreoliBR/projekt-emerald

**Comment by amilajack** [comment]
Were you able to resolve this issue?

**Comment by AndreoliBR** [comment]
Yes. I've managed to resolve my issue. It was just a simple problem with Redux.

**Comment by alexpereira** [comment]
Can you share how you resolve this issue, exactly? lol

**Comment by ajbtechservices** [comment]
I don't use redux, and I have this problem doing a CMD+R in the browser after navigating to a different route....

**Comment by ivanms1** [comment]
Also getting the same error whenever I change something in the frontend and save.

**Comment by ivanms1** [comment]
Also getting the same error whenever I change something in the frontend and save. Any help would be greatly appreciated.

**Comment by ivanms1** [comment]
This piece of code in my `App.js` was causing the issue
```jsx
<Route render={() => <Redirect to="/" />} />
```

**Comment by rafael-buzzni** [comment]
> I don't use redux, and I have this problem doing a CMD+R after navigating to a different route....

did you solve the problem?

**Comment by AndreoliBR** [comment]
> Can you share how you resolve this issue, exactly? lol

I was trying to uncouple Redux from project but I did it in wrong way, so it gave me this error.

My solution was creating a new project and don't uncouple it.

**Comment by ivanms1** [comment]
Using `HashRouter` instead of `BrowserRouter` solved it for me.
