### ISSUE TITLE
Loader: Load SVG images

### ISSUE THREAD

**Issue by pranshuchittora** [electron-react-boilerplate/electron-react-boilerplate#2522]
How to load SVG images in React components?

**Comment by nikita-skobov** [comment]
Not sure if this is the "right" way, but what I did is:

```
import repeatSvg from './repeat.svg';

<img src={repeatSvg} />
```

**Comment by amilajack** [comment]
@nikita-skobov that's the right way to do this

**Comment by SylarRuby** [comment]
Could we import svgs like the [create react app method](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs)? It would nice to use:

```jsx
import { ReactComponent as Logo } from './logo.svg';

function App() {
  return (
    <div>
      {/* Logo is an actual React component */}
      <Logo fill="red" />
    </div>
  );
}
```

**Comment by SylarRuby** [comment]
Sorry to create nose... but I've solved it. Create React App Used SVGR:

1: yarn add @svgr/webpack

2: Inside your webpack config (.erb/configs/webpack.config.base.js)

```js
[..]
{
    test: /\.svg$/,
    use: ['@svgr/webpack'],
},
[..]
```

Then you can now:

```js
import { ReactComponent as Logo } from './logo.svg';
```
