### ISSUE TITLE
(electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.

### ISSUE THREAD

**Issue by songyuc** [electron-react-boilerplate/electron-react-boilerplate#2524]
When I run "yarn dev", there is a message which says,
> (electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.

I think this might be due to the usage of `BrowserWindow.addDevToolsExtension`.
Maybe we should use `session.loadExtension`.

## Prerequisites

- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Link to stacktrace in a Gist (for bugs)
- [x] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

**Note for using latest version of devtools:**
The command for updating extensions version cannot work on Windows PowerShell, which need to be confirmed.

**Note for link to stacktrace in a Gist (for bugs):**
I am sorry for that, as a beginner, I don't know how to do that.

## Expected Behavior

Maybe we should use `session.loadExtension`instead of `BrowserWindow.addDevToolsExtension`.

## Current Behavior

There is a warning which says,
> (electron) 'BrowserWindow.addDevToolsExtension' is deprecated and will be removed. Please use 'session.loadExtension' instead.

## Steps to Reproduce (for bugs)

1. Run `yarn dev`;

2. The message shows as,
![图片](https://user-images.githubusercontent.com/27288110/87755924-85670100-c83a-11ea-907f-b65738675cc7.png)

## Context

I think we may need to use the updated method of Electron.

## Your Environment

- Node version : v12.18.2
- Version or Branch used : 1.2.0
- Operating System and version : Windows 10 
- Link to your project :

**Comment by amilajack** [comment]
See https://stackoverflow.com/questions/61894248/electron-js-devtoolsinstaller-browserwindow-adddevtoolsextension-is-depreca

Blocked on https://github.com/MarshallOfSound/electron-devtools-installer/issues/132
