### ISSUE TITLE
Discussion: Minimize the example's (counter) footprint.

### ISSUE THREAD

**Issue by pranshuchittora** [electron-react-boilerplate/electron-react-boilerplate#2530]
**Description**
Minimizing the surface area of the counter-example provided by default with the boilerplate.

**Motivation**
While working with the boilerplate for the first time I spent a lot of time removing the counter-example from the codebase.

It included:-
- Removing the react components, container.
- Modifying the routing.
- Remove the handling reducer.
- Rewire the new routes.
- Fix the global css.
- ...

I understand that providing an example is necessary in order to showcase the overall potential of the setup to the user. But it might not be that easy to remove the entire example code for someone who is new to the ecosystem.

**Proposed Solution**
1. Adding a guide in the `Getting Started` describing the cleaning procedure.
2. Setting up a special command which deletes all the example code and then deletes itself.

**Comment by jooohhn** [comment]
General idea is accepted and is being continued in #2553
