### ISSUE TITLE
Error with Node.js native module

### ISSUE THREAD

**Issue by jiladahe1997** [electron-react-boilerplate/electron-react-boilerplate#2532]
- [x] Using yarn
- [x] Using node 10.x
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

I am using a native module called [serialport](https://serialport.io/) and follow its guidelines to write the following code:
```
const SerialPort = require('serialport')
SerialPort.list().then(list=>console.log(list))
```
And it should works.

## Current Behavior
The code cause an exception.

![image](https://user-images.githubusercontent.com/22068145/88452909-2d14ac80-ce95-11ea-9781-5df33bf86a43.png)

## Possible Solution
I have debugged in source code , and found that the problem maybe is here (see pictures below):

The key code is as follows ，` Error.prepareStackTrace` is native API , the API get different results in _**electron-react-boilerplate**_.

```
  Error.prepareStackTrace = function(e, st) {
    for (var i = 0, l = st.length; i < l; i++) {
      fileName = st[i].getFileName();
      if (fileName !== __filename) {
        if (calling_file) {
          if (fileName !== calling_file) {
            return;
          }
        } else {
          return;
        }
      }
    }
  };
```

I thought it maybe a problem with webpack config:
```
/* in electron-react-boilerplate*/
  output: {
    publicPath: `http://localhost:${port}/dist/`,
    filename: 'renderer.dev.js',
  },

/* in other boilerplate*/
  output: {
    filename: '[name].js',
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '../dist/electron')
  },
```

</br>
↓↓↓↓pictures↓↓↓↓

#### **In another [Vue](https://vuejs.org/) project which could works:**
<img src="https://user-images.githubusercontent.com/22068145/88452960-8250be00-ce95-11ea-8a1e-c11f05626bd8.png" width="800px" />

#### **In electron-react-boilerplate which causes an exception:**
<img src="https://user-images.githubusercontent.com/22068145/88452986-b5934d00-ce95-11ea-8d93-6f27f84b0024.png" width="800px" />

## Steps to Reproduce (for bugs)

1.clone electron-react-boilerplate

2.add serialport using yarn

3.rebuild by `electron-rebuild` as descriped here: https://serialport.io/docs/guide-installation

## Your Environment

- Node version :    v12.16.2
- Version or Branch used : master  
- Operating System and version : Windows 10
- Link to your project :

**Comment by amilajack** [comment]
See https://github.com/amilajack/erb-serialport-example

**Comment by jiladahe1997** [comment]
> See https://github.com/amilajack/erb-serialport-example

Thanks. I solved it by change the `externals` fields in webpack config:
```
/* in configs\webpack.config.base.js */
/* change this */
  externals: [...Object.keys(externals || {})],

/* to this */
  externals: [...Object.keys(externals || {}), 'serialport','bindings'],

```
