### ISSUE TITLE
Styles are applied asynchronously when opening a new window

### ISSUE THREAD

**Issue by yan-arch** [electron-react-boilerplate/electron-react-boilerplate#2545]
## Summary

I am using electron react boilerplate for a destkop application.
In the first screen of the window, I have displayed a logo at the center of the window with adjusted width and height using CSS.

## Problem
When I run the application in production mode, the logo appeared at its original size for less than 1 second. After that, the styles are applied to let the corner get smaller and go to the center of the window.

In development mode, it doesn't happen. I think it's because the preload script is loaded asynchronously...

Please help me to fix this daunting issue.

**Comment by yan-arch** [comment]
@wincent @afrojas @typesend @dustintownsend

**Comment by amilajack** [comment]
Duplicate of https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2560
