### ISSUE TITLE
Wine Mono is not installed

### ISSUE THREAD

**Issue by denissabramovs** [electron-react-boilerplate/electron-react-boilerplate#2548]
Missing required dependency for compilation of executables.
Using latest version.
using Ubuntu
`errorOut=0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed`

**Comment by denissabramovs** [comment]
this is after launching `yarn package-all`
after launching `yarn package`, everything went fine

**Comment by denissabramovs** [comment]
it seems it can't build executable for Windows

**Comment by amilajack** [comment]
You need to install wine when building for windows from ubuntu:
https://www.electron.build/multi-platform-build#to-build-app-for-windows-on-linux
