### ISSUE TITLE
Can this project be integrated into a monorepo?

### ISSUE THREAD

**Issue by rntjr** [electron-react-boilerplate/electron-react-boilerplate#2549]
I wonder if the 1.3.0 release can integrate with a monorepo. If not and there is no example from another contributor, I would like to do so and make it available.

I will insert the PR #2546 together to also be able to generate, in addition to the executable, a version for web deployment.

**Comment by amilajack** [comment]
Yes, this is possible. See https://github.com/falcon-client/falcon
