### ISSUE TITLE
Incorrect installation "yarn install"

### ISSUE THREAD

**Issue by trae-op** [electron-react-boilerplate/electron-react-boilerplate#2551]
## Prerequisites

- [+] Using yarn
- [+] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [+] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [+] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [+] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

correct build at the initial stage

## Steps to Reproduce
running commands:
1. git clone --depth=1 \
  https://github.com/electron-react-boilerplate/electron-react-boilerplate \
  your-project-name

2. cd your-project-name

3. yarn

4. yarn dev

## Context

After running command from 3 of item "yarn"
screenshots: 
1. part-1: https://prnt.sc/tyg80x
2. part-2: https://prnt.sc/tyg95l

## Your Environment

- Node version : v12.16.3
- Operating System and version : macos mojave v10.14.6

**Comment by jooohhn** [comment]
Not sure what the bug is, could you clarify the current behavior on your machine?

**Comment by trae-op** [comment]
> Not sure what the bug is, could you clarify the current behavior on your machine?

I just run "yarn install" and see screens (https://prnt.sc/u1fy0k, https://prnt.sc/u1fyt3).
I have not installed new libs. 
Used the default libs from https://github.com/electron-react-boilerplate/electron-react-boilerplate

**Comment by duxiaoran** [comment]
me too

**Comment by mustafaKamal-fe** [comment]
hi
i had some issues with my dependencies and did this: 
1- `npm i package-lock-only`
2-`npm audit fix`
3- then removed `yarn.lock` file
4- finally `yarn import` 

this has fixed many problems for me. however, i still have this like you guys do: 
`warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".`
`warning " > eslint-config-erb@1.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".`
