### ISSUE TITLE
Extract non-universal features from boilerplate to docs

### ISSUE THREAD

**Issue by jooohhn** [electron-react-boilerplate/electron-react-boilerplate#2553]
Motivation: Boilerplate may be too opinionated and difficult for users to customize

Solution:
- Simplify boilerplate by providing only universal features (e.g. React, ESLint)
- Create docs for adding non-universal features

Accepted features to move (ongoing and **open to community discussion**):
- [ ] Redux (#2512, #2233, #2530)
- [ ] Supporting web build scripts (#2136, #2546)

**Comment by crubier** [comment]
Very good, idea, The redux part bothered me in 2018 already when I used this boilerplate. 2 years later I start another app and I am surprised to still this here (and that no other boilerplate emerged). Would you take a PR?

**Comment by jooohhn** [comment]
Yes any help would be great

**Comment by amilajack** [comment]
@crubier I hear you and I agree. Checkout https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2598
