### ISSUE TITLE
bin-wrapper module missing in production build

### ISSUE THREAD

**Issue by devlab02** [electron-react-boilerplate/electron-react-boilerplate#2555]
## Summary

Everything is working fine when running `yarn dev` and `yarn start`.
but when `yarn package-win` and running the packaged app its not working.

its says bin-wrapper module missing.

These are the packages i am using in `./app/package.json`
    "imagemin": "^7.0.1",
    "imagemin-jpegtran": "^7.0.0",
    "imagemin-mozjpeg": "8.0.0",
    "imagemin-pngquant": "8.0.0",

Any idea?

**Comment by amilajack** [comment]
Try `cd app && yarn add bin-wrapper`

**Comment by amilajack** [comment]
Can you please share the full stacktrace
