### ISSUE TITLE
` no such file or directory` shows when use `React.lazy`

### ISSUE THREAD

**Issue by Holybasil** [electron-react-boilerplate/electron-react-boilerplate#2557]
I have never modified the following default config.

webpack.config.renderer.dev.babel.js
```js
output: {
    publicPath: `http://localhost:${port}/dist/`,
    filename: 'renderer.dev.js'
  },
```
webpack.config.renderer.prod.babel.js
```js
output: {
    path: path.join(__dirname, '..', 'app/dist'),
    publicPath: './dist/',
    filename: 'renderer.prod.js'
  },
```

Everything works well, until I use `React.lazy`

App.js
```js
const LazyMyHome = React.lazy(() => import('./Home'));
const MyHome = props => (
  <Suspense fallback={<span>Loading...</span>}>
    <LazyCreateProfile {...props} />
  </Suspense>
);

...
 <Route path="/" key="home" component={MyHome} />
...
```
`npm run dev` is ok while `npm run start` shows error in console.It looks like `publicPath` didn't work.
![image.png](https://i.loli.net/2020/08/19/qbgdf23aPNuKw6Z.png)

In fact, **...../auto-perf-tool/app/dist/0.renderer.prod.js** is the correct path.

Has anyone encountered the same problem？🥺

**Comment by amilajack** [comment]
I'm not able to reproduce this. Also can you please create another issue that follows the template

**Comment by amilajack** [comment]
Are you getting this issue with a fresh clone? Also please use `yarn` to guarantee that you're getting the same dependencies

**Comment by Holybasil** [comment]
I used to change `preload: path.join(__dirname, 'dist/renderer.prod.js')` to `nodeIntegration: true` in **production** which caused the error.
![image.png](https://i.loli.net/2020/08/21/h8LERHoZsjcm1eM.png)
And I still don't understand why `nodeIntegration: true` in **production** causes my mistake.**css** file could be loaded in the correct path while **js** lost `dist` that is really strange.

**Comment by Unforgiven-wanda** [comment]
@Holybasil Hello
I'm having this exact same issue. Although reverting back to `preload: path.join(__dirname, 'dist/renderer.prod.js'),` does not seem to fix it in production.
Could I possibly trouble you to share a working example of how you do it? Or a simple explanation?
Anything will do.
Thank you.

**Comment by Holybasil** [comment]
@Unforgiven-wanda  Actually, I am using `React.lazy` with `preload: path.join(__dirname, 'dist/renderer.prod.js')`. In this problem, it looks like the subpath `dist` is lost, maybe you can find something in webpack, and according to  `<script defer src="${script}"><\script>`(when `nodeIntegration: true` ) , only files in the same directory as app.html can be requested.Apparently, it is unwise to put bundle files to `app` directory.
The above are all my thoughts on this issue, and I don’t have time to continue researching, I hope it can help you.

**Comment by VitaliSakalouConeTec** [comment]
Hello, I have the same issue. Did anybody find a solution how to fix it? Thanks
