### ISSUE TITLE
Asynchronous load

### ISSUE THREAD

**Issue by flashguru-git** [electron-react-boilerplate/electron-react-boilerplate#2560]
Currently, the `nodeIntegrations` is set to false in production environment.
But I believe the preload script let the styles to be loaded after displaying the window.

I thought we can solve this issue by enabling nodeIntegrations to true.
But I am not sure. It's just from my experience.
Would you please help me on this?

**Comment by amilajack** [comment]
`nodeIntegration` is only true if using env variable `ERB_SECURE` in version 1.3.0 of the boilerplate. `nodeIntegration` used to be the default in 1.2.0 but that default was reverted.

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/app/main.dev.ts#L66

**Comment by flashguru-git** [comment]
That's right. But why the style is applied asynchronously?
I have placed a logo in splash screen. But the logo appears with its original size at first for 0.1 secs.
The style is applied later.
How can I resolve this?

**Comment by flashguru-git** [comment]
I had this question from my friend.
Please check this issue.
https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2545

**Comment by amilajack** [comment]
There were a lot of issues with the preload option so this is no longer the default. This is no longer an issue in the latest release. I recommend upgrading to that.

**Comment by amilajack** [comment]
Preload was dropped in v2.0
