### ISSUE TITLE
How many minutes the application take to initialize?

### ISSUE THREAD

**Issue by felipefariasdasilva** [electron-react-boilerplate/electron-react-boilerplate#2561]
Hello guys!

I make the boilerplate clone and followed the procedures in README. But, the boilerplate takes 5-10 min to open.

Is it normal? Thanks

**Comment by suiyuex** [comment]
start in about 30 seconds

**Comment by amilajack** [comment]
It takes me 5 seconds. There might be something wrong with your system. This doesn't sound like a problem with the boilerplate
