### ISSUE TITLE
Not working after getting .msi from electron-builder

### ISSUE THREAD

**Issue by bcburak** [electron-react-boilerplate/electron-react-boilerplate#2562]
## Prerequisites

- [ x] Using yarn
- [ x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior
I used electron-tabs and dragula in my existed project which is based on electron-react-boilerplate.In my case; if I used electron-tabs in debug mode, its all okey. But after I'm getting buildir with electron-builder and set up project in computer, getting an error "module was not found" at this line -> **const TabGroup = require("electron");**

Created an staticFiles in app folder. StaticFiles has dragula.css and electron-tabs.css( **also can not seen this css files from node_modules in production mode**),tabhelper.js and tabModal.html.

## Current Behavior

After build, when I click my button it just open new blank window. But I was in debug mode its all looks fine.

Not rendering and working electron-tabs component
## Steps to Reproduce

My file orders like that

![image](https://user-images.githubusercontent.com/6598220/90903872-397a1f80-e3d7-11ea-8255-7876b69b0010.png)

**Main.dev.js**
```
app.on('ready', async () => {
  if (process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true') {
    await installExtensions();
  }

  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728
  });

  mainWindow.loadURL(`file://${__dirname}/app.html`);

  // @TODO: Use 'ready-to-show' event
  //        https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event
  mainWindow.webContents.on('did-finish-load', () => {
    if (!mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    mainWindow.show();
    mainWindow.focus();
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();
});

```
**tabHelper.js**

```
const { ipcRenderer } = require("electron");
const dragula = require("dragula");
const TabGroup = require("electron-tabs");

// Create a group of draggable tabs when the tabbed window first initializes
const tabGroup = new TabGroup({

  ready: tabGroup => {
    dragula([tabGroup.tabContainer], {
      direction: "horizontal"
    });
  }
});

// When the last tab is removed from the group, dispatch an event that closes this window to the main process
tabGroup.on("tab-removed", (tab, tabGroup) => {
  if (tabGroup.getTabs().length < 1) {
    ipcRenderer.send("close-tabs-window");
  }
});

// When the open tab event is dispatched, create a new tab with the provided parameters
ipcRenderer.on("open-tab", (event, params) => {
  // alert("open-tab");
  debugger;
  tabGroup.addTab({
    // Params are passed from the main process
    ...params,

    // The new tab will be visible
    visible: true,

    // Make the new tab active
    active: true
  });
});
```

## Possible Solution (Not obligatory)

Before all of them, I can't reach my static html file (tabhelper.html) from main.dev.js in production mode. I don't know the reason, maybe webpac can not compile it. So if I reach html file using LoadURL, it would be good step.

## Context

Trying to do tab pages in my sub window

Just my other project codes

## Your Environment

- Node version : 12.8.3
- electron-react-boilerplate version or branch : 3.0.10
- Operating System and version : Win 10
- Link to your project :

**Comment by bcburak** [comment]
can anyone help ?

**Comment by bcburak** [comment]
in electron builder files node changed with tabModal.html and it has done.
```
"files": [
    "app/dist/",
    "app/app.html",
    "app/tabModal.html",
    "app/main.prod.js",
    "app/main.prod.js.map",
    "package.json",
    "staticFiles/tabHelper.js"
  ],
```

**Comment by Unforgiven-wanda** [comment]
Could you please share an example repo for this? (Or stackblitz or codesandbox)
I am trying to integrate electron-tabs in my project as well
