### ISSUE TITLE
"ws" (WebSocket) module in electron does not work properly

### ISSUE THREAD

**Issue by shunmian** [electron-react-boilerplate/electron-react-boilerplate#2563]
## Prerequisites

- [x] Using yarn
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

The aws appsync subscription via [ws](https://github.com/websockets/ws) module should receive subscription event in electron.

## Current Behavior

The aws appsync subscription via [ws](https://github.com/websockets/ws) module DOES NOT receive subscription event in electron.

 
## Steps to Reproduce

The appSync code is from [here](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-node.html):

```
global.WebSocket = require('ws');
require('es6-promise').polyfill();
require('isomorphic-fetch');

// Require exports file with endpoint and auth info
const aws_exports = require('./aws-exports').default;

// Require AppSync module
const AUTH_TYPE = require('aws-appsync/lib/link/auth-link').AUTH_TYPE;
const AWSAppSyncClient = require('aws-appsync').default;

const url = aws_exports.ENDPOINT;
const region = aws_exports.REGION;
const type = AUTH_TYPE.AWS_IAM;

// If you want to use API key-based auth
const apiKey = 'xxxxxxxxx';
// If you want to use a jwtToken from Amazon Cognito identity:
const jwtToken = 'xxxxxxxx';

// If you want to use AWS...
const AWS = require('aws-sdk');
AWS.config.update({
    region: aws_exports.REGION,
    credentials: new AWS.Credentials({
        accessKeyId: aws_exports.AWS_ACCESS_KEY_ID,
        secretAccessKey: aws_exports.AWS_SECRET_ACCESS_KEY
    })
});
const credentials = AWS.config.credentials;

// Import gql helper and craft a GraphQL query
const gql = require('graphql-tag');
const query = gql(`
query AllPosts {
allPost {
    __typename
    id
    title
    content
    author
    version
}
}`);

// Set up a subscription query
const subquery = gql(`
subscription NewPostSub {
newPost {
    __typename
    id
    title
    author
    version
}
}`);

// Set up Apollo client
const client = new AWSAppSyncClient({
    url: url,
    region: region,
    auth: {
        type: type,
        credentials: credentials,
    }
    //disableOffline: true      //Uncomment for AWS Lambda
});

client.hydrated().then(function (client) {
    //Now run a query
    client.query({ query: query })
    //client.query({ query: query, fetchPolicy: 'network-only' })   //Uncomment for AWS Lambda
        .then(function logData(data) {
            console.log('results of query: ', data);
        })
        .catch(console.error);

    //Now subscribe to results
    const observable = client.subscribe({ query: subquery });

    const realtimeResults = function realtimeResults(data) {
        console.log('realtime data: ', data);
    };

    observable.subscribe({
        next: realtimeResults,
        complete: console.log,
        error: console.log,
    });
});

module.exports = {
  client,
}
```

When invoke the above code with `node pathToAboveCode`, the subscription works correctly.
But when use the above code inside the electron-react-boilerplate project, and start by `yarn dev`(the client is imported to react component), the subscription is not receiving any event.

## Possible Solution (Not obligatory)

The issue may come from the line `global.WebSocket = require('ws');`, which works for nodejs. In electron, is it appropriate to set global.WebSocket in render process?

## Your Environment

- Node version : v13.12.0
- electron-react-boilerplate version or branch :
- Operating System and version : macOS Mojave 10.14.5

**Comment by zwhs-co** [comment]
Please close it as finally it turns out has nothing to do with electron.
