### ISSUE TITLE
How do you use SASS in this template?

### ISSUE THREAD

**Issue by thomdlee** [electron-react-boilerplate/electron-react-boilerplate#2565]
## Importing .scss files doesn't work

In previous projects I have been able to simply import SCSS files directly into classes with the appropriate webpack configuration. This project's [documentation](https://electron-react-boilerplate.js.org/docs/styling/#further-readings) for migrating to SASS shows two projects that have since been deleted and no further instructions.

From the webpack config below I can see that all SCSS code is pulled int oa single style sheet, but when I run `yarn dev` my scss classes are not pulled in.

```
      // SASS support - compile all .global.scss files and pipe it to style.css
      {
        test: /\.global\.(scss|sass)$/,
        use: [
          {
            loader: 'style-loader',
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
            },
          },
          {
            loader: 'sass-loader',
          },
        ],
      },
```

**Comment by mitch3ls** [comment]
Hello @thomdlee,

I came here because I also have problems with SASS and this template, but I can solve part of your problem.

The projects that are referred to on the website you referenced still exist, the links are just broken due to poor parsing. 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/19824704/92223181-6121bb00-eea0-11ea-8317-9ccffe0a6fbb.png">
You can see that the grayish link extends into the square brackets. When you click the link it appends those greyish parts of the square brackets to the link in the address bar.

To successfully open those links you either have to properly select the link manually and then copy and paste or click the link and then edit the address bar.

I hope that helped at least a little bit!

**Comment by thomdlee** [comment]
> Hello @thomdlee,
> 
> I came here because I also have problems with SASS and this template, but I can solve part of your problem.
> 
> The projects that are referred to on the website you referenced still exist, the links are just broken due to poor parsing.
> <img alt="image" width="624" src="https://user-images.githubusercontent.com/19824704/92223181-6121bb00-eea0-11ea-8317-9ccffe0a6fbb.png">
> You can see that the grayish link extends into the square brackets. When you click the link it appends those greyish parts of the square brackets to the link in the address bar.
> 
> To successfully open those links you either have to properly select the link manually and then copy and paste or click the link and then edit the address bar.
> 
> I hope that helped at least a little bit!

Thanks @mitch3ls for pointing this out. Happy to close the ticket now that I can just investigate these two projects.

**Comment by SoldierAb** [comment]
> Hello @thomdlee,
> 
> I came here because I also have problems with SASS and this template, but I can solve part of your problem.
> 
> The projects that are referred to on the website you referenced still exist, the links are just broken due to poor parsing.
> <img alt="image" width="624" src="https://user-images.githubusercontent.com/19824704/92223181-6121bb00-eea0-11ea-8317-9ccffe0a6fbb.png">
> You can see that the grayish link extends into the square brackets. When you click the link it appends those greyish parts of the square brackets to the link in the address bar.
> 
> To successfully open those links you either have to properly select the link manually and then copy and paste or click the link and then edit the address bar.
> 
> I hope that helped at least a little bit!

pages not found

**Comment by amilajack** [comment]
Thanks for pointing this out. The links are now fixed:
https://electron-react-boilerplate.js.org/docs/styling
