### ISSUE TITLE
How to open multiple instances with different data?

### ISSUE THREAD

**Issue by sradu** [electron-react-boilerplate/electron-react-boilerplate#2566]
I'm implementing a simple chat app and looking to test out the websocket flows. What's the best way to have two dev builds open at the same time with different credentials?

**Comment by dbvrac** [comment]
The simple answers that come to my simple mind: Use two different machines/VM's, <b>OR</b> set each build to broadcast/listen on different TCP/IP ports. I'm using a multi-window variant of ERB 18.1, but the newest ERB shouldn't be significantly different.
 In Build-A:
 /configs/webpack.config.renderer.dev.babel.js:
 `const port = process.env.PORT || 1212;`
/internals/scripts/CheckPortInUse.js
`const port: string = process.env.PORT || '1212';`
/app.html
`const port = process.env.PORT || 1212;`

...and in Build-B, same files, change the port to some other unused port number.

**Comment by sradu** [comment]
I'll try it out tomorrow!

**Comment by sradu** [comment]
Perhaps I could run

```
PORT=1213 yarn dev
# and
PORT=1214 yarn dev
```

**Comment by dbvrac** [comment]
I was a bit uncertain when you mentioned "using different credentials". My thought was that it should just work, by using different credentials, provided you didn't have a port conflict while running both dev builds in the same TCP/IP environment. I also assumed you were using some kind of external authentication/database site like Firebase.
I'm curious to see what you come up with.

**Comment by sradu** [comment]
I tested it and seems to be working, even with different credentials. Really appreciate your help!

**Comment by dbvrac** [comment]
Good to hear, I'm glad I could help.

My skills have improved significantly thanks to the ERB community. Please consider making a donation through [OpenCollective](https://opencollective.com/electron-react-boilerplate#backer) if you have not already.
