### ISSUE TITLE
How to get a React web server/build?

### ISSUE THREAD

**Issue by jagzmz** [electron-react-boilerplate/electron-react-boilerplate#2575]
## Summary

I want to have both builds web app + electron. As most of the code is react based is it possible to have a react server running and some config which would build the project as a React Web Application?

**Comment by jagzmz** [comment]
When I try to open ```http://localhost:1212/``` or  ```http://localhost:1212/dist``` inside browser. It displays ```Cannot get /```

**Comment by dbvrac** [comment]
Yes, it's been done in the past with previous versions of ERB, but I don't believe that code falls within the scope of the project. It's been mentioned before, and though I've used it in the past I haven't kept up with it. Try looking here:[#2546]( https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2546)
