### ISSUE TITLE
crxToZip Error: Invalid header: Does not start with Cr24

### ISSUE THREAD

**Issue by mustafaKamal-fe** [electron-react-boilerplate/electron-react-boilerplate#2577]
## Prerequisites

- [1 ] Using yarn
- [1 ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [1 ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ 1] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [1 ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

App runs with zero warnings/Errors while in development mode
## Current Behavior

App runs with this error:
`Error: Invalid header: Does not start with Cr24
    at crxToZip (W:\devp\electron\stark\node_modules\unzip-crx\dist\index.js:32:15)
    at W:\devp\electron\stark\node_modules\unzip-crx\dist\index.js:57:32
    at callHanler (W:\devp\electron\stark\node_modules\yaku\lib\yaku.js:719:16)
    at tryCatcher (W:\devp\electron\stark\node_modules\yaku\lib\yaku.js:436:32)
    at W:\devp\electron\stark\node_modules\yaku\lib\yaku.js:575:38
    at flush (W:\devp\electron\stark\node_modules\yaku\lib\yaku.js:478:17)
    at processTicksAndRejections (internal/process/task_queues.js:76:11)
`

## Context

This error has not affected the app in any way so far. However, i have not made any changes to ERB code base.

## Your Environment

- Node version : v12.16.1
- electron-react-boilerplate version or branch : 1.3.0
- Operating System and version : Windows 10 release 10.0.18362

**Comment by andrewschreiber** [comment]
This bug is seemingly related to electron-devtools-installer. My React dev tools are not appearing.

**Comment by amilajack** [comment]
See https://github.com/MarshallOfSound/electron-devtools-installer/issues/141 and  https://github.com/MarshallOfSound/electron-devtools-installer/pull/140. Seems like the issue was fixed.

**Comment by MatthewEppelsheimer** [comment]
@amilajack Hey I just ran into this myself. The same fix worked, but I'm wondering is there's any reason not to just bump the `electron-devtools-installer` version to `^3.1.1` in this repo's package.json. It seems that a handful of folks are running into this, and updating the dependency would save others having to track this down. I'm happy to send a PR for this if you'd like.

**Comment by ulou** [comment]
Bumping up `electron-devtools-installer` to `^3.1.1` solved the problem.

**Comment by aaronlet** [comment]
@ulou Where is the installation dependency on `electron-devtools-installer`?

**Comment by jin-pin-mei-le** [comment]
> 颠簸起来`electron-devtools-installer`，以`^3.1.1`解决这个问题。

thank u

**Comment by vanminhquangtri** [comment]
Hello everybody, I still get this error after upgrade electron-devtools-installer to ^3.1.1
**Vue Devtools failed to install: Error: Invalid header: Does not start with Cr24**

I am using:  "vue": "^3.2.13", "electron": "^25.2.0", node: 16.20.0

Here is my file package.json:

```
{
  "name": "fptplay-desktop-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "@mdi/font": "5.9.55",
    "axios": "^1.4.0",
    "core-js": "^3.8.3",
    "roboto-fontface": "*",
    "vue": "^3.2.13",
    "vue-router": "^4.2.2",
    "vuetify": "^3.0.0-beta.0",
    "vuex": "^4.1.0",
    "webfontloader": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "electron": "^25.2.0",
    "electron-devtools-installer": "^3.1.1",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "vue-cli-plugin-electron-builder": "~2.1.1",
    "vue-cli-plugin-vuetify": "~2.5.8",
    "webpack-plugin-vuetify": "^2.0.0-alpha.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "@babel/eslint-parser"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead",
    "not ie 11"
  ]
}
```

Can you please give an advice.

**Comment by kenny-reyes** [comment]
Hi @vanminhquangtri 

Yep, It is caused by the constant, the ID that contains was deprecated.

I mean, when you write

```ts
import installExtension, { REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer'
installExtension(REACT_DEVELOPER_TOOLS, { forceDownload: true })
```

REACT_DEVELOPER_TOOLS contains the ID of the extension in the Chrome store. If that ID changed, the library will try to download the extensions and the chrome store will return (I don't know) maybe an error page, the library will check if the downloaded binary is a Chrome extension, which all start for CR24, so it throws an exception.

Solution: 
Take the actual ID in the details of the extension, for this you need to have it installed in chrome:
![imagen](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/11137579/e28a8e2e-1127-4143-b94e-620f7fb58232)

And paste the ID directly in the line for installing the extension.

```ts
  installExtension('nhdogjmejiglipccpnnnanhbledajbpd')
```

This library is very heavy of maintaining, because you always have to update the constants.

**Comment by sidonaldson** [comment]
Or just run `npm update electron-devtools-installer
`
