### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by Addy0119** [electron-react-boilerplate/electron-react-boilerplate#2578]
## Prerequisites

- [ ] Using yarn
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Current Behavior
I am going to build the project into production.
Then I have got such as this.

![Screen Shot 2020-09-05 at 11 21 18 AM (2)](https://user-images.githubusercontent.com/58567154/92297025-6436ad00-ef6d-11ea-80eb-096ea09fec3e.png)
I didn't make the changing in the webpack and babel.

![Screen Shot 2020-09-05 at 11 22 15 AM](https://user-images.githubusercontent.com/58567154/92297039-96480f00-ef6d-11ea-9075-9bb4954268e1.png)

And current project is working well in dev. Only giving me error in the prod.

For example code:
import React from 'react';
import styled from 'styled-components';
import {
  Content,
  Div1,
  Inputbox,
  Button1,
  Subtitle,
  Label,
  Fill,
  Header,
  HeaderTitle,
  Container,
} from './common';
import XdOpenerLogs from './common/XdOpenerLogs';

const XdOpener = () => {
  return (
    <Content>
      <Fill>
        <Header>
          <HeaderTitle>xd Opener</HeaderTitle>
        </Header>
        <XdopenerContainer>
          <ProfileSection>
            <Subtitle />
            <Section>
              <Label>Discord Token</Label>
              <InputDiscordToken />
              <Label>Joiner Token</Label>
              <Div1>
                <InputJoinerToken />
                <AutoLabel>
                  <input type="checkbox" />
                  Auto Join Invites
                </AutoLabel>
              </Div1>
              <Label>Keywords</Label>
              <InputKeyword />
              <Label>Channel IDs</Label>
              <InputChannelId />
              <Label>Number of Browsers</Label>
              <InputBrowserNumber />
              <SaveSection>
                <OpenerSave>Save</OpenerSave>
              </SaveSection>
            </Section>
          </ProfileSection>
          <XdOpenerLogs height={450} />
        </XdopenerContainer>
      </Fill>
    </Content>
  );
};

const XdopenerContainer = styled(Container)`
  justify-content: between;
`;

const ProfileSection = styled(Div1)`
  border-right: 1.1px solid rgb(133, 129, 138);
`;

const Section = styled(Div1)`
  display: flex;
  flex-direction: column;
  width: 90%;
`;

const AutoLabel = styled(Label)`
  font-size: 12px;
  margin-left: 20px;
`;

const InputBrowserNumber = styled(Inputbox)`
  width: 20%;
  margin-bottom: 20px;
`;

const InputChannelId = styled(Inputbox)`
  width: 60%;
  margin-bottom: 20px;
`;

const InputKeyword = styled(Inputbox)`
  width: 60%;
  margin-bottom: 20px;
`;

const InputJoinerToken = styled(Inputbox)`
  width: 60%;
  margin-bottom: 20px;
`;

const InputDiscordToken = styled(Inputbox)`
  width: 60%;
  margin-bottom: 20px;
`;

const OpenerSave = styled(Button1)`
  font-size: 16px;
  padding: 5px 30px;
`;

const SaveSection = styled(Div1)`
  display: flex;
  flex-direction: row;
  justify-content: center;
`;

export default XdOpener;

What did I do wrong

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by amilajack** [comment]
Can you please clarify the ask here. I don't have enough context to help.

**Comment by wenxiayili** [comment]
> Can you please clarify the ask here. I don't have enough context to help.
hi, @amilajack ,could you help me look at this issue? #2594
