### ISSUE TITLE
[Help] 'yarn dev' not working as expected

### ISSUE THREAD

**Issue by toilahung** [electron-react-boilerplate/electron-react-boilerplate#2579]
## Summary

First I'm new to electron and so grateful this repo exists. Thank you, contributors.

**I followed the instruction and ran:**
`git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name`
`cd your-project-name`
`yarn`
**then I ran:**
`
yarn dev
`
**But nothing appears. My terminal snapshot is below**
<img width="1260" alt="Screen Shot 2020-09-05 at 1 46 45 PM" src="https://user-images.githubusercontent.com/23233483/92299674-b0d6b400-ef7e-11ea-9f1b-ece5cb551680.png">

**Comment by amilajack** [comment]
I'm not able to reproduce this
