### ISSUE TITLE
CSP Guide

### ISSUE THREAD

**Issue by h0tw4t3r** [electron-react-boilerplate/electron-react-boilerplate#2580]
Hi. First of all, huge thanks for the boilerplate, it really bootstraped my development.
But now I'd like to make the app secure by adding CSP nonces generated by webpack.
I played a lot with CspHtmlWebpackPlugin and HtmlWebpackPlugin and I faced lots of issues:

1. renderer.dev script doesn't generate HTML file no matter how hard I try. I tried HTMLHardDiskPlugin, doesn't work.
2. renderer.prod works, but nonce isn't put the right way, it's inserting partially.

renderer.dev.babel.js:
https://github.com/h0tw4t3r/parrot-software-center/blob/2d466cc01d18e9f86cbc1f57e49de682ba4f0fab/configs/webpack.config.renderer.dev.babel.js#L1-L308

renderer.prod.babel.js:
https://github.com/h0tw4t3r/parrot-software-center/blob/2d466cc01d18e9f86cbc1f57e49de682ba4f0fab/configs/webpack.config.renderer.prod.babel.js#L1-L255

**Comment by amilajack** [comment]
I'm not sure how to address this. I recommend folllwing up with the CspHtmlWebpackPlugin maintainers. Closing this but please feel free to follow up if you have any more questions.
