### ISSUE TITLE
Cannot import scss/sass

### ISSUE THREAD

**Issue by marcel-fernandes** [electron-react-boilerplate/electron-react-boilerplate#2581]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

While importing [*.scss/*.sass] files, the application (yarn dev) should build with no errors.

## Current Behavior

When I import [*.scss/*.sass] files (ex changing Home.css to Home.scss), the application (yarn dev) gives me this error:

```
ERROR in ./app/components/Home.scss
Module build failed (from ./node_modules/typings-for-css-modules-loader/lib/index.js):
Error: Cannot find module 'css-loader/locals'
```

## Steps to Reproduce

1. Change the file `./app/components/Home.css` to `./app/components/Home.scss` (or .sass)

2. Change the file `./app/components/Home.tsx` to reflect the change mentioned above.

3. Run `yarn dev`

## Possible Solution (Not obligatory)

Probably **Webpack** is not properly configured to process scss/sass, even though it has rules to deal with those file extensions.

## Context

I'm trying to use scss/sass files, as it is common in React, and this error is happening.

## Your Environment

- Node version : v12.18.1
- electron-react-boilerplate version or branch : master
- Operating System and version : Windows 10

**Comment by marcel-fernandes** [comment]
People, sorry for the duplicate.

Found the answer at [#2523](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2523).

The solution given at [#2540](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2540/commits/088bd8f3cbba1da4989d9a37f75007593fbecdf1) does solves this issue.

I've noticed though that running `yarn dev` with the solution above creates the following type artifact:
Home.scss.d.ts
```
declare namespace HomeScssNamespace {
  export interface IHomeScss {
    container: string;
  }
}

declare const HomeScssModule: HomeScssNamespace.IHomeScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HomeScssNamespace.IHomeScss;
};

export = HomeScssModule;
```

The same behavior is noted working with `*.module.scss`.

I'm not a TypeScript expert, but shouldn't be better if this type instruction was implemented globally in some way, as we have in the `css.d.ts` file (already in the project)?

Otherwise we will have many `*.scss.d.ts` created in the project, one for each `*.scss` file implemented. I can't remember this behavior happening while working with React/web. But I can be talking something stupid, as I said I'm not a TypeScript expert and there may be a reason for this artifact being created.

**Comment by marcel-fernandes** [comment]
Update...

If I run `yarn run package-win` with the solution mentioned above [#2540](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2540/commits/088bd8f3cbba1da4989d9a37f75007593fbecdf1) changing the `app.global.css` to `app.global.scss`,  the font-awesome plugin is not loaded correctly, and the icons in the .exe are not displayed.

Any thoughts about that?

**Comment by amilajack** [comment]
This might have been fixed in the most recent version of ERB, released yesterday. Please check if those changes work for you

**Comment by songyuc** [comment]
I have tested it today, and this problem has been resolved.

**Comment by amilajack** [comment]
@songyuc what version of ERB are you on?

**Comment by songyuc** [comment]
Hi, @amilajack , I am not sure how to check the version of ERB I am using.
So how can I check the version of the ERB?
Besides, I just see this code in `FUNDING.yml`, as
![image](https://user-images.githubusercontent.com/27288110/97389503-671ea000-1915-11eb-8614-a04829c15b14.png)

**Comment by amilajack** [comment]
@songyuc What's the latest commit from ERB that you have?

**Comment by songyuc** [comment]
@amilajack , I am using the latest ERB.

**Comment by megancooper** [comment]
@songyuc Is this still an ongoing problem? I have the latest version of ERB (`v2.1.0`) and am still encountering an issue where I can't import `*.scss` files from a `*.tsx` file. 
<img width="1153" alt="Screen Shot 2021-03-01 at 12 55 11 AM" src="https://user-images.githubusercontent.com/8683055/109462325-ec7fa180-7a28-11eb-9f47-0210f156ed83.png">

**Comment by songyuc** [comment]
Hi, @amilajack , I am wondering whether the current version of ERB support global style `.scss` file?
