### ISSUE TITLE
How to set environment variables in production

### ISSUE THREAD

**Issue by shunmian** [electron-react-boilerplate/electron-react-boilerplate#2584]
## Summary

Hi, I'm new to electron and have googled and searched issues(for example [issue 851 in electron-react-boilerplate
](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/851), [issue 2427 in webpack](https://github.com/webpack/webpack/issues/2427)) for how to set environment variables in production but none of them works. 

Specifically, when package with `yarn package-mac` (in mac) or `yarn pacakge-linux` (in linux), `console.log(process.env.SOME_KEY)` is undefined.

My webpack.config.base.js has plugin as below, which has tried both `DefinePlugin` and `EnvironmentPlugin`.

```
 plugins: [
    new webpack.DefinePlugin({
      'process.env.SOME_KEY': JSON.stringify('SOME_VALUE'),
    }),
    new webpack.EnvironmentPlugin({
      SOME_KEY: 'SOME_VALUE',
    }),
    new webpack.NamedModulesPlugin()
  ]
```

**Comment by amilajack** [comment]
[Check how we're passing prod env variables](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/configs/webpack.config.renderer.prod.babel.js#L210-L214)/
