### ISSUE TITLE
misconfiguration detected, using production version in non-production environment

### ISSUE THREAD

**Issue by Topppy** [electron-react-boilerplate/electron-react-boilerplate#2585]
## Prerequisites

- [x] Using yarn
- [ ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Steps to Reproduce

1.

2.

3.

4.

## Possible Solution (Not obligatory)

this [issue](https://github.com/gaearon/react-hot-loader/issues/1333#issuecomment-533422757) works for me.

## Your Environment

- Node version : v12.18.3
- electron-react-boilerplate version or branch : 
- Operating System and version : MacOs
- Link to your project :

**Comment by bravikumarreddy** [comment]
added
entry: ['react-hot-loader/patch', **'webpack-hot-middleware/client'**, './src']

Please refer https://gaearon.github.io/react-hot-loader/getstarted/

**Comment by amilajack** [comment]
This has been fixed in the most recent version
