### ISSUE TITLE
ffi-napi: An object was expected

### ISSUE THREAD

**Issue by andrew-oreshko** [electron-react-boilerplate/electron-react-boilerplate#2588]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

ffi-napi should work fine within packaged app

## Current Behavior

I added ref-napi (https://github.com/node-ffi-napi/ref-napi) (v. 2.1.2) as a native dependency. It works ok when running the app locally (even prod build), but as soon as I try to run a packaged and installed version of the app (both Windows and MacOS), the error from screenshot get raised
![image](https://user-images.githubusercontent.com/56826270/93071577-f84cf680-f688-11ea-979d-451df25230af.png)

Actually this line fails
![image](https://user-images.githubusercontent.com/56826270/93071737-2d594900-f689-11ea-9a9b-968a16db800b.png)

Invocation of the `require('node-gyp-build')(path.join(__dirname, '..'))` gives me the error listed above.

## Steps to Reproduce

1. Install ref-napi as a native dependency in the app directory

2. Import and use ref-napi somewhere in renderer, e.g., any React component

3. Run `yarn cross-env DEBUG_PROD=true yarn package`

4. Install app

5. Once the app launched, you can observe error in dev console

## Context

Why: I'm using this package in conjunction with ffi-napi (https://github.com/node-ffi-napi/node-ffi-napi) to get access to the system's libraries via FFI approach (C language)
The main change: only added dotenv and utilized it in webpack configs

## Your Environment

- Node version : v12.18.2
- electron-react-boilerplate version or branch : master
- Operating System and version : MacOS Catalina 10.15.4

**Comment by andrew-oreshko** [comment]
There is some more info in addition to above.
This screenshot represents `node-gyp-build/index.js` file
When running a packaged app, `load` function fails, but when running locally as yarn dev it is working just fine. I also checked the file it tries to load (`/Applications/{appname}/Contents/Resources/app.asar/node_modules/ref-napi/build/Release/binding.node`) and it exists in the packaged app node_modules, but not getting imported in a packaged app by `load` for some reason

![image](https://user-images.githubusercontent.com/56826270/93202997-53035280-f75c-11ea-96af-f22f9a628b59.png)

**Comment by amilajack** [comment]
Add the module to the `app/package.json`, not `package.json`

**Comment by MD-AZMAL** [comment]
I have added the module in app/package.json still getting the same error

```
electron/js2c/asar.js:140 Uncaught Error: An object was expected
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:816)
    at Module._load (internal/modules/cjs/loader.js:728)
    at Function.Module._load (electron/js2c/asar.js:748)
    at Module.require (internal/modules/cjs/loader.js:853)
    at require (internal/modules/cjs/helpers.js:74)
    at load (/home/loopaz/Project…p-build/index.js:21)
    at Object.<anonymous> (/home/loopaz/Project…f-napi/lib/ref.js:8)
```

**Comment by andrew-oreshko** [comment]
@MD-AZMAL try using these versions:

 "ffi-napi": "^2.0.3",
"ref-napi": "^1.5.2"

**Comment by cohenshay** [comment]
i also struggle with that issue. the failure occurs when running  the postinstall script inside /app (thats running any time you install a dep).
the script is:  "electron-rebuild": "node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js"

when i run yarn for the first time its ok, then the second crash, then the third is ok and forth crash and so on

**Comment by cohenshay** [comment]
changing the electron-rebuild script to work with --sequential instead of --parallel,  solved the issue for me

**Comment by MD-AZMAL** [comment]
> @MD-AZMAL try using these versions:
> 
> "ffi-napi": "^2.0.3",
> "ref-napi": "^1.5.2"

tried this faced the same issue
