### ISSUE TITLE
What is process.env.PLAIN_HMR

### ISSUE THREAD

**Issue by curtk** [electron-react-boilerplate/electron-react-boilerplate#2589]
Hi all,

Simple question [I think].

Been really trying to absorb and internalize how this boilerplate is constructed and how it works. Cannot seem to find out what **_process.env.PLAIN_HMR_** is, and how it gets defined.

Obviously this environment variable is related to react hot loader. It looks to me like it is a boolean to see whether or not we want to use react hot loader (i.e. in dev/production)?

I'm asking here because I cannot find any documentation about it, and google searches bring me back to this project leading me to believe that it is something unique to this boilerplate, and not react hot loader.

Thank you,
Curtis

**Comment by amilajack** [comment]
I agree that its confusing. See https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2153 for context.

https://github.com/electron-react-boilerplate/site/issues/131 tracks documenting this.
