### ISSUE TITLE
How to remove "v0.1.0 by @mathias" it on app/main.prod.js.LICENSE.txt

### ISSUE THREAD

**Issue by rrfaria** [electron-react-boilerplate/electron-react-boilerplate#2590]
I removed this file to build my package 
but it always generate this file with:
"/*! http://mths.be/fromcodepoint v0.1.0 by @mathias */"

I want to remove this reference

**Comment by githubBrandon** [comment]
Would also like to know how to remove this.

**Comment by tapjay** [comment]
It looks like the TerserPlugin is including it inside `.erb/configs/webpack.config.main.prod.babel.js`. I added `extractComments: false` which removed it:

```
optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        extractComments: false,
      }),
    ],
  },
```

https://webpack.js.org/plugins/terser-webpack-plugin/#extractcomments
