### ISSUE TITLE
VSCode Debugging Non-deterministic

### ISSUE THREAD

**Issue by parksj10** [electron-react-boilerplate/electron-react-boilerplate#2591]
#2405  Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Debug breakpoints in VSCode should bind deterministically and halt execution once reached

## Current Behavior

Breakpoints are not followed deterministically, see end of post for example gifs

## Steps to Reproduce

1. clone repo [Electron React Boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate)

2. Execute debug run via Electron: All task

3. Quit debug and cancel webpack terminal process at various stages of debug (e.g. stepping through breakpoints/completed)

## Context

This issues makes it very challenging and frustrating to debug electron apps, as I can't reproducibly debug the content I need to. Furthermore, with Hot reload, cross-env, dev-tools, webpack, babel, and typescript, the layers of abstraction make it very difficult to understand/debug the entire stack

I have tried adding the following to the launch.json to increase stability, with no effect

```
      "cwd": "${workspaceFolder}",
      "outFiles": ["${workspaceFolder}/**/*.js"],
      "protocol": "inspector",
      "smartStep": true,
      "sourceMaps": true,
```

## Environment

- Node version : 14.11.0
- VSCode version: 1.49.1
- electron-react-boilerplate version or branch : 1.3.0
- Operating System and version : Darwin 10.15.5

### As expected, stops on first breakpoint
![2020-09-20 12-42-41 - debug 2020-09-20 12_47_20](https://user-images.githubusercontent.com/28692761/93722154-8de4fc00-fb49-11ea-890f-04078d8228e3.gif)
### Skips first breakpoint
![2020-09-20 12-50-03 - debugger 2 2020-09-20 12_52_09](https://user-images.githubusercontent.com/28692761/93722156-92111980-fb49-11ea-9b32-ce7d1d6051ee.gif)
```
Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
lib/renderer/security-warnings.ts:181
Main._createAppUI: 30.2177734375ms
devtools/bundled/shell.js:171
Main._showAppUI: 12.722900390625ms
devtools/bundled/shell.js:171
Main._initializeTarget: 7.86181640625ms
devtools/bundled/shell.js:171
Main._lateInitialization: 0.887939453125ms
devtools/bundled/shell.js:171
[HMR] Waiting for update signal from WDS...
[HMR] Waiting for update signal from WDS...
Promise
```
### Hangs at browser_init
![2020-09-20 13-40-44 debug 4 2020-09-20 13_42_52](https://user-images.githubusercontent.com/28692761/93722159-93424680-fb49-11ea-828d-4da92669a622.gif)
### Minified JS popup
![2020-09-20 13-46-49 - debug 5 2020-09-20 13_49_10](https://user-images.githubusercontent.com/28692761/93722161-93424680-fb49-11ea-9be2-4789223c144c.gif)

**Comment by bertyhell** [comment]
I'm having similar issues where breakpoints in the devtools for the react code (tsx files) do not seem to be hit, or break on different lines that where i put the breakpoints.

This is probably because of some issues with the generation of the sourcemaps somewhere in the build pipeline (typescript/babel compilation)

**Comment by parksj10** [comment]
FYI, killing all processes and breakpoints, then re-enabling seems to give a temporary solution where breakpoints are hit (in different fashions... see above)
