### ISSUE TITLE
Styled-components css not loading in prod mode.

### ISSUE THREAD

**Issue by awaisayub149** [electron-react-boilerplate/electron-react-boilerplate#2592]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`
there is no error at all, just every dive or component is not loading its css, or dev its working fine but on prod its not working.

## Expected Behavior

should load all the css in prod build as its loading in dev env

## Current Behavior

not loading any css at all in prod, 

## Steps to Reproduce

just use one styled-component with css in tsx file, it will not load the css. using styled-component 5.2.0

## Your Environment

- Node version : 10.15.0
- electron-react-boilerplate version or branch : updated master branch
- Operating System and version : MacOS and windows
- Link to your project : not available

**Comment by maciejtoporowicz** [comment]
Same setup, same issue in my case.

**Comment by awaisayub149** [comment]
I just fix my issue by downgrading styled-component version to 5.1.3.

**Comment by maciejtoporowicz** [comment]
Sorry, but I believe downgrading the lib is just a workaround - you may wish to upgrade it in the future and face the same issue again.

I found that when I change the `target` in `webpack.config.renderer.prod.babel.js` from `electron-preload` to `electron-renderer`, styled-components are working fine. However, I have no idea what the consequences are. I looked at https://webpack.js.org/configuration/target/ - seems that there's a difference between them using `JsonpTemplatePlugin` and `NodeTemplatePlugin with asyncChunkLoading set to true` underneath, but I still have no clue what it means. Anyway, I'll keep digging.

**Comment by ScripterSugar** [comment]
@maciejtoporowicz

I'm facing same issue here. Was there anything you found further about the issue?

**Comment by amilajack** [comment]
We reverted using electron preloading as the default for importing the renderer but it seems like the webpack config wasn't updated. I'll submit a fix soon.

**Comment by maciejtoporowicz** [comment]
@ScripterSugar Sorry, I haven't found anything else. At the same time I had to make some other adjustments regarding security of the app and had to disable `nodeIntegration` + enable `contextIsolation` - such config was only working fine for me when I changed the `target` to `web` and styled-components are working fine with this `target `as well.   

@amilajack So is using `electron-renderer` the correct solution to this issue?

**Comment by amilajack** [comment]
Yea that's correct

**Comment by ScripterSugar** [comment]
I can confirm using electron-renderer fixed the issue for me too. Thanks!

**Comment by codingedgar** [comment]
I'm having the same issue, with the latest main version, It works ok on dev, but css/scss is not loading at all for prod, I went from v1.1.0 to v2.3.0 (or master actually) copying the diff from: https://github.com/electron-react-boilerplate/electron-react-boilerplate/compare/v1.1.0..v2.3.0.

**Comment by codingedgar** [comment]
> I'm having the same issue, with the latest main version, It works ok on dev, but css/scss is not loading at all for prod, I went from v1.1.0 to v2.3.0 (or master actually) copying the diff from: https://github.com/electron-react-boilerplate/electron-react-boilerplate/compare/v1.1.0..v2.3.0.

if I change `webpack.config.renderer.prod.babel.js`

```diff
module: {
    rules: [
      {
        test: /.s?css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              // `./dist` can't be inerhited for publicPath for styles. Otherwise generated paths will be ./dist/dist
              publicPath: './',
+             esModule: false,
            },
          },
-         'css-loader',
+         {
+           loader: 'css-loader',
+           options: {
+             modules: {
+               localIdentName: '[name]__[local]__[hash:base64:5]',
+             },
+             sourceMap: true,
+             importLoaders: 1,
+           },
+         },
          'sass-loader'
        ],
      },
```
But honestly
![image](https://user-images.githubusercontent.com/10213241/120819265-63916e00-c521-11eb-99e7-e316ea0fcaf5.png)

**Comment by richard-livingston** [comment]
This is still an issue an issue in version 3.0.2 (latest), please can you reopen it @awaisayub149. Following @codingedgar's advice fixes css modules in production but breaks global css, the following code will enable both...

**webpack.config.renderer.prod.babel.js**: *module.rules*
```js
{
	// CSS/SCSS
	test: /\.global\.s?css$/,
	use: [
	  {
		loader: MiniCssExtractPlugin.loader,
		options: {
		  // `./dist` can't be inerhited for publicPath for styles. Otherwise generated paths will be ./dist/dist
		  publicPath: './',
		  esModule: false
		},
	  },
	  {
		loader: 'css-loader',
		options: {
			sourceMap: process.env.DEBUG_PROD === 'true'
		},
	  },
	  'sass-loader',
	],
},
{
	// CSS/SCSS
	test: /^((?!\.global).)*\.s?css$/,
	use: [
	  {
		loader: MiniCssExtractPlugin.loader,
		options: {
		  // `./dist` can't be inerhited for publicPath for styles. Otherwise generated paths will be ./dist/dist
		  publicPath: './',
		  esModule: false
		},
	  },
	  {
		loader: 'css-loader',
		options: {
			modules: {
				localIdentName: '[name]__[local]__[hash:base64:5]',
			},
			sourceMap: process.env.DEBUG_PROD === 'true',
			importLoaders: 1,
		},
	  },
	  'sass-loader',
	],
}
```
