### ISSUE TITLE
Packaging error:Get "https://github.com/electron/electron/releases/download/v10.1.2/electron-v10.1.2-darwin-x64.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address

### ISSUE THREAD

**Issue by wenxiayili** [electron-react-boilerplate/electron-react-boilerplate#2594]
Today, I used "yarn package" to package, but got the following error:
```
  • electron-builder  version=22.8.1 os=19.6.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=10.1.2 appOutDir=release/mac
  **⨯ Get "https://github.com/electron/electron/releases/download/v10.1.2/electron-v10.1.2-darwin-x64.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address**
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
	/usr/local/Cellar/go/1.14.5/libexec/src/runtime/asm_amd64.s:1373
  ⨯ /Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
```
Environment：
   system: macos 10.15.6
   Node: v14.9.0
   electron: 10.1.2
   yarn: 1.22.5

**Comment by FalekPRO** [comment]
I have the same problem

**Comment by zhukunpenglinyutong** [comment]
me too bug

**Comment by wenxiayili** [comment]
> I have the same problem

Do you have any suggestions to solve this bug?

**Comment by wenxiayili** [comment]
> me too bug

Do you have any suggestions to solve this bug?

**Comment by zhukunpenglinyutong** [comment]
> > me too bug
> 
> Do you have any suggestions to solve this bug?

l'm sory，no

**Comment by amilajack** [comment]
ERB currently does not support electron@10 at the moment. I recommend downgrading to electron 8 and seeing if that works.

**Comment by wenxiayili** [comment]
> ERB currently does not support electron@10 at the moment. I recommend downgrading to electron 8 and seeing if that works.

Wait a minute i try, thanks again。🙏

**Comment by wenxiayili** [comment]
> ERB currently does not support electron@10 at the moment. I recommend downgrading to electron 8 and seeing if that works.

I am using version 8.5, but I still get the same error.
• electron-builder  version=22.8.1 os=19.6.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.5.0 appOutDir=release/mac
  ⨯ **Get "https://github.com/electron/electron/releases/download/v8.5.0/electron-v8.5.0-darwin-x64.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address**
github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
github.com/develar/app-builder/pkg/download.(*Downloader).follow
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
github.com/develar/app-builder/pkg/download.(*Downloader).Download
	/Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
	/Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
	/Volumes/data/Documents/app-builder/pkg/util/async.go:68
runtime.goexit
	/usr/local/Cellar/go/1.14.5/libexec/src/runtime/asm_amd64.s:1373
  ⨯ /Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                                          Error: /Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                                              at ChildProcess.<anonymous> (/Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/builder-util/src/util.ts:243:14)
                                                                                                                                                                              at Object.onceWrapper (events.js:421:26)
                                                                                                                                                                              at ChildProcess.emit (events.js:314:20)
                                                                                                                                                                              at maybeClose (internal/child_process.js:1047:16)
                                                                                                                                                                              at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by FalekPRO** [comment]
There is still a bug in version 8

**Comment by wenxiayili** [comment]
> There is still a bug in version 8

me too...

**Comment by wenxiayili** [comment]
> > ERB currently does not support electron@10 at the moment. I recommend downgrading to electron 8 and seeing if that works.
> 
> I am using version 8.5, but I still get the same error.
> • electron-builder version=22.8.1 os=19.6.0
> • loaded configuration file=package.json ("build" field)
> • writing effective config file=release/builder-effective-config.yaml
> • packaging platform=darwin arch=x64 electron=8.5.0 appOutDir=release/mac
> ⨯ **Get "https://github.com/electron/electron/releases/download/v8.5.0/electron-v8.5.0-darwin-x64.zip": proxyconnect tcp: dial tcp :0: connect: can't assign requested address**
> github.com/develar/app-builder/pkg/download.(*Downloader).follow.func1
> /Volumes/data/Documents/app-builder/pkg/download/downloader.go:206
> github.com/develar/app-builder/pkg/download.(*Downloader).follow
> /Volumes/data/Documents/app-builder/pkg/download/downloader.go:234
> github.com/develar/app-builder/pkg/download.(*Downloader).DownloadNoRetry
> /Volumes/data/Documents/app-builder/pkg/download/downloader.go:128
> github.com/develar/app-builder/pkg/download.(*Downloader).Download
> /Volumes/data/Documents/app-builder/pkg/download/downloader.go:112
> github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).doDownload
> /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:192
> github.com/develar/app-builder/pkg/electron.(*ElectronDownloader).Download
> /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:177
> github.com/develar/app-builder/pkg/electron.downloadElectron.func1.1
> /Volumes/data/Documents/app-builder/pkg/electron/electronDownloader.go:73
> github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
> /Volumes/data/Documents/app-builder/pkg/util/async.go:68
> runtime.goexit
> /usr/local/Cellar/go/1.14.5/libexec/src/runtime/asm_amd64.s:1373
> ⨯ /Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE stackTrace=
> Error: /Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/app-builder-bin/mac/app-builder exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
> at ChildProcess. (/Users/liyunhua/study/electron/electron-stencil/electron-stencil/node_modules/builder-util/src/util.ts:243:14)
> at Object.onceWrapper (events.js:421:26)
> at ChildProcess.emit (events.js:314:20)
> at maybeClose (internal/child_process.js:1047:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

@amilajack There is still a bug in version 8

**Comment by wenxiayili** [comment]
@amilajack The same code can be packaged in win7, do mac packaging need other conditions?

**Comment by wenxiayili** [comment]
> > > me too bug
> > 
> > 
> > Do you have any suggestions to solve this bug?
> 
> l'm sory，no

The same code can be packaged in win7, do mac packaging need other conditions?

**Comment by wenxiayili** [comment]
@amilajack @FalekPRO @zhukunpenglinyutong 
I just resolved this issue. This is my local npm proxy setting error, not an EPR issue. thank you for your help.
Solution: delete npm proxy
   npm config delete proxy
   npm config delete https-proxy
