### ISSUE TITLE
Drop redux integration

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#2598]
Why?
1. Its a commonly requested feature, suggesting that it adds a lot of complexity that users don't need/want
2. Redux now has context and its own reducer
3. We can add redux support by adding docs for the integration

**Comment by madnesspie** [comment]
Good enhancement! 👍 

4. There are peoples who do not use Redux, but prefer MobX or other state manager.

**Comment by Noxware** [comment]
Very necessary enhancement.

I don't use redux and I'm removing it from the initial code at this moment. It is normally not used by beginners and removing it is a pain for them. People that want to use another library (like Recoil) don't need it. Advanced people who want to use redux should install it following steps from the docs.
