### ISSUE TITLE
Annotated document problem

### ISSUE THREAD

**Issue by bei-yang** [electron-react-boilerplate/electron-react-boilerplate#2604]
Hello, I just contacted Electron for a while, do you have a detailed introduction document of this project?
I want to learn more details. Thank you

**Comment by amilajack** [comment]
Checkout our docs here:

https://electron-react-boilerplate.js.org/

**Comment by bei-yang** [comment]
> Checkout our docs here:
> 
> https://electron-react-boilerplate.js.org/

Thank you very much
