### ISSUE TITLE
How do I set up custom eslint rules?

### ISSUE THREAD

**Issue by tbogard** [electron-react-boilerplate/electron-react-boilerplate#2605]
## Summary

It seems that I am unable to write my own set of rules without being annoyed by prettier. Is there a work around it? Very appreciated.

**Comment by bertyhell** [comment]
just to verify, have you tried adding your rules to the rules section of the `.eslintrc.js` file in the project root?

**Comment by tbogard** [comment]
I do, however prettier ruins my experience coding in vscode. If I set autolinter based on the .eslintrc.js it get overridden by prettier rules, which is exasperating. 😫

my current .eslintrc inside `./config/` and the rules inside of 

```
{
  "parser": "babel-eslint",
  "plugins": [
    "react"
  ],
  "ecmaFeatures": {
    "jsx": true,
    "modules": true
  },
  "env": {
    "node": true,
    "mocha": true,
    "es6": true,
    "browser": true
  },
  "globals": {},
  "rules": {
    "quotes": [
      2,
      "single"
    ],
    "curly": [
      2,
      "multi-line"
    ],
    "no-underscore-dangle": 0,
    "react/display-name": 0,
    "react/jsx-boolean-value": 1,
    "react/jsx-quotes": 1,
    "react/jsx-no-undef": 1,
    "react/jsx-sort-props": 1,
    "react/jsx-sort-prop-types": 1,
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "react/no-did-mount-set-state": 1,
    "react/no-did-update-set-state": 1,
    "react/no-multi-comp": 1,
    "react/no-unknown-property": 1,
    "react/prop-types": 1,
    "react/react-in-jsx-scope": 1,
    "react/self-closing-comp": 1,
    "react/sort-comp": 0,
    "react/wrap-multilines": 1,
    "import/prefer-default-export": "off",
    "import/no-extraneous-dependencies": [
      "error",
      {
        "peerDependencies": true
      }
    ],
    "indent": [
      "error",
      2,
      {
        "SwitchCase": 1
      }
    ],
    "object-curly-spacing": [
      "error",
      "always"
    ],
    "react/prefer-stateless-function": [
      0,
      {
        "ignorePureComponents": true
      }
    ],
    "semi": [
      "error",
      "never"
    ]
  }
}
```

what I get:
1. remove the semi at the end (eslint)
![image](https://user-images.githubusercontent.com/1978642/95788260-326de000-0ca9-11eb-82ed-6a7fd93fe1c2.png)

2. same file, added semi at the end (prettier)
![image](https://user-images.githubusercontent.com/1978642/95788333-55988f80-0ca9-11eb-9bd4-5b08e0bf6fc8.png)

Literally it is driving me nuts.

**Comment by bertyhell** [comment]
Yeah, getting prettier and eslint to stop fighting can be a pain.
Prettier can also have a config file and there is a rule for trailing semicolons: https://prettier.io/docs/en/options.html#semicolons

**Comment by tbogard** [comment]
Ok, that said, How can I remove Prettier from the project? Literally is a total chaos trying to reconciliate the configurations, and I rather want to use eslint over Prettier. Any way to stop Prettier to lint my code?

Thanks.

**Comment by bertyhell** [comment]
search for prettier in the code and delete the relevant lines?

**Comment by Noxware** [comment]
Prettier forces me to do things I don't want to do. After wasting some time customizing it, I got mad and removed it, which apparently solves the problem:

```
yarn remove prettier
yarn remove eslint-config-prettier
yarn remove eslint-plugin-prettier
```

Now you can code in peace.

**Comment by amilajack** [comment]
This is less of a question about the boilerplate so i'm going to close this. i recommend filing this in the eslint plugin prettier repo.

**Comment by TylerJNewman** [comment]
I cannot seem to update the lint rules either... is there no way to put your own lint rules?  I tried .eslintrc.js and nothing...

**Comment by hugoperier** [comment]
I have also tried to update some rules and it dont seems to be applied

In .erb/config/.eslintrc I add the rule "no-console": off but its not applied, I still have the warning `Unexpected console statement.eslintno-console`

Do someone have an idea ?

**Comment by TylerJNewman** [comment]
> I have also tried to update some rules and it dont seems to be applied
> 
> In .erb/config/.eslintrc I add the rule "no-console": off but its not applied, I still have the warning `Unexpected console statement.eslintno-console`
> 
> Do someone have an idea ?

I would also like to know the answer to this
