### ISSUE TITLE
Uncaught Error: Cannot find module 'serialport' after packaging electron app

### ISSUE THREAD

**Issue by torota** [electron-react-boilerplate/electron-react-boilerplate#2619]
![image](https://user-images.githubusercontent.com/18691085/96085724-2e85cc00-0efc-11eb-8833-dd321451ec5c.png)

When running 'yarn start' and 'yarn dev', Works well.
But after build (yarn package) I get this error.
Help me.

**Comment by torota** [comment]
i solved T_T

**Comment by JuanFLZ** [comment]
How?

**Comment by nhayhoc** [comment]
same here
