### ISSUE TITLE
Is there a how to use section somewhere that I'm not aware of in the docs/readme?

### ISSUE THREAD

**Issue by nidhaloff** [electron-react-boilerplate/electron-react-boilerplate#2622]
## Summary

I know react, but I wanted to try it with electron for the first time now. As always I searched for a boilerplate template since using create-react-app was not recommended (at least that's what I saw on the net). I found this **cool package** and followed the installation guides etc.. 

However, I was totally overwhelmed and confused when I opened my project. There are many files that I didn't know what and why they are there and whether should I delete/clean up my workspace or what. I searched in the website and in the repo here of a **get started** or **how to use** section but I didn't find anything. So how should I use this?

I'm not a react expert either. I'm just familiar with the syntax and with create-react-app, where I would just open the src folder in my project and start writing components. So my question is how are you guys using this? or better, how are you adapting this template to your use case/project?

**Comment by amilajack** [comment]
<img width="791" alt="Screen Shot 2020-10-17 at 8 44 38 AM" src="https://user-images.githubusercontent.com/6374832/96347200-fe9e0c00-1054-11eb-92a5-5ea3a077db3c.png">
<img width="295" alt="Screen Shot 2020-10-17 at 8 44 48 AM" src="https://user-images.githubusercontent.com/6374832/96347205-0493ed00-1055-11eb-97a5-aa4a5c80c0f1.png">

Here are the docs
https://electron-react-boilerplate.js.org/docs/installation

**Comment by nidhaloff** [comment]
@amilajack Hi, thanks for the response but I think you didn't read my summary. I read the docs and installed this etc.. but what I meant with get started is a section about how should I use this package. Like how do I adapt this to my preferences. I would rather have a blank or hello world example than this counter example with many folders that I didn't understand and redux integration etc..

**Comment by amilajack** [comment]
Thanks for clarifying the question. There's a task that tracks dropping redux: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2598. Feel free to PR.
