### ISSUE TITLE
Release Problem 

### ISSUE THREAD

**Issue by rafaldev** [electron-react-boilerplate/electron-react-boilerplate#2629]
Hi,
I use command : npm run dist 
**but I get error. Full log. What should I do to release correct.** 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle electron-react-typescript@0.0.7~predist: electron-react-typescript@0.0.7
6 info lifecycle electron-react-typescript@0.0.7~dist: electron-react-typescript@0.0.7
7 verbose lifecycle electron-react-typescript@0.0.7~dist: unsafe-perm in lifecycle true
8 verbose lifecycle electron-react-typescript@0.0.7~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\plrajaw\reactElectProject\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\Users\plrajaw\AppData\Local\Microsoft\WindowsApps;C:\Users\plrajaw\.dotnet\tools;C:\Users\plrajaw\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\plrajaw\AppData\Roaming\npm
9 verbose lifecycle electron-react-typescript@0.0.7~dist: CWD: C:\Users\plrajaw\reactElectProject
10 silly lifecycle electron-react-typescript@0.0.7~dist: Args: [ '/d /s /c', 'npm run build && electron-builder' ]
11 silly lifecycle electron-react-typescript@0.0.7~dist: Returned: code: 1  signal: null
12 info lifecycle electron-react-typescript@0.0.7~dist: Failed to exec dist script
13 verbose stack Error: electron-react-typescript@0.0.7 dist: `npm run build && electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid electron-react-typescript@0.0.7
15 verbose cwd C:\Users\plrajaw\reactElectProject
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error electron-react-typescript@0.0.7 dist: `npm run build && electron-builder`
22 error Exit status 1
23 error Failed at the electron-react-typescript@0.0.7 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**I have also problem with npm install**

  • electron-builder  version=22.3.2
  • loaded configuration  file=package.json ("build" field)
npm WARN electron-react-typescript@0.0.7 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1822 packages from 865 contributors and audited 1892 packages in 47.776s

45 packages are looking for funding
  run `npm fund` for details

found 3992 vulnerabilities (3910 low, 16 moderate, 66 high)
  run `npm audit fix` to fix them, or `npm audit` for details

C:\Users\plrajaw\reactElectProject>

**Comment by amilajack** [comment]
This project does not have a `dist` npm script.
