### ISSUE TITLE
Is it possible to replace Connected-Router with Plain React-Router?

### ISSUE THREAD

**Issue by jawil003** [electron-react-boilerplate/electron-react-boilerplate#2630]
## Summary

I ran into an error (Navigation is broken) after removing Redux completely including Connected-Router and now I want to know if there is a need for the Connected Router in the way this starter works or is it another Issue I created myself?

**Comment by amilajack** [comment]
IIRC, I don't think so. I have gotten the boilerplate to work without it.

**Comment by jawil003** [comment]
Just created the Problem by myself I created a `<Route/>` with a path where I missed a `/` at start, my bad.
