### ISSUE TITLE
The .node file does not work properly and can be run in the development environment, but not in production

### ISSUE THREAD

**Issue by bei-yang** [electron-react-boilerplate/electron-react-boilerplate#2631]
Error: Cannot find module 'C:\Program Files\xxxxx\unpack\xxxxxx\build\Release\xxxxxx.node'

**Comment by bei-yang** [comment]
The file exists in the directory

**Comment by amilajack** [comment]
You need to make sure your packages with native binaries are installed to `./src/package.json`. See https://electron-react-boilerplate.js.org/docs/adding-dependencies/#module-structure
