### ISSUE TITLE
Error: Exited with code 2 when "yarn dev"

### ISSUE THREAD

**Issue by Emeshka** [electron-react-boilerplate/electron-react-boilerplate#2632]
## Summary
I have some error produced by node_modules\cross-unzip\index.js:38:21 in console window when I start the app using "yarn dev". The app starts anyway, I don't see any problems, but I'm very new to React and your boilerplate in particular. I'm worrying, is everything OK with my installation?
Full log after "yarn dev":

	yarn run v1.22.5
	$ cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
	$ cross-env NODE_ENV=development webpack-dev-server --config configs/webpack.config.renderer.dev.babel.js
	Starting Main Process...
	i ?wds?: Project is running at http://localhost:1212/
	i ?wds?: webpack output is served from http://localhost:1212/dist
	i ?wds?: Content not from webpack is served from D:\1_documents\graphytica\configs\dist
	i ?wds?: 404s will fallback to /index.html

	> electron-react-boilerplate@1.3.1 start-main-dev D:\1_documents\graphytica
	> cross-env START_HOT=1 NODE_ENV=development electron -r ./internals/scripts/BabelRegister ./app/main.dev.ts

	i ?wdm?: Compiled successfully.

	(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9
	.  For more information please check https://github.com/electron/electron/issues/18397
	Error: Exited with code 2
	    at ChildProcess.<anonymous> (D:\1_documents\graphytica\node_modules\cross-unzip\index.js:38:21)
	    at ChildProcess.emit (events.js:210:5)
	    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
	03:20:02.227 > Skip checkForUpdatesAndNotify because application is not packed

When Electron window appears, I have this in Chrome console:
![Screenshot_3](https://user-images.githubusercontent.com/65328222/97376716-26039d00-18cf-11eb-871d-ce837bef2934.png)

**Comment by amilajack** [comment]
Electron has made some breaking changes recently and it has become more strict in terms of security policies. The boilerplate has yet to be updated to account for these new policies.
