### ISSUE TITLE
The biggest problem (Code Signing)

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2634]
Since this project has no discussion board or chat I hope it is ok to post it here. 

I came across a youtube video I wanted to share and after watching it I'm sure I will never publish sucessfully my app to any platform;( here the video https://youtu.be/mwuk0E-tfeg

I need to say that I'm an experienced JS dev and my app is already finished all there is left is publish it, but like the guy in the video I see no chance for me doing this, so why is this world of code signing so hard and feels like some dudes in the 70's made it? Are there any developers in the ERB community who can give me at least some hope and advice on how to finish this last step, but please only if you already have code signed Mac and Windows yourself. Thank you.

**Comment by amilajack** [comment]
I've successfully codesigned and deployed ERB apps before. What problems are you running into?
