### ISSUE TITLE
Please replace "document.addEventListener('DOMContentLoaded', () => {}" with "ReactDOM.render()"

### ISSUE THREAD

**Issue by songyuc** [electron-react-boilerplate/electron-react-boilerplate#2642]
**Appreciation:** I have donated at opencollective for your great work!
![image](https://user-images.githubusercontent.com/27288110/97827530-89426480-1cff-11eb-93ee-06f5184c6ba9.png)

I hope you can replace "document.addEventListener('DOMContentLoaded', () => {}" with `ReactDOM.render()` in `index.tsx`, so that our repo will be a more complete React-style program.

**Comment by amilajack** [comment]
This was fixed in the most recent version https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/src/index.tsx
