### ISSUE TITLE
How to read specific error infomation?

### ISSUE THREAD

**Issue by RebaekSoparkKitchen** [electron-react-boilerplate/electron-react-boilerplate#2643]
Hi,

I am brand new for electron/react and find this project extremely useful. However, I worked it around for several days and can not find a way to read the specific error information.

![issue](https://user-images.githubusercontent.com/49260863/97857943-6765d380-1d39-11eb-9be2-59ac96b69358.jpeg)

Just as the picture above, I got 11 errors but no any information shows in the console. I will be very appreciate if you can help me. Thank you very much in advance!

**Comment by amilajack** [comment]
<img width="238" alt="Screen Shot 2020-11-02 at 8 59 59 AM" src="https://user-images.githubusercontent.com/6374832/97896345-cbf94200-1ce9-11eb-9981-c6da8a439fa2.png">
You have a filter that is filtering out messages that contain a specific string.

**Comment by RebaekSoparkKitchen** [comment]
Thank you very much for your prompt response and it works!!!
