### ISSUE TITLE
White Screen Packaged, but working in DEBUG_PROD

### ISSUE THREAD

**Issue by ashmortar** [electron-react-boilerplate/electron-react-boilerplate#2644]
## Summary

So I'm working on creating the skeleton for the electron app I'm working on starting from the boilerplate and I've run into an issue where I'm not sure how to continue debugging.  When packaging my app and running it I get a default white screen with no content.  I tried running the package with the DEBUG_PROD flag and when I try and launch that executable I get an error that the modules electron-debug isn't found.  So I next tried debugging with the built js files with both `yarn cross-env DEBUG_PROD=true yarn build
yarn cross-env DEBUG_PROD=true yarn start` and just `yarn start` and everything runs totally fine without any errors.  So it has to be something with my electron builder config but I haven't really changed anything in that regard.

**Comment by AdelNamani** [comment]
I am facing exactly the same issue.

**Comment by amilajack** [comment]
Any console errors when running `yarn start`?

**Comment by AdelNamani** [comment]
I've solved it :), the problem was that I was using the lazy loading for the first screen, which worked normally in the dev, but not after packaging the app.
