### ISSUE TITLE
Add support for contextIsolation

### ISSUE THREAD

**Issue by githubBrandon** [electron-react-boilerplate/electron-react-boilerplate#2654]
`contextIsolation` will default to `true` in Electron 12, but this repo doesn't currently support it. (The page doesn't render correctly when setting `contextIsolation: true`.)

It would also help to secure apps that are based on this repo. I see that it was brought up before in #1309, but now that `contextIsolation` is going to be the default, it seems appropriate to revisit the possibility.

**Comment by amilajack** [comment]
@githubBrandon thanks for bringing this up! I'll put this on the roadmap for the next upcoming release!

**Comment by reZach** [comment]
To note, @githubBrandon (also @amilajack) - adding support for contextIsolation requires that any package your application uses and supports contextIsolation. When I was working on electron apps, they _were not_. 

I ended up building [`secure-electron-template`](https://github.com/reZach/secure-electron-template) to address this, so you can look to my repository for inspiration if you'd like.

**Comment by amilajack** [comment]
Fixed in v3
