### ISSUE TITLE
Native dependency install fails, but reordering the install works fine

### ISSUE THREAD

**Issue by MD-AZMAL** [electron-react-boilerplate/electron-react-boilerplate#2655]
## Summary

Installing native dependencies in app fails almost all the time while rebuilding dependencies. For example when I use ffi-napi and ref-napi, the ref-napi install would fail at first but running it again would build it without any error. when I added another native dependency of node-usb it did not work at all. I had to remove the node-modules in the app directory and then had to install node-usb first followed by ffi-napi and ref-napi respectively and it worked perfectly. Can anyone help me understand what is the issue and how the different order of installing the dependency does not result in an error?

**Comment by MD-AZMAL** [comment]
anyone else having this issue

**Comment by MD-AZMAL** [comment]
still facing the same issue

**Comment by amilajack** [comment]
What's the stacktrace?

**Comment by Hidenaga41** [comment]
I have same error when I use `rclnodejs`.
