### ISSUE TITLE
How to run development as win32 (but on mac)

### ISSUE THREAD

**Issue by nicwhitts** [electron-react-boilerplate/electron-react-boilerplate#2656]
## Summary

I'm trying to create a development environment where the application is ran on windows. But my machine is running mac.

My idea was to download electron for the windows platform, then use wine to run the application in development mode in the ```start-main-dev``` script.
But it seems that electron crashes on launch when downloaded this way.

Is there an easier way to do this, e.g with electron-builder?

**Comment by amilajack** [comment]
I recommend using a vm for this. Either virtualbox or vmware player should do
