### ISSUE TITLE
Existing react project

### ISSUE THREAD

**Issue by mtalhagaoglu** [electron-react-boilerplate/electron-react-boilerplate#2658]
Hi. I have a react project that i develop and i want to make this a desktop application so i need to turn this project to electron. I am not experienced in electron. how can i transfer my %100 js reactjs project to this boilerplate? i couldn't understand where to put because there is a lot of ts and other files :/

**Comment by amilajack** [comment]
@mtalhagaoglu If you simply want to wrap your application with electron I recommend using https://github.com/jiahaog/nativefier

**Comment by mtalhagaoglu** [comment]
but its working local. i think the repo you sent me is working with urls not local projects.

**Comment by amilajack** [comment]
@mtalhagaoglu I recommend taking a look at this PR, which implements that functionality
https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2546
