### ISSUE TITLE
Frameless Window, Click Event Not Working

### ISSUE THREAD

**Issue by PrexCoder** [electron-react-boilerplate/electron-react-boilerplate#2662]
Hi, so I'm trying to achieve a frameless window, by adding frame: false, but for some reasons I can't click any element from the window once I did such thing, I've tried to add some click event listeners but no results.

**Comment by PrexCoder** [comment]
Nvm, problem solved, cheers.

**Comment by jktzes** [comment]
May I know how you solved the problem?

**Comment by Mootbing** [comment]
same issue now. works on frame but goes to hell without

**Comment by PrexCoder** [comment]
`-webkit-app-region: no-drag;  `
just apply this style on the buttons and they will start working.

**Comment by Mootbing** [comment]
Yup i got it. Thank you so much
