### ISSUE TITLE
ReferenceError: process is not defined when use third library in renderer in production build

### ISSUE THREAD

**Issue by AmagiDDmxh** [electron-react-boilerplate/electron-react-boilerplate#2667]
## Summary
I got this error message when using third library wether is `electron-json-storage` or `electron-store` on the renderer process after packging.
![Screenshot_20201125_152336](https://user-images.githubusercontent.com/22388514/100291560-143e1400-2fb9-11eb-9eff-37778dfe0478.png)
This error didn't show up in development when using `yarn start`.

I figure this might caused by **webpack**, when libary that involves using **nodejs**. And for some reason **webpack** treated it as a **dynamic module**, ignore it when compiling. Which cause this error at **runtime**.

And is so weirds that non of them happend at every other open-source application I looked on.
Here is my project: [https://github.com/amagiddmxh/project-management](https://github.com/amagiddmxh/project-management)

## Step to produce this error
Make sure to install all the modules by runing `yarn`
- run `yarn package`
- run `yarn start:prod`
- With application window opened up, in the `help` menu, click `Toggle Developer Tools`.
- U should see the errors.

**Comment by jooohhn** [comment]
Hey @AmagiDDmxh 

I believe to access node on the renderer process in production, [the `nodeIntegration` tag is required](https://www.electronjs.org/docs/tutorial/quick-start#nodejs-api).

**Comment by AmagiDDmxh** [comment]
Thank very much for response @jooohhn, this helps me to dig deeper, and find outs that it wasn't causing by **webpack** or `nodeIntegration` tag. But by the third library `ant-design` thats using `Class Component` and block the `react-hooks` somehow.

But also, this bring us a request for a **feature**, how can we do the **staging** debug on this boilerplate, so that we could run the production build in development to prevent problems like this from happening.

By now,  I have two options.
1. By running `yarn start` to start development and then `yarn build && yarn start:prod` to see how does it go in production.
2. I see `DEBUG_PROD` env is written at `configs/webpack.config.renderer.prod.babel.js`, but nowhere are using it.
   1. But we can still add the env, and add some plugin in it and enable **webpack** watch feature to live-debug production build.

**Comment by AmagiDDmxh** [comment]
Update, I do more research base on these factors, eventually find out that it was the `suspense` API of `React` caused this problem.

Thank you very much for your support @jooohhn :heart:.

**Comment by SwapnilAkolkar** [comment]
hi there is there any solution for it? I also got problem when trying to integrate LevelUpDB inside react code.
