### ISSUE TITLE
React compoent cannot be used normally if its .tsx file is in the subfolder of "app/containers"

### ISSUE THREAD

**Issue by songyuc** [electron-react-boilerplate/electron-react-boilerplate#2668]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ x For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

If a self-writed React compoent is placed in  subfolder of "app/containers", the component can be used normally.

## Current Behavior

If a self-writed React compoent is placed in  subfolder of "app/containers", then an error would show like,
>react.development.js:315 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check your code at ProjectSettingsPage.tsx:56.
&nbsp;&nbsp;&nbsp;&nbsp;in ProjectSettingsPage (created by Context.Consumer)
>

## Steps to Reproduce

1. Write a React component in `.tsx`;

2. Place it in to a subfolder of "app/containers" like `app/containers`, and here is an example as,
![image](https://user-images.githubusercontent.com/27288110/100312724-022a9880-2fee-11eb-99a3-eb74c9b94ddf.png)

3. Use this component in a app and run the app;

4. The error above would show.

## Possible Solution (Not obligatory)

I think this might be relevant to the webpack settings.

## Your Environment

- Node version :v14.15.1
- Version or Branch used : 1.2.0
- Operating System and version : Windows 10 
- Link to your project :

**Comment by ramonhoyo** [comment]
Hi @songyuc, can you please share the definition file of ProjectSettingsPage.tsx and file where you are using it, It looks like an error of sintaxys insted of an error releated to ERB or webpack config, maybe your render that component wronly.

**Comment by amilajack** [comment]
Closing because this is not an error with ERB. Please continue the conversation tho.

**Comment by songyuc** [comment]
Hi, @ramonhoyo , I am able to reproduce this isse now. Could you please help me address it?
