### ISSUE TITLE
auto updater config

### ISSUE THREAD

**Issue by mtalhagaoglu** [electron-react-boilerplate/electron-react-boilerplate#2679]
## Summary

Hi. I'm making an app with this template and its very good. But i have a problem with auto updater config. I set github actions to create new version on github and change github url's on project but it doesnt see them for updating. In repo I have found one line command for autoUpdater. Is it enough for that?

`export default class AppUpdater {
  constructor() {
    log.transports.file.level = 'info';
    autoUpdater.logger = log;
    autoUpdater.checkForUpdatesAndNotify();
  }
}
`

I need help about set auto updater config

**Comment by amilajack** [comment]
For this question, I'd recommend filing a ticket in https://github.com/electron-userland/electron-builder to get more help. ERB currently doesn't have much support for auto updating.

**Comment by jfilter** [comment]
No, auto update is not fully implemented in this boilerplate. There are imported parts missing. This guide may help: https://medium.com/@johndyer24/creating-and-deploying-an-auto-updating-electron-app-for-mac-and-windows-using-electron-builder-6a3982c0cee6
