### ISSUE TITLE
Update to Electron 11

### ISSUE THREAD

**Issue by andrewschreiber** [electron-react-boilerplate/electron-react-boilerplate#2682]
This project was downgraded to Electron 8 in order to fix issues around the debugger. #2527 

As of November 17th, Electron 8 reached the end of its support life according to https://www.electronjs.org/blog/electron-11-0

**Comment by andrewschreiber** [comment]
Since the plan is to remove Redux (#2598), having the redux debugger working should no longer be a blocker (whether or not its been fixed by Electron 11).

**Comment by amilajack** [comment]
We upgraded to electron@11 in #2661
