### ISSUE TITLE
Packaged application on MacOS doesn't have any styles from App.global.css in the master branch version 2.0

### ISSUE THREAD

**Issue by zalenskiSofteq** [electron-react-boilerplate/electron-react-boilerplate#2683]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

The packaged application will look like on the **develop** mode

## Current Behavior

The packaged on MacOS doesn't have any styles. The <head> doesn't have path to compiled **style.css** file

## Steps to Reproduce

1. `git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git`
2. `cd electron-react-boilerplate`
3. `yarn`
4. `yarn package`
5. Run ElectronReact-2.0.0.dmg
6. Run ElectronReact

## Possible Solution

In the index.html there is condition `typeof process !== 'object'` should process is not object in the packaged application?
Or problem is something else?

## Your Environment

- Node version : 15.4.0
- electron-react-boilerplate version or branch : master
- Operating System and version : MacOS 11.0.1

## Screenshots
<details>
  <summary>Screenshots</summary>

  Run packaged ElectronReact with **DEBUG_PROD=true**:
<img width="1023" alt="Screenshot 2020-12-11 at 12 53 29" src="https://user-images.githubusercontent.com/63463140/101888929-d7c10980-3baf-11eb-9746-0874b5eabc8a.png">

Run packaged ElectronReact:
<img width="517" alt="Screenshot 2020-12-11 at 13 00 59" src="https://user-images.githubusercontent.com/63463140/101889795-e0fea600-3bb0-11eb-9d9b-774cf7fe5d72.png">

`yarn start`
<img width="601" alt="Screenshot 2020-12-11 at 12 57 51" src="https://user-images.githubusercontent.com/63463140/101889423-6df52f80-3bb0-11eb-9f04-17aaa7e3df7f.png">
</details>

**Comment by telanflow** [comment]
me too

**Comment by amilajack** [comment]
@telanflow @zalenskiSofteq Thanks for filing this bug! See https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/e679432174876a7ca6c8e0af47149f45b04709b9 for the fix
