### ISSUE TITLE
Failed to load .woff resources

### ISSUE THREAD

**Issue by jurij** [electron-react-boilerplate/electron-react-boilerplate#2690]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Should load `/dist/*.woff`

## Current Behavior

Is loading `/dist/dist/*.woff` in production and development

Example: `file:///C:/Users/jk/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/dist/bedd9dda935a164e00f07738e7b799f7.woff`

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/1895950/102681248-545f7380-41c0-11eb-87dd-9852379be413.png">

## Steps to Reproduce

1. `yarn add typeface-noto-sans`

2. changing: `src/App.global.css`
```diff
-@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap');
+@import '~typeface-noto-sans';

-  font-family: 'Noto Sans JP', sans-serif;
+  font-family: 'Noto Sans', 'Noto Sans JP', sans-serif;
```

3. `yarn cross-env DEBUG_PROD=true yarn package`

## Possible Solution (Not obligatory)

For productin it did help to add this again:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/c26f548c86a663846c4257e9a9c54b415757b243/configs/webpack.config.renderer.prod.babel.js#L49-L51

Im not sure what the equivalent for development is.

## Your Environment

- Node version: v12.18.4 
- electron-react-boilerplate version or branch: master (fb292007b3e9f187e377b758c1534772e5fca168)
- Operating System and version: macOS Big Sur / Windows 10
- Link to your project : /

**Comment by Unforgiven-wanda** [comment]
Having this exact same issue, with Font-awesome specifically.
Works fine in development, but font paths become `dist/dist` in production.
Adding `publicPath` did not fix it.

**Comment by jurij** [comment]
> Adding `publicPath` did not fix it.

Do you import font awesome in `App.global.css` or some other `*.css` file?

**Comment by Unforgiven-wanda** [comment]
Yep, you're right, brainfart.
I am using sass and was importing it in app.global.scss, and not css.
Thank you for pointing it out.
