### ISSUE TITLE
App don't display in window after build+package.

### ISSUE THREAD

**Issue by Bikmay** [electron-react-boilerplate/electron-react-boilerplate#2693]
I have 1.2.0 release this project. I met problem.

In scenario "dev" app good work(open,display and ect.). In scenario "start"(or build+package) app open Electron window, but not display app interface.

I haven't stacktrace in browser console and cmd.

What i can fix for build and package my app?

**Comment by mattcarpenter** [comment]
I just started having this issue too. I recently deleted my `node_modules` directory and reinstalled so I think I must have received some new/broken bits in a dependency.

**Comment by alexbrul** [comment]
Also have this problem :/
