### ISSUE TITLE
Error: Your application tried to access @babel/plugin-proposal-numeric-separator, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

### ISSUE THREAD

**Issue by keshvari** [electron-react-boilerplate/electron-react-boilerplate#2695]
## Summary

I am trying to install electron-react-boilerplate project based on the instruction but I faced build errors and I follow all instructions including the [debugging guide](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400). Does anybody recently cloned and install this project successfully? I want to know that is it my problem or is it a bug.
 The error is(after yarn command) :

> **Error: Your application tried to access @babel/plugin-proposal-numeric-separator, but it isn't declared in your dependencies; this makes the require to call ambiguous and unsound.**

After I  run`yarn add @babel/plugin-proposal-numeric-separator` I faced to this error: 

> **Error: Your application tried to access @babel/runtime, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.**

After I run `yarn add @babel/runtime` I got the error below from my log files:

> This file contains the result of Yarn building a package (electron-react-boilerplate@workspace:.)
>  Script name: postinstall
> 
> npm ERR! missing: @babel/plugin-proposal-numeric-separator@^7.12.7, required by electron-react-boilerplate@
> npm ERR! missing: @babel/runtime@^7.12.5, required by electron-react-boilerplate@
> npm ERR! missing: electron-debug@^3.1.0, required by electron-react-boilerplate@
> npm ERR! missing: electron-log@^4.2.4, required by electron-react-boilerplate@
> npm ERR! missing: electron-updater@^4.3.4, required by electron-react-boilerplate@
> npm ERR! missing: history@^5.0.0, required by electron-react-boilerplate@
> npm ERR! missing: react@^17.0.1, required by electron-react-boilerplate@
> npm ERR! missing: react-dom@^17.0.1, required by electron-react-boilerplate@
> npm ERR! missing: react-router-dom@^5.2.0, required by electron-react-boilerplate@
> npm ERR! missing: regenerator-runtime@^0.13.5, required by electron-react-boilerplate@
> npm ERR! missing: source-map-support@^0.5.19, required by electron-react-boilerplate@
> Native dependencies could not be checked
>   • electron-builder  version=22.9.1
>   • loaded configuration  file=package.json ("build" field)
>   ⨯ Cannot compute electron version from installed node modules - none of the possible electron modules are installed and version ("^11.0.1") is not fixed in project.
> See https://github.com/electron-userland/electron-builder/issues/3984#issuecomment-504968246

There should be a problem here because I expect that yarn catch all these dependencies for me. Does anybody face similar issue? Any suggestion could help.

❗️❗️ Also, please consider donating (https://opencollective.com/electron-react-boilerplate-594) ❗️❗️

Donations will ensure the following:

🔨 Long term maintenance of the project
🛣 Progress on the roadmap
🐛 Quick responses to bug reports and help requests
 -->

**Comment by dmitru** [comment]
Facing the same issue here, using Yarn2.

**Comment by lukepetrolekas** [comment]
I ran into this error today, when I tried following the [documentation](https://electron-react-boilerplate.js.org/docs/installation)

```
git clone --depth=1 \
  https://github.com/electron-react-boilerplate/electron-react-boilerplate \
  your-project-name
```

In contrast to the project's README.md, which specified

```
git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
```

Including the --single-branch flag got the project to start up.
