### ISSUE TITLE
How to install native modules (e.g. sqlite) in v2.0.0?

### ISSUE THREAD

**Issue by longsangstan** [electron-react-boilerplate/electron-react-boilerplate#2696]
Hi, I am new to electron-react-boilerplate and I am confused how to install native modules (in my case sqlite3) in this project.

According to the doc, I have to install sqlite3 in the `app` folder and have a separate `./app/package.json` file.
I know that that was a `./app/package.json` file in the [previous version](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/c26f548c86a663846c4257e9a9c54b415757b243/app/package.json), but how will the `./app/package.json` file looks like in v2.0.0?

I have tried something like but it didn't work.
```
{
  "name": "electron-react-boilerplate",
  "productName": "electron-react-boilerplate",
  "description": "Electron application boilerplate based on React, React Router, Webpack, React Hot Loader for rapid application development",
  "main": "./main.prod.js",
  "author": {
    "name": "Electron React Boilerplate Maintainers",
    "email": "electronreactboilerplate@gmail.com",
    "url": "https://github.com/electron-react-boilerplate"
  },
  "scripts": {
    "electron-rebuild": "node -r ../.erb/scripts/BabelRegister.js ../.erb/scripts/ElectronRebuild.js",
    "postinstall": "yarn electron-rebuild"
  },
  "license": "MIT",
  "dependencies": {
    "sqlite3": "^5.0.0"
  }
}
```

`Module not found: Error: Can't resolve 'sqlite3'
`
Thanks!

**Comment by zalenskiSofteq** [comment]
me too

**Comment by IamFlowZ** [comment]
I've gotten sqlite3 working with electron and would strongly recommend to use something else. It had really poor performance and the conventions it used makes it hard to work with in react. Personally I've switched to electron-store and had way better results.
