### ISSUE TITLE
First time running after installing the packaged build works, but after closing it installs the default ElectronReact program and overrides the original program.

### ISSUE THREAD

**Issue by phakhee** [electron-react-boilerplate/electron-react-boilerplate#2697]
So I made an application, built and packaged it. On my own local machine after installing it, it works fine even after closing it and opening it a second time. But on my windows server after opening it the first time and closing it, when I re-open the program, it opens the default ElectronReact boilerplate template, instead of my own program. 

![image](https://user-images.githubusercontent.com/48755051/103179420-382c9800-488c-11eb-82ce-2d2d02917c6c.png)

As you can see the third bottom exe is the original program, but gets overwritten by ElectronReact after closing the program on first use. Both exe's show the default template program after opening it the second time.

**Comment by aniketbehera** [comment]
Facing the same issue

**Comment by aniketbehera** [comment]
Make sure that the productName, name are the same and equal to your app's name (and not electron-react)

**Comment by MinhxIT** [comment]
You can try remove app.html
![image](https://user-images.githubusercontent.com/28050330/106565576-9b7fa900-6561-11eb-9687-0aeb9b16a2aa.png)
