### ISSUE TITLE
react-refresh is infinitly running and does not refresh my components

### ISSUE THREAD

**Issue by hugoperier** [electron-react-boilerplate/electron-react-boilerplate#2704]
## Prerequisites

- [X ] Using yarn
- [ X] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ X] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

I just cloned the boilerplate and writing few component until I notice that at some point, react-refresh is not updating my page, and is running infinitly for no reason. It happen all the time

I tried with another computer as well and I have the same issue again

## Steps to Reproduce

1. I have cloned the repository

2. Write some component

3. At some point the react-refresh infinitly run and here we go

![image](https://user-images.githubusercontent.com/26797879/103456295-0173d900-4cf5-11eb-85a6-844c149d1040.png)
I tried here to update my title "Sign up !!!" to "Sign up", it didnt change the h1 and now the messages on the console are running "infinitly". When I press ctrl & s then the next "App Updated" appear 2 time (you can see it on the console)

## Context

I am trying to build a cross platform desktop app with firebase managed authentification. For the moment I have a very simple form linked to firebase. Even without firebase used and installed I still encounter the problem with react-refresh.

## Your Environment

- Node version : v12.18.2 / 15.5.0 (I tried both)
- electron-react-boilerplate version or branch : v 2.0.1
- Operating System and version : Windows 10 Education
- Link to your project :

Thanks a lot for any answer

**Comment by tegmos** [comment]
I am also suddenly having this issue since last night. No idea what triggered it.

I thought it might be something else touching the file, causing a chain reaction, so I changed the polling value from 100 to 2000 in _webpack.config.renderer.dev.bable.js_:

```
watchOptions: {
			aggregateTimeout: 300, // 300
			ignored: /node_modules/,
			poll: 2000, // 100
		},
```

So far, that seems to have prevented the compile loop. Don't know if it would affect anything else.
