### ISSUE TITLE
vscode renderer debugging - 2021

### ISSUE THREAD

**Issue by skavan** [electron-react-boilerplate/electron-react-boilerplate#2714]
Hi all,

First - this boilerplate is fantastic. Thank you.
My biggest request/challenge is to get vscode based debugging of the renderer process working.
No matter what I have tried, I can't get it to work. The usual result is:
`Cannot connect to the target at localhost:9223: Could not connect to debug target at http://localhost:9223: Promise was canceled.`
I have tried all the variations I can think of, but am stuck. Has anyone pulled this off, and would they be so kind as to share the steps required.
Prior threads on this subject all use launch.jsons that don;t work, presumably because the boilerplate and electron have moved on since they were written.

Thanks in advance.

**Comment by Unforgiven-wanda** [comment]
Having the exact same issue.
