### ISSUE TITLE
Postinstall script fails,  missing path separators

### ISSUE THREAD

**Issue by CharukaHS** [electron-react-boilerplate/electron-react-boilerplate#2719]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Successful execution of postinstall script

## Current Behavior

Script fails at `yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js`  
  
```
C:\Projects\pms>yarn
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=C:\Projects\pms\src
yarn run v1.22.5
$ C:\Projects\pms\node_modules\.bin\cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
/usr/bin/bash: C:Projectspmsnode_modules.bincross-env: command not found
←[2K←[1G←[31merror←[39m Command failed with exit code 127.
←[2K←[1G←[94minfo←[39m Visit ←[1mhttps://yarnpkg.com/en/docs/cli/run←[22m for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Steps to Reproduce

1. Clone the repo as mentioned in /README.md

2. cd repo

3. yarn

## Possible Solution (Not obligatory)

remove `yarn` in postinstall script => `... && cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js &&  ...`  

## Context

I'm a windows user and when I tries to install packages, `C:Projectspmsnode_modules.bincross-env: command not found` error appears when running postinstall script

But later, I removed `yarn` part near the `cross-env` and script excuted successfully. Now when I run `yarn` I get

```
C:\Projects\pms>yarn
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=C:\Projects\pms\src
asset renderer.dev.dll.js 2.31 MiB [compared for emit] (name: renderer)
runtime modules 1.03 KiB 5 modules
cacheable modules 2.09 MiB 191 modules
20 modules

WARNING in ./node_modules/electron-debug/index.js 109:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[0]

WARNING in ./node_modules/electron-debug/index.js 110:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[0]

webpack 5.12.0 compiled with 2 warnings in 1527 ms
Thank you for using electron-react-boilerplate!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/electron-react-boilerplate-594/donate

Done in 11.36s.
```

`yarn start` also working without an issue

## Your Environment

- Node version : 14.15.3
- electron-react-boilerplate version or branch : 2.0.1
- Operating System and version : Windows 10, version 2004 build 19041.685
- Link to your project : (https://github.com/CharukaHS/pmsv2)[https://github.com/CharukaHS/pmsv2]

**Comment by Niptide** [comment]
Am having the same issue with missing path separators for cross-env, but only after I recently ran `yarn package`. Had some errors on packaging in windows 'cmd', so I tried it with WSL and git-bash too. Maybe the application was also still running while packaging. Not sure what caused it, but now it's broken. Already tried node uninstall and install again with nvm (for windows).

**Comment by alirezakay** [comment]
I was also experiencing the same problem.
Thanks to @CharukaHS 's solution, I could install and run it successfully.

But I gotta say, after removing the `yarn` word from the script section of `postinstall`, and then running the `yarn install` command, it got installed with success but then after running the `yarn start` command, I got an error in terminal:

```
Error when run npm start: Class constructor ServeCommand cannot be invoked without 'new'
```

But after deleting the whole `node_modules` folder and then again reinstalling by using the `yarn install` command, the `yarn start` command also got fixed and now I can run it with no problem (till now!!!)

**Comment by bennik88** [comment]
I'm having the same issue with
- Node version: v16.13.0
- OS: macOS Monterey 12.4
- electron-react-boilerplate version: 4.6.0

I did nothing other than moving the app's parent folder to another directory.  So I don't know what could have caused it.

**Comment by krgainer** [comment]
I've found that finder will not copy over certain files when manually moving stuff over. Best solution is to user terminal to copy these files over, or use VSCode's file browser, which I've found gets everything. Alternatively, repull the repo in the correct location.
