### ISSUE TITLE
Redux integration docs Redux Dev Tools not working?

### ISSUE THREAD

**Issue by rendomnet** [electron-react-boilerplate/electron-react-boilerplate#2722]
I understand that you dropped redux default integration.
But can you instead show how to add redux for those who needs it?

**Comment by rendomnet** [comment]
Okay I have successfully added Redux but what about Redux Dev tools they do not recognise store?

**Comment by brianramirez** [comment]
+1 for the Redux Dev tools. I cannot get it to recognize the store.

**Comment by phhoef** [comment]
Sorry for posting offtopic.
@rendomnet could you please share how you did the setup of redux? I am currently using older version of erb, which already included redux, and I am thinking of updating and therefore I need to get redux up and running to make my code work.

**Comment by JonathanRosado** [comment]
+1 for Dev Tools. Followed instructions, added plugin, connected store, and nothing show up on the Redux Dev Tools tab.

**Comment by cohenshay** [comment]
same here, redux is working but dev tool cannot recognize the store. also react dev tool not showing any tab

**Comment by h0tw4t3r** [comment]
+1, Redux and Connected Roter don't work at all now
