### ISSUE TITLE
React Developer Tools not appearing

### ISSUE THREAD

**Issue by andrewschreiber** [electron-react-boilerplate/electron-react-boilerplate#2725]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

React Dev tools appear in the Dev tools window like such:
![image](https://user-images.githubusercontent.com/1892071/104245307-dab25280-5418-11eb-93be-0a5bc8a027fc.png)

## Current Behavior

React dev tools do not appear. 
![image](https://user-images.githubusercontent.com/1892071/104246512-ffa7c500-541a-11eb-9dc1-6a3d3d00438b.png)

An error is thrown:`
(node:39620) ExtensionLoadWarning: Warnings loading extension at /Users/andrewschreiber/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'minimum_chrome_version'. Unrecognized manifest key 'update_url'. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system.`

Attempted solutions:
- Fixing the above issue by deleting the metadata folder and the unrecognized keys.
- Reinstalling electron-devtools-installer
- Adding types `yarn add -D @types/electron-devtools-installer`
- Using the standard electron approach (without electron-devtools-installer) here https://www.electronjs.org/docs/tutorial/devtools-extension
- Updating to latest React Developer Tools version (14.10.1)

## Steps to Reproduce

1. Clone repo. Run `yarn && yarn start` 

2. Notice error log and absence of React Developer Tools

## Possible Solution (Not obligatory)

Unknown, but this poster on reddit seems to have the same issue. https://www.reddit.com/r/electronjs/comments/kv0xv0/how_can_i_use_react_devtools_extension_in_my/

## Context

No changes were made to the boilerplate. 

## Your Environment

- Node version : v14.10.1
- electron-react-boilerplate version or branch : Master ( commit fb29200 from Dec 18th)
- Operating System and version : MacOS Catalina 10.15.7

**Comment by TomTomB** [comment]
This should be fixed once electron PR [#25198 ](https://github.com/electron/electron/pull/25198) is merged. Until thats the case, you need to close and reopen the devtools everytime you start erb.

**Comment by hadnet** [comment]
Closing and reopen devtools does not work either.

**Comment by DoWhileGeek** [comment]
@hadnet I'm seeing the same thing, with react or redux dev tools.

**Comment by jedhelmers** [comment]
Also seeing this error

**Comment by TomTomB** [comment]
> @hadnet I'm seeing the same thing, with react or redux dev tools.

For Redux DevTools you can use the [Remote Redux DevTools package](https://github.com/zalmoxisus/remote-redux-devtools). Sadly, I dont think there is a corresponding package for React DevTools.

**Comment by jedhelmers** [comment]
I toggled OFF Redux Dev Tools and that seemed to fix my problem. Thanks!

**Comment by mulgurul** [comment]
Same here, closing and reopening dev tool does not work. Quite annoying...

**Comment by RoderickJDunn** [comment]
I was able to get both React & Redux Devtools to show reliably by following the steps on this [comment](https://github.com/MarshallOfSound/electron-devtools-installer/issues/174#issuecomment-787514657) on electron-devtools-installer. Hopefully that helps someone
