### ISSUE TITLE
v2.2.0: export 'default' (imported as 'classes') was not found in './file.scss'

### ISSUE THREAD

**Issue by Rafatcb** [electron-react-boilerplate/electron-react-boilerplate#2726]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Importing classes in a TypeScript file as `import classes from './file.scss';` should work.

## Current Behavior

When trying to `yarn package` in the latest version, the following warning occurs:

```bash
[1] WARNING in ./src/file.tsx 157:15-29
[1] export 'default' (imported as 'classes') was not found in './file.scss' (possible exports: )
```

The `.tsx` code is:

```tsx
import classes from './file.scss';
```

## Steps to Reproduce

1. Create a `.scss` file with any class

2. Import it in `.tsx` file as `import classes from './file.scss';` 

3. Run `yarn package`.

## Possible Solution (Not obligatory)

I don't know how Webpack config works, but doing the following the warning disappeared:

```diff
{
  test: /.s?.css$/,
  use: [
    {
      loader: MiniCssExtractPlugin.loader,
      options: {
        // `./dist` can't be inherited for publicPath for styles. Otherwise generated paths will be ./dist/dist
        publicPath: './',
      }
     },
-    'css-loader',
+    {
+     loader: 'css-loader',
+     options: {
+       modules: {
+         localIdentName: '[name]__[local]__[hash:base64:5]',
+       },
+       importLoaders: 1,
+       sourceMap: true,
+     },
+   },
-    'sass-loader',
+   {
+     loader: 'sass-loader',
+     options: {
+       sourceMap: true,
+     },
+   },
  ],
}
```

I copied it from the old config (you can see it [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2720/files#diff-9b6a02a8106013144eedce66ed8b0cc5826f1a34f443ea38faeb7b15bf6807f3L99)), so I don't know if the options are right.

## Context

I'm used to import `.scss` classes like that and it worked in v2.0.1.

## Your Environment

- Node version : v12.14.1
- electron-react-boilerplate version or branch : v2.2.0
- Operating System and version : Windows 10 Home Single Language v1909

**Comment by ian-rudge** [comment]
I had the same issue, it caused the styles to completely break when the app is packaged. It seems if you rename your files to `.module.scss` it fixes the issue. I reverted back to the scss loaders in v2.0.1.

**Comment by Rafatcb** [comment]
Another break from this version related to SCSS: `.global.scss` files are not being handled as *global*, the generated `style.css` file converts it to scss modules.

**Comment by songyuc** [comment]
Also, I cannot import .scss for an element, as
```ts
import './HomePage.scss';
```
