### ISSUE TITLE
Dynamically load images from assets folder

### ISSUE THREAD

**Issue by rendomnet** [electron-react-boilerplate/electron-react-boilerplate#2728]
I have some images in assets folder for example `cat1.jpg, cat2121212.jpg, cat11121212222.jpg` and so on.

And I want to to load this image dynamically depending on my state.

this is NOT working for me
```
<img src={require(`assets/cat${id}.jpg`)} />
```
this IS working but NOT dynamic
```
import imgpath from 'assets/cat1.jpg';
<img src={imgpath} />
```

Also maybe this mehod is not right? Maybe I should store media files in external  directory not in assets folder? And require images from this external directory?

**Comment by amilajack** [comment]
You can import all the images and conditionally use a specific one:

```js
import a from './a.png'
import b from './b.png'

someCondition ? a : b
```

If the number of images is small you shouldn't be concerned about asset size but if you are you can dynamically import:

```js
someCondition
  ? import( './a.png')
  : import( './b.png')
```

**Comment by rendomnet** [comment]
@amilajack there can dozens of such files.
There is no way to import them dynamically? Without importing all?

**Comment by amilajack** [comment]
If there are than many files I recommend you implement the solution in the run-time assets section of our docs:
https://electron-react-boilerplate.js.org/docs/adding-assets#run-time-assets

**Comment by mqtik** [comment]
This isn't working for me.
Adding "assets" to the `files`, or `extraResources`, does not include files in the production bundle.

It does work on dev though, but with localhost proxying.

**Comment by Narcha** [comment]
I'm still looking for a solution of this issue.

**Comment by rajrkrish** [comment]
Similar issue.

I have to load images dynamically from assets folder without importing it. Like this

<img className="a-img" src='/assets/img/A.jpg' alt="" />

And I am getting the following error in the console running the dev server.

`Not rewriting GET /assets/img/A.jpg because the path includes a dot (.) character.`

Doesn't work in dev mode and I haven't tried it in prod mode.

And the following code in main.ts correctly points to the assets folder

  `const RESOURCES_PATH = app.isPackaged
    ? path.join(process.resourcesPath, 'assets')
    : path.join(__dirname, '../../assets');`

Not sure how to fix the dot error without breaking it in production. Help appreciated.

**Comment by lacymorrow** [comment]
@amilajack Any solution to this?

**Comment by dowmeister** [comment]
Someone has found a solution for using images using their path instead of `require `?

**Comment by lacymorrow** [comment]
@dowmeister It's not a great solution, but I'm using the `file://` protocol.

```jsx
 <img src={`file://${imagePath}`} alt="" />
```

You must disable websecurity:

```
webPreferences = {
  webSecurity: !is.development, // Required for loading sounds, comment out if not using sounds
}

**Comment by dowmeister** [comment]
thanks @lacymorrow ! will try it out.
just wondering, it works also when packaged? 

where did you ha have those images? can you show please and example directory structure?

**Comment by lacymorrow** [comment]
- Images go in `assets`
- In `package.json`, add `assets` to the `build.files` property
- use this variable in your main:

```js
export const __resources = app.isPackaged
	? path.join(process.resourcesPath, 'assets')
	: path.join(__dirname, '../../assets');
```

to provide a path to the assets folder.

You can see an example here: https://github.com/lacymorrow/electron-hotplate

**Comment by dowmeister** [comment]
appreciate your input @lacymorrow . i was wondering if you found out a way to get the dynamic asset path in renderer and looking at your code i've realized i had the same idea but maybe there was a better one

Thanks!

**Comment by lacymorrow** [comment]
In the past I've spent hundreds of hours testing different ways of doing weird things with Electron. There's likely better ways of doing it, but I don't feel like spending any more time finding it, so I just use IPC from main->renderer
