### ISSUE TITLE
App works fine with yarn start but I can't build and package it - I had to add jsx loader to production webpack configuration

### ISSUE THREAD

**Issue by piotrkraszewski** [electron-react-boilerplate/electron-react-boilerplate#2729]
I have app that works greate with yarn start, but I can't build and package it - probably typescript error

I use packages like electron-storage, react-alert that don't have or have @Types that gives an error. 

Generally speaking I get this error that points to diffrent things depending on what I comment out in a project;

Module parse failed: Unexpected token (48:14)
[0] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by albert3-3** [comment]
did you ever find a solution?

**Comment by piotrkraszewski** [comment]
Yes. I turned out to be a problem with webpack configuration. I had this problem with version 2.2.0 so maybe it was 
fixed in 2.3.0. I don't know.

I don't remember exactly what I did, but I compared files in .erb/configs. webpack.config.renderer.dev.babel with webpack.config.renderer.prod.babel. 

I added probably jsx loader from dev version of the file to prod version of the file:

`{
        test: /\.[jt]sx?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: require.resolve('babel-loader'),
            options: {
              //plugins: [
              //  require.resolve('react-refresh/babel'),
             // ].filter(Boolean),
            },
          },
        ],
      },`
