### ISSUE TITLE
how can config import path alias，the npm start use electron run js in main not webpack!

### ISSUE THREAD

**Issue by qq1053831109** [electron-react-boilerplate/electron-react-boilerplate#2737]
how can config import path alias，the npm start use electron run js in main not webpack!

**Comment by Arman19941113** [comment]
I did't get you. If you want to use alias like this:
```
import xxx from '@/components/demo'
```

First, add alias in file 'webpack.config.base.js'
```
alias: { '@': path.join(__dirname, '../../src') },
```
Second, add this below in tsconfig.json.compilerOptions
```
"baseUrl": ".",
"paths": {
  "@/*": ["src/*"]
 }
```

**Comment by thisdarktao** [comment]
Just a note for anyone else that stumbles across this: the `alias` is added to `resolve`:

```
resolve: {
    alias: { '@': path.join(__dirname, '../../src') },
    ...
},
```

**Comment by Rafatcb** [comment]
It worked for me in the Renderer process, but not in the Main process. Does anyone have an idea what the problem might be in this case?

----------------------

To complement the other answers, another option available to set the aliases in Webpack is to use [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin) as below in `webpack.config.base.js`:

```js
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";

resolve: {
  // You don't need to define the `alias` property
  plugins: [
    new TsconfigPathsPlugin({
      baseUrl: path.join(__dirname, '../..'),
    }),
  ],
},
```

Quoting its README:

> Using this plugin means that you should no longer need to add `alias` entries in your `webpack.config.js` which correspond to the `paths` entries in your `tsconfig.json`. This plugin creates those `alias` entries for you, so you don't have to!

**Comment by imjuni** [comment]
@Rafatcb 

You need two package: tsconfig-paths-webpack-plugin, [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths)

1. Modify webpack.config.base.js
    * If you need change baseUrl, prefer use in tsconfig.json. Because you pass some option that is raise ignore default option value

```ts
import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";

resolve: {
  // You don't need to define the `alias` property
  plugins: [
    new TsconfigPathsPlugin(),
  ],
},
```
2. install tsconfig-paths
3. change run command: "start:main"
```
# as-is 
"start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/babel-register ./src/main/main.ts",

# to-be
"start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/babel-register -r tsconfig-paths/register ./src/main/main.ts",
```

Thank you.

**Comment by Rafatcb** [comment]
Thank you @imjuni , it worked like a charm. I just did step 2 and 3, I didn't know I needed to register `tsconfig-paths` for the Main process.

**Comment by imjuni** [comment]
@Rafatcb `tsconfig-paths` tell about module resolution information to `ts-node`.

**Comment by Chengma999** [comment]
> I did't get you. If you want to use alias like this:
> 
> ```
> import xxx from '@/components/demo'
> ```
> 
> First, add alias in file 'webpack.config.base.js'
> 
> ```
> alias: { '@': path.join(__dirname, '../../src') },
> ```
> 
> Second, add this below in tsconfig.json.compilerOptions
> 
> ```
> "baseUrl": ".",
> "paths": {
>   "@/*": ["src/*"]
>  }
> ```

This solution doesn't work for me.  
get always error "Cannot find module 'Components/login/LoginPage' or its corresponding type declarations."

electron ^18.0.1
node 17.1.0
webpack ^5.71.0
typescript ^4.6.3

**Comment by Chengma999** [comment]
> > I did't get you. If you want to use alias like this:
> > ```
> > import xxx from '@/components/demo'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > First, add alias in file 'webpack.config.base.js'
> > ```
> > alias: { '@': path.join(__dirname, '../../src') },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Second, add this below in tsconfig.json.compilerOptions
> > ```
> > "baseUrl": ".",
> > "paths": {
> >   "@/*": ["src/*"]
> >  }
> > ```
> 
> This solution doesn't work for me. get always error "Cannot find module '@/components/login/LoginPage' or its corresponding type declarations."
> 
> electron ^18.0.1 node 17.1.0 webpack ^5.71.0 typescript ^4.6.3

is already fixed.  supposed to to use "@/renderer/components" instead of "@/components"

**Comment by sebasptsch** [comment]
You can no longer register paths with babel as the script no longer exists. How would one register paths with ts-node?

**Comment by Sebastien-Lampazona** [comment]
I've made this : 

From : 
```
    "start:main": "cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only ."
```
To
```
    "start:main": "cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only -r tsconfig-paths/register ."
```

It's working for main, but if i remove aliases from `resolve.alias` in webpack it not working in renderer ... `TsconfigPathsPlugins` not working for me 🤷‍♂️

**Comment by Vn-ChemGio** [comment]
> @Rafatcb
> 
> You need two package: tsconfig-paths-webpack-plugin, [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths)
> 
>     1. Modify webpack.config.base.js
>        
>        * If you need change baseUrl, prefer use in tsconfig.json. Because you pass some option that raise ignore default option value
> 
> 
> ```ts
> import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";
> 
> resolve: {
>   // You don't need to define the `alias` property
>   plugins: [
>     new TsconfigPathsPlugin(),
>   ],
> },
> ```
> 
>     2. install tsconfig-paths
> 
>     3. change run command: "start:main"
> 
> 
> ```
> # as-is 
> "start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/babel-register ./src/main/main.ts",
> 
> # to-be
> "start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/babel-register -r tsconfig-paths/register ./src/main/main.ts",
> ```
> 
> Thank you.



> @Rafatcb
> 
> You need two package: tsconfig-paths-webpack-plugin, [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths)
> 
>     1. Modify webpack.config.base.js
>        
>        * If you need change baseUrl, prefer use in tsconfig.json. Because you pass some option that raise ignore default option value
> 
> 
> ```ts
> import { TsconfigPathsPlugin } from "tsconfig-paths-webpack-plugin";
> 
> resolve: {
>   // You don't need to define the `alias` property
>   plugins: [
>     new TsconfigPathsPlugin(),
>   ],
> },
> ```
> 
>     2. install tsconfig-paths
> 
>     3. change run command: "start:main"
> 
> 
> ```
> # as-is 
> "start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/babel-register ./src/main/main.ts",
> 
> # to-be
> "start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/babel-register -r tsconfig-paths/register ./src/main/main.ts",
> ```
> 
> Thank you.

I've 
- Install  tsconfig-paths
- Update start:main script 
- Update tsconfig.json (the Ide had stop warning in code)
But when I ran the start script, I've got error
![image](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/25608423/47daf079-da51-4a29-b466-930d1cb22832)

I only want to use alias in directory in renderer folder :(
