### ISSUE TITLE
App keeps recompiling in `yarn start`

### ISSUE THREAD

**Issue by Haaxor1689** [electron-react-boilerplate/electron-react-boilerplate#2742]
## Summary

When I run the app with `yarn start` after first change in watched files the app just keeps recompiling over and over again constantly.

![image](https://user-images.githubusercontent.com/25706343/105625307-7f289180-5e28-11eb-9d00-70fe2f411907.png)

I have no idea where to even start on this one. Here is the project repository it is happening in:

https://github.com/Haaxor1689/electron-wow-db

**Comment by flash716** [comment]
I am also getting this all of a sudden. 

At the same time I've also noticed another issue with the compile process. When a shared library is updated (like a service) the compile process used to recompile any components that used the updated library, now it seems to just recompile the library and existing components continue using an outdated version of the library.

**Comment by flash716** [comment]
I've found changing `poll: 100` in `webpack.config.renderer.dev.babel.js` to `poll: 250` partially fixes the continuous compile, it now only happens a few times per file change.

**Comment by alexbrul** [comment]
I got this when i imported a css file and not the .tsx file

**Comment by mzihin91** [comment]
I also got the same error and later found out that there is a typo in the file path of my import statement

**Comment by tegmos** [comment]
> I also got the same error and later found out that there is a typo in the file path of my import statement

Same here. A couple of days of off-and-on trying to figure it out. Turned out it was a couple of imports where the casing of the import file name was different from the name on the actual file.

**Comment by codingedgar** [comment]
I just installed `https://github.com/Urthen/case-sensitive-paths-webpack-plugin` which helped a lot in this case, might be nice to install it as a default in this library
