### ISSUE TITLE
Runing a second hidden window, example bit outdated

### ISSUE THREAD

**Issue by mulgurul** [electron-react-boilerplate/electron-react-boilerplate#2744]
Hi

I'm new to Electron and are struggling quite a lot with all the pluming.
My newest problem:-) is that I need to run a worker window for some background processes.
I looked at the example in [https://github.com/amilajack/erb-second-renderer-window-example](https://github.com/amilajack/erb-second-renderer-window-example) but it seems to outdated, so can't make it work just using it.

I'm using typescript together with ERB.

I have the code for my second renderer in /src/udpworker/index.ts and the index.html file as well.

Focusing just on dev. mode right now I have changed from org boilerplate config to these settings in webpack.config.renderer.dev.babel.js:

```
export default merge(baseConfig, {
  devtool: 'inline-source-map',

  mode: 'development',

  target: 'electron-renderer',

  entry: {
    mainWindow: [
      'core-js',
      'regenerator-runtime/runtime',
      require.resolve('../../src/index.tsx'),
    ],
    workerWindow: [
      'core-js',
      'regenerator-runtime/runtime',
      require.resolve('../../src/udpworker/index.ts')
    ]
  },

  output: {
    publicPath: `http://localhost:${port}/dist/`,
    filename: '[name].renderer.dev.js',
  },

```

In udpworker/index.ts I try to load using:
```
<script>
      if (typeof process === 'object') {
        const scripts = [];

        if (process.env.NODE_ENV === 'development') {
          // Dynamically insert the DLL script in development env in the
          // renderer process
          scripts.push('../.erb/dll/renderer.dev.dll.js');

          // Dynamically insert the bundled app script in the renderer process
          const port = process.env.PORT || 1212;
          scripts.push(`http://localhost:${port}/dist/workerWindow.dev.js`);
        } else {
          scripts.push('./dist/renderer.prod.js');
        }

        if (scripts.length) {
          document.write(
            scripts
              .map((script) => `<script defer src="${script}"><\/script>`)
              .join('')
          );
        }
      }
</script>
```

I also changed the index.html of the main renderer so it reflect the new name 'mainWindow': `scripts.push(`http://localhost:${port}/dist/mainWindow.renderer.dev.js`);`

When I build I get this error: 

```
yarn run v1.22.10
$ cross-env NODE_ENV=development webpack serve --config ./.erb/configs/webpack.config.renderer.dev.babel.js
(node:4776) UnhandledPromiseRejectionWarning: Error: Cannot find module '../../src/updworker/index.ts'
```
I have tried with index file as .tsx and .js instead, but it is still no able to find it. 

If i move the file to the src folder and rename it to avoid clash with mainWorker, then it can be found. But why does it have to be in the root?

When the program starts I get this error:

`[4853:0124/223847.313987:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js (1)` printing to terminal each second.

In devtools I get this error if I unhide the wondow:

`Not allowed to load local resource: file:///Users/peter/Documents/Electron/DPA-Workbench-React/src/file:/Users/peter/Documents/Electron/DPA-Workbench-React/src/udpworker/index.html`

I can't figure out what's wrong, hope someone experienced with webpack can help me, please.

It would be great if the example rep was updated to reflect current version of ERB.

Thanks for providing such great help through the project.

**Comment by msansoni** [comment]
I've refactored @jp887's example for v2 [here](https://github.com/msansoni/erb-second-renderer-window-example). 

@amilajack happy to PR to examples or for anyone to duplicate for future reference for others.

**Comment by dbvrac** [comment]
@msansoni Nice work! I froze my project at [0.18.1](https://github.com/dbvrac/erb-0.18.1-multiwindow) based on 0.18.1, which is pre-typescript. I'm eager to keep it modern if you're interested in testing (read: $ available) on some in-use non-commercial code.

https://opencollective.com/electron-react-boilerplate-594
