### ISSUE TITLE
Not detecting stdout from child process?

### ISSUE THREAD

**Issue by ShaneC0** [electron-react-boilerplate/electron-react-boilerplate#2751]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

 Should react to data on stdout stream of child process

## Current Behavior

Child process runs but listener does not detect data on stdout stream

## Steps to Reproduce

1. spawn child process: const child = spawn('node', ['./scripts/scrape.js', statusObject.scrapingServer, statusObject.scrapingChannel, statusObject.sendingServer, statusObject.sendingChannel]);

2. Listen for data on stdout: child.stdout.on('data', (data) => {
                       setStatusLine(`${data}`);
                       console.log(statusLine);
               });

## Possible Solution (Not obligatory)

Something with environment variables possibly? This works on a project with webpack + react + electron from scratch.

## Context

When a submit button is pressed on a form it spawns a child process with args from the form. Sets state based on output from the child process in real time. Haven't made any changes to boilerplate after cloning.

## Your Environment

- Node version : 15.7.0
- electron-react-boilerplate version or branch : current version
- Operating System and version : Arch linux 5.10.10-arch1-1
- Link to your project :

**Comment by FlavienFe** [comment]
Why is this closed, I have the exact same problem in 2023
