### ISSUE TITLE
How can I add my app to your website showcase?

### ISSUE THREAD

**Issue by pavlobu** [electron-react-boilerplate/electron-react-boilerplate#2774]
## Summary

Hello. Thank you very much for this project. 🙏 I used electron-react-boilerplate
 to create https://deskreen.com
It got very much attention during month since first release. I wanted it to be included in:
https://electron-react-boilerplate.js.org/docs/app-showcase

But I can't find how to submit it.
How can I add Deskreen to your website showcase?

Cheers,
Paul

**Comment by alexdanilowicz** [comment]
There's a repo for the website, check out: https://github.com/electron-react-boilerplate/site/blob/master/docs/app-showcase.md. I imagine you can submit a PR to have it added.

This is the repo for the boilerplate itself.
