### ISSUE TITLE
require native node modules use node-loader error

### ISSUE THREAD

**Issue by hxkuc** [electron-react-boilerplate/electron-react-boilerplate#2775]
## Prerequisites
```
module: {
    rules: [
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
          },
        },
      },
      {
        test: /\.node$/,
        loader: 'node-loader',
      }
    ],
  },
```

- [*] Using yarn
- [*] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [*] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [*] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [*] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

require('./doctorNative.node') path is correct

## Current Behavior

Uncaught Error: node-loader:
Error: The specified module could not be found.
D:\User\Desktop\doctor\src/http://localhost:1212/dist/5465b0d54fcf3487cbdae5b0bf3c4768.node
    at ./node_modules/doctor-native/build/Release/doctorNative.node (doctorNative.node:6)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at ./node_modules/doctor-native/index.js (index.js:1)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at ./src/containers/Index/index.tsx (renderer.dev.js:2547)
    at Module.options.factory (react refresh:6)

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by mithusingh32** [comment]
Does this happen after running `yarn package` ?
How are you building your native node addon?
