### ISSUE TITLE
router does not work.

### ISSUE THREAD

**Issue by ivanjeremic** [electron-react-boilerplate/electron-react-boilerplate#2776]
First I recommend adding at least 2 views in the boilerplate example so we can see that the router works, second, the current latest boilerplate has some issues I don't know exactly what it is but I use recoil js and Chakra-ui both have a provider who we need to use to wrap the whole app if I add new routers and navigate to them it simply does not work and the app breaks.

**Comment by ivanjeremic** [comment]
@amilajack just tried on a fresh install same result, the router does not work properly. If you have any problems I can upload an repo but it would not make much sense since it is the unchanged repo only 1 route is added.

**Comment by czubik8805** [comment]
I have the same problem, did you solve it?

**Comment by ivanjeremic** [comment]
> I have the same problem, did you solve it?

I moved to electron-forge with React [LINK](https://www.electronforge.io/guides/framework-integration/react-with-typescript)
I use `MemoryRouter` instead of `BrowserRouter` all you need to to is to import it stead of `BrowserRouter` and use it 
```
import {
  MemoryRouter,
  Switch,
  Route,
  Link
} from "react-router-dom";
```

**Comment by czubik8805** [comment]
it works great thank you very much!
