### ISSUE TITLE
cannot publish release in github actions

### ISSUE THREAD

**Issue by RobinlinGit** [electron-react-boilerplate/electron-react-boilerplate#2783]
## 

I have no idea how to modify the workflow file to make the publishing release work correctly.
here is my workflow file:
publish.yml

> name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          yarn install

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.FINDX_TOKEN }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --win --linux

and error log:

<details>
<summary>and the error log</summary>
yarn run v1.22.10
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.9.1
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=D:\a\findX\findX\src
$ D:\a\findX\findX\node_modules\.bin\cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
[webpack-cli] Compilation finished
asset renderer.dev.dll.js 17.1 MiB [compared for emit] (name: renderer)
6265 modules

WARNING in ./node_modules/electron-debug/index.js 108:45-58
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[3]

WARNING in ./node_modules/electron-debug/index.js 109:61-74
Critical dependency: the request of a dependency is an expression
 @ dll renderer renderer[3]

webpack 5.5.1 compiled with 2 warnings in 14999 ms
Done in 26.23s.
yarn run v1.22.10
$ concurrently "yarn build:main" "yarn build:renderer"
[0] $ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.main.prod.babel.js
[1] $ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.renderer.prod.babel.js
[0] [webpack-cli] Compilation finished
[0] asset ./src/main.prod.js 691 KiB [emitted] [minimized] (name: main) 1 related asset
[0] 681 modules
[0] webpack 5.5.1 compiled successfully in 18387 ms
[0] yarn build:main exited with code 0
[1] [webpack-cli] Compilation finished
[1] asset renderer.prod.js 505 KiB [emitted] [minimized] (name: main) 1 related asset
[1] orphan modules 1.33 MiB [orphan] 447 modules
[1] runtime modules 931 bytes 4 modules
[1] modules by path ./node_modules/core-js/ 488 KiB 554 modules
[1] modules by path ./node_modules/@material-ui/ 192 KiB 30 modules
[1] modules by path ./node_modules/@babel/runtime/helpers/ 9.91 KiB 4 modules
[1] modules by path ./node_modules/prop-types/ 2.58 KiB 3 modules
[1] modules by path ./node_modules/react/ 6.48 KiB 2 modules
[1] modules by path ./node_modules/react-dom/ 119 KiB 2 modules
[1] modules by path ./node_modules/scheduler/ 4.91 KiB 2 modules
[1] modules by path ./node_modules/react-router/ 10.7 KiB 2 modules
[1] modules by path ./node_modules/react-is/ 2.69 KiB
[1]   ./node_modules/react-is/index.js 196 bytes [built] [code generated]
[1]   ./node_modules/react-is/cjs/react-is.production.min.js 2.49 KiB [built] [code generated]
[1] 5 modules
[1] webpack 5.5.1 compiled successfully in 18864 ms
[1] yarn build:renderer exited with code 0
Done in 23.60s.
yarn run v1.22.10
$ D:\a\findX\findX\node_modules\.bin\electron-builder --publish always --win --linux
  • electron-builder  version=22.9.1 os=10.0.17763
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=linux arch=x64 electron=11.0.1 appOutDir=release\linux-unpacked
  • scheduling remote build  target=appImage arch=x64
  • packaging       platform=win32 arch=x64 electron=11.0.1 appOutDir=release\win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v11.0.1/electron-v11.0.1-win32-x64.zip size=78 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v11.0.1/electron-v11.0.1-win32-x64.zip duration=1.34s
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1g3pad0": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  ⨯ Env WIN_CSC_LINK is not correct, cannot resolve: D:\a\findX\findX not a file
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1g3pad0": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1g3pad0": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1g3pad0": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.  
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1. 
</details>

**Comment by balsigergil** [comment]
What's the content of your `package.json` file ?
Where do you want to publish ? On GitHub ? If so, did you correctly set the `GH_TOKEN` or `GITHUB_TOKEN` in the repo secrets ?

**Comment by RobinlinGit** [comment]
This is the content of package.json file. And this is the first time that I use github CI. I have set a GH_token in the repo secrets, but it doesn't work.
<details>
  <summary>package.json</summary>

  ```{
  "name": "findX",
  "productName": "findX",
  "description": "findX is a software that helps you manage computer files better, it's built on electron-react-boilerplate",
  "scripts": {
    "build": "concurrently \"yarn build:main\" \"yarn build:renderer\"",
    "build:main": "cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.main.prod.babel.js",
    "build:renderer": "cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.renderer.prod.babel.js",
    "rebuild": "electron-rebuild --parallel --types prod,dev,optional --module-dir src",
    "lint": "cross-env NODE_ENV=development eslint . --cache --ext .js,.jsx,.ts,.tsx",
    "package": "yarn build && electron-builder build --publish never",
    "postinstall": "node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock",
    "start": "node -r @babel/register ./.erb/scripts/CheckPortInUse.js && cross-env yarn start:renderer",
    "start:main": "cross-env NODE_ENV=development electron -r ./.erb/scripts/BabelRegister ./src/main.dev.ts",
    "start:renderer": "cross-env NODE_ENV=development webpack serve --config ./.erb/configs/webpack.config.renderer.dev.babel.js",
    "test": "jest"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": [
      "cross-env NODE_ENV=development eslint --cache"
    ],
    "{*.json,.{babelrc,eslintrc,prettierrc}}": [
      "prettier --ignore-path .eslintignore --parser json --write"
    ],
    "*.{css,scss}": [
      "prettier --ignore-path .eslintignore --single-quote --write"
    ],
    "*.{html,md,yml}": [
      "prettier --ignore-path .eslintignore --single-quote --write"
    ]
  },
  "build": {
    "productName": "findX",
    "appId": "org.erb.ElectronReact",
    "files": [
      "dist/",
      "node_modules/",
      "index.html",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],
    "afterSign": ".erb/scripts/Notarize.js",
    "mac": {
      "target": [
        "dmg"
      ],
      "type": "distribution",
      "hardenedRuntime": true,
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.plist",
      "gatekeeperAssess": false
    },
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "win": {
      "target": [
        "nsis"
      ]
    },
    "linux": {
      "target": [
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "app": "src",
      "buildResources": "assets",
      "output": "release"
    },
    "extraResources": [
      "./assets/**"
    ],
    "publish": {
      "provider": "github",
      "owner": "RobinlinGit",
      "repo": "findX",
      "private": true
    }
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/RobinlinGit/findX.git"
  },
  "author": {
    "name": "lzh",
    "email": "robinlin163@163.com"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/RobinlinGit/findX/issues"
  },
  "keywords": [
    "electron",
    "boilerplate",
    "react",
    "typescript",
    "ts",
    "sass",
    "webpack",
    "hot",
    "reload"
  ],
  "homepage": "https://github.com/RobinlinGit/findX",
  "jest": {
    "testURL": "http://localhost/",
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/.erb/mocks/fileMock.js",
      "\\.(css|less|sass|scss)$": "identity-obj-proxy"
    },
    "moduleFileExtensions": [
      "js",
      "jsx",
      "ts",
      "tsx",
      "json"
    ],
    "moduleDirectories": [
      "node_modules",
      "src/node_modules"
    ],
    "setupFiles": [
      "./.erb/scripts/CheckBuildsExist.js"
    ]
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-proposal-class-properties": "^7.12.1",
    "@babel/plugin-proposal-decorators": "^7.12.1",
    "@babel/plugin-proposal-do-expressions": "^7.12.1",
    "@babel/plugin-proposal-export-default-from": "^7.12.1",
    "@babel/plugin-proposal-export-namespace-from": "^7.12.1",
    "@babel/plugin-proposal-function-bind": "^7.12.1",
    "@babel/plugin-proposal-function-sent": "^7.12.1",
    "@babel/plugin-proposal-json-strings": "^7.12.1",
    "@babel/plugin-proposal-logical-assignment-operators": "^7.12.1",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.12.1",
    "@babel/plugin-proposal-optional-chaining": "^7.12.7",
    "@babel/plugin-proposal-pipeline-operator": "^7.12.1",
    "@babel/plugin-proposal-throw-expressions": "^7.12.1",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-syntax-import-meta": "^7.10.4",
    "@babel/plugin-transform-react-constant-elements": "^7.12.1",
    "@babel/plugin-transform-react-inline-elements": "^7.12.1",
    "@babel/plugin-transform-runtime": "^7.12.1",
    "@babel/preset-env": "^7.12.7",
    "@babel/preset-react": "^7.12.7",
    "@babel/preset-typescript": "^7.12.7",
    "@babel/register": "^7.12.1",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
    "@teamsupercell/typings-for-css-modules-loader": "^2.4.0",
    "@testing-library/jest-dom": "^5.11.6",
    "@testing-library/react": "^11.2.2",
    "@types/enzyme": "^3.10.5",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/history": "4.7.6",
    "@types/jest": "^26.0.15",
    "@types/node": "14.14.10",
    "@types/react": "^16.9.44",
    "@types/react-dom": "^16.9.9",
    "@types/react-router-dom": "^5.1.6",
    "@types/react-test-renderer": "^16.9.3",
    "@types/webpack-env": "^1.15.2",
    "@typescript-eslint/eslint-plugin": "^4.8.1",
    "@typescript-eslint/parser": "^4.8.1",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.1.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-dev-expression": "^0.2.2",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
    "browserslist-config-erb": "^0.0.1",
    "chalk": "^4.1.0",
    "concurrently": "^5.3.0",
    "core-js": "^3.6.5",
    "cross-env": "^7.0.2",
    "css-loader": "^5.0.1",
    "css-minimizer-webpack-plugin": "^1.1.5",
    "detect-port": "^1.3.0",
    "electron": "^11.0.1",
    "electron-builder": "^22.3.6",
    "electron-devtools-installer": "^3.1.1",
    "electron-notarize": "^1.0.0",
    "electron-rebuild": "^2.3.2",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.3",
    "enzyme-to-json": "^3.5.0",
    "eslint": "^7.5.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-airbnb-typescript": "^12.0.0",
    "eslint-config-erb": "^2.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-import-resolver-webpack": "^0.13.0",
    "eslint-plugin-compat": "^3.8.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jest": "^24.1.3",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^4.0.8",
    "file-loader": "^6.0.0",
    "husky": "^4.2.5",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.1.0",
    "lint-staged": "^10.2.11",
    "mini-css-extract-plugin": "^1.3.1",
    "node-sass": "^5.0.0",
    "opencollective-postinstall": "^2.0.3",
    "prettier": "^2.0.5",
    "react-refresh": "^0.9.0",
    "react-test-renderer": "^17.0.1",
    "rimraf": "^3.0.0",
    "sass-loader": "^10.1.0",
    "style-loader": "^2.0.0",
    "terser-webpack-plugin": "^5.0.3",
    "typescript": "^4.0.5",
    "url-loader": "^4.1.0",
    "webpack": "^5.5.1",
    "webpack-bundle-analyzer": "^4.1.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^5.4.0",
    "yarn-deduplicate": "^3.1.0"
  },
  "dependencies": {
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/styles": "^4.11.3",
    "electron-debug": "^3.1.0",
    "electron-log": "^4.2.4",
    "electron-updater": "^4.3.4",
    "history": "^5.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "regenerator-runtime": "^0.13.5",
    "source-map-support": "^0.5.19",
    "tinycolor2": "^1.4.2"
  },
  "devEngines": {
    "node": ">=10.x",
    "npm": ">=6.x",
    "yarn": ">=1.21.3"
  },
  "collective": {
    "url": "https://opencollective.com/electron-react-boilerplate-594"
  },
  "browserslist": [],
  "prettier": {
    "overrides": [
      {
        "files": [
          ".prettierrc",
          ".babelrc",
          ".eslintrc"
        ],
        "options": {
          "parser": "json"
        }
      }
    ],
    "singleQuote": true
  },
  "renovate": {
    "extends": [
      "bliss"
    ],
    "baseBranches": [
      "next"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  }
}```
</details>

**Comment by balsigergil** [comment]
Are you signing your packaged app ? I see in the log `Env WIN_CSC_LINK is not correct`. If you are signing, try to add the path to the certificate in the repo secrets as `WIN_CSC_LINK` and not as `CSC_LINK`.
