### ISSUE TITLE
After package scss files are not loaded

### ISSUE THREAD

**Issue by rendomnet** [electron-react-boilerplate/electron-react-boilerplate#2787]
When I use `npm start`. Styles are loaded correctly.
But when I run` npm package ` it looks like `App.global.scss` is not loaded.

**Comment by balsigergil** [comment]
Hello, 
can you please provide more information about the issue. I tried to package with a `App.global.scss` and it seems to work fine.
Are you sure the scss file is imported in a JS file to be packaged with webpack like it is in [`App.tsx`](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/3cdcbaf873690189a501fd388b5456d229ea17be/src/App.tsx#L4) but with the scss extension?

**Comment by songyuc** [comment]
It seems the current version of ERB doesn't support `.scss`.

**Comment by Rami-Sabbagh** [comment]
The `webpack.renderer.prod` is not setup to load CSS modules properly...
I had to copy the style rules from the `dev` config, into the `prod` one, and replace the `styleloader` with the css plugin used
