### ISSUE TITLE
Update from node-sass to dart-sass

### ISSUE THREAD

**Issue by Atulin** [electron-react-boilerplate/electron-react-boilerplate#2796]
`node-sass` [has been deprecated](https://sass-lang.com/blog/libsass-is-deprecated) since October 2020. The one and only current implementation of SASS is `dart-sass`.

And yet, in `package.json` we can see `"node-sass": "^5.0.0",`, which causes no end of issues, like the inability to use CSS native `min()`, `max()` and `clamp()` functions, because the compiler complains about not being able to mix `px` and `%`.

**Comment by codingedgar** [comment]
I was about to open an issue for this one, is there a reason why this was closed? @amilajack
