### ISSUE TITLE
Whether the current version of ERB support global `scss` style file? 

### ISSUE THREAD

**Issue by songyuc** [electron-react-boilerplate/electron-react-boilerplate#2800]
## Summary

Hi, guys,
I am starting my program using ERB,
and am wondering whether the current version of ERB support global `scss` style file?
Is there any steps I should take to realize this feature?

Your answer or guide will be appreciated!

**Comment by amilajack** [comment]
Renaming `App.global.css` to `App.global.scss` should work.

**Comment by songyuc** [comment]
Hi, @amilajack , it works.
Thanks sincerely for your answer!
