### ISSUE TITLE
White screen in package build. How to proceed? 

### ISSUE THREAD

**Issue by alexbrul** [electron-react-boilerplate/electron-react-boilerplate#2808]
## Summary

I'm getting white screen on Release, but it works in developer mode with yarn start.

Mac os big sur. 

I have a couple typescript errors. Could this be the reason? I tried switching to HashRouter, but that doesn't work.

edit:
Tried running DEBUG_PROD=true yarn build && DEBUG_PROD=true yarn start
and it still also works.. 

Also tried doing a fresh install, and that version has no problems building, so the problem is on my side..

Any advice?

What files should I look through and what should I look for? Is there any files I can upload here? Thank you!

**Comment by asgeo1** [comment]
I'm having a 'white screen of death' issue with mine too.

If you can inspect the console, you'll be able to get the error message.

On OSX, I found some of the other methods like adding flags etc didn't work. But I was able to get to the console using these steps:

 1. `open /Applications/Whatever.app --args --remote-debugging-port=8315`
 2. Visit http://localhost:8315 and then click on the link

give that a try

**Comment by jfilter** [comment]
1. https://electron-react-boilerplate.js.org/docs/packaging/#debugging-the-production-build
 
```bash
yarn cross-env DEBUG_PROD=true yarn package
```

2. Open Dev Console and check for errors ;)
