### ISSUE TITLE
webpack problems to execute npm install?

### ISSUE THREAD

**Issue by oliver021** [electron-react-boilerplate/electron-react-boilerplate#2809]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: post-io@undefined
npm ERR! Found: webpack@5.5.1
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.5.1" from the root project
npm ERR!   peer webpack@">=4.43.0 <6.0.0" from @pmmmwh/react-refresh-webpack-plugin@0.4.3
npm ERR!   node_modules/@pmmmwh/react-refresh-webpack-plugin
npm ERR!     dev @pmmmwh/react-refresh-webpack-plugin@"^0.4.3" from the root project
npm ERR!   1 more (webpack-dev-server)

**Comment by SiyanH** [comment]
Use `yarn` instead as mentioned in README will resolve this issue.

**Comment by oliver021** [comment]
Hello thanks for the help, but out of curiosity I would like to know if there is any special reason for this incompatibility with npm?

**Comment by SiyanH** [comment]
> Hello thanks for the help, but out of curiosity I would like to know if there is any special reason for this incompatibility with npm?

Sorry, I don't know the particular reason either but I guess it's because `yarn` handles dependencies better for this boilerplate project.

**Comment by star-scraper** [comment]
Yarn handles workspaces where as NPM doesn't.  If you notice the project has two directories with a package.json file with dependencies listed in both, this is where Yarn shines and can keep dependancies organized between the two and prevent package collisions when one dir requires ver1.0 and the other ver1.1

See [](https://classic.yarnpkg.com/en/docs/workspaces/ )for more detail
