### ISSUE TITLE
Add note in the docs for why the nodeIntegration can not work in producion build

### ISSUE THREAD

**Issue by angelinimattia** [electron-react-boilerplate/electron-react-boilerplate#2843]
I had an issue that others has having with this like of code in the main render :
` mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('icon.png'),
    webPreferences:
      (process.env.NODE_ENV === 'development' ||
        process.env.E2E_BUILD === 'true') &&
      process.env.ERB_SECURE !== 'true'
        ? {
            nodeIntegration: true,
          }
        : {
            preload: path.join(__dirname, 'dist/renderer.prod.js'),
          },
  });`

that seem to not include nodeIntegration in some cases

has they have provide a solution here: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2434#issuecomment-610387812

that is only to replace the webPreference with this:
`  mainWindow = new BrowserWindow({
    show: false,
    width: 1024,
    height: 728,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      nodeIntegration: true,
    },
  });`

That said I would advise to add some notes in the documentation in the packaging section about that the issue to load the render.prod.js in the production build can be due tho this.

**Comment by amilajack** [comment]
Good callout, this should be documented. Adding to v3

**Comment by amilajack** [comment]
Fixed in v3
