### ISSUE TITLE
Github Actions doesn't work well when *.d.ts is ignored in .gitignore

### ISSUE THREAD

**Issue by shensven** [electron-react-boilerplate/electron-react-boilerplate#2847]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Steps to Reproduce

When I initialize a project from this repo, it works fine on my local machine, when I push my code to Github, Github Actions doesn't work.

see here
https://github.com/shensven/winstagram_98/actions/runs/770356499
https://github.com/shensven/winstagram_98/actions/runs/770484784

## Possible Solution (Not obligatory)
Remove  `*.css.d.ts` `*.sass.d.ts` `*.scss.d.ts` from the `.gitignore` file

## Your Environment

- Node version : 12.22.1
- electron-react-boilerplate version or branch : 509d2ac5841967c5480dea768071a9239f27c6b7
- Operating System and version : macOS 11.2.3 (20D91)
- Link to your project : https://github.com/shensven/winstagram_98

**Comment by chwancc** [comment]
same question.
typings-for-css-modules-loader cause it,many issues point it.

**Comment by amilajack** [comment]
Latest erb is using `@teamsupercell/typings-for-css-modules-loader`. Is that the dependency you're using?
