### ISSUE TITLE
Prod app (appImage) won't load preload script, dev app won't open if context isolation is enabled.

### ISSUE THREAD

**Issue by Mike-Mp** [electron-react-boilerplate/electron-react-boilerplate#2849]
## Prerequisites

- [x ] Using yarn
- [x ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

The app runs as expected using "yarn start".

App configuration that works using "yarn start" (I realize this isn't the correct and secure way to do it):

main.dev.ts:

`mainWindow = new BrowserWindow({
    show: false,
    width: 960,
    height: 600,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      nodeIntegration: true,
      preload: path.join(__dirname, './preload.js'),
      // enableRemoteModule: true,
      contextIsolation: false,
    },
  });`

preload.js:

`const { ipcRenderer } = require('electron');

window.ipcRenderer = ipcRenderer;`

Inside my react components, I can access ipcRenderer through window.

## Current Behavior

After packaging the appImage using this script:

""debugprod": "cross-env DEBUG_PROD=true yarn package-linux"
"package-linux": "rm -rf ./src/node_modules && yarn build && electron-builder build --linux"

I get these errors in the console:

![errors](https://user-images.githubusercontent.com/53409373/115732999-261dba80-a391-11eb-8f49-ba3f9ebdd552.png)

I then changed my code as follows:

`mainWindow = new BrowserWindow({
    show: false,
    width: 960,
    height: 600,
    icon: getAssetPath('icon.png'),
    webPreferences: {
      nodeIntegration: false,
      preload: path.join(__dirname, './preload.js'),
      // enableRemoteModule: true,
      contextIsolation: true,
    },
  });`

Now with "yarn start" and "yarn debugprod" , the app is blank and I get "process is not defined" errors in index.html.

Changing preload.js to:

`const { contextBridge, ipcRenderer } = require('electron');

 
contextBridge.exposeInMainWorld('api', {
   request: (signal, data) =>
     ipcRenderer.send(signal, {
       data,
     }),
   onResponse: (signal, fn) => {
     // Deliberately strip event as it includes `sender`
     ipcRenderer.on(signal, (event, ...args) => fn(...args));
   },
   process,
 });`

Makes the app not open at all.

## Context

I'm a beginner in electron, react and programming in general. The goal of the project is to make a simple youtube downloader, where using ytdl-core I download the highest audio and video and combine the two streams in one using ffmpeg-static. The .mp4 is placed in the user's Downloads folder. 

## Your Environment

- Node version : v14.15.0
- electron-react-boilerplate version or branch : main
- Operating System and version : Ubuntu 18.04
- Link to your project : https://github.com/Mike-Mp/electron-youtube-downloader

**Comment by GhaithAlHallak8** [comment]
did you find any solution?

**Comment by Mike-Mp** [comment]
> did you find any solution?

No...

**Comment by Mike-Mp** [comment]
Is it possible to preload process? Am I not supposed to "yarn start" with nodeIntegration: false and contextIsolation: true?

**Comment by apteryxf** [comment]
In my case, I needed to edit `package.json` file like this. My build target was macOS.
```
  "build": {
    "productName": "ElectronReact",
    "appId": "org.erb.ElectronReact",
    "files": [
      "dist/",
      "node_modules/",
      "index.html",
      "preload.js", // added
```

**Comment by Mike-Mp** [comment]
> In my case, I needed to edit `package.json` file like this. My build target was macOS.
> 
> ```
>   "build": {
>     "productName": "ElectronReact",
>     "appId": "org.erb.ElectronReact",
>     "files": [
>       "dist/",
>       "node_modules/",
>       "index.html",
>       "preload.js", // added
> ```

If I enable contextIsolation I get the "process is not defined" error at index.html. I need to get through that first.

**Comment by apteryxf** [comment]
This boilerplate uses Electron version 11.0.1. [The default value of contextIsolation option is `false` in this version](https://github.com/electron/electron/blob/v11.0.1/docs/api/browser-window.md) and [became `true` from v12.0.0](https://www.electronjs.org/blog/electron-12-0).
I think you can't use this boilerplate with `contextIsolation: true` until PR # 2875  is merged.
