### ISSUE TITLE
Router doesn't work

### ISSUE THREAD

**Issue by Zockedidock** [electron-react-boilerplate/electron-react-boilerplate#2850]
## Summary

I don't understand how this Router works. When I click on a `<Link>`, `<NavLink>` or `<a>`, nothing happens and when I reload the electron window I just get a black screen and the console says: 
`[4904:0422/233251.239:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js (1)`

I'm new to Electron but I used React with `BrowserRouter` before and I never got this error. Sorry if this is obvious to you but I don't know how to fix this error. Help would be appreciated.

**Comment by whoisdominic** [comment]
I am new too would love to see this answered

**Comment by mlnchk** [comment]
@Zockedidock BrowserRouter doesn't work in electron if you use `file://` protocol for your renderer.

You should use [HashRouter](https://reactrouter.com/web/api/HashRouter) or [MemoryRouter](https://reactrouter.com/web/api/MemoryRouter) instead.

**Comment by dvdprr6** [comment]
@Zockedidock  Can you provide a little more details of what you are trying to do? For example how are you defining history and how are you using the Route component?

I am using `connected-react-router` to properly route my components. `yarn add connected-react-router`. Details here: https://www.npmjs.com/package/connected-react-router you would need to add redux to your dependencies

For history I am using createHashHistory like this -> `const history = createHashHistory()` and I  include it in my ConnectedRouter component:

```JavaScript
      <Provider store={store}>
        <ConnectedRouter history={history}>
          <Switch>
            <Route exact path={'/'} component={Home}/>
            <Route path={'/dashboard'} component={DashboardPage} />
            <Route path={'/profile'} component={ProfilePage} />
            <Route path={'/settings'} component={SettingsPage} />
          </Switch>
        </ConnectedRouter>
      </Provider>
```
