### ISSUE TITLE
Tailwind CSS

### ISSUE THREAD

**Issue by whoisdominic** [electron-react-boilerplate/electron-react-boilerplate#2851]
## Summary

Hello 👋🏾 , I am new to electron along with this boilerplate and I am trying to use tailwind as a CSS framework but I can't figure out where to put the Craco scripts.

I've tried to use this guide, as it is for Tailwind and create-react-app but I don't know what to do about the scripts
https://tailwindcss.com/docs/guides/create-react-app#install-and-configure-craco

If anyone has successfully used Tailwind with this boilerplate and could point me in the right direction that'd be amazing.

Any help would be appreciated! Looking forward to building with this boilerplate!

Cheers

**Comment by clemclx** [comment]
Hey 👋🏾

I faced the same issue, when I wanted to use TailwindCSS with ERB.
I found this great article that made me on the good way and it's fully working : [https://rodpadev.medium.com/add-tailwind-css-to-the-popular-electron-react-boilerplate-erb-f1286b5b04f](url)

Hope it helps

**Comment by waptik** [comment]
> Hey 👋🏾
> 
> I faced the same issue, when I wanted to use TailwindCSS with ERB.
> I found this great article that made me on the good way and it's fully working : [Add Tailwind CSS to the popular Electron React Boilerplate (ERB)](https://rodpadev.medium.com/add-tailwind-css-to-the-popular-electron-react-boilerplate-erb-f1286b5b04f)
> 
> Hope it helps

Thanks! This workaround worked!!!

**Comment by whoisdominic** [comment]
Omg thanks so much!!! I'll try this !

**Comment by whoisdominic** [comment]
Worked for me thanks a bunch

**Comment by sepehr09** [comment]
I have problem in production.
this solution not work when packaging.
I also set this in `webpack.config.main.prod.babel`:

```js
 module: {
    rules: [
      {
        test: /.s?css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              // `./dist` can't be inerhited for publicPath for styles. Otherwise generated paths will be ./dist/dist
              publicPath: './',
            },
          },
          'css-loader',
          'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [require('tailwindcss'), require('autoprefixer')],
              },
            },
          },
        ],
      },
      // // Less
      {
        test: /\.less$/,
        use: [
          {
            loader: 'style-loader',
          },
          'css-loader',
          'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [require('tailwindcss'), require('autoprefixer')],
              },
            },
          },
          {
            loader: 'less-loader',
            options: {
              lessOptions: {
                javascriptEnabled: true,
              },
            },
          },
        ],
      },
      // WOFF Font
   // ... etc
    ]
```

any idea?
