### ISSUE TITLE
Why isn't .css working (instead of .global.css)

### ISSUE THREAD

**Issue by Shaddwo** [electron-react-boilerplate/electron-react-boilerplate#2855]
## Summary

I'm new to React and I'm trying out React with Electron with this boilerplate.
In React (`create-react-app`) when I put `import App.css` at the top of the code the styles from the CSS file get imported

but in this boilerplate
`import ./App.css`
![image](https://user-images.githubusercontent.com/72974062/115959184-9e6ab400-a528-11eb-9073-fd16191672d7.png)

`import ./App.global.css`
![image](https://user-images.githubusercontent.com/72974062/115959207-ba6e5580-a528-11eb-977a-0f3d5643491b.png)

How do I fix? (I may have deleted some files to clean up the workspace, but nothing in the `.erb` folder.

(Sorry if this is a bad question with an obvious fix by the way)

Edit: yes, i did rename the css files

**Comment by jaywhen** [comment]
Hi! I think you can have a look at this [https://electron-react-boilerplate.js.org/docs/styling](https://electron-react-boilerplate.js.org/docs/styling)
