### ISSUE TITLE
cannot integrate redux-toolkit, and redux-persist

### ISSUE THREAD

**Issue by JavoxirNazarov** [electron-react-boilerplate/electron-react-boilerplate#2859]
redux/index.ts

import {  configureStore } from '@reduxjs/toolkit'
import { persistStore, persistReducer } from 'redux-persist'
import createElectronStorage from "redux-persist-electron-storage";
import userSlice from './slices/userSlice';

const persistConfig = {
  key: 'root',
  storage: createElectronStorage()
}

const persistedReducer = persistReducer(persistConfig, userSlice)

export const store = configureStore({
  reducer: {
    userState: persistedReducer
  }
})

export type RootState = ReturnType<typeof store.getState>

export const persistor = persistStore(store);

========

index.js

import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { persistor, store } from './redux';
import App from './App';

render(
  <Provider store={store}>
    <PersistGate loading={null} persistor={persistor}>
    <App />
    </PersistGate>
  </Provider>,
  document.getElementById('root')
);

**Comment by amilajack** [comment]
Please as a more specific question

**Comment by mabdullahadeel** [comment]
Facing the same issue as well.

I am using redux-toolkit for state management and redux-persist to persist some data using `localforage`. But when implemented with ERB, it gives errors about calling `useSelector` and `useDispatch` hook wrong when everything is working smooth in the browser.

@amilajack Any Solution to this problem?

Here are some extra details 👇

Any component I try to use my state from redux store, It give gives the following error.

![image](https://user-images.githubusercontent.com/64294045/117304135-d82bab00-ae96-11eb-8867-38f202084936.png)

Here is the example, I have an array of posts that is stored in the state.

On my posts page, I need to show these posts, so I am doing the following 👇

```js
import {useSelector} from 'react-redux';
import {selectPosts} from '../{path to my reducer}' // The reducer is based on the concepts of redux-toolkit

// selectPosts is a function that return posts array ==> []

const PostPage = () => {
   const posts = useSelector(selectPosts);
}
```  

That is where I am getting that `invalid hooks` call error.

###NOTE
I have not implemented 'redux-presist` as of when that above picture was taken. But I tried implementing it and it seems to be also giving some errors related to `invalid hooks` call.

Thank you in advance!

**Comment by mabdullahadeel** [comment]
@JavoxirNazarov 
## Here is the solution (at least this worked for me 👇)

So It looks like this appears because of installing redux and dependencies in the wrong `node_modules` i-e wrong `package.json`

Try uninstalling the `redux-toolkit` and `react-redux` from the `./src/package.json` and make sure that `redux` dependencies are installed in the `package.json` which is in the root directory.

Hope this helps.
