### ISSUE TITLE
CSS Support For Existing Codebases 👩‍💻

### ISSUE THREAD

**Issue by mabdullahadeel** [electron-react-boilerplate/electron-react-boilerplate#2864]
Hey there 🙋‍♂️
I don't know if it's already a feature but it would be cool to have CSS support by default. I have gone through the styling portion of the documentation [here](https://electron-react-boilerplate.js.org/docs/styling) but could not find the solution.

Here is my use case. I have a web app that I want to wrap in electron. The codebase is already pretty large and styled with css. There is no way I can rewrite it to scss or something. If there is a way to make CSS work with ERB, please let me know.

Thanks 🙋‍♂️

**Comment by amilajack** [comment]
You should be able to import css files. Try renaming `App.global.scss` to `App.global.scss`
