### ISSUE TITLE
Unable to install on mac m1

### ISSUE THREAD

**Issue by theolouvel** [electron-react-boilerplate/electron-react-boilerplate#2867]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Be able to install the dependencies and run the project 🙃

## Current Behavior

I'm using yarn and getting a ton of errors... I've included the stack trace down below, hopefully this will help!

## Steps to Reproduce

1. Clone the project on an m1 machine
2. `yarn`
3. Hit your head against the wall 😬

[error.txt](https://github.com/electron-react-boilerplate/electron-react-boilerplate/files/6449575/error.txt)

## Possible Solution (Not obligatory)

I think it might have something to do with the fact I'm using a mac m1, although I'm using this boilerplate for the first time.

## Context

I made no change whatsoever to the boilerplate.

## Your Environment

- Node version : v16.0.0
- electron-react-boilerplate version or branch : 2.3.0
- Operating System and version : Mac os 11.3.1 
- Link to your project : #didntgetthatfar

**Comment by pedroresende** [comment]
Try to use node 15.14.0 and it works perfectly

**Comment by theolouvel** [comment]
It actually does work, thx! :)

**Comment by 4everTonyStark** [comment]
I thought I would add to this issue in case anyone is still experiencing this when trying to use a native version of Node.  I fixed this by installing node-gyp via `npm install -g node-gyp`, deleting the node_modules folder, and then running `npm install --build-from-source` rather than simply `npm install`.  I am using the latest LTS version of Node built for Arm, which is 16.13.1 at the moment.
