### ISSUE TITLE
How to open a new window opening a path in the router

### ISSUE THREAD

**Issue by saifis** [electron-react-boilerplate/electron-react-boilerplate#2869]
## Summary

I want to open a second window that calls on a path in the react-router

So I have a button in my app, and I want to open up the '/settings' route in another window

```
        <Switch>
          <Route path="/" component={MainWindow} />
          <Route path="/settings" component={SettingsWindow} />
        </Switch>

```

in the main.dev.ts

I have

```
      const SettingsWindow = new BrowserWindow({ width: 800, height: 600 });
      SettingsWindow.loadURL(   );
```

But I'm not sure what to put in the loadURL to achieve what I want, is this the right way to do this at all? I can for the time being just open it in the main window but I want to have a different window because I want to have a view of the main while playing around with other things on another window

**Comment by livthomas** [comment]
I was dealing with the same issue and I solved it by copying both `index.html` and its renderer script files. So now, I have `model.html`, `webpack.config.renderer.modal.dev.babel.js`, and `webpack.config.renderer.modal.prod.babel.js` files which are responsible for rendering the modal window.

This is how I create a new `BrowserWindow` instance for this modal window:

```ts
export function createModalWindow(mainWindow: BrowserWindow) {
  const modalWindow = new BrowserWindow({
    parent: mainWindow,
    modal: true,
    show: false,
    width: 480,
    height: 320,
    webPreferences: {
      enableRemoteModule: true,
      nodeIntegration: true,
    },
    backgroundColor: '#ffffff',
  });

  modalWindow.loadFile(`modal.html`);

  modalWindow.setMenuBarVisibility(false);

  modalWindow.on('close', event => {
    event.preventDefault();

    modalWindow.hide();
  });

  return modalWindow;
}
```

**Comment by saifis** [comment]
Yeah I did think about that but, it would mean I'd need to continually make more and more of those per new window doesn't it?

**Comment by livthomas** [comment]
No, I just have a single `BrowserWindow` instance to handle all modals in the application. It has its own routes set up and it is hidden by default as you can see in the code above. And whenever it is open, I navigate it to the right route:

```ts
export function openModalWindow(modalWindow: BrowserWindow, modalPage: ModalPage) {
  modalWindow.webContents.send(IpcChannel.NavigateModal, modalPage);
  modalWindow.show();
}
```

And the main modal component looks like this:

```ts
export function Modal() {
  const history = useHistory();

  useEffect(() => {
    const listener = (_: IpcRendererEvent, path: string) => {
      history.push(path);
    };
    ipcRenderer.on(IpcChannel.NavigateModal, listener);
    return () => {
      ipcRenderer.off(IpcChannel.NavigateModal, listener);
    };
  }, [history]);

  return (
    <Switch>
      <Route path={ModalPage.CashBoxDeposit} component={PageCashBoxDeposit} />
      <Route path={ModalPage.CashBoxStatus} component={PageCashBoxStatus} />
      <Route path={ModalPage.CashBoxWithdrawal} component={PageCashBoxWithdrawal} />
    </Switch>
  );
}
```

**Comment by saifis** [comment]
I see, thanks I'll try it on my end

**Comment by youngtype** [comment]
Cannot find name 'IpcChannel'

**Comment by youngtype** [comment]
Please show me an example, I don’t understand how it works.

**Comment by livthomas** [comment]
`IpcChannel` is just my set of constants for various IPC channels. You can use strings directly. The same goes for `ModalPage`.

**Comment by youngtype** [comment]
> `IpcChannel` is just my set of constants for various IPC channels. You can use strings directly. The same goes for `ModalPage`.

Cannot read property 'push' of undefined

`export default function App() {
  const history = useHistory();

  React.useEffect(() => {
    const listener = (_: IpcRendererEvent, path: string) => {
      history.push(path);
    };
    ipcRenderer.on('navigate-modal', listener);
    return () => {
      ipcRenderer.off('navigate-modal', listener);
    };
  }, [history]);

  return (
    <Router>
      <Switch>
        <Route path="/modal" component={Modal} />
        <Route path="/" component={Hello} />
      </Switch>
    </Router>
  );
}`

**Comment by Unforgiven-wanda** [comment]
@livthomas Could I please trouble you for a minimal example repo?

**Comment by xiajingren** [comment]
Is there a complete example
