### ISSUE TITLE
Add react and react-dom to externals

### ISSUE THREAD

**Issue by manoj-mass** [electron-react-boilerplate/electron-react-boilerplate#2870]
Hi,

## Summary

Im trying to add react and react-dom to externals in webpack.config.base.js
` externals: {
    react: 'React',
    'react-dom': 'ReactDOM'
  }`

so that i can reuse some alrady build coponents throught a library.
I added reactjs libs and other react component lib i mentioned to in index.

` <script src="https://unpkg.com/react@16.10.2/umd/react.production.min.js"></script>
    <script src="https://unpkg.com/react-dom@16.10.2/umd/react-dom.production.min.js"></script>`

Yet getting following error when start. Any  idea why I cant inject react and react-dom to index directly without bundling through package.json

![image](https://user-images.githubusercontent.com/26952806/118449769-1768c000-b711-11eb-84d1-a6657fdbe0f0.png)

**Comment by amilajack** [comment]
This boilerplate does not support this pattern so this is out of scope for this boilerplate. You can get more guidance from the webpack community.
