### ISSUE TITLE
Redux?

### ISSUE THREAD

**Issue by youngtype** [electron-react-boilerplate/electron-react-boilerplate#2871]
How do I add redux? Is there some kind of documentation or example? Help me please

**Comment by youngtype** [comment]
Help please, i'm newbie

**Comment by amilajack** [comment]
We currently have no guides for this. In the meantime you can see the diff from https://github.com/electron-react-boilerplate/electron-react-boilerplate/compare/v1.4.0...v2.0.0 that dropped redux (amongst other changes). Applying the inverse changes should add redux support to your project.
