### ISSUE TITLE
Publish Workflow fails, even on a fresh clone

### ISSUE THREAD

**Issue by GitMazzone** [electron-react-boilerplate/electron-react-boilerplate#2872]
## Prerequisites

- [X] Using yarn
- [X] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)

## Expected Behavior

On a push to the master branch, the Github Actions "Publish" workflow should pass.

## Current Behavior

After pushing to master, the default "Test" worflow passes, but "Publish" fails with the error  
```
/Users/runner/work/project_name/project_name not a file
error Command failed with exit code 1.
```

## Steps to Reproduce

[See the issue here](https://github.com/GitMazzone/bptest/runs/2605010489?check_suite_focus=true)  

1. Freshly clone the electron-react-boilerplate using:  
```
git clone --depth=1 \
  https://github.com/electron-react-boilerplate/electron-react-boilerplate \
  your-project-name
```

2. `cd` into the project, push it to GitHub ([here](https://github.com/GitMazzone/bptest))

3. This automatically triggers GitHub Actions workflows "Test" and "Publish" by default.

4. See [failure](https://github.com/GitMazzone/bptest/runs/2605010489?check_suite_focus=true).

## Possible Solution (Not obligatory)

N/A

## Context

I made no changes to anything. This is a fresh clone.  

I have never used GitHub Actions and am new to CI, so I fully suspect this could be something you're just expected to know how to resolve by doing basic setup, but I do feel it should be explained in the docs somewhere. I've read through all of [your docs on CI](https://electron-react-boilerplate.js.org/docs/ci) and there's nothing about any additional setup being required. 

## Your Environment

- Node version : `v15.6.0`
- electron-react-boilerplate version or branch : `master` (latest)
- Operating System and version : `Win 10`
- Link to your project : https://github.com/GitMazzone/bptest

**Comment by amilajack** [comment]
I'm not able to repro this:
<img width="1230" alt="Screen Shot 2021-05-19 at 7 08 57 PM" src="https://user-images.githubusercontent.com/6374832/118908171-b9390a00-b8d5-11eb-8a7d-8e28e3ec6409.png">

**Comment by GitMazzone** [comment]
@amilajack Am I required to set up any kind of auth keys/tokens with GitHub to use Actions, or is there any other setup you've done? If you try this in an incognito tab with a brand new GitHub account, can you repro it?
Like I said, it seems very likely it's just some missing setup step that most folks who are familiar with CI are used to.

**Comment by ian-bateman** [comment]
Also experiencing this issue. +1

**Comment by amilajack** [comment]
Ah I see now. I think the issue might be that you haven't yet changed the publish configs:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/package.json#L89-L90

Ideally this would work out of the box. I'll followup with a fix for this

**Comment by ian-bateman** [comment]
I tried changing the config to match my repo where you pointed out, but still seeing the same issue / it's failing at the same step.
https://github.com/freebothq/xyzxyz/runs/2713230567?check_suite_focus=true#step:8:97 
https://github.com/freebothq/xyzxyz/blob/master/package.json#L89

**Comment by amilajack** [comment]
Try making the following changes to `publish.yml`:
```diff
       - name: Publish releases
         env:
           # These values are used for auto updates signing
-          APPLE_ID: ${{ secrets.APPLE_ID }}
-          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
-          CSC_LINK: ${{ secrets.CSC_LINK }}
-          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
```

**Comment by ian-bateman** [comment]
Ah yep that fixed it! Will post up a PR for this (with doc changes) tonight / tomorrow morning! Much thanks!! :)
