### ISSUE TITLE
get error from @types/react-router-dom/index.d.ts when execute 'tsc  *.ts'

### ISSUE THREAD

**Issue by youngbody** [electron-react-boilerplate/electron-react-boilerplate#2873]
For below line  in @types/react-router-dom/index.d.ts
  ` import * as H from 'history;`
I find it will load '/home/ubuntu/Desktop/electron-react-boilerplate/node_modules/history/index',
but not '/home/ubuntu/Desktop/electron-react-boilerplate/node_modules/@types/history/index'.
I
It will report below error when execute 'tsc *.ts'
Namespace '"/home/ubuntu/Desktop/electron-react-boilerplate/node_modules/history/index"' has no exported member 'LocationState'

**Comment by amilajack** [comment]
You're probably on `history@5.x.x`
