### ISSUE TITLE
audit reports 4195 high vulnerabilities

### ISSUE THREAD

**Issue by SonataOto** [electron-react-boilerplate/electron-react-boilerplate#2876]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)

## Expected Behavior

- No or few low or moderate errors.

## Current Behavior

- Shows 4309 reporting errors in total.

## Steps to Reproduce

1. git clone --depth 1 --single-branch https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name

2. cd your-project-name

3. yarn

4. yarn audit

## Context

Just following same install steps.

## Your Environment

- Node version : 14.16.1
- electron-react-boilerplate version or branch : 2.3.0 / main
- Operating System and version : Windows 10, 1909
- Link to your project : X

**Comment by amilajack** [comment]
Please run this against `next` branch, which will be released soon as `v3.0.0`

**Comment by SonataOto** [comment]
> Please run this against `next` branch, which will be released soon as `v3.0.0`

Seems OK. I'll wait the release for use in distribution. 
Will I have a problem using it in production?
![5IDrfSs](https://user-images.githubusercontent.com/79670543/118706355-45b8cf00-b7e7-11eb-896d-342257e26884.png)
