### ISSUE TITLE
How does the project uses eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by codingedgar** [electron-react-boilerplate/electron-react-boilerplate#2884]
## Summary

I see the project has `eslint-plugin-react-hooks` and other plugins, but i don't understand how those are used if not imported in the `.eslintrc` file?

**Comment by jacobweber** [comment]
I believe it's part of the "erb" that .eslintrc.js extends: https://github.com/electron-react-boilerplate/eslint-config-erb

**Comment by codingedgar** [comment]
> I believe it's part of the "erb" that .eslintrc.js extends: https://github.com/electron-react-boilerplate/eslint-config-erb

thank you! you're right 👍
