### ISSUE TITLE
Project is running at http://localhost:1212 but can't be accessed by a browser

### ISSUE THREAD

**Issue by PrexCoder** [electron-react-boilerplate/electron-react-boilerplate#2885]
## Summary

Hi, quick question how can I enable the get also for external sources, for example if I access the localhost I will get cannot get /, but in order to implement MSAL, I'm in need of a way to solve this problem, my question is how :| ? I've been searching for a decent solution ended up with no positive results

![image](https://user-images.githubusercontent.com/72302739/120085451-81517400-c0d8-11eb-98d4-a46e6d3da0f6.png)

**Comment by PrexCoder** [comment]
Nevermind the question was stupid, and also for people having such problem you just have to add Electron Provider for msal and in the app add msal://redirect as an endpoint for desktop app's and the problem should be solved.

**Comment by dugiwarc** [comment]
How do you do that ?

**Comment by PrexCoder** [comment]
Magic :)) mind to tell me what you did not understand or what are you trying to achieve ?
