### ISSUE TITLE
Error : C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

### ISSUE THREAD

**Issue by Sanan4li** [electron-react-boilerplate/electron-react-boilerplate#2886]
I cloned the repo and while installing all the dependencies I am facing this error.
C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Is there anything else I need to install before cloning the repo?

**Comment by praveen-zluri** [comment]
Is there any update on this issue?
