### ISSUE TITLE
Is chrome devtools debugger supposed to be this slow on electron 11?

### ISSUE THREAD

**Issue by dyuan-boxlabs** [electron-react-boilerplate/electron-react-boilerplate#2893]
electron 11.4.7
webpack 5.38.1
webpack-cli 4.7.0
webpack-dev-server 3.11.2

Setting break points and stepping through code lags noticeably, using the console to evaluate getState() and other passed in variables take a long time to display the result, and the same if you're using watch expression. On windows our packaged bundle exe size is 110mb, so it doesn't seem like there's that much bloat in there.

Just wondering if anyone else has this issue or if anyone has any suggestions on how to speed up debugging?

**Comment by tegmos** [comment]
I am having the same problem currently. But I think I have figured out the cause. My bundle size is > 216k lines. I think this large file size is causing Chrome devtools to choke. But I'm not webpack-savvy enough to figure out how split things and load correctly yet.

I added this to the webpack.config.renderer.dev.babel:

`
	optimization: {
		splitChunks: {
			chunks: "all",
		},
	},`

But I get an error: "Conflict: Multiple chunks emit assets to the same filename renderer.dev.js"

Still trying to figure it out.
