### ISSUE TITLE
Why does the component not re-render after receiving an ipcRenderer event

### ISSUE THREAD

**Issue by mpowell90** [electron-react-boilerplate/electron-react-boilerplate#2895]
## Summary
Hey ERB team, I've used your fantastic boilerplate as a starter. My basic application relies on events being sent to the ipcRenderer to update state. When an event is received, it will update state on first render, counter 0 -> 1, but not update component state after that. What's interesting is when I make changes during development the counter does increment, which I assume is because the hot-reloader causes the component to re-render but retains the current state. Clearly, there is some interplay between electron and react that I don't understand.

## Example
I've condensed the issue down to the following:

```javascript
/* App.tsx */
// Other imports here...
import React, { useEffect, useState } from 'react';
import { ipcRenderer } from 'electron';

const Hello = () => {
  const [counter, setCounter] = useState(0);
  useEffect(() => {
    ipcRenderer.on('ping', () => {
      console.log(counter);
      setCounter(counter + 1);
    })
    return () => {
      ipcRenderer.removeAllListeners('ping');
    };
  }, []);

  return (
    <div>
      <h1>Counter: {counter}</h1>
    </div>
  )
}

// Hello is loaded below in the Route...

/* main.dev.ts */
// Nothing changed above this point in the file...
mainWindow.webContents.on('did-finish-load', () => {
  // window initialisation logic here...
  setInterval(() => {
    mainWindow.webContents.send('ping');
  }, 1000);
})

```

Can anyone shine a light on why the component doesn't re-render?
Is there a solution to this issue?
thank you

**Comment by brandonhee** [comment]
Your problem has to do with how the listener function gets compiled. The value of counter is 0 when the listener is created, and because the listener is within the electron framework, instead of React, the counter value does not refer to the actual state variable.

You can use useRef instead of useState, or get rid of the dependencies in useEffect so that the listener gets recreated with the latest value of counter.

Using useRef

``` js
const Hello = () => {
  const countRef = useRef(0);
  useEffect(() => {
    ipcRenderer.on('ping', () => {
      console.log(countRef.current);
      countRef.current++;
    })
    return () => {
      ipcRenderer.removeAllListeners('ping');
    };
  }, []);

  return (
    <div>
      <h1>Counter: {counter}</h1>
    </div>
  )
}
```

Remove useEffect dependencies

``` js
const Hello = () => {
  const [counter, setCounter] = useState(0);
  useEffect(() => {
    ipcRenderer.on('ping', () => {
      console.log(counter);
      setCounter(counter + 1);
    })
    return () => {
      ipcRenderer.removeAllListeners('ping');
    };
  }); // remove []

  return (
    <div>
      <h1>Counter: {counter}</h1>
    </div>
  )
}
```

**Comment by ncfausti** [comment]
Thank you! Great explanation

**Comment by gsongsong** [comment]
Does this work if `ipcRenderer.on` uses a named function as a callback?
