### ISSUE TITLE
How to prevent the installation of the default electronic react boilerplate program

### ISSUE THREAD

**Issue by SuperLeven** [electron-react-boilerplate/electron-react-boilerplate#2898]
Every time after installing the program, electronic-react-boilerplate will be installed by default. I use yarn package to package the project.

**Comment by YessineAmor** [comment]
Same issue here, this only happens to me on Windows though. Works fine on macOS Big Sur

**Comment by madebyAyan** [comment]
I've got the same issue here on windows. Is there a workaround or a way to avoid this?

**Comment by mkilp** [comment]
Is there no fix for this?
