### ISSUE TITLE
Upgrade electron to v13 in boilerplate?

### ISSUE THREAD

**Issue by takanuva15** [electron-react-boilerplate/electron-react-boilerplate#2899]
## Summary

Hi, thanks for creating this awesome boilerplate! I am trying it now for the first time, but I just realized that it is still using the older electron v11 rather than the newer electron v13 which has been adopted by the [electron-quick-start-typescript](https://github.com/electron/electron-quick-start-typescript) repo. Can we update the boilerplate to use electron v13? (Or if there's something preventing us from doing it, what is the reason?)

**Comment by takanuva15** [comment]
Lol just saw that some upgrades were being implemented in PR #2875 (I didn't realize there was that much complication involved in upgrading the boilerplate). I'll see how that pans out (though an upgrade to v13 still is relevant)

**Comment by amilajack** [comment]
Fixed in #2875
