### ISSUE TITLE
loop in Compiling... when run with yarn start and edit a file

### ISSUE THREAD

**Issue by nedphae** [electron-react-boilerplate/electron-react-boilerplate#2900]
hello, i have updated my electron-react-boilerplate version recently, but when i run yarn start, and edit a source file, the console will print Compiling... and Compiled successfully in loop , like this :

i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...

i chaged webpack config, but just add a less-loader, and a url-loader, the same config in the electron-react-boilerplate ( just  template, not add any code) does not exist this problem

**Comment by nedphae** [comment]
this is a old old issue, see https://github.com/webpack/watchpack/issues/25
add webpack-mild-compile plugin (https://github.com/yessky/webpack-mild-compile) works for me

**Comment by afazzdev** [comment]
> this is a old old issue, see [webpack/watchpack#25](https://github.com/webpack/watchpack/issues/25)
> add webpack-mild-compile plugin (https://github.com/yessky/webpack-mild-compile) works for me

this now works for me..

**Comment by Xinor** [comment]
I had this problem when using tailwind css(with jit) and this worked for me:
https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop

changed from:
```
purge: [
    './src/**/*.{js,jsx,ts,tsx}',
]
```

to:
```
purge: [
    './src/renderer/react/**/*.{js, jsx, ts, tsx}'
]
```
or
```
purge: [
    './src/renderer/**/*.{js, jsx, ts, tsx}'
]

**Comment by yessky** [comment]
> > this is a old old issue, see [webpack/watchpack#25](https://github.com/webpack/watchpack/issues/25)
> > add webpack-mild-compile plugin (https://github.com/yessky/webpack-mild-compile) works for me
> 
> this not works for me..

If you're using webpack 5, try to install the lastest version

**Comment by YungMilky** [comment]
> add webpack-mild-compile plugin (https://github.com/yessky/webpack-mild-compile) works for me

where did you add this code?

**Comment by veici** [comment]
> > this is a old old issue, see [webpack/watchpack#25](https://github.com/webpack/watchpack/issues/25)
> > add webpack-mild-compile plugin (https://github.com/yessky/webpack-mild-compile) works for me
> 
> this not works for me..

this not works for me too...
