### ISSUE TITLE
Problem installing with npm install

### ISSUE THREAD

**Issue by BrendonChirume** [electron-react-boilerplate/electron-react-boilerplate#2903]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: electron-react-boilerplate@undefined
npm ERR! Found: electron@11.0.1
npm ERR! node_modules/electron
npm ERR!   dev electron@"^11.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer electron@"^7.0.0" from browserslist-config-erb@0.0.1
npm ERR! node_modules/browserslist-config-erb
npm ERR!   dev browserslist-config-erb@"^0.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\QWERTY\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\QWERTY\AppData\Local\npm-cache\_logs\2021-06-13T09_15_21_518Z-debug.log

**Comment by tylercollins590** [comment]
I am having the same issue

**Comment by BrendonChirume** [comment]
I used yarn and it worked

**Comment by mithusingh32** [comment]
Seems like this has been an issue for a while. 

npm, pnpm, and yarn did not work for me. 

Node: 14.17
Fedora 33

**Comment by oggy-kim** [comment]
I have an same issue.
npm, yarn didn't work for me.

Node : 16.3.0
OS: Big Sur 11.4(sillicon Mac)

**Comment by mithusingh32** [comment]
I got it work. 

I had to update yarn and npm and do a fresh clone of the repo.
