### ISSUE TITLE
Suggestion to use HashRouter instead of BrowserRouter

### ISSUE THREAD

**Issue by actualdankcoder** [electron-react-boilerplate/electron-react-boilerplate#2904]
As a  url in this boilerplate corresponds to a file, using HashRouter seems more favourable over BrowserRouter in App.tsx

If I were to use the `exact` attribute in a route inside BrowserRouter

```js
    <BrowserRouter>
      <Route exact path="/settings" component={Settings} />
      <Route exact path="/" component={HomePage} />
    </BrowserRouter>
 ```

then it wouldn't render either of the routes because the actual url would correspond to a file (ie: `src/index.html#/`)

whereas the same would work with the `exact` attrib if we were using HashRouter

```js
    <HashRouter>
      <Route exact path="/settings" component={Settings} />
      <Route exact path="/" component={HomePage} />
    </HashRouter>
 ```

**Comment by asralf90** [comment]
I tried both routing methods but it only works in development and not production. I have tried using` MemoryRouter`, whitelisting the `react-router-dom` in `package.json` under `electronWebpack`, downgrading `react-router-dom` to v4, adding # to `index.html`,  etc. but I still can't render the components. Any suggestions?

**Comment by amilajack** [comment]
We now use MemoryRouter in v3 (#2875)
