### ISSUE TITLE
How to pass command line arguments to app while running from bash.

### ISSUE THREAD

**Issue by Usama-Tahir** [electron-react-boilerplate/electron-react-boilerplate#2905]
## Summary

I am running my app from the command line and want to pass command-line arguments in production build as well as when I am running the app in dev mode. 

Is there a way to achieve this in the current boilerplate?

Thanks.

**Comment by ishitb** [comment]
Hey @Usama-Tahir , I don't think there's anything extra you need to do in respect of the boilerplate. You can simply try using the `exec` function from the `child_process` module by importing it into your react file. You can search for this, there are may articles of how to run shell commands through node.
