### ISSUE TITLE
Disable Prettier?

### ISSUE THREAD

**Issue by jacobweber** [electron-react-boilerplate/electron-react-boilerplate#2906]
## Summary

Is there an easy way to disable Prettier? I can't deal with its constant harping. I don't necessarily want to disable eslint, but they seem to be integrated.

**Comment by C-Hess** [comment]
If you want to disable the ESLint errors but keep the auto-formatting you can add the following to `.eslintrc.js`:

```js
module.exports = {
  // ...
  rules: {
    "prettier/prettier": "off",
    // ...
  },
 // ...
}
```

**Comment by jacobweber** [comment]
Thanks!
