### ISSUE TITLE
Tray icon in production vanishes after 1-5 seconds even though it remains visible in development

### ISSUE THREAD

**Issue by GHOSCHT** [electron-react-boilerplate/electron-react-boilerplate#2908]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

Tray icon remains visible in production after running `yarn package`.

## Current Behavior

Tray icon in production vanishes after 5 seconds or less, even though it permanently exists when running the development build using `yarn start`.

## Steps to Reproduce

1. Implement a simple tray following the [official electron FAQ](https://www.electronjs.org/docs/faq#my-apps-tray-disappeared-after-a-few-minutes) entry for disappearing tray icons
```
import { app, BrowserWindow, shell, Tray } from 'electron';

let tray = null;

const createWindow = async () => {
...  
  tray = new Tray(getAssetPath('icon.png'));
  tray.setTitle('hello world');
...
};
```

2. Run `yarn start` -> Tray shows and stays as long as electron is running

3. Run `yarn package`

4. Start the packed program in ./release/win-unpacked -> Tray shows and disappears after 1-5s

Note: I tried packing the program with devtools enabled, but the console doesn't show anything out of the ordinary. The only messages are the usual "failed to parse SourceMap" warnings.

## Context

I'm trying to write a program that usually sits in the tray and only displays a little window like the Win10 volume control when clicked. Getting the tray to run is therefore an integral part of this project.

## Your Environment

- Node version : v14.5.0
- electron-react-boilerplate version or branch : current main branch
- Operating System and version : Win10 20H2
- Link to my demo project : https://github.com/GHOSCHT/erb-tray-demo

**Comment by Chimildic** [comment]
I have the same. Did you solve this problem?

```js
const { app, Menu, Tray } = require('electron')

const contextMenu = Menu.buildFromTemplate([
    { label: 'Item1', type: 'radio' },
])

let title = 'This is my application.'
let path = 'settings.png'
let tray = null

app.whenReady().then(() => {
  tray = new Tray(path)
  tray.setToolTip(title)
  tray.setContextMenu(contextMenu)
})

```

**Comment by GHOSCHT** [comment]
Unfortunately I didn't. After realizing that the support for this project is pretty much abandoned I threw together [my own boilerplate](https://github.com/GHOSCHT/simple-electron-react-boilerplate), which works flawlessly.
I basically set up electron, webpack, react, etc. using some guides I found on the Internet which did take some time but the result was worth it.

You could just fork my boilerplate or build one for yourself. I did consider using another boilerplate but I didn't finde one that looked easy to use. The current version of my boilerplate does have some security vulnerabilities, but I was able to fix it in my [current project](https://github.com/GHOSCHT/light-control/tree/master/Dashboard) with dependency updates (renovate bot is your friend).
