### ISSUE TITLE
Bug report issue template recommends using 'master' branch when it has been replaced by 'main'

### ISSUE THREAD

**Issue by pjdon** [electron-react-boilerplate/electron-react-boilerplate#2909]
The template for `Issue: Bug report` uses the following line:
```
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
```
Since `master` has been changed to `main` this is no longer correct, there may be value in updating this to prevent confusion for new users.

**Comment by amilajack** [comment]
Fixed in #2875
