### ISSUE TITLE
how do i set Content Security Policy for scripts

### ISSUE THREAD

**Issue by BrendonChirume** [electron-react-boilerplate/electron-react-boilerplate#2913]
i have tried 

` <meta
      http-equiv="Content-Security-Policy"
      content="script-src 'self'; script-src-elem * 'unsafe-inline'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; font-src 'self';"
    />`

**Comment by tjcouch-sil** [comment]
@BrendonChirume it appears you can set the Content Security Policy in [`src/renderer/index.ejs`](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/renderer/index.ejs)! :) The policy ERB provides is listed there already, and you can modify it as desired.
