### ISSUE TITLE
Tailwind CSS configuration

### ISSUE THREAD

**Issue by princejoogie** [electron-react-boilerplate/electron-react-boilerplate#2915]
## Summary

A question was asked in #2851 issue and the resolution to adding tailwindcss for this boilerplate was directed [here](https://rodpadev.medium.com/add-tailwind-css-to-the-popular-electron-react-boilerplate-erb-f1286b5b04f). In that link there's a part where they added some rules in a `webpack.config.renderer.dev.babel.js` file. How or where can i find this `webpack.config.renderer.dev.babel.js` in the boilerplate?

I also tried creating those files and adding the configs stated in the tutorial but I can't seem to make it work

**Comment by ncfausti** [comment]
I was having similar issues with electron-react-boilerplate and tailwindcss.

If you **DO NOT WANT TO CUSTOMIZE TAILWIND**, you can simply run `yarn add tailwindcss`, then at the bottom of **App.global.css** add:
```
@import '~tailwindcss';
``` 
That should be enough to apply default tailwind styles. You use the `~` in the beginning to tell ERB to look in the node_modules as per the instructions found here: [https://electron-react-boilerplate.js.org/docs/styling](https://electron-react-boilerplate.js.org/docs/styling) .

---

If you **DO WANT TO CUSTOMIZE TAILWIND** then do the following:

0. Install `tailwindcss`, `postcss`, `postcss-loader`, and `autoprefixer` as dev devependencies:
```
yarn add --dev tailwindcss postcss postcss-loader autoprefixer
```
or
```
npm intall --save-dev tailwindcss@latest postcss@latest postcss-loader@latest autoprefixer@latest
```
1. Add the following snippet after the `css-loader` entry in the first test for global css files ( /\.global\.css$/ ) in **webpack.config.renderer.dev.babel.js**:
```
{
    loader: 'postcss-loader',
    options: {
      postcssOptions: {
        plugins:
          [
            require('tailwindcss'),
            require('autoprefixer'),
          ]
      }
    }
}
```
2. Create **postcss.config.js** in the **.erb/configs** folder and add this to it:
```
const tailwindcss = require('tailwindcss');
const autoprefixer = require('autoprefixer');

module.exports = {
  plugins: [tailwindcss, autoprefixer],
};
```
3. Add the following at the end of your **App.global.css** file:
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

If you want to customize tailwind, create a **tailwind.config.js** file in the **root folder of your project** and place this inside of it:
```
import colors from 'tailwindcss/colors';

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        sky: colors.sky,
        cyan: colors.cyan,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

To test that tailwind is properly going through postcss-loader, create a new component and use this as the html that's returned:

```
<div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
  <div class="relative py-3 sm:max-w-xl sm:mx-auto">
    <div class="absolute inset-0 bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl"></div>
    <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
      <div class="max-w-md mx-auto">
        <div>
          <img src="/img/logo.svg" class="h-7 sm:h-8" />
        </div>
        <div class="divide-y divide-gray-200">
          <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
            <p>An advanced online playground for Tailwind CSS, including support for things like:</p>
            <ul class="list-disc space-y-2">
              <li class="flex items-start">
                <span class="h-6 flex items-center sm:h-7">
                  <svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                </span>
                <p class="ml-2">
                  Customizing your
                  <code class="text-sm font-bold text-gray-900">tailwind.config.js</code> file
                </p>
              </li>
              <li class="flex items-start">
                <span class="h-6 flex items-center sm:h-7">
                  <svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                </span>
                <p class="ml-2">
                  Extracting classes with
                  <code class="text-sm font-bold text-gray-900">@apply</code>
                </p>
              </li>
              <li class="flex items-start">
                <span class="h-6 flex items-center sm:h-7">
                  <svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                  </svg>
                </span>
                <p class="ml-2">Code completion with instant preview</p>
              </li>
            </ul>
            <p>Perfect for learning how the framework works, prototyping a new idea, or creating a demo to share online.</p>
          </div>
          <div class="pt-6 text-base leading-6 font-bold sm:text-lg sm:leading-7">
            <p>Want to dig deeper into Tailwind?</p>
            <p>
              <a href="https://tailwindcss.com/docs" class="text-cyan-600 hover:text-cyan-700"> Read the docs &rarr; </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

If all goes well, you should see a couple of cards, one on top of the other, where one is slightly at an angle AND the background color of one of the cards will be a light blue (using the customization in the **tailwind.config.js** file. Delete that customization and implement your own there as needed.

**Comment by FritzTheDev** [comment]
@ncfausti I've given up on projects before because of issues configuring TailwindCSS with electron. Doing this now... if it works, I owe you a beer. Thanks!

**Comment by princejoogie** [comment]
@ncfausti thanks you so much for this, it was a petty mistake from me I thought the `webpack.config.renderer.dev.babel.js` was located in the root directory which I couldn't find. all along it was in the `.erb` directory, Thanks!! works perfectly

**Comment by ncfausti** [comment]
> @ncfausti thanks you so much for this, it was a petty mistake from me I thought the `webpack.config.renderer.dev.babel.js` was located in the root directory which I couldn't find. all along it was in the `.erb` directory, Thanks!! works perfectly

Glad I could help! I know how difficult it is to get it right and spent way longer than I should've getting started with tailwind.

**Comment by ncfausti** [comment]
> @ncfausti I've given up on projects before because of issues configuring TailwindCSS with electron. Doing this now... if it works, I owe you a beer. Thanks!
> 
> Edit: Like a charm! Thanks

Awesome! Glad I could help.

**Comment by Deep-Codes** [comment]
> I was having similar issues with electron-react-boilerplate and tailwindcss.
> 
> If you **DO NOT WANT TO CUSTOMIZE TAILWIND**, you can simply run `yarn add tailwindcss`, then at the bottom of **App.global.css** add:
> 
> ```
> @import '~tailwindcss';
> ```
> 
> That should be enough to apply default tailwind styles. You use the `~` in the beginning to tell ERB to look in the node_modules as per the instructions found here: https://electron-react-boilerplate.js.org/docs/styling .
> 
> If you **DO WANT TO CUSTOMIZE TAILWIND** then do the following:
> 
> 1. Install `tailwindcss`, `postcss`, `postcss-loader`, and `autoprefixer` as dev devependencies:
> 
> ```
> yarn add --dev tailwindcss postcss postcss-loader autoprefixer
> ```
> 
> or
> 
> ```
> npm install --save-dev tailwindcss@latest postcss@latest postcss-loader@latest autoprefixer@latest
> ```
> 
> 1. Add the following snippet after the `css-loader` entry in the first test for global css files ( /.global.css$/ ) in **webpack.config.renderer.dev.babel.js** AND also after `sass-loader` entry in **webpack.config.renderer.prod.babel.js** (for packaging):
> 
> ```
> {
>     loader: 'postcss-loader',
>     options: {
>       postcssOptions: {
>         plugins:
>           [
>             require('tailwindcss'),
>             require('autoprefixer'),
>           ]
>       }
>     }
> }
> ```
> 
> 1. Create **postcss.config.js** in the **.erb/configs** folder and add this to it:
> 
> ```
> const tailwindcss = require('tailwindcss');
> const autoprefixer = require('autoprefixer');
> 
> module.exports = {
>   plugins: [tailwindcss, autoprefixer],
> };
> ```
> 
> 1. Add the following at the end of your **App.global.css** file:
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> If you want to customize tailwind, create a **tailwind.config.js** file in the **ROOT FOLDER of your project** and place this inside of it:
> 
> ```
> import colors from 'tailwindcss/colors';
> 
> module.exports = {
>   purge: [],
>   darkMode: false, // or 'media' or 'class'
>   theme: {
>     extend: {
>       colors: {
>         sky: colors.sky,
>         cyan: colors.cyan,
>       },
>     },
>   },
>   variants: {
>     extend: {},
>   },
>   plugins: [],
> };
> ```
> 
> To test that tailwind is properly going through postcss-loader, create a new component and use this as the html that's returned:
> 
> ```
> <div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
>   <div class="relative py-3 sm:max-w-xl sm:mx-auto">
>     <div class="absolute inset-0 bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl"></div>
>     <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
>       <div class="max-w-md mx-auto">
>         <div>
>           <img src="/img/logo.svg" class="h-7 sm:h-8" />
>         </div>
>         <div class="divide-y divide-gray-200">
>           <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
>             <p>An advanced online playground for Tailwind CSS, including support for things like:</p>
>             <ul class="list-disc space-y-2">
>               <li class="flex items-start">
>                 <span class="h-6 flex items-center sm:h-7">
>                   <svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
>                     <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
>                   </svg>
>                 </span>
>                 <p class="ml-2">
>                   Customizing your
>                   <code class="text-sm font-bold text-gray-900">tailwind.config.js</code> file
>                 </p>
>               </li>
>               <li class="flex items-start">
>                 <span class="h-6 flex items-center sm:h-7">
>                   <svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
>                     <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
>                   </svg>
>                 </span>
>                 <p class="ml-2">
>                   Extracting classes with
>                   <code class="text-sm font-bold text-gray-900">@apply</code>
>                 </p>
>               </li>
>               <li class="flex items-start">
>                 <span class="h-6 flex items-center sm:h-7">
>                   <svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
>                     <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
>                   </svg>
>                 </span>
>                 <p class="ml-2">Code completion with instant preview</p>
>               </li>
>             </ul>
>             <p>Perfect for learning how the framework works, prototyping a new idea, or creating a demo to share online.</p>
>           </div>
>           <div class="pt-6 text-base leading-6 font-bold sm:text-lg sm:leading-7">
>             <p>Want to dig deeper into Tailwind?</p>
>             <p>
>               <a href="https://tailwindcss.com/docs" class="text-cyan-600 hover:text-cyan-700"> Read the docs &rarr; </a>
>             </p>
>           </div>
>         </div>
>       </div>
>     </div>
>   </div>
> </div>
> ```
> 
> If all goes well, you should see a couple of cards, one on top of the other, where one is slightly at an angle AND the background color of one of the cards will be a light blue (using the customization in the **tailwind.config.js** file. Delete that customization and implement your own there as needed.

Thanks a ton ❤️

**Comment by myhendry** [comment]
@mike-apiabroad same here. i followed the steps but I'm not seeing any styles applied

it seems some files have been renamed in the latest version webpack.config.renderer.dev.ts, webpack.config.renderer.prod.ts and I don't see a app.global.css file. there's only a app.css file

**Comment by xrebelox** [comment]
@myhendry @mike-apiabroad I created a new [issue](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3023), this is 100% related to version 4.3.0 as I managed to get it working on version 4.2.0.

So until we have a real solution the only way to fix this is to utilize version 4.2.0 instead of 4.3.0.

**Comment by myhendry** [comment]
@xrebelox Thanks pal! Im using release-v4.3.1 and it's not working as well

**Comment by amilajack** [comment]
See this working example: https://github.com/amilajack/erb-tailwind-example
Update the docs: https://electron-react-boilerplate.js.org/docs/styling/#tailwind-integration

**Comment by mike-apiabroad** [comment]
@amilajack thanks for the update! I would imagine we were all pretty close but got something screwed up with the webpack configs.
