### ISSUE TITLE
ESM-only modules

### ISSUE THREAD

**Issue by erikKeresztes** [electron-react-boilerplate/electron-react-boilerplate#2919]
## Summary

I'm trying to use [lowdb](https://github.com/typicode/lowdb) but it's an ESM package, whenever I start the project I get a webpack error saying

> Must use import to load ES Module: /`...`/src/node_modules/lowdb/lib/index.js
require() of ES modules is not supported.

I tried setting 'module' to 'ES2020' in tsconfig.json and adding '@babel/plugin-transform-modules-commonjs' to the babel.config.js plugins section and the problem still happens.

**Comment by eyesofkids** [comment]
- https://2ality.com/2019/10/hybrid-npm-packages.html
- https://github.com/ArthurGerbelot/stackoverflow-test-es6-module/tree/master/1-npm-package-with-cjs-support

**Comment by eyesofkids** [comment]
lowdb

https://github.com/typicode/lowdb/issues/471#issuecomment-850908461
https://github.com/typicode/lowdb/issues/480

**Comment by JenniferFalkenstein** [comment]
Any updates on this one? I got the same problem 😕
