### ISSUE TITLE
CSS does not apply in DEV mode

### ISSUE THREAD

**Issue by nazarma** [electron-react-boilerplate/electron-react-boilerplate#2922]
## Summary
I am trying to add new .css file to my react component. I done it with a standard way, just on a top of my react component
`import './MyCssFile.css';`

But when I am in debug mode (e.g. via `yarn start`), my css settings are not applied. But everything is fine when I build application in PROD mode. 

Can you please advise how can I enable my custom css files in dev mode?

**Comment by somanei** [comment]
你或许可以试一试在全局样式中导入你的样式文件
![image](https://user-images.githubusercontent.com/54315950/125264374-62303e00-e336-11eb-81b0-153a177d6e97.png)

**Comment by nazarma** [comment]
Hey @somanei , thanks for feedback. Unfortunately, that does not work for some reason. I am blaming Webpack and tried to play with different configurations/parameters inside of `webpack.config.renderor` file, but no luck so far. 

As a workaround I am using `.less` instead of `.css`.

**Comment by amilajack** [comment]
Can't repro
