### ISSUE TITLE
Styling not loading

### ISSUE THREAD

**Issue by Cutewarriorlover** [electron-react-boilerplate/electron-react-boilerplate#2927]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

My CSS loads and gives the element with a `sender` class a red background.

## Current Behavior

My CSS loads, but has a mangled selector, which doesn't select the element.

## Steps to Reproduce

1. Have a SCSS file with a `.sender` selector

2. Launch your app

3. Notice that the resulting selector looks something like this: `.Message__sender__3EAdq`. It doesn't select the element, which has a class of `sender`.

## Context
I was trying to style an element. I added some files, but didn't change anything big.

## Your Environment

- Node version : `v16.2.0`
- electron-react-boilerplate version or branch : `v2.3.0 at master`
- Operating System and version : `Linux Ubuntu 20.04.1 LTS`
- Link to your project : None

**Comment by yeah02** [comment]
Hi!
Isn't a bug. You need import this SCSS to your App.global.css and import the element like a module in your App.js.
