### ISSUE TITLE
It could use fs in 2.0, but not in 3.0.

### ISSUE THREAD

**Issue by torota** [electron-react-boilerplate/electron-react-boilerplate#2938]
I migrated from 2.0 to 3.0.
It could use 'fs' in 2.0, but not in 3.0.
The same goes for fs as well as path .

<--- ERROR LOG --->
ERROR in ./src/renderer/configs/Path.ts 5:11-26
Module not found: Error: Can't resolve 'path' in '/Users/torota/workspace/mls-client-v2/src/renderer/configs'
Did you mean './path'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (/Users/torota/workspace/mls-client-v2/src, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/renderer/services/ConfigReaderServiceImpl.ts 16:0-52 28:52-69
 @ ./src/renderer/pages/welcome/Welcome.tsx 60:0-81 70:22-73
 @ ./src/renderer/App.tsx 8:0-46 26:15-22
 @ ./src/renderer/index.tsx 8:0-24 19:36-39

ERROR in ./src/renderer/services/ConfigReaderServiceImpl.ts 15:0-20
Module not found: Error: Can't resolve 'fs' in '/Users/torota/workspace/mls-client-v2/src/renderer/services'
 @ ./src/renderer/pages/welcome/Welcome.tsx 60:0-81 70:22-73
 @ ./src/renderer/App.tsx 8:0-46 26:15-22
 @ ./src/renderer/index.tsx 8:0-24 19:36-39

----------------------------------------------------

```
import fs from 'fs';
import { LocalConfigType } from 'renderer/types/Type';
import { LOCAL_CONFIG_PATH } from '../configs/Path';

export class ConfigReaderServiceImpl {
  private static instance: ConfigReaderServiceImpl;

  private constructor() {}

  static get getInstance() {
    if (!ConfigReaderServiceImpl.instance) {
      ConfigReaderServiceImpl.instance = new ConfigReaderServiceImpl();
    }
    return this.instance;
  }

  readLocalConfig(): LocalConfigType | undefined {
    try {
      const configJson: LocalConfigType = JSON.parse(
        fs.readFileSync(LOCAL_CONFIG_PATH, 'utf8')
      );
      return configJson;
    } catch (error) {
      console.log(error);
    }
    return undefined;
  }
```

**Comment by amilajack** [comment]
The renderer process has node integration disabled by default. You have two options:

1. [Enable nodeIntegration in the renderer process](https://electron-react-boilerplate.js.org/docs/native-modules#renderer-process-native-modules)
2. Provide a browser polyfill for fs as the error message suggests: https://www.npmjs.com/package/path-browserify
