### ISSUE TITLE
yarn command fails in 3.0.1 on Windows network drives

### ISSUE THREAD

**Issue by denexapp** [electron-react-boilerplate/electron-react-boilerplate#2941]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

`yarn` command completes succesfully.

## Current Behavior

`yarn` command shows an error, looks like it can't create symlinks

## Steps to Reproduce

1. `git clone --depth 1 --branch main https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name`

2. `cd your-project-name`

3. `yarn`

Stacktrace: https://gist.github.com/denexapp/d8d9ba6001d503ad601073f7f9af4dcc

## Possible Solution (Not obligatory)

~~I have no idea how to fix it.~~
Update: `yarn` command should be run in an elevated command line

## Context

I was trying to use this boilerplate. It doenst work.

## Your Environment

- Node version : 14.17.0 LTS
- electron-react-boilerplate version or branch : 3.0.1
- Operating System and version : Windows 10 20H2 19042.1165
- Link to your project : https://github.com/electron-react-boilerplate/electron-react-boilerplate

**Comment by Ze-Liu** [comment]
same issue!!!

**Comment by LarryKlugerDS** [comment]
Didn't work for me either.
Win 10
Node v14.17.5
Yarn 1.22.5

Output is attached. Thank you for your help and time on this, Larry
[log.txt](https://github.com/electron-react-boilerplate/electron-react-boilerplate/files/7005583/log.txt)

**Comment by yeah02** [comment]
Did you `yarn install` ?

**Comment by denexapp** [comment]
`yarn` is an alias for `yarn install` ([yarn docs](https://classic.yarnpkg.com/en/docs/cli/#toc-default-command)). I used `yarn`

**Comment by yeah02** [comment]
But my project doesn't install the dependencies if I don't ask for the explicit command.

Maybe your project is having the same problem?

**Comment by denexapp** [comment]
I'm not sure this is the case, the stacktrace I attached above ([link](https://gist.github.com/denexapp/d8d9ba6001d503ad601073f7f9af4dcc)) shows that it does install dependencies. 

Anyway I will try to use the `yarn install` command and I'll post results here

**Comment by denexapp** [comment]
I've tried to use `yarn install` instead of `yarn`, I've got the same error

**Comment by yeah02** [comment]
I'll try to reproduce your issue.

**Comment by LarryKlugerDS** [comment]
## Regression bug
The [v2.3.0](https://github.com/electron-react-boilerplate/electron-react-boilerplate/releases/tag/v2.3.0) release works fine on Windows, with the exact same setup / environment that fails on v3.0.1

**Comment by denexapp** [comment]
Update: I've found a workaround. `yarn` command should be run in an elevated command line. I've updated the original post

**Comment by amilajack** [comment]
The offending line is https://gist.github.com/denexapp/d8d9ba6001d503ad601073f7f9af4dcc#file-gistfile1-txt-L81

ERB v3.0.0 [requires symlinking node_modules ](https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/561569a9d89ff939b91b5f170007dc11f780d7c5#diff-3955c07d721232220a78804a40c7cfd99b650786a0229c8dac3bf44c3ca3516dR8), which seems to require admin privileges in windows

**Comment by denexapp** [comment]
While I think the best solution is to get rid of symlinks (i.e. tools like create-react-app doesn't require an elevated prompt), I understand that they do exists for a reason.

So my suggestion here is to mention this requirement in the documentation. That _should_ fix the problem.

There may be a slight chance that running `yarn` with an admin rights breaks something in certain scenarios, but I haven't noticed any related errors so far

**Comment by amilajack** [comment]
Does creating a junction fix the problem for you?
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/next/.erb/scripts/link-modules.js#L8

**Comment by LarryKlugerDS** [comment]
Hi @amilajack , Where can I try your fix?
Is there a branch I should clone?
(Or should I monkey patch v3.01 on my machine to test?) 
Thank you for your help, Larry

**Comment by LarryKlugerDS** [comment]
OK, I downloaded the `next` branch using the command
```` 
git clone -b next --single-branch --depth=1   \
  https://github.com/electron-react-boilerplate/electron-react-boilerplate \
  docusign-electron-react-v2
````
Then used commands `yarn` and `yarn start`

✅   Good news: It worked on the C: drive!

❌.  Not as great news: it did not work on a networked drive. (I have a Parallels virtual PC.)

See attached log. Thank you for your help.
 
[fail_log.txt](https://github.com/electron-react-boilerplate/electron-react-boilerplate/files/7020410/fail_log.txt)

**Comment by denexapp** [comment]
Looks like your fix is working: version from the `next ` branch creates symlinks without an elevated prompt, yarn command finishes succesfully

**Comment by LarryKlugerDS** [comment]
@amilajack  -- thank you for your time on this issue. 

As noted above, I also suggest that the right solution is to eliminate the need for a symlink (of any type). 
Using network drives, NFS, etc for development is not uncommon.
Do you concur? Should I file an issue? 

PS, I was a good scout and donated to the project. Thanks again for the great software.

**Comment by amilajack** [comment]
@LarryKlugerDS linking is actually very common amongst package managers and build infrastructure. ERB should be able to symlink without any issues. I'll investigate this further to see how npm does this
