### ISSUE TITLE
production build exe doesn't display content in 2.2.0 version

### ISSUE THREAD

**Issue by new-furry** [electron-react-boilerplate/electron-react-boilerplate#2946]
I have project that was built on 2.2.0 version.
packaged source never display content.
I know this was fixed in higher versions. 
but I would like to fix this issue on current project without update.
any suggestions? thank you.

**Comment by amilajack** [comment]
What's the stacktrace in the devtools when running `DEBUG_PROD=true yarn package`?

**Comment by new-furry** [comment]
thank you for your reply.
I resolved this issue. renderer.prod.js was not able to load because of preload didn't work on production mode.
so I deleted preload. code is like this for webPreferences option.

```
    icon: getAssetPath('icon.png'),
    webPreferences: {
      nodeIntegration: true
    }
```

thank you
