### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in ...

### ISSUE THREAD

**Issue by LarryKlugerDS** [electron-react-boilerplate/electron-react-boilerplate#2949]
## Summary

Trying to use `fs` in the renderer. It worked in an older version of electron/react etc

Now the code 
````
import fs from 'fs'; // fails
````

I updated main.ts to include nodeIntegration:
````
  mainWindow = new BrowserWindow({
....
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      // See https://stackoverflow.com/a/55776662/64904
      nodeIntegration: true, // <--- flag
      nodeIntegrationInWorker: false, // <---  for web workers
    },
  });

````

I've tried solutions from various SO answers but, unfortunately, no success yet.

I did make a donation. Thank you.

**Comment by tsha123** [comment]
let foward [this](https://electron-react-boilerplate.js.org/docs/native-modules)

**Comment by LarryKlugerDS** [comment]
Thank you!

**Comment by supermanklk** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/28639384/154941883-93345f8d-7146-4db0-b711-7db25a9efcd0.png">


change electron-react-boilerplate default config && src/main/main.ts   

end the issue is resolve

**Comment by duongvanchien** [comment]
> let follow [this](https://electron-react-boilerplate.js.org/docs/native-modules)

thanks so much bro
