### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by tsha123** [electron-react-boilerplate/electron-react-boilerplate#2950]
## Summary

I use this template
`yarn start`, `yarn package`,.. everything OK
but when I push my project, and then pull, run `yarn install`, and then ....

> TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (D:\work\UpPos\node_modules\webpack\lib\NormalModule.js:203:10)

old project in local still work, but whenever pull from github and run `yarn install`, I got this error, not only me, my friend too

how can I fix this @@

**Comment by dlamon1** [comment]
I too have received this error. I am reading it may be due to conflicting webpack dependencies. Did you resolve your issue?

**Comment by dlamon1** [comment]
I cannot find the thread I found this in, but it was mentioned somewhere that the issue could be due to Administrative rights in vscode. So far I am still getting this error from vscode terminals -  gitbash/powershell/cmd. I have tried running VScode in admin mode and changed the rules from the command line. When I run from the standalone cmd terminal I do not get this error.

**Comment by tsha123** [comment]
> Try running from outside VScode (I'm assuming you're using VScode). I cannot find the thread I read this in, but it was mentioned somewhere that the issue could be due to Administrative rights in vscode. So far I am still getting this error from vscode terminals - gitbash/powershell/cmd. I have tried running VScode in admin mode and changed the rules from the command line. When I run from the standalone cmd terminal I do not get this error.

I run `yarn start` on windows terminal, not using vs terminals
But when i run on my mac, i didn't get this, don't know why 😂😂

**Comment by rendomnet** [comment]
I have this error too on Windows  node v18.14.2
