### ISSUE TITLE
how to use remote module from electron in a react component

### ISSUE THREAD

**Issue by gaowujian** [electron-react-boilerplate/electron-react-boilerplate#2955]
How do I use the remote module provided by electron to show a dialog?

I have enable the nodeIntegration and remote module in main.ts
```
   webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: true,
      enableRemoteModule: true,
    },
```

but in react component  index.tsx

```
import { remote } from "electron";   
```

doesn't work properly, and cause the error below

```
Module not found: Error: Can't resolve 'fs' in '/home/ubuntu/Desktop/3W6D_AI_VPS/node_modules/electron'
 @ ./src/renderer/Home/index.tsx 25:0-34 124:4-32
 @ ./src/renderer/App.tsx 15:0-26 118:15-19
 @ ./src/renderer/index.tsx 7:0-24 8:41-44

ERROR in ./node_modules/electron/index.js 2:13-28
Module not found: Error: Can't resolve 'path' in '/home/ubuntu/Desktop/3W6D_AI_VPS/node_modules/electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/renderer/Home/index.tsx 25:0-34 124:4-32
 @ ./src/renderer/App.tsx 15:0-26 118:15-19
 @ ./src/renderer/index.tsx 7:0-24 8:41-44

webpack compiled with 2 errors
ℹ ｢wdm｣: Failed to compile.
Not rewriting GET /index.html because the path includes a dot (.) character.
```
** so what is the proper way to import module from electron and do something like open a dialog in a click event in a react component ? **

**Comment by l3alr0g** [comment]
Awesome @phuebner that did the trick :grin: 
I just had to add the corresponding `ipcRenderer.on` calls in my main.ts and now everything just works

**Comment by gaowujian** [comment]
> @gaowujian you should not need to add the electron module to your react .tsx files. The whole point of the contextBridge is to map your node functions (e.g. ipcRenderer ) to the global window object. Therefore in any renderer .tsx file you can simply use `window.electron.ipcRenderer.once('ipc-example', ... );` without needing to import any modules.
> The issue is that typescript does not know about the context bridge. Therefore you need to add a type declaration file that let's typescript know about the additional `electron.ipcRenderer` object that is added to window.
> 
> In it's simplest form this type declaration file could be in a file like `global.d.ts` and look something like this:
> 
> ```ts
> declare global {
>   interface Window {
>     electron: any;
>   }
> }
> export {};
> ```
> 
> But it obviously makes sense if you add a bit more information to your type declaration. For example something like this:
> 
> ```ts
> declare global {
>     interface Window {
>         electron: {
>             ipcRenderer: {
>                 on: (channel: string, listener: (event: Electron.IpcRendererEvent, ...args: any[]) => void) => void;
>             }
>         }
>     }
> }
> export {};
> ```
> 
> adding more information gives you that sweet auto-complete and type-checking benefit of typescript.
> 
> @l3alr0g the contextBridge declaration belongs in the preload.js file, not in a renderer file. You should not need to change anything in the webpack configuration. So it's best if you reset that back to default. You don't need to include electron in the renderer .tsx file. Including electron will give you errors. You also can't use any other node modules in the renderer (such as fs or path). This for sure adds some complexity to a project, but increases the security of the application.
> 
> You can enable the old way of exposing electron to the renderer and integrating node by editing your `webPreferences` inside the `main.ts` file.
> 
> ```ts
>  webPreferences: {
>       nodeIntegration: true,
>       contextIsolation: false,
>       enableRemoteModule: true,
>     },
> ```
> 
> However this may expose you to some risks. Here is some information and warnings about that: [Electron | Remote](https://www.electronjs.org/docs/api/remote)
> 
> I hope this helps.
> 
> Best Regards,
> Patrick

Great response. This way of structure help to code in an easy way. Put the file operation and other back-end operation in main.ts and listen on some events and map the function through preload.js to window object, so the we are able to use these configured function by triggering the events in the render process.

**Comment by karljinang** [comment]
I am not very familiar with typescript and new to electron-react-boilerplate. Thank you in advance for answering my question.

I have a question about the global.d.ts file.

1. **Where do I make this global.d.ts? In src/ folder?**
2. **How do I import Electron.IpcRendererEvent type?**


**What I tried:**

- I created a global.d.ts file in the src/ folder and pasted the code below into the global.d.ts.
> `declare global {
    interface Window {
        electron: {
            ipcRenderer: {
                on: (channel: string, listener: (event: Electron.IpcRendererEvent, ...args: any[]) => void) => void;
            }
        }
    }
}
export {};`

- To get Electron.IpcRendererEvent, I tried importing electron's electron.d.ts in node_modules:

`import Electron from 'electron/electron'`
However typescript is warning me on VSCode that _'/node_modules/electron/electron.d.ts' is not a module_.

What am I getting wrong? Thank you.

**Comment by phuebner** [comment]
Hi @karljinang. The latest version of the boilerplate code has already a working example of this type declaration for the electron context bridge. The following files contain the relevant code: 
| File | Description |
|----|----|
|/src/main/preload.ts   |   File containing the electron contextBridge, which exposes the electron IPC to the renderer. You can find more information about the contextBridge and why it is recommended here: [Electron - Context Isolation](https://www.electronjs.org/zh/docs/latest/tutorial/context-isolation#:~:text=There%20is%20a%20dedicated%20module%20in%20Electron%20to,website%20is%20running%20in.%20API%20%E8%BF%98%E5%8F%AF%E4%BB%A5%E5%83%8F%E4%BB%A5%E5%89%8D%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BB%8E%20window.myAPI%20%E7%BD%91%E7%AB%99%E4%B8%8A%E8%AE%BF%E9%97%AE%E3%80%82). In short: It is allows you to expose only a subset of electrons functionality without the need to have node.js integration enabled. |
|/src/renderer/preload.d.ts | File containing a type declaration that matches the type of the contextBridge that is exposed in *preload.ts*. This is necessary to have proper type checking in the renderer. |
|/src/renderer/index.tsx |  File containing the example code in the renderer. Note that it is not necessary to `import * from 'electron'` in the renderer because the ipc is exposed as part of the DOM Window object. |

I hope this helps you.
