### ISSUE TITLE
Missing lzma-native depedence

### ISSUE THREAD

**Issue by yeah02** [electron-react-boilerplate/electron-react-boilerplate#2956]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Current Behavior

`npm ERR! missing: lzma-native@6.0.1, required by electron-rebuild@2.3.5`

## Steps to Reproduce

1. Add any native dependence to ./build/app

2. So, run `yarn` or `yarn install`

## Possible Solution (Not obligatory)

This seems to be outside the scope of this boilerplate, but I think it can be fixed by adding **lzma-native@^6.0.1** to devDepedencies.

## Your Environment

- Node version : 14.17.3
- electron-react-boilerplate version or branch : 3.0.2
- Operating System and version : Windows 10, latest
- Link to your project :

**Comment by TrumanDu** [comment]
when will it be repaired?

**Comment by pplonski** [comment]
@TrumanDu I got similar error during installation (last week it was working ok). Any idea what can be the cause?

**Comment by TrumanDu** [comment]
@pplonski I guess it’s a resource problem, I can download normally now

**Comment by pplonski** [comment]
@TrumanDu thank you for explaining! It is still not working for me.
