### ISSUE TITLE
Node-fetch not woking with Electron 11, error resp.body.pipe is not a function

### ISSUE THREAD

**Issue by valerxx22** [electron-react-boilerplate/electron-react-boilerplate#2957]
So I am basically trying to use `node-fetch` to download a zip from a URL, but I get this error: `TypeError: res.body.pipe is not a function`

Since I have updated my Electron app version from `"electron": "^8.2.3"` to `"electron": "^11.0.1"`

My download function doesn't seem to work anymore, and I can't understand the problem. Since my app is based on this boilerplate, I tried it on a clean `electron-react-boilerplate` and I have the same error.

My function for doing this image download is below:

```
import React from 'react';
import fetch from 'node-fetch';
import { createWriteStream } from 'fs';

const Hello = () => {
  const onDownload = async () => {
    const { url } = { url: 'https://file-examples-com.github.io/uploads/2017/02/zip_10MB.zip' };

    try {
      const res = await fetch(url);
      const { status } = res;

      if (status === 200) {
        const fileStream = createWriteStream(
          `./downloads/archive.zip`
        );

        res.body.pipe(fileStream);
      } else {
        console.log('error');
      }
      res.body.on('end', () => {
        console.log('end');
      });
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <div>
      <h1>electron-react-boilerplate</h1>
      <div className="Hello">
        <button type="button" onClick={() => onDownload()}>
          Download
        </button>
      </div>
    </div>
  );
};
```

The same function works with no issues on the old electron version, is there something that I'm missing here?

**Comment by ironfinger** [comment]
Why should we use IPC rather than using fetch in thee render process ?
