### ISSUE TITLE
Puppeteer not executing in packaged app

### ISSUE THREAD

**Issue by goodbeysr** [electron-react-boilerplate/electron-react-boilerplate#2959]
I created an app that has a button that triggers a script via IPC, the script is just a nodejs file that calls puppeteer and starts processing. in my local and when I run the app with yarn start it works perfectly and u can see that a browser is running and scrapping is working fine. when I package my app with yarn package --win the app is generated and after clicking on the button nothing happens. The problem is I don't know how to debug the packaged app. In fact, I did run these commands 

`yarn cross-env DEBUG_PROD=true yarn build &&
yarn cross-env DEBUG_PROD=true yarn start`

the app works fine but the MSI file doesn't

![image](https://user-images.githubusercontent.com/22368199/130995416-2fa88ed3-1103-469a-a074-d3192f8d9fea.png)

**Comment by odysseymemoirs** [comment]
its seems to me that problem related to babel and webpack
try to move all puppeteer libs from `/node_modules` to `build/app/node_modules`

1. `npm uninstall puppeteer ...`
2. `cd build/app npm install puppeteer ...`
