### ISSUE TITLE
Using node modules in different js files than the ones from main and renderer processes

### ISSUE THREAD

**Issue by krzysztofMlczk** [electron-react-boilerplate/electron-react-boilerplate#2971]
## Summary
I would like to implement js functions for saving data using nedb-promises package.  I have the following project structure:
```js
src: {
   main: {
      main.ts,
      menu.ts,
      preload.ts,
      utils.ts,
   },
   renderer: {
      components,
      ...
   },
   backend: {
      setup.js,
      ...
   }
}
```

In setup.js file I require the following node modules:
```js
const { app } = require('electron');
const Datastore = require('nedb-promises');
```
But I get the following error (I haven't edited webpack config files - they are the same as in the boilerplate):
`ERROR in ./node_modules/@seald-io/nedb/lib/persistence.js 7:13-28
Module not found: Error: Can't resolve 'path' in '...\node_modules\@seald-io\nedb\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./node_modules/@seald-io/nedb/lib/datastore.js 8:20-47
 @ ./node_modules/@seald-io/nedb/index.js 1:18-44
 @ ./node_modules/nedb-promises/src/Datastore.js 4:24-49
 @ ./node_modules/nedb-promises/index.js 1:0-43
 @ ./src/backend/database/setup.js 7:16-40
 @ ./src/backend/middleware/users.js 8:0-40 22:19-32 50:19-34
 @ ./src/renderer/components/DBtest.jsx 9:0-55
 @ ./src/renderer/App.jsx 9:0-41 43:38-44
 @ ./src/renderer/index.jsx 7:0-24 8:41-44

ERROR in ./node_modules/electron/index.js 1:11-24
Module not found: Error: Can't resolve 'fs' in '...\node_modules\electron'
 @ ./src/backend/database/setup.js 4:15-34
 @ ./src/backend/middleware/users.js 8:0-40 22:19-32 50:19-34
 @ ./src/renderer/components/DBtest.jsx 9:0-55
 @ ./src/renderer/App.jsx 9:0-41 43:38-44
 @ ./src/renderer/index.jsx 7:0-24 8:41-44

ERROR in ./node_modules/electron/index.js 2:13-28
Module not found: Error: Can't resolve 'path' in '...\node_modules\electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/backend/database/setup.js 4:15-34
 @ ./src/backend/middleware/users.js 8:0-40 22:19-32 50:19-34
 @ ./src/renderer/components/DBtest.jsx 9:0-55
 @ ./src/renderer/App.jsx 9:0-41 43:38-44
 @ ./src/renderer/index.jsx 7:0-24 8:41-44`

How can I modify the boilerplate so that I can use node modules (without errors) in the js files located in the 'backend' directory?
Please help me I have tried many solutions (including the ones proposed by the error prompt), neither of them worked. 

Thanks :)

**Comment by Rafatcb** [comment]
Have you tried to add the following:
```javascript
fallback: {
  fs: false,
  path: false,
},
```

to the `resolve` property in `webpack.config.base.js`? It would look something like this:

```javascript
// ...
export default {
  // ...
  resolve: {
    // ...
    fallback: {
      fs: false,
      path: false,
    },
    // ...
  }
}
```

**Comment by amilajack** [comment]
Closing because this is likely no longer an issue.

If you're still having issues with this please comment and I'll reopen.

**Comment by justdeko** [comment]
Thanks @Rafatcb, this helped me get a step further. I had an issue when using the new version of remote for electron, where the same error of path and fs not being resolved appeared. Now i get a different error of `path.join is not a function
`, but it is probably better to open a new issue for this or ask/look around for solutions a bit.

**Comment by justdeko** [comment]
> Now i get a different error of `path.join is not a function `

Answering my own "issue" for anyone who bumps into this error or chain of errors:

don't forget to use `window.require` and not just `require` when using stuff like `const { BrowserWindow } = window.require('@electron/remote');`, folks
