### ISSUE TITLE
Black screen on app start

### ISSUE THREAD

**Issue by MihailSerikov** [electron-react-boilerplate/electron-react-boilerplate#2977]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)

## Expected Behavior

When the application starts there is no black screen.

## Current Behavior
![black-screen-start](https://user-images.githubusercontent.com/17761509/132850012-4e0ceb77-ae0f-4914-973e-b1501be3d6bb.gif)

On application start, a black screen appears for about 1 second.

## Steps to Reproduce

1. clone boilerplate

2. install dependencies

3. run package script

4. run build

5. pay attention to black screen appeared before window content was rendered 

## Context

It doesn't look like native electron behavior.
I didn't make any changes to the boilerplate.

## Your Environment

- Node version: 14.17.0
- electron-react-boilerplate version or branch: main (3.0.2)
- Operating System and version: Windows 10 Pro 21H1 19043.1165
- Link to your project: (i just cloned this repo and reproduced it as mentioned in Steps to Reproduce)

**Comment by Rafatcb** [comment]
Replacing this:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/2528e688ebfc8b477ab59b75d9a0cb5d49fb8988/src/main/main.ts#L89-L101

with this:

```javascript
mainWindow.once('ready-to-show', () => {
  // ...
});
```

solves the problem?

**Comment by MihailSerikov** [comment]
> Replacing this:
> 
> https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/2528e688ebfc8b477ab59b75d9a0cb5d49fb8988/src/main/main.ts#L89-L101
> 
> with this:
> 
> ```js
> mainWindow.once('ready-to-show', () => {
>   // ...
> });
> ```
> 
> solves the problem?

Hi, @Rafatcb. Thanks for your reply.
Nope, it's still there.

**Comment by amilajack** [comment]
Closing because this is likely no longer an issue.

If you're still having issues with this please comment and I'll reopen.
