### ISSUE TITLE
how to create 2nd renderer process?

### ISSUE THREAD

**Issue by amitava82** [electron-react-boilerplate/electron-react-boilerplate#2980]
## Summary
Hi, I'm upgrading from v1 of this boilerplace. I'm not sure how to create background window for background worker. I have this working perfectly fine on v1 codebase. The documentation is very minimal and there is no example based on latest version.

A simple example project would be helpful or at least some direction on how to go about this. Thanks!

**Comment by amilajack** [comment]
By background window do you mean a 2nd renderer process? Comment and I'll reopen

**Comment by amitava82** [comment]
Yes that is correct. In my app I use 2nd render process which is hidden window for any background workers, cpu intensive work. Example from v1
```
function createBgWindow() {
  bgWindow = new BrowserWindow({
    show: process.env.NODE_ENV === 'development',
    webPreferences: {
      nodeIntegration: true,
    },
  });
  const entry = process.env.NODE_ENV === 'development' ? `${__dirname}/background/index.html` : path.join(app.getAppPath(),'../', '../', 'app', 'background', 'index.html');
  bgWindow.loadURL(`file://${entry}`);
  bgWindow.on('closed', () => {
    console.log('background window closed');
    bgWindow = null;
  });

  bgWindow.webContents.openDevTools();

  return bgWindow;
}
```

**Comment by amilajack** [comment]
Specifically, what's the problem you're running into?

**Comment by amitava82** [comment]
I really don't recall since it has been couple of months and I downgraded to v1 to complete my project. I think it was throwing error about not being able to read the html file at ` bgWindow.loadURL(`file://${entry}`);`

**Comment by amilajack** [comment]
Sure, closing until there's more demand for this

**Comment by AlexMenor** [comment]
I would find this helpful too. 
Have you been able to move further @amitava82?

**Comment by amitava82** [comment]
Nope, I haven't done any more work after my last project.
