### ISSUE TITLE
"our installation debugging guide" link on homepage is broken

### ISSUE THREAD

**Issue by mnpenner** [electron-react-boilerplate/electron-react-boilerplate#2983]
This link on [the homepage](https://electron-react-boilerplate.js.org/docs/installation/)

![image](https://user-images.githubusercontent.com/1112998/133540783-a4b6fb58-e2b6-4c20-b212-3c112c10b1bf.png)

Takes me to a 404 page.

![image](https://user-images.githubusercontent.com/1112998/133540812-ac8e5435-bafa-42d5-a463-34bde4081864.png)

**Comment by amilajack** [comment]
Fixed in https://github.com/electron-react-boilerplate/site/commit/7b0c5865fc02921db4602eb032809399313636f0
