### ISSUE TITLE
With new version of ERB, how can I use path inside the App? How can I access the public assets folder from the App? Thank you!

### ISSUE THREAD

**Issue by wcimediastudios** [electron-react-boilerplate/electron-react-boilerplate#2984]
With new version of ERB, how can I import and path inside the App? 
How can I access the public assets folder from the App? Thank you!

**Comment by odysseymemoirs** [comment]
Please, describe your problem is more details
In my case i created `assets` folder inside `renderer` and referencing the contents of the folder something like this
`import logo from '../assets/images/logo.svg';
`

**Comment by theyameen** [comment]
how to use .well-known folder <link rel="assetlinks.json file" href="%PUBLIC_URL%/.well-known/assetlinks.json" /> ?
