### ISSUE TITLE
With all due respect, your project is broken on Windows

### ISSUE THREAD

**Issue by medmin** [electron-react-boilerplate/electron-react-boilerplate#2985]
## Prerequisites

- [x] Using yarn
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true yarn build && yarn start`

## Expected Behavior

 `yarn install` successfully executed

## Current Behavior

 `yarn install` error

## Steps to Reproduce

1. yarn install

2.

3.

4.

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by IAmMadfly** [comment]
Having the same issue. Even after following the debugging guide.

Error output:


your-project-name on  main via  v15.14.0 took 5s
❯ yarn
yarn install v1.22.11
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info dmg-license@1.0.9: The platform "win32" is incompatible with this module.
info "dmg-license@1.0.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info iconv-corefoundation@1.1.6: The platform "win32" is incompatible with this module.
info "iconv-corefoundation@1.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @pmmmwh/react-refresh-webpack-plugin@0.4.3" has incorrect peer dependency "react-refresh@>=0.8.3 <0.10.0".
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > enzyme-adapter-react-16@1.15.6" has incorrect peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.15.6" has incorrect peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "eslint-config-airbnb-typescript@^8.0.2".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "eslint-config-prettier@^6.11.0".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "eslint-import-resolver-webpack@^0.12.2".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "eslint-plugin-jest@^23.13.2".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.2.3".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "eslint-plugin-promise@^4.2.1".
warning " > eslint-config-erb@3.0.0" has unmet peer dependency "eslint-plugin-testcafe@^0.2.1".
warning " > eslint-config-erb@3.0.0" has incorrect peer dependency "react@^16.13.1".
[4/4] Building fresh packages...
$ node -r @babel/register .erb/scripts/check-native-dep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
  • electron-builder  version=22.11.5
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=win32 arch=x64 appDir=C:\Users\karl.runge\Projects\your-project-name\build\app
  ⨯ C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
yarn install v1.22.11
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild && yarn link-modules
yarn run v1.22.11
$ node -r ../../.erb/scripts/babel-register.js ../../.erb/scripts/electron-rebuild.js
Done in 0.94s.
yarn run v1.22.11
$ node -r ../../.erb/scripts/babel-register.js ../../.erb/scripts/link-modules.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error output:
node:internal/fs/utils:323
    throw err;
    ^

Error: EPERM: operation not permitted, symlink 'C:\Users\karl.runge\Projects\your-project-name\build\app\node_modules' -> 'C:\Users\karl.runge\Projects\your-project-name\src\node_modules'
    at Object.symlinkSync (node:fs:1222:3)
    at Object.<anonymous> (C:\Users\karl.runge\Projects\your-project-name\.erb\scripts\/link-modules.js:8:6)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module._compile (C:\Users\karl.runge\Projects\your-project-name\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.newLoader [as .js] (C:\Users\karl.runge\Projects\your-project-name\node_modules\pirates\lib\index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path: 'C:\\Users\\karl.runge\\Projects\\your-project-name\\build\\app\\node_modules',
  dest: 'C:\\Users\\karl.runge\\Projects\\your-project-name\\src\\node_modules'
}
error Command failed with exit code 1.
error Command failed with exit code 1.
  failedTask=installAppDeps stackTrace=Error: C:\Program Files\nodejs\node.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Output:
yarn install v1.22.11
[1/4] Resolving packages...
success Already up-to-date.
$ yarn electron-rebuild && yarn link-modules
yarn run v1.22.11
$ node -r ../../.erb/scripts/babel-register.js ../../.erb/scripts/electron-rebuild.js
Done in 0.94s.
yarn run v1.22.11
$ node -r ../../.erb/scripts/babel-register.js ../../.erb/scripts/link-modules.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by caionakai** [comment]
@IAmMadfly your problem is because you are running `yarn install` on a terminal without admin permissions. 
To solve it open CMD as admin and try `yarn intall` again

**Comment by leopucci** [comment]
> @IAmMadfly your problem is because you are running `yarn install` on a terminal without admin permissions. To solve it open CMD as admin and try `yarn intall` again

Thanks @caionakai this solves the problem on the yarn install. Obrigado
