### ISSUE TITLE
Uses a web server, very insecure!!

### ISSUE THREAD

**Issue by h57758** [electron-react-boilerplate/electron-react-boilerplate#2987]
# Web server
By just looking at the startup logs, i can see that it is using a web server, iWas looking for a way to use react with electron without a web server, but i guess that does NOT exist.

# Fixes
I think you could just fix it by changing o little bit of code in either the react builder, or electron.

# Result
I will NOT be using react to work with electron EVER!!
Instead i will use my good old friends, HTML, Javascript, CSS.

# Comment
"The default issue thing was not for this issue."

**Comment by Slapbox** [comment]
Imagine opening an issue to complain about your lack of knowledge...

People might offer some help if you had a better attitude, but instead I'll just say, "@amiliajack, let's close this."

**Comment by h57758** [comment]
Ok. Sorry

**Comment by Slapbox** [comment]
If you need some assistance, please ask questions and I'm sure people will be happy to help you.

The web server is only used during development, not in the packaged production app.
