### ISSUE TITLE
How to install and configure electron-store?

### ISSUE THREAD

**Issue by Juninho-dev** [electron-react-boilerplate/electron-react-boilerplate#2988]
## Summary

I can't get electron-store to work in my app, there are too many errors

**Comment by amilajack** [comment]
See https://github.com/electron-react-boilerplate/site/commit/bc533775e75bd4cd422b9f7fcfe1a5c224bc6adf

**Comment by denysovkos** [comment]
Probably thats OK for someone to expose store to the outer world, but what if I want to hide it and use it incapsulated in some inner modules? Or I want to do some inversions?
