### ISSUE TITLE
After I package my application, it does not pull data from external data.json file

### ISSUE THREAD

**Issue by tolgagnydnn** [electron-react-boilerplate/electron-react-boilerplate#2990]
Hello there. My English is a bit bad, I apologize in advance for that. I have an application and I am packaging this application. I have a data.json file in a non-application folder in my application and I pull my data from there. When working normally everything is great, I can list my data. But when I package my application my data is not coming. It also works nicely on windows platform when I package it. But on the linux side, the data is not coming.

**Comment by odysseymemoirs** [comment]
Its seems that problem are in your relative paths that are different in dev mode and production
And another problem appears in packaged app that is read only 
Try to use external storage as `electron-store`
