### ISSUE TITLE
Display local videos in dev environment (webpack)

### ISSUE THREAD

**Issue by pietrop** [electron-react-boilerplate/electron-react-boilerplate#3009]
## Summary

I am refactoring https://autoEdit.io to use this boilerplate (https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/1106#issuecomment-942828441), it's an app for text based video editing, it uses ffmpeg under the hood, and needs access to audio and video files stored on the user's application data path folder. 

However in development, because of how the app is served with webpack, it fails to show the files, because if appends the absolute file system app to the localhost url, creating an incorrect resource location. 

I do realize is a bit a niche use case, but was wondering if anyone else has had a similar use case, and might have found a workaround?

---

updated 

I found this [on stackoverflow "Webpack Build Not Rendering HTML5 Video"](https://stackoverflow.com/questions/49103589/webpack-build-not-rendering-html5-video) , and tried adding this to webpack `webpack.config.renderer.dev.ts` 

```js
 {
        test: /\.(mov|mp4)$/, use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]'
            }
          }
        ]
      },
```

It adds the correct path to the `src` of the `video` element, but the media doesn't play. I guess that might be because in development it's still served via webpack local server and that might not be able to serve static assets on the user's system?

**Comment by amilajack** [comment]
There's an example of an html video example working here
https://github.com/amilajack/erb-video-example
