### ISSUE TITLE
How-to add run-time assets? Docs is unclear, or maybe outdated?

### ISSUE THREAD

**Issue by IzaacJ** [electron-react-boilerplate/electron-react-boilerplate#3013]
## Summary

I'm using `better-sqlite3-helper`, specifically for the migrations feature. I'm however unable to figure out where to put the folder, and how to get it included.

I've made multiple attempts to figure this out, without any luck. All attempts have been made with one of `assets`, `assets/` and `assets/**/*` added to `./package.json[build][files]`.

1. `./src/assets/migrations/001-initial.sql`
   - Nothing added in `./release/build/**/*`
   - Nothing added in `asar list ./release/build/win-unpacked/resources/app.asar`
1. `./src/main/assets/migrations/001-initial.sql`
   - Nothing added in `./release/build/**/*`
   - Nothing added in `asar list ./release/build/win-unpacked/resources/app.asar`
1. `./src/app/assets/migrations/001-initial.sql`
   - Nothing added in `./release/build/**/*`
   - Nothing added in `asar list ./release/build/win-unpacked/resources/app.asar`
1. `./assets/migrations/001-initial.sql`
   - Nothing added in `./release/build/win-unpacked/resources/assets`
   - Nothing added in `asar list ./release/build/win-unpacked/resources/app.asar`
1. `./release/assets/migrations/001-initial.sql`
   - Nothing added in `./release/build/**/*`
   - Nothing added in `asar list ./release/build/win-unpacked/resources/app.asar`
1. `./release/app/assets/migrations/001-initial.sql`
   - Nothing added in `./release/build/**/*`
   - Nothing added in `asar list ./release/build/win-unpacked/resources/app.asar`

The docs about [run-time assets](https://electron-react-boilerplate.js.org/docs/adding-assets#run-time-assets) specifies that `./package.json[build][files]` is relative to `./src`, but that doesn't seem to be the case, as shown by my first attempt, or am I missing something?

Note that my goal is to have the files added, as-is, without having to import them, as `better-sqlite3-helper` handles all of that, it just need to have access to the directory, in `main`, not the `renderer`.

**Comment by amilajack** [comment]
I put together a repo to clarify this

https://github.com/amilajack/erb-better-sqlite3-example

[Here are the specific lines](https://github.com/amilajack/erb-better-sqlite3-example/commit/56a4d94a66eaf2e983758ea856fd21dd198c027c#diff-7adaa52a2eacb085ba5e07e6683a61fb3601547dc00b51fd50fbaf685e13fe96R51-R55) you'd be interested in.

In summary:

1. **[Add your directory to package.json > build > files](https://github.com/amilajack/erb-better-sqlite3-example/commit/56a4d94a66eaf2e983758ea856fd21dd198c027c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R41)**. They're relative to `release/app`.
2. **[Determine the path of your files](https://github.com/amilajack/erb-better-sqlite3-example/commit/56a4d94a66eaf2e983758ea856fd21dd198c027c#diff-7adaa52a2eacb085ba5e07e6683a61fb3601547dc00b51fd50fbaf685e13fe96R51-R53) of your files**. They're different in dev and in prod.

The docs were outdated, thanks for catching that! Assets in package.json > build > files are relative to `release/app`.

**Comment by amilajack** [comment]
Please lmk if you have any questions and I'll reopen. To setup the working example above, run the following commands:

```bash
git clone https://github.com/amilajack/erb-better-sqlite3-example.git
cd erb-better-sqlite3-example
npm i
npm start
```

**Comment by andrewrt** [comment]
@amilajack , thanks for this. 
I was thinking I could apply similar logic to having an executable file as a runtime asset that gets spawned by the main process, but it seems I need to configure webpack for this as well, right? 

Out of the box, your method works for main.ts spawning `my_executable` without webpack modification, so:
Add `my_executable` to release/app/assets, and assets to package.json's build/files...
Then access it from main.ts with `path.join(__dirname, '../../assets/my_executable')`.

 but the executable doesn't get copied over to the packaged solution when doing
```sh
npm run package
```

**Comment by NaClYen** [comment]
In my case, I focus on rendering scripts usage situations.

1. Place assets to `release/app/data`
2. For runtime, I add building file setting in `package.json` as ...
  According to my research, the `from`'s path is based on `release/app`, therefore use `data` here simply.
  ```
    {
      "from": "data",
      "to": "dist/renderer/data",
      "filter": "**/*"
    }
  ```
3. For dev, I add static folder setting in `.erb/configs/webpack.config.renderer.dev.ts` as ...
  ```
    {
      directory: 'release/app/data',
      publicPath: '/data',
    },
  ```

---

Finally, in the script, I can use them via a related path, both of dev or prod.
e.g. `data/help.md`

It works for me, but I am not sure about this solution is good or not...?
