### ISSUE TITLE
Unable to set background-image in a `scss` file

### ISSUE THREAD

**Issue by smultar** [electron-react-boilerplate/electron-react-boilerplate#3014]
## Prerequisites

- [ ] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Expecting the image to load from the file into scss.

## Current Behavior

No image is being present/loaded into the application.

## Steps to Reproduce
 Create a project, and then try to add a background-image with a url().

**Comment by amilajack** [comment]
Please provide a repo that reproduces this issue.
