### ISSUE TITLE
Property 'electron' does not exist on type 'Window & typeof globalThis'. Did you mean 'Electron'?

### ISSUE THREAD

**Issue by samcodee** [electron-react-boilerplate/electron-react-boilerplate#3016]
## Summary

I am trying to call the IPCrenderer through the built-in context bridge and receive the following error:

`Property 'electron' does not exist on type 'Window & typeof globalThis'. Did you mean 'Electron'?`

**App.tsx**

```Javascript
import { MemoryRouter as Router, Switch, Route } from 'react-router-dom';
import './App.global.css';

const Login = () => {
  const handleButtonClick = () => {
    window.electron.ipcRenderer.onButtonClick('Button Clicked');
  };

  return (
    <div>
      <button
        type="button"
        onClick={handleButtonClick}
      >
        Login &gt;
      </button>
    </div>
  );
};

export default function App() {
  return (
    <Router>
      <Switch>
        <Route path="/" component={Login} />
      </Switch>
    </Router>
  );
}
```
**main.tsx**(code snippet added in event listener section)

```Javascript
ipcMain.on('button-example', (arg) => {
  console.log(arg);
});
```
**preload.js**

```Javascript
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electron', {
  ipcRenderer: {
    onButtonClick() {
      ipcRenderer.send('button-example', 'Button Clicked');
    },
  },
});
```
Any guidance on this topic would be helpful.

**Comment by paragbaxi** [comment]
Anyone have a working example of this? 

I tried

`renderer/renderer.d.ts`
```
export interface IElectronAPI {
  loadPreferences: () => Promise<void>;
}

declare global {
  interface Window {
    electronAPI: IElectronAPI;
  }
}
```

`App.tsx`
```
...
window.electronAPI.loadPreferences();

const Hello = () => {
  const paylocityLogin = () => {
    window.electron.ipcRenderer.on('ipc-example', (arg: string) => {
      // eslint-disable-next-line no-console
      console.log(arg);
    });
  };
...
```

vscode still giving error on `electron`:
`Property 'electron' does not exist on type 'Window & typeof globalThis'. Did you mean 'Electron'?ts(2551)`

**Comment by raine** [comment]
> Anyone have a working example of this?

Works here: https://github.com/raine/pr-buddy

Can't say offhand what could be wrong with your example

**Comment by BigOldWei** [comment]
> This should help you: https://www.electronjs.org/docs/latest/tutorial/context-isolation#usage-with-typescript

If the problem cannot be solved according to the official tutorial, it is likely that the configuration in package.json is missing.
add ` "typings": "global1.d.ts" ` will help you!

```json
{
   ...
  "dependencies": {
    "antd": "^5.0.5",
    "electron-squirrel-startup": "^1.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "typings": "global1.d.ts" //here
}
```
If this helps you, give me a reply

**Comment by arjundangi01** [comment]
in glonal.d.ts 

import type { globals } from 'src/preload';


```
declare global {
  const electron: typeof globals;
  .............
  const __APP_VERSION__: string;
  interface Window {
    electron: {
      store: {
        get: (key: string) => unknown;
        set: (key: string, val: unknown) => void;
        delete: (key: string) => void;
      };
      ipcRenderer: IpcRenderer;
      shell: Shell;
      
    };
  }
}
```

now in preload js also write ipc related things

and then you will be able to use window.electron.ipcRender
