### ISSUE TITLE
Adding runtime asset

### ISSUE THREAD

**Issue by SevenSinS02** [electron-react-boilerplate/electron-react-boilerplate#3017]
It seems that adding runtime assets via the `files` field in package.json doesn't seem to work for all file types.
Added a `.js` file but it is not included in the packaged bundle. 

However, I have noticed that if it's a `.ts` file it is included.

(Used `asar list release/build/mac/ElectronReact.app/Contents/Resources/app.asar` to inspect the contents of the packaged build)

Below is what I've added to the package.json file

```
"build": {
    // ...
    "files": [
      "example.js"
      // ...
    ],
}
```

**Comment by amilajack** [comment]
`example.js`'s path should be `release/app/example.js`.

See https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3013#issuecomment-1001817920. The file paths are relative to `release/app`.
