### ISSUE TITLE
`electron-store` support out of the box

### ISSUE THREAD

**Issue by samcodee** [electron-react-boilerplate/electron-react-boilerplate#3020]
Maybe it would be nice if `electron-store` was supported out of the box. 

## Example
There could be example in the `App.tsx` file demonstrating it. There could be a button. When clicking the button, a value would be saved in `electron-store`. The next time opening the app will show a text with the value from `electron-store`.

## Referance
https://stackoverflow.com/questions/68873456/using-electron-store-with-react

**Comment by xrebelox** [comment]
> Instead we should provide documentation for common integrations, [similar to what we do with tailwind](https://electron-react-boilerplate.js.org/docs/styling/#tailwind-integration). Looking forward to the contribution to the docs if you're interested.

@amilajack is it possible to update the tailwind documentation? currently, the documentation is not up to that and tailwind won't work with the current version of ERB.

**Comment by amilajack** [comment]
@samcodee It should be fine if you PR the docs to a file called `electron-store.md` in this directory: https://github.com/electron-react-boilerplate/site/tree/master/docs

**Comment by amilajack** [comment]
@xrebelox I was unaware that the docs were broken. Would you be interested in submitting a PR?

**Comment by samcodee** [comment]
@amilajack, I have created the docs for `electron-store` here - #3022
Please check and reply if it is helpful.

**Comment by xrebelox** [comment]
@amilajack [this comment](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2915#issuecomment-953572451) already mentions the issue with version 4.3.0, I think it could be discussed there and then a PR could be submitted.
