### ISSUE TITLE
How can I install webpack version?

### ISSUE THREAD

**Issue by Devilanc** [electron-react-boilerplate/electron-react-boilerplate#3021]
Hello, I'm trying electron-react-boilerplate js version.

I add some option at git clone and installed js version successfully, but i can't remember what option i used..

**Comment by kbrisso** [comment]
Look in root project folder for package. json it should be `webpack": "^5.60.0"`  If you are not sure about clone then try it again.

**Comment by Devilanc** [comment]
I want to Install JS Version, not typescript. why i have to change package.json??

**Comment by UserJHansen** [comment]
Just remove all the typescript parts from the default files and rename the to js. Then you shouldn't have to do any of the type checking

**Comment by Devilanc** [comment]
@UserJHansen I remember there's an option on electron-react-boilerplate. install to ts or js.
renaming some files makes error..

**Comment by amilajack** [comment]
> Just remove all the typescript parts from the default files and rename the to js. Then you shouldn't have to do any of the type checking

this solution should work
