### ISSUE TITLE
Tailwind Integration not working in version 4.3.0

### ISSUE THREAD

**Issue by xrebelox** [electron-react-boilerplate/electron-react-boilerplate#3023]
## Prerequisites

- [X] Using npm
- [X] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Accordingly, to the [docs ](https://electron-react-boilerplate.js.org/docs/styling/#tailwind-integration) the tailwind integration should've worked, meaning that you should be able to utilize tailwind's classes.

## Current Behavior

If you follow the docs and try to integrate tailwind in the recent version (4.3.0) of ERB you won't be able to utilize the tailwind classes, perhaps this is due to the webpack configuration change in 4.3.0.

    const Hello = () => {
      return (
        <div className="absolute inset-0 bg-white text-center h-full flex flex-col justify justify-center">
          ERB + TAILWIND = ❤
        </div>
      );
    };

This is the result I obtained when running the above snippet:
![image](https://user-images.githubusercontent.com/37772515/139541964-fb237385-a4de-4d89-aba5-3052dfae4ad5.png)

If you try the same integration in 4.2.0 and utilize the same snippet this is the result and the expected result:
![image](https://user-images.githubusercontent.com/37772515/139541927-77ecec1b-59cf-4296-97c2-0a48a434df65.png)

## Steps to Reproduce

1. Follow the [documentation](https://electron-react-boilerplate.js.org/docs/styling/#tailwind-integration) regarding the tailwind integration.

2. Try utilizing any tailwind class and it should not work.

## Possible Solution (Not obligatory)

I suspect that the problem surrounding this issue is related to the simplification of the webpack config and other changes in version 4.3.0 as listed [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/releases/tag/v4.3.0).

## Context

This issue seems to be affecting more people as mentioned [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2915#issuecomment-954900037).

I decided to downgrade from 4.3.0 to 4.2.0 and follow the tailwind integration again and it worked perfectly, that is why I believe the issue is related to the webpack configuration.

## Your Environment

- Node version : 14.17.1
- electron-react-boilerplate version or branch : 4.3.0
- Operating System and version: Windows 10
- Link to your project : N/A

**Comment by amilajack** [comment]
It isn't clear what you mean by "doesn't work". Can you please provide what isn't working. Are there compiler errors?

**Comment by xrebelox** [comment]
> It isn't clear what you mean by "doesn't work". Can you please provide what isn't working. Are there compiler errors?

@amilajack Sorry, I edited the main post. There are no compiler errors, however, you won't be able to use any of the tailwind classes as they're not being generated. 

However, If you do try the same integration in 4.2.0 you'll be able to utilize all the classes as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/37772515/139541927-77ecec1b-59cf-4296-97c2-0a48a434df65.png)

In comparison this is what happens in 4.3.0:
![image](https://user-images.githubusercontent.com/37772515/139541964-fb237385-a4de-4d89-aba5-3052dfae4ad5.png)

**Comment by amilajack** [comment]
See this working example: https://github.com/amilajack/erb-tailwind-example
Update the docs: https://electron-react-boilerplate.js.org/docs/styling/#tailwind-integration

**Comment by xrebelox** [comment]
@amilajack thanks for the update! I'm reading the documentation now and I was trying to check your working example but it seems that repo is private.

**Comment by amilajack** [comment]
Ahh thanks for the callout. Fixed! 🥳

**Comment by xrebelox** [comment]
Thanks a lot @amilajack,  I managed to get it working now!

As a side note, it seems that you don't need to import tailwind.css inside App.tsx, I managed to get it working by importing tailwind in App.css like this:

    @tailwind base;
    @tailwind components;
    @tailwind utilities;

 And then just import `App.css` inside `App.tsx`

**Comment by amilajack** [comment]
it isn't a requirement. either option works

**Comment by myhendry** [comment]
Thanks folks for the solution. I am not familiar with babel and webpack integration. The webpack config seems a bit different compared to the setup here <https://rodpadev.medium.com/add-tailwind-css-to-the-popular-electron-react-boilerplate-erb-f1286b5b04f>. 

Thanks for making it work :)
