### ISSUE TITLE
Can't import any modules in any file.

### ISSUE THREAD

**Issue by BustosAndrew** [electron-react-boilerplate/electron-react-boilerplate#3025]
### Discussed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/discussions/3024

<div type='discussions-op-text'>

<sup>Originally posted by **BustosAndrew** October 31, 2021</sup>
I've been trying for a couple hours to find out why I keep getting this error after each time I import firebase into any js/tsx file:
```
Not rewriting GET /index.html because the path includes a dot (.) character.
```
What's the workaround for this? Am I likely to run into this problem with three.js as well if I try importing three into any js/tsx file?

**Edit:** after trying to import axios into the App.tsx file, I get the same error. Am I installing npm packages wrong?</div>

**Comment by guillermoriv** [comment]
Can you check the console?, because this is a related problem with Eslint, there is some rules that don't let you compile if you don't fix them, maybe is something related, at least was one problem for me.

**Comment by BustosAndrew** [comment]
Yea I found that out after further testing of why it doesn't compile. I kinda wish they mentioned this in their readme because some webpack projects let warnings compile.
