### ISSUE TITLE
github CI publish failing on `postinstall` script: "command not found: electron-builder"

### ISSUE THREAD

**Issue by angle943** [electron-react-boilerplate/electron-react-boilerplate#3026]
I'm having a failing CI: https://github.com/thenewboston-developers/Wallet/runs/4062889990?check_suite_focus=true

Anyone know why I'm getting the error "command not found: electron-builder"?

**Comment by amilajack** [comment]
Yarn >=1 isn't supported by ERB so i'll close this but feel free to continue the discussion

**Comment by angle943** [comment]
thank you!
