### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by mumairofficial** [electron-react-boilerplate/electron-react-boilerplate#3028]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)

## Expected Behavior
Followed the instructions to set up the project

```sh
git clone --depth 1 --branch main https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name
cd your-project-name
npm install
```

and then
```sh
npm start
```

Application should render

## Current Behavior

Upon `npm start` developer console throws the following error, while the application screen remains blank

Devtools
![image](https://user-images.githubusercontent.com/6498132/140024577-f419c08c-5ad8-4d11-a94c-71177026f322.png)

Application Window
![image](https://user-images.githubusercontent.com/6498132/140025115-48818b27-a64f-4fa0-801e-eead927ce432.png)

## Steps to Reproduce

1. Generate project as per instructions mentioned in README file

2. `npm install` then `npm start`

3. It will launch the blank window and devtools showing error

## Context

Trying to create MQTT client, just a freshly generated project today (3-10-2021) without modifying any source file I am getting errors.

## Your Environment

- Node version : 14.17.6
- electron-react-boilerplate version or branch : main
- Operating System and version :  Windows 10

**Comment by amilajack** [comment]
Try upgrading your dev tools:

```
UPGRADE_EXTENSIONS=1 npm build
```

**Comment by budowski** [comment]
Experiencing the same issue - upgrading dev tools did not help. MacOS 10.15.7 with node v14.17.1

**Comment by budowski** [comment]
Update: If I remove the call to `installExtensions` (in `main.ts` file) -> everything works fine

**Comment by neopostmodern** [comment]
The [above suggestion](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3028#issuecomment-958722260) didn't work for me, but led me to running this once, which fixed it permanently:
```
UPGRADE_EXTENSIONS=1 npm run start
```

**Comment by ishandutta2007** [comment]
@budowski I think inside `installExtensions` it's failing trying to do something like this 

```require('electron-devtools-installer')['REACT_DEVELOPER_TOOLS']```

Whats the fix ?
