### ISSUE TITLE
I can not start the boilerplate.

### ISSUE THREAD

**Issue by nikolaytoplev** [electron-react-boilerplate/electron-react-boilerplate#3033]
- Node version :12.16.0
- electron-react-boilerplate version or branch :master branch 2days ago
- Operating System and version :Windows10 64bit

as you can see above , I am working in the same environment above.
But I can start the boilerplate using "npm start" or "yarn start"
I hope you will resolve this problem as fast as possible.

**Comment by UserJHansen** [comment]
Have you run `npm install` first?

**Comment by selvex** [comment]
Hi,
> Node version :12.16.0

That's an old node version. This boilerplate does not work with any given node version. In the package.json it states:
```json
  "devEngines": {
    "node": ">=14.x",
    "npm": ">=7.x"
  },
```

However, I'm not sure if it works with any node version >14. I tried with 16.6 and it did not work for me.

It does work with current NodeJS LTS version 16.13.0.
