### ISSUE TITLE
webpack issue when using nodejs modules. 

### ISSUE THREAD

**Issue by arunkumar413** [electron-react-boilerplate/electron-react-boilerplate#3035]
## Summary
Hi Team, 

I'm facing a webpack issue  when trying to use nodejs `fs` module. Below is the error. I tried various configuration methods but they didn't work.  Could you please look into this.  Here (  https://github.com/arunkumar413/electron-react-boilerplate )  is the source code
```

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/renderer/App.tsx 9:35-60
 @ ./src/renderer/index.tsx 10:30-46

```

Thanks,
Arun

Need help configure the app to access nodejs fs module and to run the app as desktop app.

**Comment by sensible-s** [comment]
I'm certainly not an authoritative source but the [webpack 5 migration guide](https://webpack.js.org/migrate/5/#clean-up-configuration) says:

> If you are using something like node.fs: 'empty' replace it with resolve.fallback.fs: false.

So update your `webpack.config.base.ts` resolve block to something like this:
```
	resolve: {
		extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
		modules: [webpackPaths.srcPath, 'node_modules'],
		fallback: {
			path: false,
		},
	},
```

**Comment by amilajack** [comment]
Using node modules exposes you to security vulnerabilities. If you're okay with the risk, here are the docs to [enable native modules in the renderer process](https://electron-react-boilerplate.js.org/docs/native-modules/#renderer-process-native-modules).

**Comment by dmatora** [comment]
@amilajack I tried changes mentioned on page you've mentioned, and got ```
Cannot read properties of undefined (reading 'ipcRenderer')
```

**Comment by amilajack** [comment]
Okay, I'll take a look today and see if I can repro
