### ISSUE TITLE
I have a lot of problems with ERB

### ISSUE THREAD

**Issue by LIMPIX31** [electron-react-boilerplate/electron-react-boilerplate#3036]
I decided to move my project to a newer version of the ERB, but I get all kinds of errors, even at the point of installing packages.
I'm 99% sure I'm the problem, but I can't find the solution.

- Error loading fonts
- Error loading less (I added the less-loader to the webpack config)
- Error installing packages
- Error compilling

![image](https://user-images.githubusercontent.com/81296950/141453760-b3c1242b-bf53-440c-9846-59a27f4bf6d1.png)

![image](https://user-images.githubusercontent.com/81296950/141454035-88af5f09-ccd1-400f-a034-2b0447e98771.png)

This is the third time I have had the headache of trying to migrate a project to a new version of ERB (as of this writing)

The packages I installed:

- antd
- axios
- uuid
- classnames
- discord-rpc
- electron-dl
- formik
- fs-extra
- json-prune
- imgur
- less
- less-loader
- node-localstorage

Please help me, I don't understand something.

Thanks

**Comment by guillermoriv** [comment]
Are you trying to use the `fs` in the renderer process?, I mean that's the first thing that you show in the screenshots, remember that you need to install `native modules` under `release/app/package.json`, and everything else under the `root/package.json` and still in the `devDependencies`, try to look into these first steps and then comment into the issue again !, I am here happy to help

**Comment by LIMPIX31** [comment]
@guillermoriv
If webpack captures everything in the render folder, then the problem is clear, I store functions to run in the main thread in the renderer folder. In the old version of the ERB there is no such rigid separation

**Comment by kbrisso** [comment]
Is the font being loaded available in the old source path? The import is looking for old path and it is not finding it.  Can't resolve old source in new target dir.

**Comment by LIMPIX31** [comment]
Okay, I fixed all but one problem, how do I turn preload.js into preload.ts. I can't use ts modules in the js file and this is a big problem for my application

**Comment by kbrisso** [comment]
The idea behind preload.js is, it is used for IPC process only (IMHO). It's the bridge between client and server. If you are familiar with Java think RMI. I would only use it to make IPC calls to main. Take a look at my example https://github.com/kbrisso/erb-bootstrap-ipc In my example I created a type file for IPC and show how to receive drive info from main process.  In my example project I use IPC in App.tsx and the typed file for it is global.d.ts. I found these parts poorly documented or half documented on the web.  Let me know if this helps if it doesn't please post code and what exactly you are trying to accomplish.
