### ISSUE TITLE
Change window's height from 728 to 768 on main.ts

### ISSUE THREAD

**Issue by BangHyeongSik** [electron-react-boilerplate/electron-react-boilerplate#3040]
![image](https://user-images.githubusercontent.com/53025965/141934016-e686c375-e59b-491a-80b8-4e8fc0f39d59.png)

Now, mainWindow's height in main.ts is 728.
It seems that you matched resolution 1024*768.

How about changing height 728 to 768?

**Comment by amilajack** [comment]
What's the reason for changing it?

**Comment by BangHyeongSik** [comment]
Because, I just thought it was a typo.
Usually, the monitor resolution is set to 4:3 (like 1080*768).
Please, close this issue if it's not a mistake.
