### ISSUE TITLE
Strange behavior on native module installation using link-modules.ts.

### ISSUE THREAD

**Issue by HyunGook-Kim** [electron-react-boilerplate/electron-react-boilerplate#3046]
## Summary

If i run ```yarn``` command to install dependencies on project root and then add native module to ```/release/app/package.json``` using ```yarn add serialport``` symlinks are not generated by ```link-module.ts``` because ```fs.existsSync``` on ```srcNodeModulesPath``` and ```appNodeModulesPath``` are both ```true```.

It seems ```link-module.ts``` generate symlink if ```srcNodeModulesPath``` is not exists and ```appNodeModulesPath``` is exits. So i have to add native module first in ```/release/app/package.json``` using ```yarn add serialport``` to ensure ```srcNodeModulesPath(/projectRoot/node_modules)``` is not exists.

Should i remove node_modules in project root every time i want to add native moduels in the project?

**Comment by HyunGook-Kim** [comment]
```javascript
import fs from 'fs';
import path from 'path';
import webpackPaths from '../configs/webpack.paths';

const srcNodeModulesPath = webpackPaths.srcNodeModulesPath;
const appNodeModulesPath = webpackPaths.appNodeModulesPath;

fs.readdirSync(appNodeModulesPath).forEach(nativeModuleDependency => {
  const srcCheckPath = path.join(srcNodeModulesPath, nativeModuleDependency)
  const appCheckPath = path.join(appNodeModulesPath, nativeModuleDependency)

  if (!fs.existsSync(srcCheckPath) && fs.existsSync(appCheckPath) && isDirectory(appCheckPath)) {
    fs.symlinkSync(appCheckPath, srcCheckPath, 'junction');
  }
});

function isDirectory(path:string) {
  return fs.statSync(path).isDirectory()
}
```

Changing code in ```link-modules.ts``` by this code works on my case. But not sure is it right.

**Comment by telanflow** [comment]
> ```js
> import fs from 'fs';
> import path from 'path';
> import webpackPaths from '../configs/webpack.paths';
> 
> const srcNodeModulesPath = webpackPaths.srcNodeModulesPath;
> const appNodeModulesPath = webpackPaths.appNodeModulesPath;
> 
> fs.readdirSync(appNodeModulesPath).forEach(nativeModuleDependency => {
>   const srcCheckPath = path.join(srcNodeModulesPath, nativeModuleDependency)
>   const appCheckPath = path.join(appNodeModulesPath, nativeModuleDependency)
> 
>   if (!fs.existsSync(srcCheckPath) && fs.existsSync(appCheckPath) && isDirectory(appCheckPath)) {
>     fs.symlinkSync(appCheckPath, srcCheckPath, 'junction');
>   }
> });
> 
> function isDirectory(path:string) {
>   return fs.statSync(path).isDirectory()
> }
> ```
> 
> Changing code in `link-modules.ts` by this code works on my case. But not sure is it right.

me too

**Comment by amilajack** [comment]
> ```js
> ```js
> import fs from 'fs';
> import path from 'path';
> import webpackPaths from '../configs/webpack.paths';
> 
> const srcNodeModulesPath = webpackPaths.srcNodeModulesPath;
> const appNodeModulesPath = webpackPaths.appNodeModulesPath;
> 
> fs.readdirSync(appNodeModulesPath).forEach(nativeModuleDependency => {
>   const srcCheckPath = path.join(srcNodeModulesPath, nativeModuleDependency)
>   const appCheckPath = path.join(appNodeModulesPath, nativeModuleDependency)
> 
>   if (!fs.existsSync(srcCheckPath) && fs.existsSync(appCheckPath) && isDirectory(appCheckPath)) {
>     fs.symlinkSync(appCheckPath, srcCheckPath, 'junction');
>   }
> });
> 
> function isDirectory(path:string) {
>   return fs.statSync(path).isDirectory()
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> Changing code in link-modules.ts by this code works on my case. But not sure is it right.
> 
> me too
> ```

Closing but comment if this solution doesn't work and I'll reopen
