### ISSUE TITLE
errors while building `electron-react-boilerplate@workspace:.` on yarn 2+

### ISSUE THREAD

**Issue by pjalsGit** [electron-react-boilerplate/electron-react-boilerplate#3054]
## Prerequisites

- [ ] Using npm (yarn is superior)
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400) (I don't have node_modules)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start` (can't, it doesn't even build your package)

## Expected Behavior

Build the package

## Current Behavior

Errors, here are the logs:
```
# This file contains the result of Yarn building a package (electron-react-boilerplate@workspace:.)
# Script name: postinstall

Debugger listening on ws://127.0.0.1:32931/2047b205-a061-4ba5-ab57-c9fc10f8ecac
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Error: ENOENT: no such file or directory, scandir 'node_modules'
    at Object.readdirSync (node:fs:1390:3)
    at NodeFS.readdirSync (/home/me/Projects/rcsbg/.pnp.cjs:21437:26)
    at makeCallSync.subPath.subPath (/home/me/Projects/rcsbg/.pnp.cjs:24416:26)
    at ZipOpenFS.makeCallSync (/home/me/Projects/rcsbg/.pnp.cjs:24512:26)
    at ZipOpenFS.readdirSync (/home/me/Projects/rcsbg/.pnp.cjs:24415:17)
    at VirtualFS.readdirSync (/home/me/Projects/rcsbg/.pnp.cjs:21738:24)
    at PosixFS.readdirSync (/home/me/Projects/rcsbg/.pnp.cjs:21738:24)
    at URLFS.readdirSync (/home/me/Projects/rcsbg/.pnp.cjs:21738:24)
    at Object.<anonymous> (/home/me/Projects/rcsbg/.erb/scripts/check-native-dep.js:9:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'node_modules'
}
```

## Steps to Reproduce

1. Get boilerplate

2. Run `yarn set version stable`

3. See error in `/tmp/xxx-xxxxxxx/build.log

## Possible Solution (Not obligatory)

I'm pretty sure you shouldn't rely on `node_modules` existing, as [PNP](https://yarnpkg.com/features/pnp) exists.

## Context

Trying to make a project with yarn

## Your Environment

- Node version : v16.11.0
- electron-react-boilerplate version or branch : `main`
- Operating System and version : `Linux fedora 5.15.5-201.fsync.fc35.x86_64 #1 SMP Sun Nov 28 16:39:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Link to your project : https://github.com/electron-react-boilerplate/electron-react-boilerplate (works without any changes)

**Comment by amilajack** [comment]
Latest ERB doesn't support yarn. This is not a bug with the boilerplate.
