### ISSUE TITLE
electron-preload instead of electron-main

### ISSUE THREAD

**Issue by ahmafi** [electron-react-boilerplate/electron-react-boilerplate#3057]
I was reading [webpack documentation](https://webpack.js.org/configuration/target/#string) and there is an `electron-preload` target. But you are using `electron-main` for transpiling preload files:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/bd18dd3b44d19dc761dc10fd629f057daa5dfb34/.erb/configs/webpack.config.main.prod.ts#L30-L36

Could it make any problems?

**Comment by amilajack** [comment]
No, since preload is a subset of the functionality of electron-main.
