### ISSUE TITLE
support preload.ts 

### ISSUE THREAD

**Issue by DeeGeeMan** [electron-react-boilerplate/electron-react-boilerplate#3058]
If I rename the `preload.js` to `preload.ts` and then run `npm run start`, it will not load the preload script file.

Error:
```
Unable to load preload script: Unable to load preload script: .../src/main/preload.js
```

**Comment by FreelanceDev217** [comment]
I guess you should not rename `preload.js`. It seems to be a pre-defined filename in electron.

**Comment by DeeGeeMan** [comment]
Why?  The `main.ts` is using typescript.  Plus other boilerplates for React supports `preload.ts` e.g [Vue CLI 3 plugin for Electron ](https://nklayman.github.io/vue-cli-plugin-electron-builder).

**Comment by CREATE-AI** [comment]
+1

**Comment by m4tta** [comment]
Yeah this is pretty absurd that all the files are typescript based but this one is just left out?

**Comment by shyamkumaryadav** [comment]
+1
