### ISSUE TITLE
import 3d models for component BABYLON js

### ISSUE THREAD

**Issue by denisTrubicin93** [electron-react-boilerplate/electron-react-boilerplate#3065]
## Summary

I am using sceneloader which requires the path to the directory where the 3d model file is located.
I cannot find the correct file path. Can you help me with this

let model = SceneLoader.Append("src/components/DemoGame/assets/models/", "flower-yellow.glb", scene, function (model) {
        console.log('SCENE', model)
    })

**Comment by 1zilc** [comment]
I happened to encounter a similar problem, this is my solution：
`.erb/configs/webpack.config.base.ts`
```
     // model
      {
        test: /\.(glb|gltf|bin)$/,
        type: 'asset/resource',
      },
```
then  `import Model from 'src/components/DemoGame/assets/models/flower-yellow.glb';`

```
 const model = await BABYLON.SceneLoader.ImportMeshAsync('', Model);
```
