### ISSUE TITLE
ERB not working with the newest Tailwind, v3.0 

### ISSUE THREAD

**Issue by Solias99** [electron-react-boilerplate/electron-react-boilerplate#3067]
## Summary

Looks like ERB is not working with Tailwind's latest update, v3.0 (Was released ~7 days ago IIRC)
Any guidance on how to get it working, or if an update is in the pipeline, will be super helpful. Thanks!

P.S in the meanwhile, am I expected to use Tailwind 2.2.19?

**Comment by TheBoringDude** [comment]
It works just fine for me though.

**Comment by sbaum23** [comment]
I had to add the following to my `tailwind.config.js` to get version 3 working:

```
content: ["./src/**/*.{js,jsx,tsx}"],
```

So, my full `tailwind.config.js` looks like this:

```
import colors from "tailwindcss/colors"

module.exports = {
  content: ["./src/**/*.{js,jsx,tsx}"],
  darkMode: 'media', // or 'class'
  theme: {
    extend: {
      colors: {
        sky: colors.sky,
        cyan: colors.cyan,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

**Comment by Solias99** [comment]
@amilajack doesn't work

**Comment by Lermatroid** [comment]
I can't seem to get it working either, have you found anything in the last couple of hours?

**Comment by Lermatroid** [comment]
I can't seem to get it working either, have you found anything in the last couple of hours @Solias99?

**Comment by Solias99** [comment]
Somewhat erratic behaviour @Lermatroid

I was able to get it to work in 1 project, but not in another with the same file config. Might be webpack dependency versions, not sure. I'm investigating.

**Comment by Solias99** [comment]
Hey guys, @amilajack @Lermatroid looks like removing `purge: []` from the Tailwind config solved everything. 
Would really like an explanation for why and how this works, thanks.

**Comment by AlexMenor** [comment]
I made it work without removing purge. In my case what I had to do was to include it in the second rule instead of the first.

**Comment by masonlee** [comment]
For anyone else arriving here via google, the ERB docs (mentioned above by @rohanmayya) do now describe how to use Tailwind 3 with ERB. Works for me, at least.  https://electron-react-boilerplate.js.org/docs/styling#custom-tailwind-config

**Comment by LennyTheIntern** [comment]
I fallow the instructions here, https://electron-react-boilerplate.js.org/docs/styling#custom-tailwind-config. but then the app breaks and i get this error

```
\your-project-name\node_modules\tailwindcss\tailwind.css Unknown word

  1 |
> 2 |       import API from "!../style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../style-loader/dist/runtime/insertBySelector.js";
```

Googling around sugests that the problem is in tailwind.config.js but im not sure what would be wrong with it in my case

**Comment by wbhob** [comment]
<img width="1333" alt="Screenshot 2023-04-11 at 1 20 01 PM" src="https://user-images.githubusercontent.com/4442130/231279148-3c06387b-f1e4-4522-886b-ebccde61d2c4.png">

I'm also unable to get it to work and getting this strange error. Followed the instructions directly from the website, latest everything. This is the error I get from postinstall
