### ISSUE TITLE
Can't make VS debug working

### ISSUE THREAD

**Issue by FlorinDob** [electron-react-boilerplate/electron-react-boilerplate#3070]
I'm trying to make the project to work with debug form VS. 
The app is building and launching, but the debugger is not attaching.
Form what I can see from my limited web dev experience is that the task Start Webpack Dev is not finishing and therefore the debugging is not attaching . 
Please see the attached imaged.
If you need more info please ask.

Thanks a lot,
Florin 
![Screenshot 2021-12-18 224320](https://user-images.githubusercontent.com/1931813/146655016-9128d8af-89fd-44d3-8511-cdd2b7408087.png)

**Comment by FlorinDob** [comment]
Hey @amilajack , sorry to bother you. Do you have any idea ?

**Comment by amilajack** [comment]
See https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/428#issuecomment-956038679. Moving convo there.
