### ISSUE TITLE
I can't use cookies

### ISSUE THREAD

**Issue by LIMPIX31** [electron-react-boilerplate/electron-react-boilerplate#3071]
With the switch to the new ERB version, I can't use cookies. ERB either can't save them or can't send them. I use Axios as a library for API requests.

I use the same code in browser and ElectronJS and made sure that cookies doesn't work in ElectronJS. I'm writing this issue here, because it occurred when I switched to a new version of ERB.

```ts
checkAuth() {
    return axios
      .get<APIResponseType<LoginResponseType>>(
        `${ApiManager.APIUrl}auth/refresh`,
        {
          withCredentials: true,
          timeout: 5000
        }
      )
      .then(res => res.data)
      .catch(handleCatchError)
```

**Comment by amilajack** [comment]
The only change that might have caused this is the electron upgrade.

> The main electron process is a NodeJS process, not a Chromium process, and is not restricted by CORS; The rendering process is a Chromium process, which is restricted by CORS. By running axios in the main process, you can break through CORS and read and modify cookies instead.



Try taking a look at these resources:

* https://github.com/axios/axios/issues/943
* https://www.electronjs.org/docs/latest/api/cookies
