### ISSUE TITLE
Error using serialport...

### ISSUE THREAD

**Issue by laolaolulu** [electron-react-boilerplate/electron-react-boilerplate#3075]
## Summary

(Use `electron --trace-warnings ...` to show where the warning was created)
11:05:28.651 > Skip checkForUpdatesAndNotify because application is not packed
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
ERROR in ./node_modules/@serialport/bindings/lib/darwin.js 1:22-37
Module not found: Error: Can't resolve 'util' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/@serialport/bindings/lib/index.js 10:4-40
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/linux-list.js 1:21-45
Module not found: Error: Can't resolve 'child_process' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'
 @ ./node_modules/@serialport/bindings/lib/linux.js 4:18-41
 @ ./node_modules/@serialport/bindings/lib/index.js 14:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/linux.js 1:22-37
Module not found: Error: Can't resolve 'util' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/@serialport/bindings/lib/index.js 14:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/unix-read.js 1:11-24
Module not found: Error: Can't resolve 'fs' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'
 @ ./node_modules/@serialport/bindings/lib/linux.js 6:17-39
 @ ./node_modules/@serialport/bindings/lib/index.js 14:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/unix-read.js 4:22-37
Module not found: Error: Can't resolve 'util' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/@serialport/bindings/lib/linux.js 6:17-39
 @ ./node_modules/@serialport/bindings/lib/index.js 14:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/unix-write.js 1:11-24
Module not found: Error: Can't resolve 'fs' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'
 @ ./node_modules/@serialport/bindings/lib/linux.js 7:18-41
 @ ./node_modules/@serialport/bindings/lib/index.js 14:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/unix-write.js 4:22-37
Module not found: Error: Can't resolve 'util' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/@serialport/bindings/lib/linux.js 7:18-41
 @ ./node_modules/@serialport/bindings/lib/index.js 14:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/bindings/lib/win32.js 3:22-37
Module not found: Error: Can't resolve 'util' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\bindings\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/@serialport/bindings/lib/index.js 6:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/parser-byte-length/lib/index.js 1:22-39
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\parser-byte-length\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/parsers.js 2:14-55
 @ ./node_modules/serialport/lib/index.js 3:16-36
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/parser-cctalk/lib/index.js 1:22-39
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\parser-cctalk\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/parsers.js 3:10-46
 @ ./node_modules/serialport/lib/index.js 3:16-36
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/parser-delimiter/lib/index.js 1:22-39
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\parser-delimiter\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/parsers.js 4:13-52
 @ ./node_modules/serialport/lib/index.js 3:16-36
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/parser-inter-byte-timeout/lib/index.js 1:22-39
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\parser-inter-byte-timeout\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/parsers.js 5:20-68
 @ ./node_modules/serialport/lib/index.js 3:16-36
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/parser-ready/lib/index.js 1:22-39
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\parser-ready\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/parsers.js 7:9-44
 @ ./node_modules/serialport/lib/index.js 3:16-36
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/parser-regex/lib/index.js 1:22-39
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\parser-regex\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/parsers.js 8:9-44
 @ ./node_modules/serialport/lib/index.js 3:16-36
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/stream/lib/index.js 1:15-32
Module not found: Error: Can't resolve 'stream' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\stream\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }
 @ ./node_modules/serialport/lib/index.js 1:19-48
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@serialport/stream/lib/index.js 2:13-28
Module not found: Error: Can't resolve 'util' in 'D:\codeup\electron-react-boilerplate-main\node_modules\@serialport\stream\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }
 @ ./node_modules/serialport/lib/index.js 1:19-48
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/bindings/bindings.js 5:9-22
Module not found: Error: Can't resolve 'fs' in 'D:\codeup\electron-react-boilerplate-main\node_modules\bindings'
 @ ./node_modules/@serialport/bindings/lib/win32.js 1:16-35
 @ ./node_modules/@serialport/bindings/lib/index.js 6:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/bindings/bindings.js 6:9-24
Module not found: Error: Can't resolve 'path' in 'D:\codeup\electron-react-boilerplate-main\node_modules\bindings'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./node_modules/@serialport/bindings/lib/win32.js 1:16-35
 @ ./node_modules/@serialport/bindings/lib/index.js 6:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/file-uri-to-path/index.js 6:10-29
Module not found: Error: Can't resolve 'path' in 'D:\codeup\electron-react-boilerplate-main\node_modules\file-uri-to-path'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./node_modules/bindings/bindings.js 7:18-45
 @ ./node_modules/@serialport/bindings/lib/win32.js 1:16-35
 @ ./node_modules/@serialport/bindings/lib/index.js 6:4-39
 @ ./node_modules/serialport/lib/index.js 2:16-47
 @ ./src/renderer/App.tsx 14:37-58
 @ ./src/renderer/index.tsx 10:30-46

webpack compiled with 19 errors
Not rewriting GET /index.html because the path includes a dot (.) character.

**Comment by amilajack** [comment]
Serialport is a native dependency, which means it requires node in your renderer context. Run it in your main process and use IPC to communicate to your renderer process.

See the electron-store example
https://electron-react-boilerplate.js.org/docs/electron-store

**Comment by Astrojoinl** [comment]
They add a renderer process functionality that appers not work with webpack: [https://github.com/serialport/electron-serialport/tree/master](url)
