### ISSUE TITLE
How to include css and js if you have purchased a ready-made template?

### ISSUE THREAD

**Issue by javi20gu** [electron-react-boilerplate/electron-react-boilerplate#3077]
## Summary

Good, I have a question, I bought a template, the typical internet portfolio, of course ahi me come css and js files, as I could integrate it, because when hahcerlo in the index.ejs gives me error, tells me that only supports html/text, greetings!

**Comment by javi20gu** [comment]
![image](https://user-images.githubusercontent.com/33096723/147385321-1f7f83dc-3abd-4f4f-b051-5c2a3262d89f.png)

**Comment by amilajack** [comment]
Every template is different so unfortunately I can't answer this. Closing since this is out of the scope of the boilerplate.

**Comment by saberjsd** [comment]
HI, @javi20gu I have the same question. Did you have solution? [issues#2116](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3107)

**Comment by javi20gu** [comment]
Hi, the only solution I can think of is to integrate the Webpack plugin CopyWebpackPlugin, best regards!

**Comment by saberjsd** [comment]
@javi20gu Hi, Sorry for the late reply, I'm too busy working.
Thank you very much for helping me.
I solved the problem no need other package, 
[This is the pull request](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3129/commits/910a0d7c3e37db80ed84fd5e8ada00c31d0fe238)

**Comment by k1er** [comment]
thanks a lot, solve my issue
