### ISSUE TITLE
How to modify .env or make some app.settings.json file for AppImage

### ISSUE THREAD

**Issue by MonsieurPatate** [electron-react-boilerplate/electron-react-boilerplate#3078]
## Summary

Hi,

I've packaged app for linux, so the application extension is `AppImage` and it holds `.env` file with the settings that I've set before packaging and now I'd like to modify `.env` file. How I can achieve this?

Thanks in advance

**Comment by amilajack** [comment]
I highly recommend using [electron-settings](https://www.npmjs.com/package/electron-settings). It has different configs for packaged and dev versions of your electron app.

**Comment by MonsieurPatate** [comment]
Thanks, @amilajack , I've read about it and now I'm struggling with another problem)

**Comment by amilajack** [comment]
What's the other problem?

**Comment by MonsieurPatate** [comment]
> What's the other problem?
I described it [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3081)
For now I use navbar from `react-bootstrap`
Thanks for reply =)
