### ISSUE TITLE
ERB not working on Mac with existing project

### ISSUE THREAD

**Issue by Solias99** [electron-react-boilerplate/electron-react-boilerplate#3080]
## Summary

I cloned an existing project (was working on Windows so far) on my Mac.

After cloning, running npm install and then trying to start, I get:

```
/Users/username/my-app/node_modules/webpack-sources/lib/ReplaceSource.js:166
                                content = content.match(SPLIT_LINES_REGEX) || [];
                      ^
RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at checkOriginalContent (/Users/username/my-app</anonymous>/node_modules/webpack-sources/lib/ReplaceSource.js:166:23)
    ...
```

Seems like a repeat of the issue here:
https://stackoverflow.com/questions/70308969/react-electron-app-webpack-sources-maximum-call-stack-size-exceeded

Any thoughts?

**Comment by amilajack** [comment]
See https://github.com/webpack/webpack-sources/issues/131. You'll probably need to upgrade webpack and related webpack dependencies

**Comment by Solias99** [comment]
I'll look into this and get back to you

**Comment by amilajack** [comment]
Sure, comment and I'll reopen
