### ISSUE TITLE
Render component in a new window or React-Route from the electron menu(submenu) bar

### ISSUE THREAD

**Issue by MonsieurPatate** [electron-react-boilerplate/electron-react-boilerplate#3081]
## Summary

I've created test files like the `App` ones:
![image](https://user-images.githubusercontent.com/3740644/147566564-04577527-f7d2-47fb-be55-ccd4dc2d140d.png)

Then I've created new menu item and tried to use `resolveHtmlPath` function from the **main.ts** file:
```
buildDefaultTemplate() {
    const templateDefault = [
              ..................................................................
    {
        label: 'Settings',
        click: () => {
          let win = new BrowserWindow({ width: 600, height: 800 });
          win.removeMenu();
          win.loadURL(resolveHtmlPath('test.html'));
        },
      },
```

And got an error:
![image](https://user-images.githubusercontent.com/3740644/147566743-c3944be5-9c59-410b-8a22-e092a5e8726b.png)

Then I've tried to modify **webpack.config.renderer.dev.ts** file:
```
const configuration: webpack.Configuration = {
  devtool: 'inline-source-map',

  mode: 'development',

  target: ['web', 'electron-renderer'],

  entry: [
    `webpack-dev-server/client?http://localhost:${port}/dist`,
    'webpack/hot/only-dev-server',
    'core-js',
    'regenerator-runtime/runtime',
    path.join(webpackPaths.srcRendererPath, 'index.tsx'),
    path.join(webpackPaths.srcRendererPath, 'test.tsx'), <--------------- ADDED THIS LINE
  ],
```
And now at the start of the program `test.html` page loads by default, don't understand why, but the `settings` menu item still does'nt render anything:
![image](https://user-images.githubusercontent.com/3740644/147566920-83de0362-5200-4f24-b557-8b7c71b6342f.png)

Then I added this in plugins section of **webpack.config.renderer.dev.ts**:
```
new HtmlWebpackPlugin({
      filename: path.join('test.html'),
      template: path.join(webpackPaths.srcRendererPath, 'test.ejs'),
      minify: {
        collapseWhitespace: true,
        removeAttributeQuotes: true,
        removeComments: true,
      },
      isBrowser: false,
      env: process.env.NODE_ENV,
      isDevelopment: process.env.NODE_ENV !== 'production',
      nodeModules: webpackPaths.appNodeModulesPath,
    }),
```
And now on main page and child window I get only `test.html`:
![image](https://user-images.githubusercontent.com/3740644/147567150-18ec3a4c-b7e0-4b18-b8ce-1d277cc38483.png)

How I can make it to render normally or how I can use `react-route` from the electron menu(submenu) items?

Any help please? I'm stuck =(

**Comment by amilajack** [comment]
You're trying to create a 2nd renderer window. I put together [an example of a 2nd renderer window](https://github.com/amilajack/erb-second-renderer-window-example) but it's a bit outdated, however the same principles apply.

Look at commit range 874dbb8a1fa9c357beff2d3fc57915aa754d374d .. ce36e560363c6f9ad334e628ee34da3d33a88e71

**Comment by ErikEBZ** [comment]
when you create the HtmlWebpackPlugin for each entry you need to add:
`chunks: ['window1'],` where window1 must be replaced with the entry name, this way each window loads only it's generated script.

**Comment by amilajack** [comment]
Closing but feel free to continue the conversation

**Comment by xiajingren** [comment]
hi @amilajack . I tried creating a second window, navigating it to another component, but the router doesn't work


main.ts:
```typescript
this.floatingWindow = new BrowserWindow({
      show: false,
      width: 200,
      height: 200,
      type: 'toolbar',
      frame: false,
      resizable: false,
      minimizable: false,
      maximizable: false,
      skipTaskbar: true,
      transparent: true,
      alwaysOnTop: true,
      useContentSize: true,
      webPreferences: {
        preload: path.join(__dirname, 'preload.js'),
      },
    });

    this.floatingWindow.loadURL(resolveHtmlPath('index.html/#/floating'));
```

App.tsx:
```
return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Router>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/floating" element={<Floating />} />
        </Routes>
      </Router>
    </ThemeProvider>
  );
```

but it always goes to index.html:
`Rewriting GET /index.html/%23/floating to /index.html`

I looked at your example project, https://github.com/amilajack/erb-second-renderer-window-example 
but it hasn't been updated in a long time, is there a new reference? thanks a lot

**Comment by xiajingren** [comment]
solved. 
see:  https://github.com/ErikEBZ/erb-tailwindcss-two-windows

**Comment by dudu631** [comment]
@xiajingren I have the same issue, but couldn't figure it out with the link you provided. 

How do you pass a different path for Router to use?

**Comment by Ja-sonYun** [comment]
For those seeking a solution, consider using HashRouter
