### ISSUE TITLE
How to use sqlite sequalize inside boilerplate

### ISSUE THREAD

**Issue by HackersSpirit** [electron-react-boilerplate/electron-react-boilerplate#3083]
Hi, 
I tried using the following ORM inside the boilerplate [preload.js]
https://sequelize.org/master/manual/getting-started.html

Unable to find reference to implement the same.

**Comment by amilajack** [comment]
Please reference this example. https://github.com/amilajack/erb-sqlite-example

Invoke sqlite in main process and send query reults via IPC to renderer process
