### ISSUE TITLE
Tailwind CSS Not Working When Following Instructions in ERB Docs

### ISSUE THREAD

**Issue by Lermatroid** [electron-react-boilerplate/electron-react-boilerplate#3084]
Tailwind CSS seems to not be working in ERB, I found another person who is having a similar issue in #3067. I am using the latest versions of tailwind and ERB. There are no errors, styles just simply don't apply.

tailwind.config.js
```js
import colors from "tailwindcss/colors";

module.exports = {
  purge: [],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        sky: colors.sky,
        cyan: colors.cyan,
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
```

postcss.config.js
```js
const tailwindcss = require("tailwindcss");
const autoprefixer = require("autoprefixer");

module.exports = {
  plugins: [tailwindcss, autoprefixer],
};
```

webpack.config.renderer.dev.ts
```js
module: {
    rules: [
      {
        test: /\.s?css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
            },
          },
          'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                ident: 'postcss',
                plugins: [require('tailwindcss'), require('autoprefixer')],
              },
            },
          }
        ],
```

Any idea what the issue might be here?

**Comment by TheBoringDude** [comment]
I integrated Tailwind in here, can you try it? https://github.com/TheBoringDude/erb-tailwind

**Comment by Lermatroid** [comment]
Using the dev renderer webpack config you provided seems to work, any idea why that would be  @TheBoringDude?

**Comment by Solias99** [comment]
@Lermatroid could you do a diff check between the 2 files and check what's different?

Also could you try in a brand new project? I'm having the same issue but mine was randomly closed a few days ago.

**Comment by TheBoringDude** [comment]
> Using the dev renderer webpack config you provided seems to work, any idea why that would be @TheBoringDude?

I think you set the `postcss-loader` in a different config rule. Also, I always use the `jit` mode of Tailwind and I would need to set the `content` config of it.

**Comment by Lermatroid** [comment]
@Solias99 I am not able to send the diff right now but will try to send it tomorrow.

@TheBoringDude The postcss-loader might be it, also afaik JIT is enabled by default with v3+.

**Comment by Solias99** [comment]
Hey guys, @amilajack @Lermatroid looks like removing purge: [] from the Tailwind config solved everything.
Would really like an explanation for why and how this works, thanks.

**Comment by WachsenHaus** [comment]
I also saw this thread and solved it thank you so much

**Comment by amilajack** [comment]
@WachsenHaus awesome! What was the solution?

**Comment by rlempa** [comment]
Based on the above comments (@TheBoringDude), I'm posting this for people (like me) that search for a copy-pasted solution. Replace only the `module` key.

File `webpack.config.renderer.dev.ts`:

```module: {
    rules: [
      {
        test: /\.s?css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
            },
          },
          'sass-loader',
        ],
        include: /\.module\.s?(c|a)ss$/,
      },
      {
        test: /\.s?css$/,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [require('tailwindcss'), require('autoprefixer')],
              },
            },
          },
        ],
        exclude: /\.module\.s?(c|a)ss$/,
      },
      // Fonts
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: 'asset/resource',
      },
      // Images
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: 'asset/resource',
      },
    ],
  },
```
  
File `webpack.config.renderer.prod.ts`:
```module: {
    rules: [
      {
        test: /\.s?(a|c)ss$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
            },
          },
          'sass-loader',
        ],
        include: /\.module\.s?(c|a)ss$/,
      },
      {
        test: /\.s?(a|c)ss$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader',
          {
            loader: 'postcss-loader',
            options: {
              postcssOptions: {
                plugins: [require('tailwindcss'), require('autoprefixer')],
              },
            },
          },
        ],
        exclude: /\.module\.s?(c|a)ss$/,
      },
      // Fonts
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: 'asset/resource',
      },
      // Images
      {
        test: /\.(png|svg|jpg|jpeg|gif)$/i,
        type: 'asset/resource',
      },
    ],
  },
  ```
@amilajack

**Comment by mithusingh32** [comment]
To add, if you're using nested CSS, you will also need to add that to you postcss and webpack configs. 

`const tailwindcss = require('tailwindcss');
const tailwindcssNesting = require('tailwindcss/nesting');
const autoprefixer = require('autoprefixer');

module.exports = {
  plugins: [tailwindcssNesting, tailwindcss, autoprefixer],
};
`

**Comment by marnixah** [comment]
In addtion to @rlempa's solution, I also needed to do the following to my tailwind.config.js:

- Remove ``purge: [],``
- Replace it with ``content: ['./src/renderer/**/*.{js,jsx,ts,tsx,ejs}'],``

After that it worked!

**Comment by uwemneku** [comment]
> I integrated Tailwind in here, can you try it? https://github.com/TheBoringDude/erb-tailwind

Thank you

**Comment by xs0521** [comment]
tailwind.config.js
content: ['./src/renderer/**/*.{js,jsx,ts,tsx,ejs}']

For beginners
Make sure your code is under the renderer folder


<img width="299" alt="Xnip2024-04-08_23-17-53" src="https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/12245582/a2b61b73-b74d-4e47-ba75-809037612efd">

**Comment by sidonaldson** [comment]
I found to fix it with the latest version and v3 tailwind I followed the changes in the example but moved tailwind.conf.js and postcss.config.js to the root of the project and then it works just fine
