### ISSUE TITLE
Incorrect rebuild task in package.json

### ISSUE THREAD

**Issue by aolsenjazz** [electron-react-boilerplate/electron-react-boilerplate#3087]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Running `npm run rebuild` rebuilds native dependencies

## Current Behavior

Running `npm run rebuild` outputs the following:

````
> rebuild
> electron-rebuild --parallel --types prod,dev,optional --module-dir src

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
ENOENT: no such file or directory, open '/Users/alexanderolsen/workspace/test/super-controller/src/package.json'

Error: ENOENT: no such file or directory, open '/Users/alexanderolsen/workspace/test/super-controller/src/package.json'
````

Rebuild task in package.json currently reads:

`electron-rebuild --parallel --types prod,dev,optional --module-dir src`

and should read:

`electron-rebuild --parallel --types prod,dev,optional --module-dir release/app`

Happy to open a PR to fix this if it would help. Thanks again for the work all of the maintainers do.

**Comment by amilajack** [comment]
Thanks for catching this. Fixed in fea054d844397bd2f0b0b5cce1202acc7236fb19
