### ISSUE TITLE
Open a second render window that loads a react route

### ISSUE THREAD

**Issue by ErikEBZ** [electron-react-boilerplate/electron-react-boilerplate#3089]
## Summary

I'm trying to implement the steps described in [erb-second-renderer-window-example ](https://github.com/msansoni/erb-second-renderer-window-example) to the current version of erb with tailwindscss and the posibility to open a second window. I have already managed to get tailwidincss working but i'm having trouble to get a second window open this is what i have already done:

- In `main.ts` add a declaration for  the second window.
- moved the content of mainWindow to window1 and copied its content to another dir named window2.
- In `webpack.config.renderer.dev.ts` added the entry for window1 but in line 143 where HtmlWebpackPlugin is created i had to hard-code the route `window1/index.html` but i don't know how i can get it to work for both windows.

I would like to receive some help/guidance on how to do this properly and if it goes well make this as an update o the current example i mentioned above.

In this repo i uploaded all i have done in case it helps: https://github.com/ErikEBZ/erb-tailwindcss-two-windows

In other issues i read about creating the corresponding webpack config files for the second window but i don't know if that is really necessary.

Also i would like to wish you all a happy new year :)

**Comment by ErikEBZ** [comment]
In case someone is interested it's already working so this issue can be closed.

**Comment by xiajingren** [comment]
hi @ErikEBZ  . This solved my problem, thank you !
