### ISSUE TITLE
when i npm run package

### ISSUE THREAD

**Issue by NTnewStudent** [electron-react-boilerplate/electron-react-boilerplate#3090]
## Summary

when i npm run package
error:

[1] npm run build:renderer exited with code 0
  • electron-builder  version=22.14.5 os=10.0.19044
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=release\build\builder-effective-config.yaml
  • installing production dependencies  platform=win32 arch=x64 appDir=E:\pcwork\reactboilepale\electron-react-boilerplate-main\release\app
  • packaging       platform=win32 arch=x64 electron=16.0.5 appOutDir=release\build\win-unpacked
  **⨯ Get "https://github.com/electron/electron/releases/download/v16.0.5/electron-v16.0.5-win32-x64.zip": proxyconnect tcp: dial tcp :0: connectex: The requested address is not valid in its context.**

How can i solve this problem

**Comment by amilajack** [comment]
This isn't an issue with the boilerplate. This is likely a bug with GitHub's release download service.

**Comment by Cornstar23** [comment]
I saw this somewhere else and it worked:
Added NO_PROXY = * in environment variables.

**Comment by dilshod1d** [comment]
Hi have you found solution???
