### ISSUE TITLE
Can't import native packages in the main proccess

### ISSUE THREAD

**Issue by denexapp** [electron-react-boilerplate/electron-react-boilerplate#3093]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] (N/A) Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] (N/A) For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

A native package gets imported

## Current Behavior

It shows an error message: "Cannot find module 'package-name'"

## Steps to Reproduce

1. Add any package to `release/app`, I've tried `fluent-ffmpeg`, `@ffprobe-installer/ffprobe` and `ffprobe-static-electron`
```
npm install -D @types/fluent-ffmpeg
cd ./release/app
npm install fluent-ffmpeg
```

2. Import it into `src/main/main.ts`
```
// src/main/main.ts

import ffmpeg from 'fluent-ffmpeg';
```

3. Use the imported package, i.e. `console.log(package-name)`
```
// src/main/main.ts

console.log(ffmpeg)
```

4. Start development mode, I press F5 in VS Code

## Possible Solution (Not obligatory)

I think recent changes have broke something

## Context

I was migrating from december 2021 version of this template to the latest january 2022 version. My goal was to make ffprobe work, but in the latest version seems like I can't use any native module at all.

## Your Environment

- Node version : 16.8.0
- electron-react-boilerplate version or branch : https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/eab36f9079c2494c75d70b2572b3e26740fc0db6
- Operating System and version : Windows 10 64 bit with latest updates

## Stacktrace

```
App threw an error during load
Error: Cannot find module 'fluent-ffmpeg'
Require stack:
- C:\Users\mukhametov.d\Code\your-project-name\src\main\main.ts
- C:\Users\mukhametov.d\Code\your-project-name\node_modules\electron\dist\resources\default_app.asar\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as 
_resolveFilename] (C:\Users\mukhametov.d\Code\your-project-name\node_modules\@cspotcode\source-map-support\source-map-support.js:679:30)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (C:\Users\mukhametov.d\Code\your-project-name\src\main\main.ts:19:1)  
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Module.m._compile (C:\Users\mukhametov.d\Code\your-project-name\node_modules\ts-node\src\index.ts:1371:23)
```

**Comment by amilajack** [comment]
Seems like the modules linker broke. It no longer runs on postinstall.

As a workaround, run it manually:

```
cd release/app
npm run link-modules
```

**Comment by amilajack** [comment]
I have confirmed that `electron-builder@22.13.1` works for me. `electron-builder@12.14.5` seems broken.

**Comment by denexapp** [comment]
I decided to stick to the december version of the template, you can close this issue or keep it to track this issue until electron-builder fixes it

**Comment by thekingofcity** [comment]
The workaround works perfectly for me:

```bash
cd release/app
npm run link-modules
```
