### ISSUE TITLE
Struggling to add a protocol to my electron-react app

### ISSUE THREAD

**Issue by rohanmayya** [electron-react-boilerplate/electron-react-boilerplate#3096]
## Summary

I'm following this guide:
https://www.electronjs.org/docs/v14-x-y/tutorial/launch-app-from-url-in-another-app

To handle Google OAuth from browser to my Electron app. Using firebase for this purpose.
When I try to open my Electron app using a protocol (eg: `electron-fiddle://data`) 

I get the following error:
![image](https://user-images.githubusercontent.com/32911377/148028341-d11d7bb1-013f-4748-8161-d685bf41efdd.png)

Any thoughts?

Edit: I should probably mention that this is only happening on my Windows machine. Mac seems fine.

**Comment by amilajack** [comment]
Are you still running into this issue?

**Comment by Solias99** [comment]
On my current version of erb, yes. 
Should I try pulling latest and trying?

**Comment by amilajack** [comment]
https://electron-react-boilerplate.js.org/docs/roadmap
