### ISSUE TITLE
Image doesn't remain after navigating back from a new component.

### ISSUE THREAD

**Issue by Reply2Zain** [electron-react-boilerplate/electron-react-boilerplate#3098]
## Prerequisites

- [X] Using npm
- [X] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [X] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [X] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [X] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

When going from the home page to a separate page and then back to the home page, the image should have remained.

## Current Behavior

Within the packaged build, any image on the homepage becomes unfound after navigating to a different component. 

## Steps to Reproduce

1. Add an image using an img tag within the renderer referencing a local image file. 
2. Package the electron-react-boilerplate. 
3. Launch the packaged app.
3. Navigate to a the component with the image and then a different component (using Router) and then return back to the component with the image. The image would then be missing with only the alt text appearing.

My image tag:
`   <img
          style={{ margin: '50px', width: '30%', height: '30%' }}
          src={logo}
          className="App-logo"
          alt="logo"
        />`

## Context

I would like the image to remain when I go back to the home screen. Instead the image 'alt' remains.

I made minimal changes to the boilerplate. I mainly just added my react code to the render directory. 

## Your Environment

- Node version : v16.13.0
- electron-react-boilerplate version or branch : 4.5.0
- Operating System and version : macOS Montery
- Link to your project : can be provided upon request

**Comment by flash716** [comment]
@Reply2Zain I am seeing a similar issue. How did you resolve this?
