### ISSUE TITLE
Implementing express js server with sqlite in production app.

### ISSUE THREAD

**Issue by fiicode** [electron-react-boilerplate/electron-react-boilerplate#3099]
I want my application to work online and offline. Online I use a remote server, if the application is offline I want it to use a local server in `sqlite` to save the data without interruptions.
In development everything works fine, I use `expressjs` with `sqlite` and `pm2` to launch the server.
`execSync('./node_modules/.bin/pm2 start src/server.js')`

**How to build to launch the local server sqlite works in production ?**

**Comment by amilajack** [comment]
This is almost identical to the run-time asset doc example:
https://electron-react-boilerplate.js.org/docs/adding-assets/#run-time-assets

**Comment by fiicode** [comment]
@amilajack Thank you for your answer.
I placed the referenced files in the package.json build

<img width="448" alt="Capture d’écran 2022-01-07 à 19 38 57" src="https://user-images.githubusercontent.com/16849426/148597877-839e3fe4-5636-4867-8fff-15f2d9b1d4ec.png">

In production I have this error

<img width="419" alt="Capture d’écran 2022-01-07 à 19 51 42" src="https://user-images.githubusercontent.com/16849426/148599270-65d33ddc-9907-4e07-8daa-b67957715235.png">

I have no idea if the build worked or not!
Need help

**Comment by kbrisso** [comment]
Why don't you start your remote ExpressJS server in a another project? Are you going to bundle it with the app itself? If not it should be its own project/package.  You can reference/use the remote server like an API server and call the API through the Electron main.js file if needed.

**Comment by fiicode** [comment]
@kbrisso Thank you for your answer.

The application uses a remote server with an `API`. My problem is that I want the application to run in online/offline mode without interruption to the client. In offline mode, I use sqlite to temporarily save the data with the same remote architecture.

I tried several approaches for this problem to try to launch the local server with `localhost` followed by the port after build for the client via `node`, `nodemon`, `pm2` but still without success as these commands are not recognized. In development mode, everything works fine.

My question is: is it possible to launch a local server like `localhost:3000` with the builder application for the client?

the other question. **after building the application for the client, what is the relative path to the folder well in `node_modules`?**
**And what module launches react when the action is builder?**
`/Applications/myApp.app/Contents/Frameworks/myApp Helper (Renderer).app/Contents/MacOS/myApp Helper (Renderer)`

**Comment by kbrisso** [comment]
ERB uses Webpack you are going to have to do some research on where to put the start up config/cmd. ERB dev server is started in webpack.config.renderer.dev.ts - the port info is in the file too.  You can script Express port in a similar way in regards to your question about ports.

Here is a SO question about this topic, maybe this can help you figure it out. 
https://stackoverflow.com/questions/35233291/running-a-node-express-server-using-webpack-dev-server

Again..unless you really need the API started in this script. I would start the API outside this project. You can create a shell or bat file to start both. Hacking it into Webpack will slow down the start time of ERB - and slow dev time down.  With two processes/ cmd windows you can test/simulate API failure by shutting it down and leaving other process on.

**Comment by fiicode** [comment]
finally I used `electron-store` [here](https://github.com/sindresorhus/electron-store) to save the data temporarily.
