### ISSUE TITLE
Can't load image from assets folder

### ISSUE THREAD

**Issue by pierretusseau** [electron-react-boilerplate/electron-react-boilerplate#3101]
## Summary

I successfully get the path to an image with ```path.join(__dirname,`../../assets/collectibles/collectibles_${newItemID}.png`)``` in my `main.ts` file.

But when I try to use it as a `<img src={image} alt="some image" />` in a React component I get this error in inspector :

`Not allowed to load local resource: file:///C:/Pro/www/ansuz/assets/collectibles/collectibles_105.png`

When I Copy/paste this exact URL (or without `file:///` protocol) directly into a chrome browser it does show me the correct image, so I guess the path is right, but my front can't access the file

I followed https://electron-react-boilerplate.js.org/docs/adding-assets and added `"assets/"` inside the `package.json['build']['file']` array

Did I miss something important ?

**Comment by pierretusseau** [comment]
I succeeded by using base64 as such in my `main.ts` :
```
const contents = fs.readFileSync(
    path.join(
      __dirname,
      `../../assets/collectibles/collectibles_${imagePath}.png`
    ),
    { encoding: 'base64' }
  );
``` 

And in my front : 
```
<img
        src={`data:image/png;base64, ${item.image}`}
        alt={`Item ${item.ID}`}
/>
```

I don't know if it's good practice but it's working.

I wonder if `assets/"` inside the `package.json['build']['file']` array is necessary. I didn't not clearly understand it's role in the docs.

**Comment by sytolk** [comment]
images with  file:///C:/Pro/www/ansuz/assets/collectibles/collectibles_105.png is loaded successfull in production build. look: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3558
You cannot use fs in renderer with default electron webPreferences: nodeIntegration: false
