### ISSUE TITLE
Anyone have a working example of Context Isolation in TypeScript?

### ISSUE THREAD

**Issue by paragbaxi** [electron-react-boilerplate/electron-react-boilerplate#3105]
Anyone have a working example of [Context Isolation in TypeScript](https://www.electronjs.org/docs/latest/tutorial/context-isolation#usage-with-typescript)? 

I tried

`renderer/renderer.d.ts`
```
export interface IElectronAPI {
  loadPreferences: () => Promise<void>;
}

declare global {
  interface Window {
    electronAPI: IElectronAPI;
  }
}
```

`renderer/App.tsx`
```
...
window.electronAPI.loadPreferences();

const Hello = () => {
  const paylocityLogin = () => {
    window.electron.ipcRenderer.on('ipc-example', (arg: string) => {
      // eslint-disable-next-line no-console
      console.log(arg);
    });
  };
...
```

vscode still giving error on `electron`:
`Property 'electron' does not exist on type 'Window & typeof globalThis'. Did you mean 'Electron'?ts(2551)`

_Originally posted by @paragbaxi in https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3016#issuecomment-1008403170_

**Comment by ajaynair1998** [comment]
Hi did you find the solution

**Comment by paragbaxi** [comment]
Yes, it's working now. Example here:

https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3016#issuecomment-1008677150
