### ISSUE TITLE
How Can I import other umd bundle library like `Luckysheet`

### ISSUE THREAD

**Issue by saberjsd** [electron-react-boilerplate/electron-react-boilerplate#3107]
### I want use the library [Luckysheet](https://github.com/mengshukeji/Luckysheet). But this library is use old technology without `esm`. What should I do?

I try to import file in `/src/renderer/App.tsx` like this:
```js
  import "./lib/luckySheet/plugins/css/pluginsCss.css";
  import "./lib/luckySheet/plugins/plugins.css";
  import "./lib/luckySheet/css/luckysheet.css";
  import "./lib/luckySheet/assets/iconfont/iconfont.css";
  import "./lib/luckySheet/plugins/js/plugin.js";
  import "./lib/luckySheet/luckysheet.umd.js"
```
or like this in `/src/renderer/index.ejs`:
```html
    <link rel='stylesheet' href='/lib/luckySheet/plugins/css/pluginsCss.css' />
    <link rel='stylesheet' href='/lib/luckySheet/plugins/plugins.css' />
    <link rel='stylesheet' href='/lib/luckySheet/css/luckysheet.css' />
    <link rel='stylesheet' href='/lib/luckySheet/assets/iconfont/iconfont.css' />
    <script src="/lib/luckySheet/plugins/js/plugin.js"></script>
    <script src="/lib/luckySheet/luckysheet.umd.js"></script>
```

**Comment by saberjsd** [comment]
How can I use `public` path that can access by `localhost:port/public/somefile.js`

**Comment by Mad-hu** [comment]
1、\src\renderer\index.ejs  change  to index.html，or create index.html
2、add custom-made static resources file or folder.
exp:
![image](https://user-images.githubusercontent.com/13977755/150943669-f33af83f-0957-4ab4-9835-8adcf4a7e032.png)
![image](https://user-images.githubusercontent.com/13977755/150943847-f5e5d3b1-27b6-431b-a2b3-e10c69e992a4.png)
3、inject script element in body
```
 // static resources start . add anything by you self
  <script defer type="text/javascript" charset="utf-8" src="./static/js/start.js"></script>
  <script defer type="text/javascript" charset="utf-8" src="./static/js/aliplayer-min2.8.2.js"></script>
// static resources end
  <script defer>
    const scripts = [];

    if (process.env.NODE_ENV === 'development') {
      // Dynamically insert the DLL script in development env in the
      // renderer process
      scripts.push('../../.erb/dll/renderer.dev.dll.js');

      // Dynamically insert the bundled app script in the renderer process
      const port = process.env.PORT || 1212;
      scripts.push(`http://localhost:${port}/renderer.dev.js`);
      if (scripts.length) {
        document.write(
          scripts
            .map((script) => `<script defer src="${script}"><\/script>`)
            .join('')
        );
      }
    }
  </script>
```
exp:
![image](https://user-images.githubusercontent.com/13977755/150944481-b339262f-1602-4f1c-b324-6d6d14286df0.png)
All the renderer work is done！！！！
4、Modify the file .erb\configs\webpack.config.renderer.dev.ts
![image](https://user-images.githubusercontent.com/13977755/150946235-a40de45e-cb90-4df1-a5f0-24e93bebe15e.png)
![image](https://user-images.githubusercontent.com/13977755/150950442-0c1e1cda-9ec3-426f-a3bf-339999edc10f.png)
5、Modify the file .erb\configs\webpack.config.renderer.prod.ts
![image](https://user-images.githubusercontent.com/13977755/150950616-8d48fdca-4cc2-4ff2-97b4-ff9a38bd592d.png)
```
const CopyPlugin = require('copy-webpack-plugin');
```
![image](https://user-images.githubusercontent.com/13977755/150950895-8cb24fb2-b598-472c-8d52-0ec43aba5eae.png)
```
new CopyPlugin({
      patterns: [
        {
          from: path.join(webpackPaths.srcRendererPath, 'static'),  // static path
          to: path.join(webpackPaths.distRendererPath, '/static'),
        },
      ],
    }),
```
6、All the work is done！！！！ try again.

**Comment by saberjsd** [comment]
@Mad-hu Hi, Sorry for the late reply, I'm too busy working.
Thank you very much for helping me.
I solved the problem no need other package, 
[This is the pull request](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3129/commits/910a0d7c3e37db80ed84fd5e8ada00c31d0fe238)
