### ISSUE TITLE
How do I get react-router to actually navigate?

### ISSUE THREAD

**Issue by hoggworks** [electron-react-boilerplate/electron-react-boilerplate#3110]
## Summary

Hi, I'm trying to get the router to successfully reload the app to load a different route. I've tried both <Link to={'/path'}>Link</Link> and using the history object, both with the useHistory hook and using the prop passed via the router. It looks like the history object is being appended, but no redirection happens.

I've played around with some different react-router versions, but my current setup is:

"react-router": "^5.1.2",
"react-router-dom": "^5.1.2",

And in App.tsx, I've got:

```
import { MemoryRouter, Switch, Route } from 'react-router-dom';

import Editor from './editor/Editor.client';
import Explorer from './explorer/Explorer';

export default function App() {
  return (
    <MemoryRouter>
      <Switch>
        <Route path="/" component={Explorer} />
        <Route path="/editor" component={Editor} />
      </Switch>
    </MemoryRouter>
  );
}

```

Thanks!

**Comment by mithusingh32** [comment]
Do you have button/links on the app to navigate to it? 

Something like this:
```
 <Link to="/editor" >Editor</Link>
```

**Comment by hoggworks** [comment]
I do, yeah. I cloned the empty project and the routing works fine, so I must have done something to it. I'm going to copy my files over to the new repo and hope the routing remains functional.
