### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module fix-path/index.js from main.ts not supported. Instead change the require of index.js in main.ts to a dynamic import() which is available in all CommonJS modules.

### ISSUE THREAD

**Issue by mangei** [electron-react-boilerplate/electron-react-boilerplate#3112]
## Expected Behavior

Library import of [fix-path](
https://www.npmjs.com/package/fix-path) and its usage works.

## Current Behavior

Error on startup.

## Steps to Reproduce

1. Add the example code to main.ts
```
import fixPath from 'fix-path';
fixPath();
```

2. Build (`npm run build`) and Run (`npm run start`)

3. Error on startup

```
App threw an error during load
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/manuel/src/electron-react-boilerplate/node_modules/fix-path/index.js from /Users/manuel/src/electron-react-boilerplate/src/main/main.ts not supported.
Instead change the require of index.js in /Users/manuel/src/electron-react-boilerplate/src/main/main.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/Users/manuel/src/electron-react-boilerplate/node_modules/ts-node/dist/index.js:729:20)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (/Users/manuel/src/electron-react-boilerplate/src/main/main.ts:21:36)
    at Module.m._compile (/Users/manuel/src/electron-react-boilerplate/node_modules/ts-node/dist/index.js:735:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/manuel/src/electron-react-boilerplate/node_modules/ts-node/dist/index.js:737:16)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at loadApplicationPackage (/Users/manuel/src/electron-react-boilerplate/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/Users/manuel/src/electron-react-boilerplate/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:222:9)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Object.<anonymous> (node:electron/js2c/browser_init:193:3197)
    at Object../lib/browser/init.ts (node:electron/js2c/browser_init:193:3401)
    at __webpack_require__ (node:electron/js2c/browser_init:1:128)
    at node:electron/js2c/browser_init:1:1200
    at node:electron/js2c/browser_init:1:1267
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)

```

## Possible Solution (Not obligatory)

I tried the following, but no luck:

- adding `"type": "module"` in `package.json`
- lazy import `const fixPath = await import('fix-path'); fixPath();`
- use libary [fix-esm](https://www.npmjs.com/package/fix-esm)

## Your Environment

- Node version : v16.13.1
- electron-react-boilerplate version or branch : https://github.com/mangei/electron-react-boilerplate/commit/10e4462189620ef210ffc229111d51a140f19604
- Operating System and version : MacOS 12.1
- Link to your project : 

## Resources/Research

- [Pure ESM Package](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c)
- [standard-things/esm](https://github.com/standard-things/esm)
- [Dynamic import lands in Node.js, we can import ES6 modules in CommonJS code ](https://techsparx.com/nodejs/esnext/dynamic-import.html)
- [Stackify: NodeJS "Must use import to load ES Module"](https://stackify.dev/565384-nodejs-must-use-import-to-load-es-module)
- [[Solved] TypeError [ERR_INVALID_ARG_TYPE]: The “path” argument must be of type string. Received type undefined raised when starting react app](https://exerror.com/typeerror-err_invalid_arg_type-the-path-argument-must-be-of-type-string-received-type-undefined-raised-when-starting-react-app/)
- [standard-things/esm/issues/868: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module / require() of ES modules is not supported](https://github.com/standard-things/esm/issues/868)
- https://github.com/jason-henriksen/typescript-with-esm-no-babel-boilerplate
- [diauweb/esmRequire.js](https://gist.github.com/diauweb/f9f7be271ecc7bc0aecaf3dc891e18d2)
- [Level/level/issues/140: TypeError The "path" argument must be of type string. Received type undefined](https://github.com/Level/level/issues/140)

Thanks for your help! 👍

**Comment by mifi** [comment]
node_modules need to be included into webpack bundle, or wait for electron to support ESM.
See also: https://github.com/mifi/build-electron

**Comment by DittmerOk** [comment]
I still do not understand how to solve the problem. where is the solution?

**Comment by hanzlamateen** [comment]
I fixed this by adding lines in my `main.ts`
```
if (process.env.NODE_ENV === 'production') {
  const prodFixes = require('./prodFixes')
  prodFixes.loadProdConfigs();
}
```
And then creating a file `prodFixes.ts` with content:
```
import fixPath from 'fix-path'

export const loadProdConfigs = () => fixPath()
```

**Comment by thekingofcity** [comment]
What about native modules that are published in ESM? They are hard to be bundled in `webpack`. @mifi

**Comment by eherozhao** [comment]
I hit the same issue on an Electron project with `fix-path`.

**Comment by mifi** [comment]
@thekingofcity the js part of the modules is bundled while the native part of the module is obviously kept as is (my tool handles this)

**Comment by thekingofcity** [comment]
> the js part of the modules is bundled while the native part of the module is obviously kept as is (my tool handles this)

Is it possible to share more details about this approach? In which repo or which script did you manage to achieve this? Thanks in advance.

**Comment by kmturley** [comment]
You can use the previous version of the package:
```
npm install fix-path@v3.0.0
```

**Comment by thekingofcity** [comment]
> You can use the previous version of the package:

Thanks. But I'm dealing with a native module that has no previous CJS release.

**Comment by exerror8** [comment]
[[Solved] require() of ES modules is not supported using recharts](https://exerror.com/require-of-es-modules-is-not-supported-using-recharts/)

**Comment by raphael-dario** [comment]
> You can use the previous version of the package:
> 
> ```
> npm install fix-path@v3.0.0
> ```

this fixed it for me. was using v4.0.0 when issue appeared.

**Comment by Foddie2** [comment]
How do we solve this in Nuxt[3](https://nuxt.com/docs/getting-started/installation)

**Comment by bobbyadamski** [comment]
@Foddie2 add this to package.json

"resolutions": {
    "wrap-ansi": "7.0.0",
    "string-width": "4.1.0"
}

**Comment by Pet9948** [comment]
I have similar problem with WebToorent, nothing helps in solving this issue. Is there currently a solution to such a problem?

**Comment by kostia-lev** [comment]
cannot import any library to main.ts
