### ISSUE TITLE
how to get BrowserWindow from electron

### ISSUE THREAD

**Issue by hamidone** [electron-react-boilerplate/electron-react-boilerplate#3114]
hello
I can't speak English good, sorry

when:
`import electron from 'electron';`
electron not have 'BrowserWindow' function for get  webContents.getPrinters() in new version of electron-react-boilerplate

![1](https://user-images.githubusercontent.com/22000936/149660604-bc016e50-0100-432f-acdb-d1f67b05a18f.PNG)

I want webContents and getPrinters list

please help me! 
thanks

(i have last version of electron-react-boilerplate)

**Comment by Mad-hu** [comment]
electron 14 And a higher version 没有/ remove remote module。you 自己 install. 
```
// first install @electron/remote 
npm i -D @electron/remote

// main process
app.on('ready',function(){
+ require('@electron/remote/main').initialize();
+ require('@electron/remote/main').enable(mainWindow.webContents);  // set webcontents
mainWindow.loadFile('./index.html') // load page
})

next.
// render process
const { BrowserWindow } = require('@electron/remote');
```

**Comment by hamidone** [comment]
> 

thanks, worked for me!
very thanks
