### ISSUE TITLE
Auto update removed files

### ISSUE THREAD

**Issue by zaynekomichi** [electron-react-boilerplate/electron-react-boilerplate#3115]
Packed my app, ran it, it updated but when I opened it once again all my old files where gone shows the default template for electron react boilerplate

**Comment by TrofinSorin** [comment]
Happens to me also. It downloads 4.5.0 but with the default electron app that overwrites the actual app.

**Comment by TrofinSorin** [comment]
Sorry for the late reply, i'm not running into the same issue anymore, i've changed some things in package json and it's okay now.
