### ISSUE TITLE
how can i use preload in webview.

### ISSUE THREAD

**Issue by Mad-hu** [electron-react-boilerplate/electron-react-boilerplate#3117]
The current version
![image](https://user-images.githubusercontent.com/13977755/149917167-9f88ad49-c228-457b-b7a2-a54dd87ec22a.png)
The previous version
![image](https://user-images.githubusercontent.com/13977755/149917968-99778e15-0a5a-44d5-9c4e-a727d89688be.png)

help! help! Come and help me up!!

**Comment by Mad-hu** [comment]
#3107

**Comment by saberjsd** [comment]
@Mad-hu Hi, Sorry for the late reply, I'm too busy working.
Thank you very much for helping me.
I solved the problem no need other package, 
[This is the pull request](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3129/commits/910a0d7c3e37db80ed84fd5e8ada00c31d0fe238)

**Comment by gary123123** [comment]
How to solve this problem
