### ISSUE TITLE
keytar native module

### ISSUE THREAD

**Issue by akoskm** [electron-react-boilerplate/electron-react-boilerplate#3120]
I'm trying to use the keytar https://www.npmjs.com/package/keytar native module in an app built on top of electron-boilerplate.

As the documentation points out: https://electron-react-boilerplate.js.org/docs/native-modules/#what-are-native-modules

> Native modules in electron-react-boilerplate are installed to the ./release/app/node_modules directory and are copied into your electron app before it is packaged. 

That's why I assume that they should be also put into `./release/app/package.json`.

This approach works on windows, the app starts fine, however on macOS, I'm getting the following error:

```
% npm start                                  

> start
> ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer


> start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts

Starting Main Process...
(node:27384) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1212/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.0.10:1212/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:1212/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/akoskm/Projects/sprcalc-electron/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'

> start:main
> cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts

App threw an error during load
Error: Cannot find module 'keytar'
Require stack:
- /Users/akoskm/Projects/sprcalc-electron/src/oauth/tokenStorage.ts
- /Users/akoskm/Projects/sprcalc-electron/src/main/main.ts
- /Users/akoskm/Projects/sprcalc-electron/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/akoskm/Projects/sprcalc-electron/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/akoskm/Projects/sprcalc-electron/src/oauth/tokenStorage.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
    at Module.m._compile (/Users/akoskm/Projects/sprcalc-electron/node_modules/ts-node/src/index.ts:1371:23)
ERROR in /Users/akoskm/Projects/sprcalc-electron/src/oauth/tokenStorage.ts
1:19-27
[tsl] ERROR in /Users/akoskm/Projects/sprcalc-electron/src/oauth/tokenStorage.ts(1,20)
      TS2307: Cannot find module 'keytar' or its corresponding type declarations.
```

if I `ls` keytar in `release/app/node_modules` I see that it was installed:

```
% ls -l release/app/node_modules/keytar 
total 40
-rw-r--r--   1 akoskm  staff  1055 Jan 23 10:11 LICENSE.md
-rw-r--r--   1 akoskm  staff  3172 Jan 23 10:11 README.md
-rw-r--r--   1 akoskm  staff  1898 Jan 23 10:11 binding.gyp
drwxr-xr-x   3 akoskm  staff    96 Jan 23 10:11 build
-rw-r--r--   1 akoskm  staff  1777 Jan 23 10:11 keytar.d.ts
drwxr-xr-x   3 akoskm  staff    96 Jan 23 10:11 lib
-rw-r--r--   1 akoskm  staff  1670 Jan 23 10:11 package.json
drwxr-xr-x  10 akoskm  staff   320 Jan 23 10:11 src
```

If I move the keytar module to `./package.json` that works on macOS but breaks the Windows build.

I also tried `npm prune && npm rebuild` after reading https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/242#issuecomment-225312819 and it didn't help. I ended up with the same error.

**Comment by Mad-hu** [comment]
check link release/app/node_modules  to src/node_modules is done.
```

**Comment by akoskm** [comment]
Thanks, @Mad-hu, this is the output of the link-modules command:

```
% cd release/app 
akoskm@Akoss-MacBook-Pro app % npm run link-modules

> supersonic-desktop@1.1.9-snapshot link-modules /Users/akoskm/Projects/sprcalc-electron/release/app
> node -r ts-node/register ../../.erb/scripts/link-modules.js
```

I'm getting the same error after running this.

**Comment by amilajack** [comment]
@akoskm are you still running into this issue?

**Comment by Mad-hu** [comment]
您好：
      已经收到您的来信。
                            呼岩东

**Comment by akoskm** [comment]
@amilajack Yep, I just tested this and I'm getting the same errors. I didn't include in my original message only pointed out that when keytar is in the main package.json I'm getting this at the end of `npm i`:

```
 Webpack does not work with native dependencies.
keytar is a native dependency and should be installed inside of the "./release/app" folder.
 First, uninstall the packages from "./package.json":
npm uninstall your-package
 Then, instead of installing the package to the root "./package.json":
npm install your-package
 Install the package to "./release/app/package.json"
cd ./release/app && npm install your-package
 Read more about native dependencies at:
https://electron-react-boilerplate.js.org/docs/adding-dependencies/#module-structure
```

**Comment by akoskm** [comment]
@amilajack any idea how I should approach this problem?

**Comment by Mad-hu** [comment]
您好：
      已经收到您的来信。
                            呼岩东

**Comment by amilajack** [comment]
> @amilajack Yep, I just tested this and I'm getting the same errors. I didn't include in my original message only pointed out that when keytar is in the main package.json I'm getting this at the end of `npm i`:
> 
> ```
>  Webpack does not work with native dependencies.
> keytar is a native dependency and should be installed inside of the "./release/app" folder.
>  First, uninstall the packages from "./package.json":
> npm uninstall your-package
>  Then, instead of installing the package to the root "./package.json":
> npm install your-package
>  Install the package to "./release/app/package.json"
> cd ./release/app && npm install your-package
>  Read more about native dependencies at:
> https://electron-react-boilerplate.js.org/docs/adding-dependencies/#module-structure
> ```

the error message you quoted says how to resolve the issue

**Comment by akoskm** [comment]
@amilajack I'm sorry but the reason why I opened this issue is that the message I quoted doesn't work.

When the package is installed to "./release/app/package.json" I also get an error. See the issue.

**Comment by akoskm** [comment]
@ezequielvictor yes! In our case, the problem was in `release/app/package.json`.

There was this npm script:

```
"link-modules": "node -r ts-node/register ../../.erb/scripts/link-modules.js",
```

However, this file got turned into a TypeScript file at some point in the boilerplate code. When we moved to the nevest version of the boilerplate we missed updating the file extensions in the `link-modules` script:

```
"link-modules": "node -r ts-node/register ../../.erb/scripts/link-modules.ts",
```

**Comment by SantoshKumarRavi** [comment]
Even i tried to run link modules in release/app from root package.json, it again showing keytar undefined err.
I am using keytar in my renderer folder.

anyone knows how to solve this ?


my implementation
   "postinstall": "npm-run-all --parallel postinstall-root postinstall-release-app",
    "postinstall-root": "ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts && chmod +x .husky/pre-commit",
    "postinstall-release-app": "cd release/app && npm run postinstall",

**Comment by SantoshKumarRavi** [comment]
my release/app link-modules:
    "link-modules": "node -r ts-node/register ../../.erb/scripts/link-modules.ts"

still getting keytar undefined err

**Comment by Omar25py** [comment]
> my release/app link-modules: "link-modules": "node -r ts-node/register ../../.erb/scripts/link-modules.ts"
> 
> still getting keytar undefined err

You need to remover node_modules and npm install again
