### ISSUE TITLE
I created an electron application and installed it in MacBook, after closing the window by pressing x button on top left of application, it does not reopen from the dock directly.?? 

### ISSUE THREAD

**Issue by sameer12patwal** [electron-react-boilerplate/electron-react-boilerplate#3121]

**Comment by cameronSlupeiks** [comment]
I am also experiencing a similar issue on Windows. After installation, a shortcut gets added to the desktop and the application opens. Once I close the application, the shortcut icon becomes blank (I assume it's due to a path change).

**Comment by mangei** [comment]
Extend the `main.ts` to show the window:

```
app.on('activate', () => {
  if (mainWindow === null) {
    createWindow();
  } else {
    mainWindow?.show();
  }
});
```

**Comment by sameer12patwal** [comment]
Hello mangei, i have two browser windows in my electron application, will your code execute successfully in that case too, if it is used separately for both the windows.
