### ISSUE TITLE
core-js and regenerator-runtime purpose

### ISSUE THREAD

**Issue by aveeday** [electron-react-boilerplate/electron-react-boilerplate#3122]
## Summary

Documentation about `core-js` and `regenerator-runtime` says they need to support browser compatibility and support of old browsers but in electron app we have only one browser and with last electron we have last version, so it very confused to include libs for browsers compatibility in electron app.

Including these libs in bundle increased bundle size and slow down application startup time.

Both electron and react application can work without these libs, but why its required in electron react boilerplate?

Is it possible to remove these libs from bundle?

I tried to remove core-js from renderer bundle and looks like app works fine.
But when I removed regenerator-runtime then app started and shows only white screen.

Please provide some clarification

**Comment by amilajack** [comment]
Dropping them https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/chore/drop-polyfills
