### ISSUE TITLE
Changelog stuck on 2.1, current version on 4.5

### ISSUE THREAD

**Issue by mulgurul** [electron-react-boilerplate/electron-react-boilerplate#3124]
## Summary

The Changelog.md seems to have been forgotten since version 2.1. It might have to do with changing build pipeline to Github actions?
But there seem to be details on releases tab.
Is it possible to get it updated/maintained or should it just be dropped?

**Comment by amilajack** [comment]
Ideally this would be automated. Haven't spent the time to automate it

**Comment by amilajack** [comment]
I'll update it in the upcoming release
