### ISSUE TITLE
Shortcut icon on desktop goes blank and app gets deleted after closing app post-installation

### ISSUE THREAD

**Issue by cameronSlupeiks** [electron-react-boilerplate/electron-react-boilerplate#3126]
## Summary

After running the `Setup` executable within the `build` folder, a shortcut gets added to the desktop and the application opens. Once I close the application, the shortcut icon becomes blank and I cannot reopen the application (I assume it was deleted or it's path changed somehow). Any help in solving this issue would be much appreciated!

Device: Dell Latitude 7220 Rugged Extreme Tablet
OS: Windows 10 Pro
Dependencies:
```
"electron": "^15.3.0",
"electron-builder": "^22.13.1",
"electron-devtools-installer": "^3.2.0",
"electron-notarize": "^1.1.1",
"electron-rebuild": "^3.2.3",
```

**Comment by saberjsd** [comment]
Do you have anti-virus software installed on your computer? I've been in the same situation as you. Exit the anti-virus software, or find the interception record, restore!
good luck!
