### ISSUE TITLE
Fail to compile native modules

### ISSUE THREAD

**Issue by samu21req** [electron-react-boilerplate/electron-react-boilerplate#3128]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

`cd release/app && npm install fsuipc` from the electron docs for native modules.
When `npm start`, no errors.

## Current Behavior

When running `npm start` after having installed `cd release/app && npm install fsuipc`:
```
> start:main
> cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts


App threw an error during load
Error: The module '\\?\C:\Project\release\app\node_modules\fsuipc\build\Release\fsuipc.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 98. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at bindings (C:\Project\release\app\node_modules\fsuipc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Project\release\app\node_modules\fsuipc\main.js:1:35)
```

The native module does not compile to an electron version (the one required by the boilerplate is 98) but instead compiles to version 102 which is my current node.js version. From the docs I can't clearly see what I should execute to compile the module for node_module_version 98 (electron).

PD. See [abi version registry](https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json) for a list of node module versions.

## Steps to Reproduce

1. `cd release/app && npm install fsuipc`

2. `npm install`

3. `cd ../../ && npm start`

## Context

I need this module to work, but I can't seem to compile it to the requested version. Following electron's docs doesn't help.

Changes were made in the boilerplate after cloning, however same happens on boilerplate straight after cloning.

## Your Environment

- Node version : v17.4.0
- electron-react-boilerplate version or branch : main
- Operating System and version : Windows 10
- Link to native_module: https://github.com/koesie10/fsuipc-node

**Comment by samu21req** [comment]
I managed to manually compile the module to the required version but maybe this could be done automatically by the boilerplate's postinstall scripts? The process which I followed was:
1. `cd release/app && npm install fsuipc`
2. `cd node_modules/fsuipc`
3. `npm install`
4. `node-gyp rebuild --target=15.3.5 --arch=x64 --dist-url=https://electronjs.org/headers`
5. `cd ../../ && npm install`

Also set  `'win_delay_load_hook': 'true'` in the module's binding.gyp.

**Comment by Hidenaga41** [comment]
I'm facing the same problem. 

Node version : v16.13.0
electron-react-boilerplate version or branch : main
Operating System and version : ubuntu20.04
Link to native_module: [https://github.com/RobotWebTools/rclnodejs](https://github.com/RobotWebTools/rclnodejs)

**Comment by amilajack** [comment]
@samu21req

You may not have re-compiled correctly

```
NODE_MODULE_VERSION 102. This version of Node.js requires
NODE_MODULE_VERSION 98. Please try re-compiling or re-installing
```

Are you able to repro the issue on a fresh clone of the boilerplate?

**Comment by amilajack** [comment]
failing on specific os's is likely a library specific issue instead of an issue with the boilerplate. closing but feel free to continue the convo
