### ISSUE TITLE
Please bring back the old naming scheme for css classes

### ISSUE THREAD

**Issue by LIMPIX31** [electron-react-boilerplate/electron-react-boilerplate#3136]
![image](https://user-images.githubusercontent.com/81296950/153395431-4702d3dd-6c0c-4f2a-99f9-e5f2c469c233.png)
I expect `[name]__[local]___[hash:base64:5]`
How do I get the old schema back into the webpack?

**Comment by HyperClockUp** [comment]
you can change the css-loader config file in `/.erb/configs/webpack.config.renderer.dev.ts`.

add the property `localIdentName` as ` localIdentName: "[name]__[local]___[hash:base64:5]",`

[css-loader documentation](https://webpack.js.org/loaders/css-loader/#localidentname)
