### ISSUE TITLE
Unable to package for foreign OS

### ISSUE THREAD

**Issue by seandough3rty** [electron-react-boilerplate/electron-react-boilerplate#3138]
## Summary
I'm trying to package my app for Linux so that I can run it on my raspberry pi, but I develop the app on windows.
Whenever I try `$ npm run package --linux ` on my Win10 machine, it still packages for windows. As a test I also attempted `$ npm run package --mac` like the docs show, and it still compiles only for windows.

I could try to clone, build, and package on the pi, but I'd like to take advantage of my dev machine's speed.

**Comment by anniekatlin** [comment]
check this https://www.electron.build/multi-platform-build
