### ISSUE TITLE
Native modules do not build on ARMv7l, when there are multiple modules in package.json dependencies  (raspberry pi 4)

### ISSUE THREAD

**Issue by AshwinDeTaeye** [electron-react-boilerplate/electron-react-boilerplate#3139]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Project should be able to build native modules on ARMv7l (raspberry pi 4)
cd release/app && npm install from the electron docs for native modules.
When npm start, no errors.

## Current Behavior

Project doesn't build the native modules when they are all at the same time in package.json (release/app/)

## Steps to Reproduce

1. Clone this repo

2. Add following to the package.json (release/app): 
```
  "dependencies": {
    "spread-the-word": "^0.8.4",
    "websocket": "^1.0.34",
    "nfc-pcsc": "^0.8.1",
    "serialport": "^9.0.6"
  }
```
3. NPM install

4. Will result in error below on ARMv7l will work fine on x86-64 Linux

## Context

It's only possible to build the above on x86-64 (Linux). When i try to build it on ARMv7 (RPI4) it always fails.

However, when i add the native modules one by one, it does actually build all the modules but never when you list all the modules in a single package.json.

So following does build on ARM:
```
  "dependencies": {
    "spread-the-word": "^0.8.4"
  }
```
And every other native module works when i only build a single native module (only one in the dependencies list).

Below the error when the 4 modules are in the package.json. 
```
> electron-react-boilerplate@4.5.0 postinstall
> npm run electron-rebuild && npm run link-modules


> electron-react-boilerplate@4.5.0 electron-rebuild
> node -r ts-node/register ../../.erb/scripts/electron-rebuild.js


Error output:
- Searching dependency tree
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/home/pi/git/emptyErb/release/app/node_modules/utf-8-validate'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: You must run `node-gyp configure` first!



Error: node-gyp failed to rebuild '/home/pi/git/emptyErb/release/app/node_modules/utf-8-validate'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: You must run `node-gyp configure` first!
```

## Your Environment

- Node version : v16.3.1.
- electron-react-boilerplate version or branch : 14/02/2022
- Operating System and version : Linux, debian, raspberry pi 4 (armv7l)

**Comment by amilajack** [comment]
seems like this is an issue with the dependency's compatibility with electron. closing for now
