### ISSUE TITLE
Files in the `.erb` directory don't seem to be linted

### ISSUE THREAD

**Issue by gyorgy-kurucz-vacuum** [electron-react-boilerplate/electron-react-boilerplate#3140]
## Prerequisites

- [X] Using **yarn**
- [X] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
All files in the project, including the scripts and configs in the `.erb` directory are linted.

## Current Behavior
The files in the `.erb` directory don't seem to be linted. If I add `!.erb` to `.eslintignore`, I get linting errors:

```
/home/kgy/src/electron-react-boilerplate/.erb/configs/webpack.config.renderer.dev.ts
   11:1   error    `@pmmmwh/react-refresh-webpack-plugin` import should occur before import of `./webpack.config.base`  import/order
   21:29  warning  Forbidden non-null assertion                                                                         @typescript-eslint/no-non-null-assertion
  152:3   error    Do not use "@ts-ignore" because it alters compilation errors                                         @typescript-eslint/ban-ts-comment
  171:53  warning  Forbidden non-null assertion                                                                         @typescript-eslint/no-non-null-assertion

/home/kgy/src/electron-react-boilerplate/.erb/scripts/check-native-dep.js
  41:34  error  Replace `'cd·./release/app·&&·npm·install·your-package'` with `⏎··'cd·./release/app·&&·npm·install·your-package'⏎`  prettier/prettier

/home/kgy/src/electron-react-boilerplate/.erb/scripts/clean.js
  2:26  error  Unexpected use of file extension "ts" for "../configs/webpack.paths.ts"       import/extensions
  3:1   error  `process` import should occur before import of `../configs/webpack.paths.ts`  import/order

/home/kgy/src/electron-react-boilerplate/.erb/scripts/electron-rebuild.js
  1:8  warning  'path' is defined but never used  @typescript-eslint/no-unused-vars

/home/kgy/src/electron-react-boilerplate/.erb/scripts/link-modules.ts
  4:7   error  Use object destructuring  prefer-destructuring
  5:7   error  Use object destructuring  prefer-destructuring
  5:59  error  Insert `;`                prettier/prettier

/home/kgy/src/electron-react-boilerplate/.erb/scripts/notarize.js
  10:26  error  Replace `"true"` with `'true'`                                                                                                                                                                  prettier/prettier
  16:18  error  Replace `'Skipping·notarizing·step.·APPLE_ID·and·APPLE_ID_PASS·env·variables·must·be·set'` with `⏎······'Skipping·notarizing·step.·APPLE_ID·and·APPLE_ID_PASS·env·variables·must·be·set'⏎····`  prettier/prettier
```

## Steps to Reproduce
1. `yarn install`
2. Add `!.erb` to `.eslintignore`
3. `yarn lint`

## Context
I am adding some configs in the `.erb` directory, and would like them to be linted.

## Your Environment
- Node version : `v16.13.2`
- electron-react-boilerplate version or branch : 9ef120923cdfa85043aed2f7785c4ce9dac57f62

**Comment by gyorgy-kurucz-vacuum** [comment]
Note that ignoring hidden directories by default is a behavior of eslint: https://github.com/eslint/eslint/issues/8429

**Comment by amilajack** [comment]
Thanks for finding this. This would be a great first contribution. Feel freee to PR!

**Comment by gyorgy-kurucz-vacuum** [comment]
Thanks, I just wanted to confirm that this is an upstream issue first. I will try to make a PR here as well when we get around to fixing it on our project. (So as far as I can tell the fix should be as simple as including the `!.erb` rule I mentioned, and reformatting the files with it.)
