### ISSUE TITLE
Error after starting the newly cloned repo.

### ISSUE THREAD

**Issue by AlimovSV** [electron-react-boilerplate/electron-react-boilerplate#3144]
## Summary

```bash
git clone --depth=1 \
  https://github.com/electron-react-boilerplate/electron-react-boilerplate \
  your-project-name

cd your-project-name

npm install

npm start
```

The project runs but does not render the app and the console window has the error:

<img width="640" src="https://user-images.githubusercontent.com/4921904/155482727-39fdeb83-44f5-4aa8-a551-bfe4d86ba8b6.png">

I tried the next node versions, the result is the same:
- v16.14.0
- v14.19.0

**Comment by AlimovSV** [comment]
Found the workaround: removing [REACT_DEVELOPER_TOOLS](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/main/main.ts#L49) resolves this issue.

**Comment by AlimovSV** [comment]
looks like this issue is related to https://github.com/MarshallOfSound/electron-devtools-installer/issues/205

**Comment by amilajack** [comment]
solution is to upgrade devtools
https://electron-react-boilerplate.js.org/docs/dev-tools/#devtools-extension
