### ISSUE TITLE
Esbuild analog of `webpack.config.renderer.dev.dll.ts`

### ISSUE THREAD

**Issue by LIMPIX31** [electron-react-boilerplate/electron-react-boilerplate#3147]
I'm trying to change in my project using ERB webpack to esbuild because it's faster, I almost succeeded, but I'm stuck on `webpack.config.renderer.dev.dll.ts`, I can't figure out how I can replace it with the analog using esbuild.

EDIT: Oops sorry, I forgot to provide an error.
```
electron failed to install correctly please delete node_modules
```

**Comment by LIMPIX31** [comment]
I solved the problem by making the following changes. Do I need to do this with all dependencies? Is what I did right?
```diff
build({
  entryPoints: [
    path.join(__dirname, '../../src/main/main.ts'),
    path.join(__dirname, '../../src/main/preload.js')
  ],
  bundle: true,
  minify: true,
  platform: 'node',
+ external: ['electron'],
  outdir: DIST_MAIN_PATH
}).catch(() => process.exit(1))
```

**Comment by amilajack** [comment]
hard to verify but looks right
