### ISSUE TITLE
release/app npm run electron-rebuild error with the parameter "--parallel"

### ISSUE THREAD

**Issue by HyperClockUp** [electron-react-boilerplate/electron-react-boilerplate#3149]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

install native module and rebuild successfully
## Current Behavior
cannot rebuild native module successfully

when rebuild native module, it goes error like

> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE
>\VC\VCTargets\Microsoft.CppBuild.targets(321,5): error MSB3491: 未能向文件“Release\obj\ffi\ffi.tlog\ffi.lastbuildstate”写
>入命令行。文件“D:\projects\electron-template\release\app\node_modules\ffi->?>napi\build\deps\libffi\Release\obj\ffi\ffi.tlog\ffi.lastbuildstate”正由另一进程使用，因此该进程无法访问此文
件。

## Steps to Reproduce
install native module such as ffi-napi

1. cd projectPath

2. npm install ffi-napi

## Possible Solution (Not obligatory)

it seems like that two processes want to call a same program at the same time, so I searched in the **electron-rebuild.js** and I got th
the core command line
```
const electronRebuildCmd =
    '../../node_modules/.bin/electron-rebuild --parallel --force --types prod,dev,optional --module-dir .';
```

from the [electron-rebuild doc](https://github.com/electron/electron-rebuild#cli-arguments), I guess maybe the "parallel" cause the error. and after I remove the parameter, everything work well.
## Your Environment

- Node version :16.13.0
- electron-react-boilerplate version or branch :2022/3/1 latest in master
- Operating System and version : win 10
- Link to your project : private

**Comment by amilajack** [comment]
Fixed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/6e0ae6013313e2508db06ef85edccf62b6b1c91f
