### ISSUE TITLE
process is not deined in renderer process

### ISSUE THREAD

**Issue by PARADISELIN** [electron-react-boilerplate/electron-react-boilerplate#3151]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)

## Expected Behavior
can use `process` in renderer process

```jsx
export default function App() {
  console.log(process.platform)
  return (
    <div>
      {/*  ... */}
    </div>
  )
}
```

## Current Behavior

![1](https://user-images.githubusercontent.com/17696492/156303256-9b624e31-1958-4b5a-8e86-7d7d77bcfcdd.png)

```js
new BrowserWindow({
    show: true,
    minWidth: 1400,
    minHeight: 850,
    frame: false,
    icon: getAssetPath('icon.png'),
    webPreferences: {'
      nodeIntegration: true,
      preload: path.join(__dirname, 'preload.js'),
    },
})
```

I set `nodeIntegration: true` and restart, but still throw error

## Steps to Reproduce

1. use `process` in renderer (`App.tsx`)

## Your Environment

- Node version : 16.4.0
- electron-react-boilerplate version or branch : main
- Operating System and version : macOS M1 12.1

**Comment by amilajack** [comment]
https://electron-react-boilerplate.js.org/docs/native-modules/#renderer-process-native-modules

**Comment by akochemasov** [comment]
@amilajack please give me example how to use `process.env` in redrerer parts

**Comment by amilajack** [comment]
use the define plugin

https://webpack.js.org/plugins/define-plugin/

```
new webpack.DefinePlugin({
  'process.type': JSON.stringify("some-value"),
});
```
