### ISSUE TITLE
Updated CI (github actions) yml files for the latest version of package.json 

### ISSUE THREAD

**Issue by chipimix** [electron-react-boilerplate/electron-react-boilerplate#3152]
Greetings!

I'm trying to setup github actions for the first time using the latest electron-react-boilerplate.
Forgive me for being a n00b, it seems that the [CI documentation](https://electron-react-boilerplate.js.org/docs/ci) is outdated.
Of the following lines:
```
script:
  - npm run package-ci
  - npm run lint
  - npm run ts
  - npm test
  - npm run build-e2e
  - npm test-e2e
```

❓ What are the latest electron-react-boilerplate version equivalent?
Since ts and build-e2e scripts are missing from the latest package.json file, I think its something like this:

```
script:
  - npm run package
  - npm run lint
  - npm test
  - npm test-e2e
```

But I'm not sure.
Thanks in advance!

**Comment by amilajack** [comment]
fixed in https://github.com/electron-react-boilerplate/site/commit/c55775c5a708137a49846902e5a08610fff482f9

**Comment by chipimix** [comment]
Thanks!
