### ISSUE TITLE
Doesn't work with opensea-js

### ISSUE THREAD

**Issue by fpena06** [electron-react-boilerplate/electron-react-boilerplate#3154]
## Summary

I'm trying to use opensea-js with the boilerplate. 

`import { OpenSeaPort, Network } from 'opensea-js';`

`  const seaport = new OpenSeaPort(provider, {
    networkName: Network.Main,
    apiKey: 'xxxxxxxxxxxxxxxx',
  });`

But getting lots of errors and not sure how to figure it out, any help is appreciated.

> Compiled with problems:X

WARNING in ./node_modules/@0x/assert/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/base-contract/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/utils/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/web3-wrapper/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/wyvern-js/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/wyvern-schemas/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/assert/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/base-contract/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/utils/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/@0x/web3-wrapper/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/wyvern-js/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/wyvern-schemas/node_modules/ethers/dist/ethers.min.js 1:484-485

Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by amilajack** [comment]
Install to release/app/package.json

**Comment by fpena06** [comment]
yes, this is what I have done, also installed to package.json to see if that helped.

**Comment by fpena06** [comment]
@amilajack could you please give it a try with a clean repo? It would save my sanity, I've been trying to get this to work for about a week now, thanks appreciate your help and support.

**Comment by amilajack** [comment]
Sure I'll give it a go
