### ISSUE TITLE
Mas build rejected on app store Could not set sandbox profile data: Operation not permitted (1)

### ISSUE THREAD

**Issue by ashvin777** [electron-react-boilerplate/electron-react-boilerplate#3157]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
The app should be allowed to be published into the store

## Current Behavior
I have not observed this on my machine, however app store team is rejecting my application with the given error that its crashing on launch with below error 
{"libsystem_secinit.dylib":["Could not set sandbox profile data: Operation not permitted (1)"]},
## Your Environment

- Node version : v16.0.0, npm 7.10.0
- electron-react-boilerplate version or branch : master
- Operating System and version : macOS

Buidl settings in package.json

```json
"build": {
    "productName": "xxx",
    "appId": "xxx",
    "buildVersion": "xxx",
    "asar": true,
    "asarUnpack": "**\\*.{node,dll}",
    "files": [
      "dist",
      "node_modules",
      "package.json"
    ],
    "afterSign": ".erb/scripts/notarize.js",
    "mac": {
      "target": "mas",
      "icon": "assets/icon.png",
      "type": "distribution",
      "entitlements": "assets/entitlements.mac.plist",
      "entitlementsInherit": "assets/entitlements.mac.inherit.plist",
      "provisioningProfile": "assets/xxxx.provisionprofile",
      "extendInfo": {
        "ITSAppUsesNonExemptEncryption": "NO"
      }
    },
    "directories": {
      "app": "release/app",
      "buildResources": "assets",
      "output": "release/build"
    },
    "extraResources": [
      "./assets/**"
    ],
    "publish": {
      "provider": "github",
      "owner": "xxx",
      "repo": ""
    }
  },
```

## entitlements.mac.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
      <string>xxx</string>
    </array>

    <key>com.apple.application-identifier</key>
    <string>xxx</string>

    <key>com.apple.developer.team-identifier</key>
    <string>xxx</string>
  </dict>
</plist>  
```

## entitlements.mac.inherit.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">  
<plist version="1.0"> 
  <dict>  
    <key>com.apple.security.app-sandbox</key><true/>  
    <key>com.apple.security.inherit</key><true/>  
  </dict> 
</plist>  
```

**Comment by amilajack** [comment]
unfortunately configuring sandbox config for your erb app is out of scope for what i can help with. were you able to resolve the issue?
