### ISSUE TITLE
Adding Build-time Assets documentation still not clear.

### ISSUE THREAD

**Issue by chrisle** [electron-react-boilerplate/electron-react-boilerplate#3158]
## Summary

1. Where are you supposed to put .png, .svg files? 
From the root of the project:

```
here? /assets/img/cat.jpg 
or here? /release/app/img/cat.jpg
```

2. When you import it does webpack somehow know exactly where to find them?
```js
// src/renderer/Components/MyComponent.ts

import catImage from './image/cat.jpg' // What is "./" relative to? /assets?
```

3. Is it necessary to add this directory to package.json? The jpg is needed at "run-time", so yes?

```json
{
   "name": "project",
   ...
   "build": {
      "productName": "MyProject",
      "files": [
         "dist",
         "node_modules",
         "package.json",
         "assets/img/",  ????         
         "assets/app/img/",  ????
      ]
...
}
```

I wrote this because the following doesn't seem to work:

The following file exists:
```
/assets/img/img_1.png
```

```js
// src/renderer/Components/CoverArt.tsx
import React from 'react';
import DefaultArtWork from './img/img_1.png';

export class CoverArt extends React.Component {
  render() {
    return (
      <img className="artwork" src={DefaultArtWork} alt="artwork" />
    )
  }
}
```

```
> start:main
> cross-env NODE_ENV=development electron -r ts-node/register/transpile-only ./src/main/main.ts

21:14:09.671 › Skip checkForUpdatesAndNotify because application is not packed
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
ERROR in ./src/renderer/Components/CovertArt.tsx 12:36-62
Module not found: Error: Can't resolve './img/img_1.png' in '/Users/chrisle/code/nowplaying2/src/renderer/Components'
 @ ./src/renderer/NowPlayingScreen/CoverMain.tsx 8:20-54
 @ ./src/renderer/NowPlayingScreen/MainLeft.tsx 7:20-42
 @ ./src/renderer/NowPlayingScreen/index.tsx 9:19-40
 @ ./src/renderer/App.tsx 9:27-56
 @ ./src/renderer/index.tsx 17:30-46

webpack compiled with 1 error
Not rewriting GET /index.html because the path includes a dot (.) character.
```

The documentation says, pretty much exactly what it says I'm doing... right?
```
import catImage from "./cat.jpg";

function CatComponent() {
  return <img src={catImage} />;
}
```

**Comment by lobut** [comment]
hi @chrisle, I took a look at the webpack configuration and it seems as though you put the image in your local relative directory.  Webpack will copy it from your source to your destination.

So from your example, let's say your directory structure is: 

- src/renderer/CatComponent.tsx
- src/renderer/cat.jpg

It should work as expected and you shouldn't need to do anything else.  My visual studio seems to complain, however, but it does run perfectly fine.

For more information, here's the part of the webpack config that dictates how images are handled: 

https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/.erb/configs/webpack.config.renderer.dev.ts#L91-L94

Here is the webpack documentation for it:
https://webpack.js.org/guides/asset-modules/

**Comment by chrisle** [comment]
That seemed to work.

```js
// Image saved to: src/renderer/img/img_1.png
// This class is in: src/renderer/Components/MyComponent.tsx
import DefaultArtWork from '../img/img_1.png';
export class MyClass extends React.Component {
  render() {
    return (<img src={DefaultArtWork} />);
  }
}
```
