### ISSUE TITLE
Azure Login works in Development mode but not in production (deploying as Windows executable)

### ISSUE THREAD

**Issue by vishnu-marthala** [electron-react-boilerplate/electron-react-boilerplate#3159]
## Prerequisites

- [x] Using npm
- [x]Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
I have used React Azure [MASL Library ](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample) for Authentication with Azure. The Sign In and Sign up page will show up and After login is success it has to redirect to my application.This works fine in Development mode as well as in production. 

## Current Behavior
I have used React Azure [MASL Library ](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/samples/msal-react-samples/typescript-sample) for Authentication with Azure. The Sign In and Sign up page will show up and After login is success it has to redirect to my application.This works fine in Development mode i.e. if i start the application as `npm start` a Windows application will run and everything is working fine but after packing it as windows executable by running `npm run package -- --win` . The Windows Application works till signup and after signup it will never be returned to my application an empty page is shown.

## Steps to Reproduce

1. create an windows executable by running `npm run package -- --win` 

2. Start the Application by clicking the .exe

3. Sign with Azure credentials

4.After login success you see white blank page and on the Header of the Windows App you can see it it sill in "Sign In and Sign Up page" from Azure. 

## Your Environment

- Node version : 16.14.0
- electron-react-boilerplate version or branch :4.5.0
- Operating System and version : Windows 10
- Link to your project :private repo

**Comment by amilajack** [comment]
Integration with 3p libraries is out of scope for what i can offer support for.
