### ISSUE TITLE
git commit -m "initial commit" deleted ALL OF my new files

### ISSUE THREAD

**Issue by aelkheir** [electron-react-boilerplate/electron-react-boilerplate#3170]
## Summary

I want to restore my  changes. All I did is switched to a new branch and did that commit. the commit failed but then deleted all my new files.

**Comment by amilajack** [comment]
this might have something to do with the pre-commit hook. it'll be removed in the near future

**Comment by s97712** [comment]
What does hook do? How do I get my files back?

**Comment by amilajack** [comment]
Closing because this has likely been resolved by now. Please comment if your'e still running into this issue and I'll reopen
