### ISSUE TITLE
How to optimize the startup time

### ISSUE THREAD

**Issue by mgscreativa** [electron-react-boilerplate/electron-react-boilerplate#3172]
Hi! I have a simple question, is there any guide on how to optimize my electron-react-boilerplate app startup time?

I use MUI in my project and I thought that the packager was smart enough to avoid including the whole MUI library in the bundle, but after changing imports from this:
```
import { Tooltip, Button, IconButton } from '@mui/material';
```
to this
```
import Tooltip from '@mui/material/Tooltip';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
```
I was able to reduce startup time by about 15 seconds!

I wonder if there are other optimizations, because I import all my components like this
```
import` { useRef, MouseEvent, useEffect, SyntheticEvent } from 'react';
```

Thanks in advise!

**Comment by amilajack** [comment]
Wrote about electron specific optimizations here https://amilajack.com/improving-electron-performance/. This is more of a question about front-end perf, which is out of scope. but i'd recommend using route-based code splitting with react-router and webpack.
