### ISSUE TITLE
How to add new plugin to webpack?

### ISSUE THREAD

**Issue by moriokii** [electron-react-boilerplate/electron-react-boilerplate#3175]
How to add new plugin to webpack? I want to add plugin to renderer. I added to base config, but it make error
![image](https://user-images.githubusercontent.com/60312254/160066078-c0b9412f-bb11-46ad-96cd-c3539d121c9c.png)

**Comment by amilajack** [comment]
what's the error? add it to renderer dev and renderer prod configs
