### ISSUE TITLE
How about changing default type 'any' to 'unknown'?

### ISSUE THREAD

**Issue by BangHyeongSik** [electron-react-boilerplate/electron-react-boilerplate#3176]
Hello, I'm an avid user of this project (I did not contribute.)

Here are some suggestions.

First, As you see the title, I know the 'Any' type is very insecure. Also, I don't think there is any reason to use 'Any' type in the 'preload.ts' and 'preload.d.ts'.
If so, How about change 'Any' type to 'Unknown' type?

Second, 
'removeListener' is a useful feature. However, if you create a listener with 'preload.ts', removing the listener is not easy.
So I would like to suggest this code.

```typescript

// ...

on(channel: string, func: (...args: unknown[]) => void) {
  const validChannels = ['ipc-example'];
  if (validChannels.includes(channel)) {
    const subscription = (
      _event: Electron.IpcRendererEvent,
      ...args: unknown[]
    ) => func(...args);
    // Deliberately strip event as it includes `sender`
    ipcRenderer.on(channel, subscription);
    return () => ipcRenderer.removeListener(channel, subscription);
  }
  return () => {};
},

// ...
```
This code is a code extracted from code created by other users.
I think this code will be a useful example for users.

Finally, I hope my suggestions will be helpful to you.
Thanks for reading.

**Comment by amilajack** [comment]
great suggestions! happy to accept both in separate pr's
