### ISSUE TITLE
ERROR in dll renderer

### ISSUE THREAD

**Issue by dwrtz** [electron-react-boilerplate/electron-react-boilerplate#3189]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

After installing firebase with ```npm install firebase```, running ```npm install``` should not produce an error in the postinstall script

## Current Behavior

I get the following error:
ERROR in dll renderer renderer[3]
Module not found: Error: Package path . is not exported from package /Users/dwurtz/dev/electron-react-boilerplate-example/node_modules/firebase (see exports field in /Users/dwurtz/dev/electron-react-boilerplate-example/node_modules/firebase/package.json)

## Steps to Reproduce

1. ```npm install firebase```

2. ```npm install```

## Context

Similar [issue](https://github.com/firebase/firebase-js-sdk/issues/5456) was reported in the firebase repo but was deemed an electron-react-boilerplate issue

## Your Environment

- Node version : v17.4.0
- electron-react-boilerplate version or branch : I reproduced with v4.5.0 release and on main
- Operating System and version : macos 12.3.1
- Link to your project :

**Comment by aaronvg** [comment]
I fixed this by adding "firebase" to the externals array in `webpack.config.renderer.dev.ddl.ts`
...
`  externals: ['fsevents', 'crypto-browserify', 'firebase'],`

I actually don't understand precisely why it seems to work -- I got the idea from reading this https://github.com/firebase/firebase-js-sdk/issues/5140.

I am using yarn v3

**Comment by dwrtz** [comment]
Thanks! This fixed the issue for me.

**Comment by arvid220u** [comment]
Thank you @aaronvg!! Fixed the issue for me as well :)

**Comment by subatomicglue** [comment]
Fixed for me as well.   Many thanks!

**Comment by shreypdev** [comment]
killer @aaronvg

**Comment by dwrtz** [comment]
Yeah,

Thanks @aaronvg <https://github.com/aaronvg>
