### ISSUE TITLE
All my work has been deleted

### ISSUE THREAD

**Issue by LIMPIX31** [electron-react-boilerplate/electron-react-boilerplate#3190]
I cloned the repository as specified in `README.md` and worked in it for 2 days, I wanted to commit the changes
```
git add -A
git commit -m "myFirstCommit"
```
But instead all my changes were rolled back. How do I get them back?

**Comment by Gu-Miao** [comment]
I think your commands are correct. Maybe you meet some malicious code? (not sure)
https://beny23.github.io/posts/on_weaponisation_of_open_source/

**Comment by LIMPIX31** [comment]
> I think your commands are correct. Maybe you meet some malicious code? (not sure) https://beny23.github.io/posts/on_weaponisation_of_open_source/

I think it is related to `husky` since the execution of `pre-commit` failed, after which I noticed the missing files. I already recovered them thanks to `WebStorm`, but I still wonder why this happened.
