### ISSUE TITLE
White screen after install react-native-web

### ISSUE THREAD

**Issue by InternetProducts** [electron-react-boilerplate/electron-react-boilerplate#3191]
I'm new to React. I downloaded this boilerplate and it installed without a hitch. I built a Linux package and the demo app executed properly. But when I installed react-native-web (npm i react-native-web) and ran the builder again (npm run package --linux), the generated app image produced a blank white window.

NOTE: It works fine when running in development mode.

Is there some extra step required for adding React modules? Or React-Native-Web in particular?

**Comment by SenselessA** [comment]
+ I have the same problem with my project, when I try to build app for linux or windows platform

**Comment by anytoany** [comment]
I have same issue after npm run package app show white screen, in development all ok.

**Comment by frankcalise** [comment]
Did you ever manage to resolve this issue?

**Comment by amilajack** [comment]
Closing because this has likely been resolved by now. Please comment if your'e still running into this issue and I'll reopen
