### ISSUE TITLE
Cannot read properties of undefined (reading 'ipcRenderer')

### ISSUE THREAD

**Issue by khunemz** [electron-react-boilerplate/electron-react-boilerplate#3192]
## Prerequisites

- [ YES] Using npm
- [ YES] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ YES] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ NO] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ NO] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior

```
Call Stack
 Object../src/renderer/index.tsx
  renderer.dev.js:68966:17
 Object.options.factory
  renderer.dev.js:73907:31
 __webpack_require__
  renderer.dev.js:73352:33
 undefined
  renderer.dev.js:74489:37
 undefined
  renderer.dev.js:74492:12
 webpackUniversalModuleDefinition
  renderer.dev.js:7:11
 undefined
  renderer.dev.js:10:3

```
## Steps to Reproduce

1. git clone --depth 1 --branch main https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name

2. then `npm i` and `npm start`
3. it shows error above

4.

## Your Environment

- Node version : 14.17.0
- electron-react-boilerplate version or branch : main
- Operating System and version : macOS
- Link to your project : -

**Comment by bigcakes** [comment]
Also hitting this on windows with Node 16.

Looks like it is likely from this PR: https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3155

However I am not sure the fix at the moment, I think it is due to the webpack transforms on the preload.ts file causing it to not properly expose the electron object on the window.

**Comment by GasperFunda** [comment]
Please fix this I am facing the same issue when I tried to follow the tutorial on adding native modules to electron app with your boilerplate: https://electron-react-boilerplate.js.org/docs/native-modules/

**Comment by badaz** [comment]
Same thing for me, noob at electron apps, does anyone has a simple workaround?

**Comment by badaz** [comment]
Ok, I figured it out by trying it on a real Ubuntu.  starting the project actually opens an electron windo, which was not the case on Windows, so I tried to open the CLI url in Chrome. Problem is with WSL not being able to open GUI apps. You have to follow Step 4 of this tutorial https://www.beekeeperstudio.io/blog/building-electron-windows-ubuntu-wsl2 as well as meddle with your firewall rules afterward https://github.com/cascadium/wsl-windows-toolbar-launcher#firewall-rules and it works and opens a dedicated gui after yarn start

**Comment by cmal** [comment]
macos same problem when opening a browser window.

**Comment by meyer-denney-ds** [comment]
Why was this issue closed with no solution? I'm still experiencing it on node v 16.16 and WebPack v5.7

**Comment by rezol99** [comment]
I commented out the following example and it fixed it.

I don't know why.

`src/renderer/index.tsx`

```
import { createRoot } from 'react-dom/client';
import App from './App';

const container = document.getElementById('root')!;
const root = createRoot(container);
root.render(<App />);

// window.electron.ipcRenderer.once('ipc-example', (arg) => {
//   console.log(arg);
// });
// window.electron.ipcRenderer.sendMessage('ipc-example', ['ping']);
```

**Comment by samdiefenbacher** [comment]
> I commented out the following example and it fixed it.
> 
> I don't know why.
> 
> `src/renderer/index.tsx`
> 
> ```
> import { createRoot } from 'react-dom/client';
> import App from './App';
> 
> const container = document.getElementById('root')!;
> const root = createRoot(container);
> root.render(<App />);
> 
> // window.electron.ipcRenderer.once('ipc-example', (arg) => {
> //   console.log(arg);
> // });
> // window.electron.ipcRenderer.sendMessage('ipc-example', ['ping']);
> ```

Thank you! Worked.

**Comment by dushyanttessact** [comment]
@rezol99 but how am i supposed to use these functions in renderer?

Application works fine on development but on production it throws me "TypeError: Cannot read properties of undefined (reading 'ipcRenderer')",

i checked with isElectron() library, its true on dev and false on prod?

Can someone help me out here what might be the issue?

**Comment by dushyanttessact** [comment]
> Why was this issue closed with no solution? I'm still experiencing it on node v 16.16 and WebPack v5.7

did you find any fix?

**Comment by rezol99** [comment]
Try this.
```
import { ipcRenderer } from 'electron';

ipcRenderer.sendMessage('ipc-example', ['ping']);
```

**Comment by dushyanttessact** [comment]
@rezol99 

Thank you for the reply, so i tried your suggestion, but now its giving me this error :

```
ERROR in ./node_modules/electron/index.js 1:11-24
Module not found: Error: Can't resolve 'fs'
```

**Comment by ingusjan** [comment]
Hey all, I've managed to get it working on my end using the following:

```typescript
// 👇 Add this to your preload.js file:
contextBridge.exposeInMainWorld('electron', {
  ipcRenderer: { ...ipcRenderer, on: ipcRenderer.on },
});

// 👇 Use ipcRenderer in your React components
const { ipcRenderer } = window.require('electron');
```

Hope this helps!

**Comment by khunemz** [comment]
I abandoned on it and moved to `flutter` to build desktop app. It's better.

**Comment by voyager-gold** [comment]
I am facing the same issue when reading `window.electron` from renderer.
I tried to put `console.log()` in `main/preload.ts`, and nothing logged in my terminal.
It doesn't seem like `webPreferences.preload` is working when creating a new `BrowserWindow` [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/main/main.ts#L78-L80).

**Comment by jayantasamaddar** [comment]
> I abandoned on it and moved to `flutter` to build desktop app. It's better.

Damn, I'm facing this now and it's so irritating. Might move to Tauri or Flutter.

**Comment by hershicon** [comment]
Saw this thread and solved it for me at least, I had followed instructions for using native modules in the electron boilerplate [here](https://electron-react-boilerplate.js.org/docs/native-modules) so I could use ipcRenderer with `import {ipcRenderer} from 'electron';`   I was getting a error: 
"Uncaught TypeError: Cannot read properties of undefined (reading 'ipcRenderer')", so I commented out the same code that @rezol99 did and it worked.  I think it worked because the updates to include native modules in the electron react boilerplate removed the use of the preload script, so the commented out code no longer works?

**Comment by omourissoux** [comment]
Hi,
This issue is not fixed, I still have the problem. I think it's due to preload.ts execution/loading error.

**Comment by Scottsdaaale** [comment]
Hello,
I have encountered the same issue and seem to have found a fix(?). After following [this](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3192#issuecomment-1295922704) suggestion, and [this](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3192#issuecomment-2120634435) suggestion, I removed all typescript syntax from preload.js. `npm start `and `npm run build `now work.

**Comment by isaiahb** [comment]
from React fontend this worked for me

const { ipcRenderer } = window.require('electron');
const result = ipcRenderer.invoke('select-folder', projectPath);

**Comment by mikedeng** [comment]
what a shame, it still not fixed

**Comment by mikedeng** [comment]
what a shame, it still not fixed

**Comment by mikedeng** [comment]
what a shame, it still not fixed

**Comment by mikedeng** [comment]
Change the content in the preload.ts to the following, but this only works in the electron window, and the content from the chrome window still report the error.

// preload.ts
// Disable no-unused-vars, broken for spread args
/* eslint no-unused-vars: off */
import { contextBridge, ipcRenderer } from "electron"

const electronHandler = {
  ipcRenderer: {
    sendMessage(channel, ...args) {
      ipcRenderer.send(channel, ...args)
    },
    on(channel, func) {
      const subscription = (_event, ...args) => func(...args)
      ipcRenderer.on(channel, subscription)

      return () => {
        ipcRenderer.removeListener(channel, subscription)
      }
    },
    once(channel, func) {
      ipcRenderer.once(channel, (_event, ...args) => func(...args))
    }
  }
}

contextBridge.exposeInMainWorld("electron", electronHandler)
