### ISSUE TITLE
Unable to load svgs as react components

### ISSUE THREAD

**Issue by comountainclimber** [electron-react-boilerplate/electron-react-boilerplate#3193]
## Prerequisites
Clean install of ERB - followed the advice in this issue https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2522 which led to a separate problem => 

`SvgoParserError: Non-whitespace before first tag.`

(I have validated that these svgs do not have any syntax errors)

## Expected Behavior
The following code should work `import { ReactComponent as Logout } from './assets/<any.svg>';`

## Current Behavior

```
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

## Steps to Reproduce

Attempt to import an svg just like you would in many other react app boilerplate projects or CRA 

## Possible Solution (Not obligatory)

By default ERB should ship with the ability to load svg as react components... Still no idea how to fix this issue and it is blocking progress on my project

**Comment by shensven** [comment]
```tsx
import React, { SVGProps } from 'react';

export function IcBaselineAccountCircle(props: SVGProps<SVGSVGElement>) {
  return (
    <svg width="1em" height="1em" viewBox="0 0 24 24" {...props}>
      <path
        fill="currentColor"
        d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10s10-4.48 10-10S17.52 2 12 2zm0 3c1.66 0 3 1.34 3 3s-1.34 3-3 3s-3-1.34-3-3s1.34-3 3-3zm0 14.2a7.2 7.2 0 0 1-6-3.22c.03-1.99 4-3.08 6-3.08c1.99 0 5.97 1.09 6 3.08a7.2 7.2 0 0 1-6 3.22z"
      ></path>
    </svg>
  );
}

export default IcBaselineAccountCircle;
```

This example works well if you wanna wrap svg as a React component

**Comment by comountainclimber** [comment]
I was actually able to solve the issue with the following solution:

in `webpack.config.base.ts` 

```
      {
        test: /\.svg$/,
        use: ['@svgr/webpack', 'url-loader'],
      },
```

**Comment by peilinok** [comment]
@comountainclimber Would please tell me which tag or commit do you use? I still have this problem when I follew the upstair steps with the latest version or tag 4.5.0.

**Comment by peilinok** [comment]
> 
I found the solution whit is do not add the loader into the "webpack.config.base.ts" but in the "webpack.config.base.renderer.dev|prod.ts" file
