### ISSUE TITLE
How to use browser-compatible parts of nodejs libraries with webpack

### ISSUE THREAD

**Issue by LIMPIX31** [electron-react-boilerplate/electron-react-boilerplate#3196]
**I post this question here because I am currently working with ERB**

I ran into this problem that I need to use some classes from a library that does not support the browser. These classes work in the browser, but because of the other parts of the library that only work in the nodejs environment, webpack gives an error.

What can I do to solve this?

**Comment by amilajack** [comment]
You have two options.

1. import the library in the main process and install it to `release/app/package.json`
2. import the specific module that is browser specific (`import foo from 'my-lib/browser-compat'`)

**Comment by LIMPIX31** [comment]
The second option is more likely to work for me.

**Comment by LIMPIX31** [comment]
```
Package path ./browser is not exported from package
```
```json
"exports": {
  ".": "./lib/index.js",
  "./browser": "./lib/browser.js"
},
"typesVersions": {
  "*": {
    "browser": ["lib/browser.d.ts"]
  }
},
```

**Comment by amilajack** [comment]
This is more of a webpack and third party issue than an issue with the boilerplate. Closing but feel free to continue the convo.

**Comment by afeichuanqi** [comment]
This will increase your software volume

> The problem was solved, my package was installed both at the root and in `release/app`.

This will increase your software volume
