### ISSUE TITLE
TypeError: object null is not iterable

### ISSUE THREAD

**Issue by yuis-ice** [electron-react-boilerplate/electron-react-boilerplate#3200]
## Prerequisites

- [x ] Using npm
- [x ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

should launches successfully 

## Current Behavior

launch.json > "Electron: Main" fails on task "Start Webpack Dev" as the following error. 

```
> Executing task: npm run start:renderer <


> start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts     

Starting preload.js builder...
Starting Main Process...
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:1212/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.200:1212/
<i> [webpack-dev-server] Content not from webpack is served from 'C:\pg\electron-react-boilerplate\public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'       

> start:preload
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts


> start:main
> cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only ./src/main/main.ts

[electronmon] waiting for a change to restart it

(node:20696) ExtensionLoadWarning: Warnings loading extension at C:\Users\username\AppData\Roaming\Electron\extensions\fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for 
more details.

(Use `electron --trace-warnings ...` to show where the warning was created)
20:10:53.093 > Skip checkForUpdatesAndNotify because application is not packed
IPC test: ping
[20696:0422/201057.103:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[20696:0422/201057.104:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
[28388:0422/201252.927:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is disabled, ANGLE is
```

## Steps to Reproduce

1. git clone --depth 1 --branch main https://github.com/electron-react-boilerplate/electron-react-boilerplate.git electron-react-boilerplat

2. cd electron-react-boilerplat

3. npm i

4. `npm start` as documented on the quick start, so I have confirmed this launches the app successfully. then quit the app. 

5. open the "electron-react-boilerplat" dir on vscode 

6. start debugging process (pressing F5) 

7. fails on the error 

## Possible Solution (Not obligatory)

I don't know. 

## Context

launches the app through the vscode debugger 

## Your Environment

- Node version :v16.13.2
- electron-react-boilerplate version or branch : latest
- Operating System and version : Windows 10 Pro  2009
- Link to your project :

**Comment by yuis-ice** [comment]
okay, I figured out why it didn't work. I should have launch the debug process on the "All" but not "Main". Thanks.

**Comment by yuis-ice** [comment]
I don't think the Electron: Renderer and Electron: Main are launching successfully on the debug process, but only the "Start Webpack Dev" preLaunchTask and stuck on it with the above mentioned error?

**Comment by amilajack** [comment]
Assuming this has been resolved by now. If it isn't, please comment and I'll reopen
