### ISSUE TITLE
Is there any next plan?

### ISSUE THREAD

**Issue by BangHyeongSik** [electron-react-boilerplate/electron-react-boilerplate#3204]
I love this repository and use it often.

However, the homepage doesn't have up-to-date information on the roadmap, so I don't know if there are any next plans for an update.
Do you have a roadmap for the following?

If so, what are your plans?
I want to know your opinion.

**Comment by amilajack** [comment]
I totally agree, I'll update the roadmap soon. Anything you'd like to see on the roadmap?

**Comment by BangHyeongSik** [comment]
I think it would be good to focus on additional packages or major changes to prepare for future changes.

**Comment by amilajack** [comment]
I'll be updating https://electron-react-boilerplate.js.org/docs/roadmap

but I can also create a ticket to track this
