### ISSUE TITLE
Issue running repo

### ISSUE THREAD

**Issue by daskabe** [electron-react-boilerplate/electron-react-boilerplate#3206]
## Prerequisites

- [ ] Using npm
- [ ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Should render the Hello Component 

## Current Behavior

nothing is rendered. 
![image](https://user-images.githubusercontent.com/94478096/165845444-364ddf72-fa21-45cf-af20-25ac7d7223c1.png)
![image](https://user-images.githubusercontent.com/94478096/165846163-afebf7d1-bfa5-45e7-b208-8a960d747c4d.png)

```
....
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
[electronmon] renderer file change: src\renderer\index.ejs
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
[electronmon] renderer file change: src\renderer\index.ejs
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
[electronmon] renderer file change: src\renderer\index.ejs
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
[electronmon] renderer file change: src\renderer\index.ejs
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
<i> [webpack-dev-middleware] wait until bundle finished: /renderer.dev.js
[electronmon] renderer file change: src\renderer\index.ejs
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
[35060:0428/155859.698:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[35060:0428/155859.698:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
```
## Steps to Reproduce

1. Clone Main branch.

2. yarn

3. npm start

4.

## Your Environment

- Node version : v16.14.0
- electron-react-boilerplate version or branch :
- Operating System and version : WIN
- Link to your project :

**Comment by wtedw** [comment]
seeing the same issue

**Comment by yuis-ice** [comment]
I have a similar problem as #3200 but not very sure this is a bug or my sides problem

**Comment by mimamuh** [comment]
I got the same issue with a fresh setup. I turns out that when I comment out `await installExtensions();` in `main.ts -> createWindow()` function, that all works fine. See also here: https://github.com/electron/electron/issues/32133#issuecomment-1107635348

**Comment by amilajack** [comment]
Assuming this has been resolved by now. If it isn't, please comment and I'll reopen
