### ISSUE TITLE
Need to create new folder in pc using  react component . please help me

### ISSUE THREAD

**Issue by itranga** [electron-react-boilerplate/electron-react-boilerplate#3207]
## Summary

Need to create new folder in PC using  react component . please help me. 

var fs = require('fs');

// Without checking if dir already exists
fs.mkdir('PATH/TO/DIR');

// With checking if dir already exists
if (!fs.existsSync('PATH/TO/DIR')) fs.mkdir('PATH/TO/DIR');

**Comment by rvignesh123** [comment]
React is a front end library , you cannot access a system folder without the help of backend support.

In this case you can use an IPC call to do all your backend operation and send some response to React frontend.
In electron-react-boilerplate you will have two folders one is **main** and other is **renderer** , main is used for backend nodejs works, and renderer you can use react.

In your case .. 

Main.ts
`
import * as fs from 'fs';
ipcMain.on('create-folder', async (event, arg) => {
  if (!fs.existsSync('PATH/TO/DIR')) fs.mkdir('PATH/TO/DIR');
  event.reply('create-folder', 'folderCreated');
});`

preload.ts
`createFolder(arg: object) {
      ipcRenderer.send('create-folder', arg);
 }`

also add in 'once' method.

Frontend:

FrontEndComponent.tsx
`
useEffect(() => {
window.electron.ipcRenderer.once('create-folder', (result) => {
  // you should probably receive folderCreated
  console.log(result);
});
window.electron.ipcRenderer.createFolder('argument');
}, []);
`

I'm not an expert , hope this works.

**Comment by itranga** [comment]
Thank you very much for your support .  I will try to do it

**Comment by amilajack** [comment]
Closing because this has likely been resolved by now. Please comment if your'e still running into this issue and I'll reopen
