### ISSUE TITLE
Can't import native modules from release/app in preload.ts

### ISSUE THREAD

**Issue by BarakChamo** [electron-react-boilerplate/electron-react-boilerplate#3212]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

Importing native module packages installed in `release\app` should work, as described in:

## Current Behavior

I'm trying to setup `serialport` and `usb-detection` in the `preload.ts` script and expose a few handlers to the renderer process.
I followed instructions on installing native modules, ran the `postinstall` a few times to verify rebuild and linking and made sure the `node_modules` folder is linked in the source folder.

However, when running the project, the packages are not found.

This is the console error for example in Electron:
```
Unable to load preload script: D:\dev\...\.erb\dll\preload.js
(anonymous) @ VM113 renderer_init:73
VM113 renderer_init:73 Error: Cannot find module 'serialport'
Require stack:
- D:\dev\...\.erb\dll\preload.js
```

## Steps to Reproduce

1. Clone the latest `electron-react-boilerplate`
2. Install serialport inside `release\app`
3. require `serialport` in preload script
 
## Context

I'm trying to communicate with custom USB devices.

## Your Environment

- Node version : 18.1.0, tried 16.3.2, no change
- electron-react-boilerplate version or branch : fresh install from `main`
- Operating System and version : `Win 11`

**Comment by BarakChamo** [comment]
update:

Installing `serialport` to the root folder fixed this issue, which now moved on to `usb-detection`.

The serialport library seems to not have direct native modules so I wasn't getting to console warning, but I did with `usb-detction`

It seems whatever mechanism exists to make these externals from `release\app` available is not working.

**Comment by fmtrack** [comment]
I tried to instal leveldown and rxdb I am also having the same issue

**Comment by SimantoR** [comment]
I tried to install `@thiagoelg/node-printer` and `node-thermal-printer` modules in `release\app` folder, declare module types manually in `.\type.d.ts` file. Somewhat similar but not the same error occures. `Cannot find module @thiagoelg/node-printer`. I wonder if they are part of the same issue.

**Comment by rezol99** [comment]
I commented out the following example and it fixed it.

I don't know why.


`src/renderer/index.tsx`
```
import { createRoot } from 'react-dom/client';
import App from './App';

const container = document.getElementById('root')!;
const root = createRoot(container);
root.render(<App />);

// window.electron.ipcRenderer.once('ipc-example', (arg) => {
//   console.log(arg);
// });
// window.electron.ipcRenderer.sendMessage('ipc-example', ['ping']);
```

**Comment by thealexbaron** [comment]
I am also experiencing this sisue with `node-hid` (as well as node-printer as others mentioned)

**Comment by danwillm** [comment]
Experiencing the same issue.. is there a fix for this?

**Comment by siriwatknp** [comment]
@SimantoR I have a similar issue with `serialport`. Related to #3046 

Here is the step that works for me:
- replace the code in `link-modules.ts` with this https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3046#issuecomment-975098333.
- run `yarn --cwd release/app link-modules` at your root terminal (or `cd release/app` and then run the `link-modules` script)
- `yarn start` should work

**Comment by calumbutler** [comment]
This is not ideal but is a workaround for now. I added these 2 lines and resolves issues with using `yarn start`. Externals exclude the package from the bundle, so not ideal for how we are running our application in developer mode. 

The documentation on this is pretty vague, so would be nice to have some clarity provided on how we should be importing native dependencies with this architecture.

```
externals: process.env.NODE_ENV === "production" ? [  ...Object.keys(externals || {}) ] : [],
```

```
modules: [webpackPaths.srcNodeModulesPath, webpackPaths.srcPath, "node_modules"],
```

**Comment by amilajack** [comment]
preload isn't intended for native modules, main is
