### ISSUE TITLE
Disable hot releod or exclude assest folder from hot reload while developing.

### ISSUE THREAD

**Issue by theguidingstar** [electron-react-boilerplate/electron-react-boilerplate#3213]
Hey, I have been stuck somewhere. is there a way to disable hot reload on the dev environment? I am adding assets in the assets folder in runtime and it hot reloads the whole app. Looking forward to a quick help here

**Comment by chrisjoshuamartin** [comment]
Im looking to disable a folder from hot reload, as Im downloading files and its reloading. Thanks!

**Comment by theguidingstar** [comment]
This will happen in Development mode. But in case you want to disable it. 
You can replace electronmon to electron in "start" script.

I haven't found any specific reference to skip out the folder myself yet. I hope this helps.

**Comment by genesst** [comment]
Add this to your `package.json`:
```
"electronmon": {
    "patterns": ["!to_ignore/**"]
}
```
