### ISSUE TITLE
helper me , react redux devTools error

### ISSUE THREAD

**Issue by wy2022** [electron-react-boilerplate/electron-react-boilerplate#3219]
The latest template

npm run start 

![image](https://user-images.githubusercontent.com/40479235/168191914-1d54e832-0acc-44a4-857b-d574b7ab5087.png)

我查阅了相关资料，发现是redux 扩展问题，我尝试了好多方案都没解决.帮帮我

**Comment by wy2022** [comment]
I looked it up and found that it was a Redux extension problem, and I tried many solutions but failed to solve it.  Help me

**Comment by amilajack** [comment]
redux is out of scope for erb
