### ISSUE TITLE
MongoDB Realm integration with electron-react-boilerplate

### ISSUE THREAD

**Issue by genesst** [electron-react-boilerplate/electron-react-boilerplate#3220]
## Summary

Followed [this](https://www.mongodb.com/docs/realm/sdk/node/integrations/electron-cra/) tutorial to get started with Realm in Electron. Though had to skip steps related to CRACO, it's not trivial to implement it in electron-react-boilerplate. Added following settings to `webPreferences`:
```
nodeIntegration: true,
contextIsolation: false,
```

Added following code to `App.tsx`:
```
import Realm from 'realm';

const app = new Realm.App({ id: 'my-app-id' });
```

But it throws:
```
Module not found: Can't resolve 'fs' in '/Users/User/Deceloper/repo/node_modules/bindings'
node_modules/bindings/bindings.js
```

How to expose 'fs' bindings to the renderer process, so the dependencies could be resolved by the packages?

**Comment by amilajack** [comment]
here are the docs you're looking for

https://electron-react-boilerplate.js.org/docs/native-modules/#renderer-process-native-modules

cheers!

**Comment by genesst** [comment]
Thanks! Did all as described and it's now stuck on window open with the blank screen. Dev console shows this:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/13213650/168452769-04fcf79c-e0e5-4bc4-a33e-70851bc7be12.png">

Also console output:
```
[electronmon] renderer file change: mongodb-realm/realm-app-12345/server-utility/metadata/sync_metadata.realm.management/access_control.write.mx
[electronmon] renderer file change: mongodb-realm/realm-app-12345/server-utility/metadata/sync_metadata.realm.management/access_control.control.mx
[electronmon] renderer file change: mongodb-realm/realm-app-12345/server-utility/metadata/sync_metadata.realm
[electronmon] renderer file change: mongodb-realm/realm-app-12345/server-utility/metadata/sync_metadata.realm.lock
[10932:0515/124842.883611:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
[10932:0515/124842.883647:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)
```

No other errors or anything. Any ideas what might have caused the issue?
