### ISSUE TITLE
Build Release Crash on Windows 7 32 bit

### ISSUE THREAD

**Issue by aqilhex** [electron-react-boilerplate/electron-react-boilerplate#3222]
## Summary

I get exported version for windows 7 32 bit using  npm run package command. The installer works fine on some OS. But one of the computers which run Windows 7 32 bit, After i install exe file, It get installed but won't lunch. It gets crash. What could be the reason of this crash? can somebody help.

**Comment by amilajack** [comment]
windows 7 support is out of scope for ERB
