### ISSUE TITLE
Creating different version of release from package.json version

### ISSUE THREAD

**Issue by detronetdip** [electron-react-boilerplate/electron-react-boilerplate#3225]
Hi I am using electron-react-boilerplate to create a software. But unfortunately `packaging` is not working properly.  When it is creating a release it is not the same version as mentioned in my `package.json` file.
My `package.json` looks like
```
{
  .....
  "version": "0.1.1",
  .....
 "scripts": {
    ......
    "package": "ts-node ./.erb/scripts/clean.js dist && npm run build && electron-builder build --publish always",
     ...
  },
....
 "build": {
    "productName": "snehyamoyeebilldesk",
    "appId": "com.package.sj",
    "publish": {
      "provider": "github",
      "owner": "username",
      "repo": "repo-name",
      "private": true
    }
  },
....
}
```
When I am running `npm run package` it is creating a draft in github with `v4.6.0`, I have tried searching for this issue but could not get any solution.

**Comment by ainvoner** [comment]
@detronetdip look at https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/a104b64943b6465f782ace601ef845c22dafc138/release/app/package.json#L3
