### ISSUE TITLE
Dynamic loading of images

### ISSUE THREAD

**Issue by MartinMouritzen** [electron-react-boilerplate/electron-react-boilerplate#3227]
Hi, thanks for a great project.

I have a ton of images in my application, and I am really struggling to load them dynamically.

I've tried the suggestions in "[Run-time assets](https://electron-react-boilerplate.js.org/docs/adding-assets)", but I can't seem to load the images from CSS or image tags. Any help here would be much appreciated. <3

**Comment by amilajack** [comment]
Closing because this has likely been resolved by now. Please comment if your'e still running into this issue and I'll reopen

**Comment by lacymorrow** [comment]
Having the same issue, what is the proper method for using an img tag in this library with a large amount of dynamic images?
