### ISSUE TITLE
Nested queries with ipcRenderer and ipcMain

### ISSUE THREAD

**Issue by egeres** [electron-react-boilerplate/electron-react-boilerplate#3231]
I'm new to electron and I'm not sure about how to approach nested queries to the back-end. I'm thinking of a case where a function returns a list of elements, and a query is performed for each one of such elements. An example using fetch would be as follows:
```javascript
await fetch("http://localhost:8888/list_of_files")
.then(out => {
	let out_b = out.map(async (x) => { fetch("http://localhost:17462/file_info?name=" + x)).json() })
	Promise.all(out_b).then(x => this.setState({categories:x,}))
})
```
However, as far as I know, using electron's ipc, the query result is received by the `.on()` located in the `ipcRenderer` instance:
```javascript
window.electron.ipcRenderer.my_request_method()

window.electron.ipcRenderer.on("a_return_of_the_previous_request", (msg) => {
	// ...
})
```
What I'm actually interested into is a behavior where I don't receive the response in a separate method, but rather, after finishing my request to then be able to store the value in the same line. This might look like `let res = window.electron.ipcRenderer.my_request_method()`, yet I haven't seen a way to achieve such thing. How could this be accomplished?

**Comment by amilajack** [comment]
I'm assuming this has been resolved by now. If it isn't, please comment and I'll reopen
