### ISSUE TITLE
structuredClone

### ISSUE THREAD

**Issue by FelixKahle** [electron-react-boilerplate/electron-react-boilerplate#3232]
## structuredClone ReferenceError
I try to use the function structuredClone(), however I get the following error: **ReferenceError: structuredClone is not defined**.
What do I need to do to access this function. I also installed a module which throws the same error (pdfjs-dist).
Thanks in advance.

**Comment by Slapbox** [comment]
Use this method: https://nodejs.org/api/v8.html#v8serializevalue

It uses structured clone algorithm by default, or at least is compatible with structured clone.

**Comment by amilajack** [comment]
Seems like more of an electron related question. I'd recommend asking the larger electron community
