### ISSUE TITLE
Debug VS code guide

### ISSUE THREAD

**Issue by EnricoBeltramo** [electron-react-boilerplate/electron-react-boilerplate#3233]
## Summary

Debug electron and react part in vsCode

There is a guide to apply to debug step by step in vscode?
Usually with React apps, I run npm start and after I attach to process, but here what is the strategy? 

- I tried to start debug (Main, render, all) and none of them looks able to enter in debug
- I tried to do npm start and after run debug, but doesn't works.

**Comment by MohamedWagih** [comment]
@EnricoBeltramo Me too I tried the same as you mentioned and it didn't work.

**Comment by hongwen000** [comment]
Same question.

**Comment by amilajack** [comment]
fixed in b32c5627fc0c2cac87b4c92384e3af7d965731ca
