### ISSUE TITLE
Does Webpack DLL still matter/still help?

### ISSUE THREAD

**Issue by Slapbox** [electron-react-boilerplate/electron-react-boilerplate#3234]
## Summary

I noticed the Webpack configuration still includes the DLL config. As far as I know this isn't beneficial anymore, but I can't find any firm sources for that. The closest I can find is this repo saying it will no longer be necessary: https://github.com/asfktz/autodll-webpack-plugin

Do we know if there's still a performance benefit in Webpack 5?

**Comment by amilajack** [comment]
I had the same question recently but haven't spent the time validating my hypothesis that doesn't add value anymore. Feel free to play around with removing dlls and share your learnings

**Comment by Slapbox** [comment]
I actually never got it working in our configuration (which has diverged very substantially) and hadn't thought about whether we were missing out on performance gains until seeing it still incorporated into the boilerplate.

**Comment by Cori1109** [comment]
I actually never got it working in our configuration (which has diverged very substantially) and hadn't thought about whether we were missing out on performance gains until seeing it still incorporated into the boilerplate.

**Comment by amilajack** [comment]
I'll drop the dll integration and see see if there's any significant performance degradation

We'll be migrating to esbuild or swc/turbobuild at some point in the future (#3188)

**Comment by Slapbox** [comment]
> We'll be migrating to esbuild

Will that prevent using Babel plugins during transpilation?
