### ISSUE TITLE
Clean-install project reports "Parsing error: '>' expected" error

### ISSUE THREAD

**Issue by hongwen000** [electron-react-boilerplate/electron-react-boilerplate#3236]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
No error should be reported by VSCode code inspector for an clean-install of the project.

## Current Behavior
While npm start successes and the template application could launch normally, VSCode code inspector reports `Parsing error: '>' expected` after opening `src/renderer/index.ejs`.

<img width="1091" alt="截屏2022-06-03 10 08 54" src="https://user-images.githubusercontent.com/25456415/171773000-421eb2a9-d5b3-4c1e-b50a-4f3963ad38b0.png">

## Steps to Reproduce

1. Clone and npm install the project.

2. Open in VSCode.

3. Navigate to `src/renderer/index.ejs`.

4.

## Your Environment

- Node version : v16.15.1
- electron-react-boilerplate version or branch : commit a104b64943b6465f782ace601ef845c22dafc138 (grafted, HEAD -> main, tag: v4.6.0, origin/main, origin/HEAD)
- Operating System and version : Windows 11 build 22621.1
- Link to your project :

**Comment by amilajack** [comment]
this may have been fixed by b32c5627fc0c2cac87b4c92384e3af7d965731ca. please comment if this isn't the case
