### ISSUE TITLE
Adding mp4 files

### ISSUE THREAD

**Issue by timothymalcham** [electron-react-boilerplate/electron-react-boilerplate#3237]
## Summary

What is the best/recommended way to add video files (mp4, webm, etc.)?

I've added this to the webpack config:
```
            // Video
            { test: /\.(mp4)$/, loader: 'url-loader' },
            {
                test: /\.html$/,
                use: {
                    loader: 'html-loader',
                    options: {
                        attrs: [':src'],
                    },
                },
            },
```

Which works in development, but in production after packaging up the app, the videos don't load. Using html loader is "suppose" to fix this, but I can't figure out why they don't show up.

**Comment by amilajack** [comment]
which webpack config did you add it to?
