### ISSUE TITLE
.prettierrc does`t work

### ISSUE THREAD

**Issue by venlee1993** [electron-react-boilerplate/electron-react-boilerplate#3238]
![image](https://user-images.githubusercontent.com/27339765/172276848-a672fc46-836a-4597-9550-088fc5606677.png)

**Comment by shensven** [comment]
erb configure Prettier via package.json
see these example
https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/a104b64943b6465f782ace601ef845c22dafc138/package.json#L66-L79
https://github.com/shensven/Yadds/blob/28e81b5aace143f4053c28718e20583e6706eea4/package.json#L55-L69
