### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by RuiRocha1991** [electron-react-boilerplate/electron-react-boilerplate#3239]
## Summary
I'm learning to work with electron and I'm having the problem that I identify in the following image whenever I add the electron functions IpcRenderer.send(....) in my react files.
Has anyone ever experienced this? How can I solve the problem?
I also send my repository with the project in question.
https://github.com/RuiRocha1991/JiraEnvironmentManager_electron

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/29250466/172574238-f0f2b1b4-05ff-4bb4-9041-20abec293ea1.png">

Thank you for your help.

**Comment by velut** [comment]
You should call `ipcRenderer` only from the `preload.ts` script, [which has access to the node APIs](https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts).

In your react components, you should call the corresponding `window.electron.doSomething()` methods registered using the `contextBridge` ([see docs](https://www.electronjs.org/docs/latest/api/context-bridge)) in `preload.ts`.

To make things clearer, here's what you should do to call function `foobar(s: string): number` available in the main (node) process from the renderer (client) process.

1. Define function `foobar` somewhere, for example in file `foobar.ts`  
3. In `src/main/main.ts`, after the `app` is ready, register an handler using `ipcMain` that calls `foobar` on its channel key
4. In `src/main/preload.ts`, use the `contextBridge` to expose the foobar API to the renderer process through the `window` global; here you call `ipcRenderer.invoke` with the appropriate channel and arguments
5. Update `src/renderer/preload.d.ts` to reflect the API exposed from `preload.ts`
6. In your react components, call the exposed `window.electron.foobar()` method

```ts
// src/lib/foobar.ts

export default function foobar(s: string): number {
  // Do anything, including using node APIs
  console.log(s);
  return s.length;
}
```

```ts
// src/main/main.ts

// At the bottom of the file
app
  .whenReady()
  .then(() => {

    // Register you handler here
    ipcMain.handle('myFoobarChannel' , (_, ...args) => {
      return foobar(args[0] as string);
    });

    createWindow();
    app.on('activate', () => {
      // On macOS it's common to re-create a window in the app when the
      // dock icon is clicked and there are no other windows open.
      if (mainWindow === undefined) createWindow();
    });
  })
  .catch(console.log);
```

```ts
// src/main/preload.ts

contextBridge.exposeInMainWorld("electron", {
  foobar(s: string): Promise<number> {
    return ipcRenderer.invoke('myFoobarChannel', s);
  },
});
```

```ts
// src/renderer/preload.d.ts

declare global {
  interface Window {
    electron: {
      foobar(s: string): Promise<number>;
    };
  }
}

export {};
```

```ts
// src/renderer/components/MyComponent.tsx

export default function MyComponent() {
  useEffect(() => {
    // Should log `5` in the console
    window.electron.foobar('hello').then(console.log);
  });

  return <div>...</div>;
}
```

**Comment by RuiRocha1991** [comment]
Thank you for your availability and your help. After your answer, I went to analyze the boilerplate code and I already understood the preload function and everything is clearer for me.
I confess that it is my first electron application created by me.
