### ISSUE TITLE
An error occurred when I use ipcRenderer.send()

### ISSUE THREAD

**Issue by Beacontownfc** [electron-react-boilerplate/electron-react-boilerplate#3241]
For example, `ipcRenderer.send('ipc-example')`.
An error as shown in the following figure appears. I don't know how to fix it.
![微信截图_20220613235024](https://user-images.githubusercontent.com/89081023/173394266-4d8e634d-4a01-4ea1-bd04-48ce07e5b2e1.png)

**Comment by velut** [comment]
You are probably calling `ipcRenderer` directly from react components. See this comment instead https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3239#issuecomment-1155041899

**Comment by Beacontownfc** [comment]
> You are probably calling `ipcRenderer` directly from react components. See this comment instead [#3239 (comment)](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3239#issuecomment-1155041899)

Thanks, your reply is very helpful to me. The code is changed to the following code and successfully solved the problem.
`window.electron.ipcRenderer.sendMessage('ipc-example', []);`
