### ISSUE TITLE
Possible to use child_process.spawn in renderer? 

### ISSUE THREAD

**Issue by alexanderkershaw** [electron-react-boilerplate/electron-react-boilerplate#3243]
## Summary

Is it possible to run a child_process within the renderer process? 

I've tried to import spawn in App.tsx with
`const spawn = require('child_process').spawn;`

as well as various other forms, but I always get 

```
Module not found: Can't resolve 'child_process' in 'D:\checkouts\wow-recorder\src\recorder'
src/recorder/Recorder.tsx
```

Not sure if the solution is to run spawn in the main process, I thought I read that shouldn't happen as risks blocking the main process. I've seen a mention here: https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/2396 but it didn't lead me to a solution. 

Thanks.

**Comment by velut** [comment]
For security reasons, the renderer process does not have access to Node APIs. Depending on your use case, you should look into different solutions.

See https://www.electronjs.org/docs/latest/tutorial/process-model#the-renderer-process.

**Comment by amilajack** [comment]
I second @velut's feedback. please spawn child processes in the main process or use web workers in the renderer process
