### ISSUE TITLE
Create multiple Windows

### ISSUE THREAD

**Issue by ZGKtob** [electron-react-boilerplate/electron-react-boilerplate#3248]
How to do create multiple Windows

**Comment by cinderblock** [comment]
At a minimum, you'll need a second call to `new BrowserWindow({...})` in your main process. You might also want different html template entry points.

If you want to load a different html template for the second window, you'll need another `new HtmlWebpackPlugin({...})` entry in the various webpack configs.

**Comment by ZGKtob** [comment]
> HtmlWebpackPlugin

我配置了但是加载的是同一个html文件

**Comment by cinderblock** [comment]
> I configured but the same html file is loaded

Did you see the `.loadURL(...)` line in the example?

**Comment by ZGKtob** [comment]
> 
看了的
![Uploading 企业微信截图_16566554008018.png…]()

**Comment by ZGKtob** [comment]
![企业微信截图_16566554008018](https://user-images.githubusercontent.com/46163371/176834031-3a8f98ad-29ac-4864-8716-1ed6f2e4d244.png)
kanl
![企业微信截图_16566554262746](https://user-images.githubusercontent.com/46163371/176834039-87510233-ecab-428f-b8e3-038addece7f5.png)
![企业微信截图_16566554533770](https://user-images.githubusercontent.com/46163371/176834044-be6a83c8-7d0a-4b7c-970f-7c7fdda00ddb.png)
看了的

**Comment by ZGKtob** [comment]
渲染的时候还是调用的renderjs来进行渲染的

**Comment by ZGKtob** [comment]
我用路由的形式去，在开发环境下可以但是在生产环境下就不行了

**Comment by cinderblock** [comment]
`HtmlWebpackPlugin` automatically inserts a script tag for the Webpack "`entry`". You're getting into some slightly more advanced usage of `HtmlWebpackPlugin`.

I think you'll need to add a second `entry` for webpack and then configure the different `HtmlWebpackPlugin` instances to use one or the other. I think that's what the `chunks` array is for.

**Comment by ZGKtob** [comment]
这个entry 我配置了第二个 但是输出的文件都只有这一个呀 我在webpack.config.render.dev.ts 中配置了 也在 webpack.config.render.prod.ts中也配置了 但是输出的文件都只有render.js

**Comment by 1zilc** [comment]
生产环境是file协议，可能要用hash路由或者用query来区分渲染不同的页面

> 我用路由的形式去，在开发环境下可以但是在生产环境下就不行了

**Comment by ch3rn1k** [comment]
> HtmlWebpackPlugin

Hello! Can you tell me what have you done? Ty

**Comment by DVGY** [comment]
Anyone stuck here pls contact me

**Comment by alielmajdaoui** [comment]
I made a guide based on this issue
https://medium.com/@alielmajdaoui/multiple-windows-in-electron-react-boilerplate-c6d763f38306

**Comment by DVGY** [comment]
@alielmajdaoui Nice, even I wrote a blog. 
https://dvgy.hashnode.dev/how-to-make-multi-window-electron-application

**Comment by emptydn1** [comment]
> @alielmajdaoui Nice, even I wrote a blog. https://dvgy.hashnode.dev/how-to-make-multi-window-electron-application
thank you for tutorial but its not working when i build exe file.... can u fix it ?

**Comment by emptydn1** [comment]
> @alielmajdaoui Nice, even I wrote a blog. https://dvgy.hashnode.dev/how-to-make-multi-window-electron-application

thank you for tutorial but its not working when i build exe file, can u fix it pls ?

**Comment by alielmajdaoui** [comment]
@emptydn1 you will need to edit the webpack prod file. I will try to document that in the same article I wrote if I got time this week.

**Comment by DVGY** [comment]
> I will try to document that in the same articl

@emptydn1 you need to copy paste the same config in webpack prod files

**Comment by amilajack** [comment]
Closing because this seems resolved

**Comment by EricProcessor** [comment]
@alielmajdaoui how about prod file, do u have time to write it?

**Comment by alielmajdaoui** [comment]
@EricProcessor it's already updated
