### ISSUE TITLE
Copying seperate assets to release during build

### ISSUE THREAD

**Issue by cheynewallace** [electron-react-boilerplate/electron-react-boilerplate#3249]
## Summary
I've read the documentation on this (its very brief) but im still totally stuck trying to move a few basic files across during the build.

Next to my `index.ejs` file, I have a plain HTML file called "identify.html"..  This file loads one image from `./assets/images/logo.png`,  ``` <img class="logo" src="./assets/images/logo_white.png" />```  simple.

However when I build, the images are compiled into a finger printed format and moved out of the `assets/images` path and are moved just into the root release renderer folder with a name like `c7f61544cd5008b981fb.png`..
Obviously now I can't reference that image anymore, the path and name has changed, the HTML file is just a plain HTML file, it does not perform any imports etc nor it is aware of any environments.

I just want to copy these two files acrosss during the build untouched and be able to load the image on the page with out having to build an entire application to be compiled back into a simple HTML file..  Someone has suggested I need to define an entirely new webpack bundler, next to main and renderer... This seems crazily over complicated to just copy two files without changing them. 

Can someone point me how to do this? Theres so much "webpack magic" going on, changing names and moving things around im completely lost and iv wasted hours trying to copy two files

**Comment by Goldiserv** [comment]
I had a similar need to copy files from the public folder to assets folder during build/packaging. 
Electron seems to ignore the public folder upon packaging. 

I created a 'copy-locales.js' file and added it to:
package.json > scripts > 
 	"package": "npm run copy-locales ... etc.
along with:
package.json > scripts > 
	"copy-locales": "ts-node ./.erb/scripts/copy-locales.js",


--- copy-locales.js script below ---
import path from 'path';
import fse from 'fs-extra';

const fsCopy = () => {
  const srcDir = path.join(__dirname, '../..', 'public/locales');
  const destDir = path.join(__dirname, '../..', 'assets/locales');

  console.log('copying files from:', { srcDir, destDir }, '\nfor Prod package');
  try {
    fse.copySync(srcDir, destDir, { overwrite: true });
  } catch (err) {
    console.log(err);
  }
};

fsCopy();
