### ISSUE TITLE
WebHID API not working when debugging

### ISSUE THREAD

**Issue by MXBeElec** [electron-react-boilerplate/electron-react-boilerplate#3250]
Hi,

I'm starting a new project based on erb using web-hid api in order to communicate with an usb HID device.

As shown on electron documentation:
https://www.electronjs.org/fr/docs/latest/tutorial/devices
I use navigator api like this:
`navigator.hid.requestDevice({ filters: [] }).then(function (device) {
    console.log(device);
  });`

This work well (i get connected hid devices list) when I build a release with `npm run package` and launch it. 

But when I try to debug the app with `npm start` I am not able to get this api working. (it returns an empty list)

I am beginner in web based dev so I may miss something obvious.

I guess `npm start` run the app in a sort of lightened environment.

Do you have any idea on how i can debug this app with webhid working ?

Thanks for any help

**Comment by siriwatknp** [comment]
I had a similar issue with the WebSerial API #3389

**Comment by amilajack** [comment]
Assuming this has been resolved by now. If it isn't, please comment and I'll reopen
