### ISSUE TITLE
Packaged app doesn't show css styles

### ISSUE THREAD

**Issue by YungMilky** [electron-react-boilerplate/electron-react-boilerplate#3251]
## Prerequisites

- [✔] Using npm
- [ Using 2.3.0, having a hard time to upgrade with redux because electron-redux 2.0 isn't released yet ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [✔] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [✔] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

I ran: npx cross-env DEBUG_PROD=true npm run build
and then npm start separately
- [✔ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

devtools output:
> redux-logger.js:1  action @@router/LOCATION_CHANGE @ 17:35:43.620
> log.js:24 [HMR] Waiting for update signal from WDS...
> index.js:48 [WDS] Hot Module Replacement enabled.
> index.js:52 [WDS] Live Reloading enabled.
> electron/js2c/renderer_init.js:111 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
>     Policy set or a policy with "unsafe-eval" enabled. This exposes users of
>     this app to unnecessary security risks.
> 
> For more information and help, consult
> https://electronjs.org/docs/tutorial/security.
> This warning will not show up
> once the app is packaged.
> (anonymous) @ electron/js2c/renderer_init.js:111
> Promise.then (async)
> warnAboutInsecureCSP @ electron/js2c/renderer_init.js:111
> logSecurityWarnings @ electron/js2c/renderer_init.js:111
> (anonymous) @ electron/js2c/renderer_init.js:111
> async function (async)
> (anonymous) @ electron/js2c/renderer_init.js:111

in the packaged app I get "DevTools failed to load SourceMap" in devtools.

## Expected Behavior
![image](https://user-images.githubusercontent.com/63095356/176720773-e92e1849-05d7-47af-9452-bcf4851e70f2.png)
this is a screenshot from development (yarn/npm start)

## Current Behavior
![image](https://user-images.githubusercontent.com/63095356/176721042-2e531e76-1967-4cd0-96ef-66256694f067.png)
also I get `Module not found: Error: Can't resolve 'utf-8-validate'` and `Module not found: Error: Can't resolve 'bufferutil'` when building and packaging

## Steps to Reproduce
1. `npm run build`
> > build
> > concurrently "yarn build:main" "yarn build:renderer"
> 
> yarn run v1.22.10
> yarn run v1.22.10
> $ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.main.prod.babel.js      
> $ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.renderer.prod.babel.js  
> [0] Browserslist: caniuse-lite is outdated. Please run:
> [0] npx browserslist@latest --update-db
> [0]
> [0] Why you should do it regularly:
> [0] https://github.com/browserslist/browserslist#browsers-data-updating
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1] npx browserslist@latest --update-db
> [1]
> [1] Why you should do it regularly:
> [1] https://github.com/browserslist/browserslist#browsers-data-updating
> [0] Browserslist: caniuse-lite is outdated. Please run:
> [0] npx browserslist@latest --update-db
> [0]
> [0] Why you should do it regularly:
> [0] https://github.com/browserslist/browserslist#browsers-data-updating
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1] npx browserslist@latest --update-db
> [1]
> [1] Why you should do it regularly:
> [1] https://github.com/browserslist/browserslist#browsers-data-updating
> [0] asset ./src/main.prod.js 961 KiB [emitted] [minimized] (name: main) 1 related asset
> [0] orphan modules 451 KiB [orphan] 67 modules
> [0] runtime modules 1.04 KiB 5 modules
> [0] modules by path ./node_modules/ 2.32 MiB 837 modules
> [0] 22 modules
> [0]
> [0] WARNING in ./node_modules/engine.io/node_modules/ws/lib/buffer-util.js 105:21-42
> [0] Module not found: Error: Can't resolve 'bufferutil' in 'F:\Coding\bigting\ShareHub\client\node_modules\engine.io\node_modules\ws\lib'
> [0]  @ ./node_modules/engine.io/node_modules/ws/lib/websocket.js 24:21-45
> [0]  @ ./node_modules/engine.io/node_modules/ws/index.js 3:18-44
> [0]  @ ./node_modules/engine.io/lib/server.js 10:26-46
> [0]  @ ./node_modules/engine.io/lib/engine.io.js 6:15-34
> [0]  @ ./node_modules/socket.io/dist/index.js 32:15-35
> [0]  @ ./node_modules/socket.io/wrapper.mjs 1:0-33 3:43-45
> [0]  @ ./src/main.dev.ts 31:0-35 237:37-43
> [0]
> [0] WARNING in ./node_modules/engine.io/node_modules/ws/lib/validation.js 86:20-45
> [0] Module not found: Error: Can't resolve 'utf-8-validate' in 'F:\Coding\bigting\ShareHub\client\node_modules\engine.io\node_modules\ws\lib'
> [0]  @ ./node_modules/engine.io/node_modules/ws/lib/receiver.js 13:43-66
> [0]  @ ./node_modules/engine.io/node_modules/ws/index.js 7:21-46
> [0]  @ ./node_modules/engine.io/lib/server.js 10:26-46
> [0]  @ ./node_modules/engine.io/lib/engine.io.js 6:15-34
> [0]  @ ./node_modules/socket.io/dist/index.js 32:15-35
> [0]  @ ./node_modules/socket.io/wrapper.mjs 1:0-33 3:43-45
> [0]  @ ./src/main.dev.ts 31:0-35 237:37-43
> [0]
> [0] 2 warnings have detailed information that is not shown.
> [0] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
> [0]
> [0] webpack 5.41.1 compiled with 2 warnings in 10518 ms
> [0] yarn build:main exited with code 0
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1] npx browserslist@latest --update-db
> [1]
> [1] Why you should do it regularly:
> [1] https://github.com/browserslist/browserslist#browsers-data-updating
> [1] asset renderer.prod.js 934 KiB [emitted] [minimized] (name: main) 1 related asset
> [1] asset 06113bf748ae7dc33e05189a90815625.ttf 311 KiB [emitted] [immutable] [from: assets/Helvetica.ttf] (auxiliary name: main)
> [1] asset style.css 12.5 KiB [emitted] [minimized] (name: main)
> [1] Entrypoint main 946 KiB (311 KiB) = style.css 12.5 KiB renderer.prod.js 934 KiB 1 auxiliary asset  
> [1] 1202 modules
> [1] webpack 5.41.1 compiled successfully in 17070 ms
> Done in 19.25s.
> [1] yarn build:renderer exited with code 0

2. `npm run package`

> > package
> > yarn build && electron-builder build --publish never
> 
> yarn run v1.22.10
> $ concurrently "yarn build:main" "yarn build:renderer"
> $ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.main.prod.babel.js      
> $ cross-env NODE_ENV=production webpack --config ./.erb/configs/webpack.config.renderer.prod.babel.js  
> [0] Browserslist: caniuse-lite is outdated. Please run:
> [0] npx browserslist@latest --update-db
> [0]
> [0] Why you should do it regularly:
> [0] https://github.com/browserslist/browserslist#browsers-data-updating
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1] npx browserslist@latest --update-db
> [1]
> [1] Why you should do it regularly:
> [1] https://github.com/browserslist/browserslist#browsers-data-updating
> [0] Browserslist: caniuse-lite is outdated. Please run:
> [0] npx browserslist@latest --update-db
> [0]
> [0] Why you should do it regularly:
> [0] https://github.com/browserslist/browserslist#browsers-data-updating
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1] npx browserslist@latest --update-db
> [1]
> [1] Why you should do it regularly:
> [1] https://github.com/browserslist/browserslist#browsers-data-updating
> [0] asset ./src/main.prod.js 961 KiB [compared for emit] [minimized] (name: main) 1 related asset
> [0] orphan modules 451 KiB [orphan] 67 modules
> [0] runtime modules 1.04 KiB 5 modules
> [0] modules by path ./node_modules/ 2.32 MiB 837 modules
> [0] 22 modules
> [0]
> [0] WARNING in ./node_modules/engine.io/node_modules/ws/lib/buffer-util.js 105:21-42
> [0] Module not found: Error: Can't resolve 'bufferutil' in 'F:\Coding\bigting\ShareHub\client\node_modules\engine.io\node_modules\ws\lib'
> [0]  @ ./node_modules/engine.io/node_modules/ws/lib/receiver.js 12:42-66
> [0]  @ ./node_modules/engine.io/node_modules/ws/index.js 7:21-46
> [0]  @ ./node_modules/engine.io/lib/server.js 10:26-46
> [0]  @ ./node_modules/engine.io/lib/engine.io.js 6:15-34
> [0]  @ ./node_modules/socket.io/dist/index.js 32:15-35
> [0]  @ ./node_modules/socket.io/wrapper.mjs 1:0-33 3:43-45
> [0]  @ ./src/main.dev.ts 31:0-35 237:37-43
> [0]
> [0] WARNING in ./node_modules/engine.io/node_modules/ws/lib/validation.js 86:20-45
> [0] Module not found: Error: Can't resolve 'utf-8-validate' in 'F:\Coding\bigting\ShareHub\client\node_modules\engine.io\node_modules\ws\lib'
> [0]  @ ./node_modules/engine.io/node_modules/ws/lib/receiver.js 13:43-66
> [0]  @ ./node_modules/engine.io/node_modules/ws/index.js 7:21-46
> [0]  @ ./node_modules/engine.io/lib/server.js 10:26-46
> [0]  @ ./node_modules/engine.io/lib/engine.io.js 6:15-34
> [0]  @ ./node_modules/socket.io/dist/index.js 32:15-35
> [0]  @ ./node_modules/socket.io/wrapper.mjs 1:0-33 3:43-45
> [0]  @ ./src/main.dev.ts 31:0-35 237:37-43
> [0]
> [0] 2 warnings have detailed information that is not shown.
> [0] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
> [0]
> [0] webpack 5.41.1 compiled with 2 warnings in 9865 ms
> [0] yarn build:main exited with code 0
> [1] Browserslist: caniuse-lite is outdated. Please run:
> [1] npx browserslist@latest --update-db
> [1]
> [1] Why you should do it regularly:
> [1] https://github.com/browserslist/browserslist#browsers-data-updating
> [1] assets by status 311 KiB [cached] 1 asset
> [1] asset renderer.prod.js 934 KiB [compared for emit] [minimized] (name: main) 1 related asset        
> [1] asset style.css 12.5 KiB [compared for emit] [minimized] (name: main)
> [1] Entrypoint main 946 KiB (311 KiB) = style.css 12.5 KiB renderer.prod.js 934 KiB 1 auxiliary asset  
> [1] 1202 modules
> [1] webpack 5.41.1 compiled successfully in 14623 ms
> [1] yarn build:renderer exited with code 0
> Done in 17.17s.
>   • electron-builder  version=22.11.7 os=10.0.18363
>   • loaded configuration  file=package.json ("build" field)
>   • writing effective config  file=release\builder-effective-config.yaml
>   • packaging       platform=win32 arch=x64 electron=11.4.9 appOutDir=release\win-unpacked
>   • building        target=nsis file=release\Mingler Setup 2.3.0.exe archs=x64 oneClick=false perMachine=false
>   • building block map  blockMapFile=release\Mingler Setup 2.3.0.exe.blockmap

Examples of css module and usage:
1. SplashScreen.jsx:
```
import styles from './SplashScreen.module.css';

//...
const Separator = () => {
  return <h6 className={styles.separator}>or</h6>;
};
```

2. SplashScreen.module.css:

```
.separator {
  display: flex;
  flex-direction: row;
  padding-inline: 16%;
  color: var(--dark-mode-light-black);
  opacity: 0.2;
}
```

note that each file contains more code than presented, but they both work seemingly flawlessly in development (pictured above)

## Context
I've been using [stitches](https://github.com/stitchesjs/stitches) until I found out the scrollbar was showing and a few inputs had missing styles in the packaged app. I've spent two days porting everything over to regular css modules (+App.global.css), and now all  styles are missing. I'm also using framer motion.

## Your Environment

- Node version : v14.17.2
- electron-react-boilerplate version or branch : 2.3.0
- Operating System and version : Windows 10 Pro 1909
- Link to your project : https://github.com/YungMilky/havingabadtime/tree/main

**Comment by Veniceeeeee** [comment]
Damn that’s crazy

**Comment by YungMilky** [comment]
I went back to stitches and this old ERB commit fixed the missing global styles:

index.html
```
<script>
//...

const link = document.createElement('link');
link.rel = 'stylesheet';
link.href = './dist/style.css';
// HACK: Writing the script path should be done with webpack
document.getElementsByTagName('head')[0].appendChild(link);
</script>
```
