### ISSUE TITLE
Feature Request: Develop for remote system

### ISSUE THREAD

**Issue by cinderblock** [electron-react-boilerplate/electron-react-boilerplate#3252]
## The Problem

I've been making some user interfaces based on Raspberry Pi + display combos for some "appliance" type devices. The official Pi touch screen with a case makes for a *great* touch interface to control operations. It's easy enough to set an Electron to run on startup locked in full screen (I run it straight on X so no KDE or GNOME to break things).

For many things, it's plenty good enough to develop on another machine and then send the completed/packaged program to the Pi to run. You can even do things like lock the window size in development to the same resolution as the final full screen kiosk.

However, in particular on a Raspberry Pi, there is some functionality that cannot be reasonably replicated or mocked on a development system with different hardware. A prominent example is reading GPIO from sysfs drivers in the kernel or via a native module like pigpio. It's possible to make mocks that are good enough for many development workflows but I'd like to propose an alternate workflow that I think could have a lot of value for others and might fit in nicely here.

## My Workflow

My workflow has relied on keeping development files on my fast/high performance development computer and hooking into the bundler to push the compiled result directly to the remote system. This has wonderful performance implications for development as I can develop on my fast computer with a big screen and then quickly (on save) compile (with fast CPU), publish, and re-start the app on the target (slow) remote machine. Incremental builds make this blazingly fast as it keeps the TypeScript compiler loaded and does the minimum recompilation on every change. With a little fineness, Hot Reload/Fast Refresh can work too.

A little more work allows me to start the remote electron with remote debugging/inspecting of the real app. It can even integrate with the code editor for inspection/stepping through real code, or getting access to a repl.

One issue that complicates things in this case is the bundling of packages that change their behavior based on the system they're installed on. A simple example is almost any native module. Another prominent package that wants to be built on the target/remote machine is pigpio - it will actually silently pretend to install on systems missing core dependencies causing runtime errors instead of installation errors ([imho, a bad choice](https://github.com/fivdi/pigpio/issues/136)).

To solve this, I copy the local `pacakge.json` to the target system and then run an `npm i` there first. This guarantees that any of my dependencies are "npm installed" on the target machine exactly how they expect to be "installed" (allowing any `postinstall` scripts to run, for instance).

## Proposal

I see some talk about the "next" plans for ERB. Is this crazy workflow something that could be supported here?

I realize my Raspberry Pi case is a little limited but I wonder if the same could make sense for other developers (developing on Mac OS for Windows target?).

This has implications for other common use cases like bundling native modules. Do you bundle a version for each possible target? Can you build all needed native modules with a cross-compiler?

## Other Thoughts

I've considered using VS Code's Remote SSH plugin but that runs almost everything on the remote system so compilation and bundling are slow, especially for big projects on small Pis.

**Comment by amilajack** [comment]
outside the scope of this repo
