### ISSUE TITLE
error when use @reduxjs/toolkit

### ISSUE THREAD

**Issue by vishwajit76** [electron-react-boilerplate/electron-react-boilerplate#3254]
`Uncaught TypeError: Cannot read properties of undefined (reading 'createSlice')`

**Comment by elton11220** [comment]
I can use the @reduxjs/toolkit normally. Just deconstruct the createSlice from @reduxjs/toolkit like 'import {createSlice} from "@reduxjs/toolkit"'.You can show us the exact code that cause the issue

**Comment by brioapp** [comment]
Redux/toolkit works fine.

**Comment by amilajack** [comment]
closing since this seems resolved
