### ISSUE TITLE
BetterSqlite3 best practices

### ISSUE THREAD

**Issue by alex-buys-github** [electron-react-boilerplate/electron-react-boilerplate#3257]
## Summary

First and foremost, a massive thank you to you and the team for the great work you are doing with ERB!! 

I have a question about how best to use BetterSqlite3.
Looking at https://github.com/amilajack/erb-better-sqlite3-example, I can see that any/all database logic resides in `main.ts` (i.e. Electron).  

1. Is it possible/advisable to have the database logic on the renderer (React) side?
2. If not, do you make use of IPC to send and receive the db data between Electron and React?
3. Are there any downsides to doing this (performance, security, etc.) vs having db logic in React?

Thanx in advance for your time and assistance.

**Comment by amilajack** [comment]
There's no good reason, aside from convenience, to run database queries on the client side. Even though electron allows that, it isn't a good idea.

The electron community is moving away from the "nodeIntegration as default" model to a much more secure "node only in main process" model.
