### ISSUE TITLE
Application not loading after pplication restarts

### ISSUE THREAD

**Issue by parachute-dev** [electron-react-boilerplate/electron-react-boilerplate#3259]
Has anyone run into an issue when packaging up the app - deploying it to a device - all works ok, but then on a restart of the app, nothing shows? No error - nothing in the taskmanager either.

If i reinstall the package - it works again.

**Comment by dhanyn10** [comment]
can you show about Steps to Reproduce your app?

**Comment by amilajack** [comment]
Assuming this has been resolved by now. If it isn't, please comment and I'll reopen
