### ISSUE TITLE
Web Worker File Path

### ISSUE THREAD

**Issue by tegmos** [electron-react-boilerplate/electron-react-boilerplate#3260]
Hi,

I'm trying to get a webworker running, but I am not able to find the correct path to the worker file. 

I can't include any example files. But in a file run in the renderer process, I have this:

`const worker = new Worker("worker.js");`

worker.js is located in the same directory as the file attempting to load it.

When I run the dev server, I get "http://localhost:1212/worker.js" 404 (Not Found).

I looked through the documentation for the boilerplate, but I must be just too new at it and didn't see anything applicable.

 How do I determine the path to my worker file and also include it in packaging or dev?

Thanks!

**Comment by jj185154** [comment]
Create a public folder in the project and put the worker.js there.
const worker = new Worker('.worker.js')
