### ISSUE TITLE
React-Auth0 Integration on Production

### ISSUE THREAD

**Issue by olan-go2** [electron-react-boilerplate/electron-react-boilerplate#3261]
I have integrated auth0-react and it's working fine in development since I have whitelisted the dev and the server is running on `localhost:8080`, redirection seems to be working fine.

However, on production, the location changes, and it's somehow running on a file path directly to my file system. ie.`file:///Users...`
And I can't whitelist something arbitrary on auth0 admin.

Any suggestions on how to fix it in production? Thank you.

**Comment by amilajack** [comment]
Closing because this has likely been resolved by now. Please comment if your'e still running into this issue and I'll reopen

**Comment by H3XAGON** [comment]
Hi, I'm having this issue. Everything works fine in development, but when I switch to production my app goes blank when I click the 'Log in' button. Is there a solution for this? Thanks

**Comment by mohamedikram7** [comment]
hi any update on this @amilajack

**Comment by mohamedikram7** [comment]
@olan-go2  and @H3XAGON  did u find any solution
