### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by brioapp** [electron-react-boilerplate/electron-react-boilerplate#3262]
Caused by IPC: `import { ipcRenderer } from 'electron';`

**Comment by NinthMonee** [comment]
> Caused by IPC: `import { ipcRenderer } from 'electron';`

I have the same problem

**Comment by NinthMonee** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/47859908/180193795-a30153ac-46cf-4907-9e96-30b0787a0229.png">

**Comment by Goldiserv** [comment]
You're meant to access ipcRenderer via window.electron.ipcRenderer

Here's my sample code in App.tsx via a useEffect, no imports needed.
useEffect(() => {
window.electron.ipcRenderer.send('app_version'); // request app version text update
}, []);

**Comment by abbasKareem** [comment]
I am able to send data from renderer to main process,
but how you get data from main process to renderer? 
is there any code can help me with this?

**Comment by brioapp** [comment]
> 

Without 'import' it works fine, just like the code you posted.
