### ISSUE TITLE
How to pass MainWindow to react renderer

### ISSUE THREAD

**Issue by a7medmo7med9** [electron-react-boilerplate/electron-react-boilerplate#3274]
how can i use MainWindow variable that created in main/main.ts in frontend to use it with [dialog] window

![Screenshot from 2022-07-30 20-40-23](https://user-images.githubusercontent.com/34967435/181937486-9c2cba6b-a80a-4884-8478-6a2348849e31.png)

**Comment by NichuNaizam** [comment]
i think you should use the ipcRenderer and use the main process to do the dialog stuff

**Comment by MrSharpp** [comment]
you should first make a channel to handle "OPEN_ASSET_BROWSE" like this in action.ts, and then from the front end use ipcRenderer to call that channel, and return the chosen file path with the return keyword in action.ts and you will get the selected file in the front end.

**Comment by amilajack** [comment]
Closing, since solutions are mentioned above.
