### ISSUE TITLE
Compatibility with electron-better-ipc

### ISSUE THREAD

**Issue by PaulSender** [electron-react-boilerplate/electron-react-boilerplate#3285]
Currently, [electron-better-ipc](https://github.com/sindresorhus/electron-better-ipc#readme) doesn't work with the webpack configuration for electron-react-boilderplate. 

The following error occurs when trying to make a call from rerender to main as defined in the package's [docs](https://github.com/sindresorhus/electron-better-ipc#using-the-built-in-ipc): 

```Module not found: Error: Can't resolve 'fs' in '/Users/paulsender/dev/beacon/electron/node_modules/electron```

I tried resolving the error through the following thread: 

https://github.com/sindresorhus/electron-better-ipc/issues/36. 

A package maintainer for electron-better-ipc said the issue is one with webpack. I followed the "solutions" on this thread and realized everything was already configured according to those solutions. 

Since electron-react-boilerplate uses .erbs for it's webpack configs. I'm assuming there must be some additional configuration not documented anywhere to get this type of package to work with .erb webpack configs. If I'm wrong about this assumption a point in the right direction would be greatly appreciated.

**Comment by amilajack** [comment]
You could fix this by adding this to your webpack main and renderer prod and dev configs:

```ts
// renderer webpack configs
new webpack.DefinePlugin({
  'process.type': JSON.stringify('renderer'),
});

// main webpack configs
new webpack.DefinePlugin({
  'process.type': JSON.stringify('main'),
});
```

**Comment by amilajack** [comment]
Additionally, `electron-better-ipc` [imports electron in the renderer process](https://github.com/sindresorhus/electron-better-ipc/blob/main/source/renderer.js#L2), which isn't allowed when `nodeIntegration` is false.
