### ISSUE TITLE
Upgrading project from ERB 2.2 to 4.6

### ISSUE THREAD

**Issue by andrewschreiber** [electron-react-boilerplate/electron-react-boilerplate#3286]
## Summary

Hey I'm interested in updating the foundation for my app. I've seen some tremendous changes have happened over the past year and a half - well done! However I'm unclear the implications of moving from to NPM from Yarn, two package.json to one, etc.

Curious for any guides/recommendations. Also if I should wait because of even bigger changes happening soon.

**Comment by andrewschreiber** [comment]
Here is a basic guide https://electron-react-boilerplate.js.org/docs/upgrade-guide

**Comment by amilajack** [comment]
Unfortunately there are no guides except the one you mentioned. I recommend following the changes in the releases and updating accordingly.
