### ISSUE TITLE
Unable to load preload script if electron >= 20

### ISSUE THREAD

**Issue by shensven** [electron-react-boilerplate/electron-react-boilerplate#3288]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior

bump electron to v20

## Steps to Reproduce

1. `git clone`, commit at [ccb801ecc948cf1c7074e6541634aba321168fa4](https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/ccb801ecc948cf1c7074e6541634aba321168fa4)

2. `npm install`

3. `npm i -D electron@20`

4. `npm start`

## Possible Solution (Not obligatory)
Specify `sandbox: false`
``` js
webPreferences: {
    ...
    sandbox: false
    preload: app.isPackaged
        ? path.join(__dirname, 'preload.js')
        : path.join(__dirname, '../../.erb/dll/preload.js'),
},
```

## Your Environment

- Node version : v16.16.0
- electron-react-boilerplate version or branch : commit at [ccb801ecc948cf1c7074e6541634aba321168fa4](https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/ccb801ecc948cf1c7074e6541634aba321168fa4)
- Operating System and version : macOS 12.5

## Screenshot
<img width="1236" alt="Xnip2022-08-10_17-02-37" src="https://user-images.githubusercontent.com/16205980/183861385-fcf926e5-01cc-4fce-b7f5-7361391b67e0.png">

Electron v20 has sandbox enabled by default.
https://www.electronjs.org/releases/stable#20.0.0

The console reports there error, but it doesn't actually seem to have any effect even though `sandbox: true`, and the renderer process displays as normal.

**Comment by killpowa** [comment]
up, I am having the same issue

**Comment by amilajack** [comment]
Investigating this, thanks for opening this

**Comment by amilajack** [comment]
fixed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3291
