### ISSUE TITLE
Add module import for development environment

### ISSUE THREAD

**Issue by simplynormal** [electron-react-boilerplate/electron-react-boilerplate#3293]
I have a `service` folder inside `src` folder. When I tried to import using the alias import from webpack, in dev mode, it didn't work.

```javascript
import file from 'services/file';
```

console:

```bash
App threw an error during load
Error: Cannot find module 'services/file'
... and some javascript fallbacks
```

But when the app is packaged it works perfectly fine. I guess when `npm start` it uses [electronmon](https://www.npmjs.com/package/electronmon) so it doesn't support that syntax, but can ERB supports something like this?

**Comment by simplynormal** [comment]
Forgot to mention, this import is located in `main`, in `renderer` this syntax works even in dev environment

**Comment by amilajack** [comment]
Which webpack config did you modify? `webpack.config.base.js` is the config to modify.

**Comment by simplynormal** [comment]
I didn't modify anything though, the problem is when `npm start` it says cannot find module, but when the app is packaged by `npm run package` it works fine without the error cannot find module.

I found these lines in `webpack.config.base.ts` so that's how I know when app is packaged it will import successfully, not when `npm start` though.

**Comment by simplynormal** [comment]
```javascript
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
    modules: [webpackPaths.srcPath, 'node_modules'],
  },
```

**Comment by liuyike98** [comment]
> I didn't modify anything related to webpack though, just the import in `main`, the problem is when `npm start` it says cannot find module, but when the app is packaged by `npm run package` it works fine without the error cannot find module.
> 
> I found these lines in `webpack.config.base.ts` so that's how I know when app is packaged it will import successfully, not when `npm start` though.
> 
> ```js
>   resolve: {
>     extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
>     modules: [webpackPaths.srcPath, 'node_modules'],
>   },
> ```
> 
> Because when `npm start` it doesn't load the `webpack.config.main.prod.ts` but simply starts the electron by [electronmon](https://www.npmjs.com/package/electronmon)

same to you, have you solve the problem?

**Comment by simplynormal** [comment]
@liuyike98 fortunately yes! You just need to install [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) and change the `start:main` in `package.json` at the root to:
```json
{
  scripts: {
    "start:main": "cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only -r tsconfig-paths/register .",
  }
}
``` 

I found the answer from #2737

**Comment by liuyike98** [comment]
> @liuyike98 fortunately yes! You just need to install [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) and change the `start:main` in `package.json` at the root to:
> 
> ```
> {
>   scripts: {
>     "start:main": "cross-env NODE_ENV=development electronmon -r ts-node/register/transpile-only -r tsconfig-paths/register ."
>   }
> }
> ```
> 
> I found the answer from #2737

got it, thank u!!!
