### ISSUE TITLE
testing error:  No such module was linked: electron_common_features

### ISSUE THREAD

**Issue by dhanyn10** [electron-react-boilerplate/electron-react-boilerplate#3295]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior

```
npm run test

> test
> jest

 FAIL  src/__tests__/App.test.tsx
  ● Test suite failed to run

    No such module was linked: electron_common_features

      at Object.getElectronBinding (node_modules/@electron/remote/dist/src/common/get-electron-binding.js:6:24)
      at Object.<anonymous> (node_modules/@electron/remote/dist/src/common/module-names.js:45:41)
      at Object.<anonymous> (node_modules/@electron/remote/dist/src/renderer/remote.js:7:24)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.734 s
Ran all test suites.
```
## Steps to Reproduce

  1. clone repository
  ```
  https://github.com/dhanyn10/mfm-react.git
  ```
  2. install package
  ```
  npm install
  ```
  3. run test
  ```
  npm run test
  ```

## Your Environment

- Node version :v16.14.0
- electron-react-boilerplate version or branch : im not sure, my project created at april 2022. So, it should be the latest version
- Operating System and version : windows 10, 21H2
- Link to your project : https://github.com/dhanyn10/mfm-react

**Comment by dhanyn10** [comment]
solved, i added jest mock for the first line
```tsx
// project/src/_tests_/App.test.tsx
jest.mock('@electron/remote', () => ({ exec: jest.fn() }));// here is my solution
import '@testing-library/jest-dom';
import { render, screen } from '@testing-library/react';
import App from '../renderer/App';

describe('App', () => {
  it('should render', () => {
    render(<App />);
    expect(screen.getByText('Myapp'));
  });
});

```

**Comment by MohamedJellali** [comment]
How to fix it with mocha and chai?

**Comment by dhanyn10** [comment]
@MohamedJellali can you share your project first?

**Comment by MohamedJellali** [comment]
Sorry, I can’t share the project, it’s a private repo I am contributing on, but to clarify the problem, I am trying to test a method of a resolved class ( using inversify container), The project is built with theia and electron, and the test library is mocha.

**Comment by dhanyn10** [comment]
@MohamedJellali maybe you can create your own simple testing project that have some little similar function with project you've contributing. So you will free to share it with any engineer outside.

**Comment by Stanzilla** [comment]
How would this work with Vitest?
