### ISSUE TITLE
Should I disable @typescript-eslint-no-non-null-assertion?

### ISSUE THREAD

**Issue by karmaral** [electron-react-boilerplate/electron-react-boilerplate#3297]
## Summary

Hello. I've been getting an eslint error on some of the webpack config files, where you use `code!` as an argument or `document.getElementById('root')!;` in `renderer/index.tsx`.

Since this is set up by default in the template, I'd assume it would've jumped in the radar already, so it's probably my own thing and not a bug. 
My question is, should I just disable the rule on such files or is it perhaps that there's someting else that's malfunctioning?

Thanks in advance.

**Comment by amilajack** [comment]
this is fine
