### ISSUE TITLE
Custom local fonts integration into Electron React Boilerplate App

### ISSUE THREAD

**Issue by eltaurito** [electron-react-boilerplate/electron-react-boilerplate#3298]
## How to integrate local fonts into an Electron React Boilerplate App?

Hi guys, 
I tried to find some documentation about this problem, but i did not find anything useful for me.

The only way, which works for me, it is to install the fonts on my computer, but i would like to find a better solution.

I placed my fonts files into:
**assets/fonts/**

And i tried to use it in my scss file located in:
**src/renderer/scss/commons/_fonts.scss**

In this way:
```
@font-face {
  font-family: 'Bariol Regular';
  font-style: normal;
  font-weight: normal;
  src: local('Bariol Regular'),
    url('/assets/fonts/Bariol-Regular.ttf') format('ttf');
  }
```

These are my current Electron versions

```
    "electron": "^15.1.0",
    "electron-builder": "^22.11.7",
    "electron-devtools-installer": "^3.2.0",
    "electron-notarize": "^1.1.1",
    "electron-rebuild": "^3.2.3",
```

I would be grateful if someone could help me.
And i hope this could help someone else.

Thank you!

**Comment by karmaral** [comment]
You should be getting an error on the console, right? Where is it pointing to? I'm inclined to say it should be `../assets/` and not `/assets/`, although it depends on your stylesheet's location really.

**Comment by eltaurito** [comment]
I **resolved** the issue by updating Electron from version 15 to version 20.
Without changing any line of code.
