### ISSUE TITLE
cant push to my own github.

### ISSUE THREAD

**Issue by CaiIsProgrammer** [electron-react-boilerplate/electron-react-boilerplate#3300]
## Prerequisites

- [ x ] Using npm
- [ x ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ x ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ x ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ x ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
able to push to my own github

## Current Behavior
not pushing up to my github

## Steps to Reproduce

ΓêÜ Preparing lint-staged...
> Running tasks for staged files...
  > package.json ΓÇö 11 files
    > *.{js,jsx,ts,tsx} ΓÇö 6 files
      ├ù cross-env NODE_ENV=development eslint --cache [FAILED]
    Γåô *.json,.{eslintrc,prettierrc} ΓÇö no files [SKIPPED]
    ΓêÜ *.{css,scss} ΓÇö 1 file
    Γåô *.{html,md,yml} ΓÇö no files [SKIPPED]
Γåô Skipped because of errors from tasks. [SKIPPED]
ΓêÜ Reverting to original state because of errors...
ΓêÜ Cleaning up temporary files...

├ù cross-env NODE_ENV=development eslint --cache:

Oops! Something went wrong! :(

ESLint: 8.22.0

ESLint couldn't find the config "react-app" to extend from. Please check that the name of the config is correct.

The config "react-app" was referenced from the config file in "C:\Users\cmart\Documents\package.json".

If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.

husky - pre-commit hook exited with code 1 (error)

## Context
ive cloned the repo and trying to upload to my own github but its not allowing me to

## Your Environment

- Node version :v14.17.1

- electron-react-boilerplate version or branch : 4.6
- Operating System and version : windows 10 21H1
- Link to your project : its privated

**Comment by theashishmaurya** [comment]
If the error is `Remote rejected (shallow update not allowed) after changing Git remote URL`, you can follow this guide.
[Remote rejected (shallow update not allowed) after changing Git remote URL](https://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url)

This was the error I was having while pushing to my own GitHub.

**Comment by tegmos** [comment]
This line indicates that it is a linting problem:

husky - pre-commit hook exited with code 1 (error)

I would get an error "npm WARN config global..." and be blocked from committing, but I would scroll up and see that husky error every time. After fixing the linting errors, or just disabling husky, I was able to commit.

**Comment by sinanbozkus** [comment]
We have the same problem on windows machines.

**Comment by amilajack** [comment]
> If the error is `Remote rejected (shallow update not allowed) after changing Git remote URL`, you can follow this guide. [Remote rejected (shallow update not allowed) after changing Git remote URL](https://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url)
> 
> This was the error I was having while pushing to my own GitHub.

closing because this seems like a solution

**Comment by kamarajcalm** [comment]
git remote add old https://github.com/electron-react-boilerplate/electron-react-boilerplate.git
git fetch --unshallow old  
git push origin main
