### ISSUE TITLE
Auto-update app version

### ISSUE THREAD

**Issue by vladkrutenyuk** [electron-react-boilerplate/electron-react-boilerplate#3302]
Usually in node projects I can call "npm version minor" or "...major" etc. But as I understood main package.json file in the root of repository doesnt provide version for your electron app. So version should be changed manually in release/app/package.json

How can I setup app version auto-updating via npm script (like "npm version minor")?

**Comment by jurij** [comment]
`"version:up": "cd release/app && yarn version --patch && cd ../..",`

**Comment by amilajack** [comment]
correct, please update the `release/app/package.json` version
