### ISSUE TITLE
Adding Microsoft Graph SDK - Webpack/polyfill issues

### ISSUE THREAD

**Issue by rbWies** [electron-react-boilerplate/electron-react-boilerplate#3303]
## Prerequisites

- [x ] Using npm
- [x ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Ability to use @microsoft/mgt-electron-provider to authenticate and access Microsoft Graph API

## Current Behavior

I am attempting to add @microsoft/mgt-element @microsoft/mgt-electron-provider, but am running into native node module errors, related to polyfill. I have attempted polyfills, but have not had success. Specifically, I have tried node-polyfill-webpack-plugin and setting fallback for node modules to false.

## Steps to Reproduce

1. Clone ERB repository and npm install

2. Follow the steps outlined in microsoft documention to implement Graph SDK https://docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app

## Possible Solution (Not obligatory)

I believe this all comes down to polyfill and the breaking change of webpack > 5, but cannot find a concise resource on how to solve for it.

## Context

No changes made to ERB before following Graph SDK steps

## Your Environment

- Node version : 16.13.2
- electron-react-boilerplate version or branch : Current version
- Operating System and version : Windows 10, VScode
- Link to your project :

**Comment by amilajack** [comment]
what's the stack trace?

**Comment by rbWies** [comment]
ERROR in ./node_modules/@microsoft/mgt-electron-provider/node_modules/electron/index.js 1:9-22
Module not found: Error: Can't resolve 'fs' in 'C:\GIT\erb-graphSDK-test\node_modules\@microsoft\mgt-electron-provider\node_modules\electron'
 @ ./node_modules/@microsoft/mgt-electron-provider/dist/Provider/ElectronProvider.js 17:0-39 47:8-22 65:32-50 78:18-36 89:18-36
 @ ./node_modules/@microsoft/mgt-electron-provider/dist/Provider/index.js 7:0-35 7:0-35
 @ ./src/renderer/App.tsx 13:19-76
 @ ./src/renderer/index.tsx 10:30-46

ERROR in ./node_modules/@microsoft/mgt-electron-provider/node_modules/electron/index.js 2:11-26
Module not found: Error: Can't resolve 'path' in 'C:\GIT\erb-graphSDK-test\node_modules\@microsoft\mgt-electron-provider\node_modules\electron'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./node_modules/@microsoft/mgt-electron-provider/dist/Provider/ElectronProvider.js 17:0-39 47:8-22 65:32-50 78:18-36 89:18-36
 @ ./node_modules/@microsoft/mgt-electron-provider/dist/Provider/index.js 7:0-35 7:0-35
 @ ./src/renderer/App.tsx 13:19-76
 @ ./src/renderer/index.tsx 10:30-46

webpack compiled with 2 errors


I attempted a fallback for path using path-browserify, but it didn't seem to work. Also, what's the fallback for fs?

**Comment by wds4** [comment]
Did you find a solution to this problem (i.e. the problem  that webpack5 no longer supports polyfills)? I found [this solution](https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5) which addresses the problem in create-react-app, which uses the single package system. Not sure yet whether this same solution will work for erb, which is two-package system.

**Comment by amilajack** [comment]
I'm assuming this has been resolved by now. If it isn't, please comment and I'll reopen
