### ISSUE TITLE
[Question] Why using electron-builder --publish always in workflow?

### ISSUE THREAD

**Issue by zxcvbnm3057** [electron-react-boilerplate/electron-react-boilerplate#3304]
## Summary

I am learner in the first stage about this boilerplate and get a simply question that why using `--publish always` in publish workflow? It seem `--publish onTag` is enough for autoupdate. And there is a test workflow for testing purpose. Thanks for any reply.

**Comment by amilajack** [comment]
please see electron-builder docs for this
