### ISSUE TITLE
Unable to import native dependency in main.ts

### ISSUE THREAD

**Issue by H4kt** [electron-react-boilerplate/electron-react-boilerplate#3309]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Native dependency should load fine according to documentation.

## Current Behavior

Application crashes on start with error:
![image](https://user-images.githubusercontent.com/50774419/188649563-5ed43a05-2d1c-46c0-af8e-6d9b210680c0.png)

## Steps to Reproduce

1. Clone electron-react-boilerplate

2. Install `@napi-rs/lzma` as native dependency into release/app

3. Add some sample code to main.ts to invoke the added library
```ts
import { compress, decompress } from "@napi-rs/lzma/lzma";

(async () => {

  const compressed = await compress('Hello napi-rs 🚀');
  const decompressed = await decompress(compressed);

  console.log(decompressed.toString('utf8'));

})();
```

4. Run the app in dev or release mode

## Your Environment

- Node version : 16.16.0
- electron-react-boilerplate version or branch : main
- Operating System and version : Win 11

**Comment by Aaqu** [comment]
If you have a shortcut to _node_modules_ in  `src` folder, remove and also remove _node_modules_ in `release/app` run `npm instal` and `npm run postisntall`

**Comment by H4kt** [comment]
> If you have a shortcut to _node_modules_ in `src` folder, remove. Also remove _node_modules_ in `release/app` in this path run `npm instal` and `npm run postisntall`

Already tried it.
I even tried to use just the template with an extra piece of code provided in the issue.
The crash still occurs

**Comment by amilajack** [comment]
Add `@napi-rs/lzma/lzma` to your webpack externals in your base webpack config.

That should do the trick.

**Comment by amilajack** [comment]
Example

```ts
  externals: [...Object.keys(externals || {}), '@napi-rs/lzma/lzma'],
```
