### ISSUE TITLE
Why was sandbox disabled for renderer in electron v20?

### ISSUE THREAD

**Issue by aaronvg** [electron-react-boilerplate/electron-react-boilerplate#3324]
## Summary

Isn't the template already following guidelines on not using node integration? Sandbox still allows electron to communicate via IPC with main process no?

**Comment by amilajack** [comment]
We're currently targeting commonjs. Webpack generates references to `module` which aren't supported in the sandbox env. 

Fixed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3328
