### ISSUE TITLE
Unable to load preload script .erb\dll\preload.js

### ISSUE THREAD

**Issue by Traineratwot** [electron-react-boilerplate/electron-react-boilerplate#3329]
1) download repo
2) npm install
3) npm start
4) get error

Until I noticed that this error break something, but still an error is an error and it's better to fix it

![image](https://user-images.githubusercontent.com/41589091/193243005-f32d51b5-8123-4e4c-8345-d9076bec7575.png)

[localhost-1664531363803.log](https://github.com/electron-react-boilerplate/electron-react-boilerplate/files/9682993/localhost-1664531363803.log)

```log
VM4 sandbox_bundle:93 Unable to load preload script: C:\Projects\electron-react-boilerplate\.erb\dll\preload.js
(anonymous) @ VM4 sandbox_bundle:93
VM4 sandbox_bundle:93 ReferenceError: module is not defined
    at <anonymous>:114:1
    at <anonymous>:115:12
    at runPreloadScript (VM4 sandbox_bundle:93:2213)
    at Object.<anonymous> (VM4 sandbox_bundle:93:2480)
    at ./lib/sandboxed_renderer/init.ts (VM4 sandbox_bundle:93:2636)
    at __webpack_require__ (VM4 sandbox_bundle:1:170)
    at VM4 sandbox_bundle:1:1242
    at ___electron_webpack_init__ (VM4 sandbox_bundle:1:1320)
    at VM4 sandbox_bundle:160:455
(anonymous) @ VM4 sandbox_bundle:93
index.js:551 [webpack-dev-server] Server started: Hot Module Replacement enabled, Live Reloading enabled, Progress disabled, Overlay enabled.
log.js:24 [HMR] Waiting for update signal from WDS...
index.js:551 [webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading disabled, Progress disabled, Overlay disabled.
log.js:24 [HMR] Waiting for update signal from WDS...
index.tsx:11 IPC test: pong
```

**Comment by andrewrt** [comment]
I see the same, and it was caused by one of the last 4 commits from what i'm seeing: e933be3, 0450601, 7dabac9, and/or b4cc4ec

**Comment by amilajack** [comment]
https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/51b40ccfaf8ede29823028772907e8ea3c9de19d should fix it for you. Let me know if it doesn't.

**Comment by Traineratwot** [comment]
Yes, it helped, thank you very much
