### ISSUE TITLE
Can we hide native dependencies from app.asar.unpacked node_modules?

### ISSUE THREAD

**Issue by TrofinSorin** [electron-react-boilerplate/electron-react-boilerplate#3332]
## Summary

Can we hide native dependencies from app.asar.unpacked -> node_modules, after installing the app?

![image](https://user-images.githubusercontent.com/43543139/193476447-da020b5a-b0d8-4da4-8dde-f5868464d4be.png)

**Comment by amilajack** [comment]
this isn't possible right now
