### ISSUE TITLE
How to load web-assembly bundle?

### ISSUE THREAD

**Issue by aaronvg** [electron-react-boilerplate/electron-react-boilerplate#3341]
## Summary

I'm trying to follow this tutorial:
https://docs.agora.io/en/interactive-live-streaming/develop/ai-denoiser/#implementation 

but I can't seem to get the WASM module to load properly. Any tips on what I could try?

**Comment by amilajack** [comment]
see https://electron-react-boilerplate.js.org/docs/adding-assets#run-time-assets
