### ISSUE TITLE
postinstall throws with "Module parse failed: Unexpected character '@'" when a sass file is used

### ISSUE THREAD

**Issue by laurentsenta** [electron-react-boilerplate/electron-react-boilerplate#3342]
Hi there, thanks for sharing this very useful repository.

I imported & used Bulma + bulma-checkradio plugin in my repository.
The `postinstall` was failing with the error below.
I found a fix, I'm not sure if that's the proper one, but that might help someone.

## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Current Behavior

```sh
› npm run postinstall

> TickingFocus@4.0.0 postinstall
> ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts

  • electron-builder  version=23.3.3
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=darwin arch=arm64 appDir=/Users/laurent/dev/apps/tomato/release/app
ERROR in ./node_modules/bulma-checkradio/dist/css/bulma-checkradio.sass 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @use "sass:math"
| @import "node_modules/bulma/sass/utilities/_all.sass"
|
 @ dll renderer renderer[2]

ERROR in ./node_modules/bulma/bulma.sass 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @charset "utf-8"
| /*! bulma.io v0.9.4 | MIT License | github.com/jgthms/bulma */
| @import "sass/utilities/_all"
 @ dll renderer renderer[1]

webpack compiled with 2 errors
```

## Steps to Reproduce

I think using the latest electron react boilerplate + a module that depends on sass will trigger this error.

## Possible Solution

```diff
diff --git a/.erb/configs/webpack.config.renderer.dev.ts b/.erb/configs/webpack.config.renderer.dev.ts
index 9fcb2f8..ec0038d 100644
--- a/.erb/configs/webpack.config.renderer.dev.ts
+++ b/.erb/configs/webpack.config.renderer.dev.ts
@@ -63,7 +63,7 @@ const configuration: webpack.Configuration = {
   module: {
     rules: [
       {
-        test: /\.s?css$/,
+        test: /\.s?(c|a)ss$/,
         use: [
           'style-loader',
           {
@@ -79,7 +79,7 @@ const configuration: webpack.Configuration = {
         include: /\.module\.s?(c|a)ss$/,
       },
       {
-        test: /\.s?css$/,
+        test: /\.s?(c|a)ss$/,
         use: ['style-loader', 'css-loader', 'sass-loader'],
         exclude: /\.module\.s?(c|a)ss$/,
       },
```

## Your Environment

- Node version : 16.16.0
- electron-react-boilerplate version or branch : https://github.com/electron-react-boilerplate/electron-react-boilerplate/commit/0450601a481a9da865dd91998f8f1b8756cd2e10
- Operating System and version : macOS, 12.6
- Link to your project :

**Comment by amilajack** [comment]
Assuming this has been resolved by now. If it isn't, please comment and I'll reopen
