### ISSUE TITLE
How to use typescript enums from node modules?

### ISSUE THREAD

**Issue by yles9056** [electron-react-boilerplate/electron-react-boilerplate#3348]
## Summary

I am trying to use an enum from a node module, `obs-studio-node`, but it would result in `TypeError: Cannot read properties of undefined`.

Here's how I use it:
```javascript
// main.ts

// Import the module
import * as osn from 'obs-studio-node';

// EVideoCodes is an enum defined inside the module
console.log(osn.EVideoCodes.Success)

// The above script would result in "TypeError: Cannot read properties of undefined (reading 'Success')"
```

I assume I need to change the configuration of webpack. I've tried the following configuration to webpack.config.base.ts:
```javascript
// webpack.config.base.ts
...
    rules: [
      ...
      { // Add a new rule here
        test: /\.(ts|tsx)$/,
        include: [
          path.resolve(webpackPaths.appNodeModulesPath, 'obs-studio-node'),
        ],
        use: {
          loader: 'ts-loader',
          options: {
            // Remove this line to enable type checking in webpack builds
            transpileOnly: true,
            compilerOptions: {
              module: 'esnext',
            },
          },
        },
      },
    ],
...
```

This configuration does not solve the problem.
What is the correct way of using enum from node modules in `main.ts`?

**Comment by velut** [comment]
This is not a problem with this project but with `obs-studio-node`. 

You are trying to use a `const enum` (see [declaration file](https://unpkg.com/browse/obs-studio-node@0.10.10/module.d.ts#L27)) which are inlined and erased at compile time (see [TypeScript handbook](https://www.typescriptlang.org/docs/handbook/enums.html#const-enums)). 

In other words, there is no enum that you can use in the compiled code that you are importing. You have to use the real value, like `0` for `Success`, in your code.

**Comment by yles9056** [comment]
@velut 
Thanks for the reply.
I'm not saying something is wrong with the npm package, `obs-studio-node`.
That package has a `const enum` that I want to import and use in `main.ts`.
I've done this before in an electron-typescript project without webpack, but I can't make it work in electron-react-boilerplate.

**Comment by amilajack** [comment]
I'm assuming this has been resolved by now. If it isn't, please comment and I'll reopen
