### ISSUE TITLE
How to start a Web Worker ?

### ISSUE THREAD

**Issue by guidra-rev** [electron-react-boilerplate/electron-react-boilerplate#3350]
I want to start a Web Worker in the renderer process, but nothing happens

`in renderer process`
```
const worker = new Worker('BacktestRunnerWorker.js', {
  type: 'module',
});

worker.addEventListener('message', (e) => {
  console.log(e.data);
});

worker.postMessage('run');
```

`BacktestRunnerWorker.ts`
```
window.addEventListener('message', (e) => {
  postMessage(`BacktestRunnerWorker : message received ${e.data}`);

  if (e.data === 'run') {
    console.log("do something");
  }
});
```
I placed `BacktestRunnerWorker.ts` in the `assets` folder, so it can be fetched.

Also [Webpack documentation](https://webpack.js.org/guides/web-workers/) says `const worker = new Worker(new URL('./deep-thought.js', import.meta.url));`
But unfortunately, `import.meta.url` is not available when `tsconfig.compilerOptions.module === commonjs`

**Comment by softmarshmallow** [comment]
Webworker has no relations to electron. It runs on the web thread, can be used on browsers

**Comment by Wxh16144** [comment]
I'm having this problem too and it's very frustrating.
