### ISSUE TITLE
React Router Dom doesnt work with new windows

### ISSUE THREAD

**Issue by ezequiellopez-methodo** [electron-react-boilerplate/electron-react-boilerplate#3352]
Hello Community! I have a question, how can i open multiple windows in electron using react router dom? I tried follow the issue #3248 but, it doesnt work for my project.

The problem is when i try open a new window with the new screen, the new window show's the same initial view. 

Code

**main.ts**
 
      ipcMain.on('myIpc', async () => {
    const RESOURCES_PATH = app.isPackaged
      ? path.join(process.resourcesPath, 'assets')
      : path.join(__dirname, '../../assets');
    const getAssetPath = (...paths: string[]): string =>
      path.join(RESOURCES_PATH, ...paths);
    const customWindow = new BrowserWindow({
      show: false,
      minWidth: 1366,
      minHeight: 728,
      icon: getAssetPath('icon.png'),
      webPreferences: {
        devTools: true,
        nodeIntegration: true,
        preload: app.isPackaged
          ? path.join(__dirname, 'preload.js')
          : path.join(__dirname, '../../.erb/dll/preload.js'),
      },
    });
    customWindow.loadURL(resolveHtmlPath('index.html/board'));
    customWindow.show();
  });
  
**The button that open the new window**

    <CardActions>
         <Button
              onClick={() => window.custom.ipc2.sendMessage('myIpc', ['openWindow'])} >
               Open window
             </Button>
             </CardActions>
**App.tsx with router**

        export default function App() {
          return (
            <Router>
              <Routes>
               <Route path="/" element={<KitchenDisplaySystem />} />
                <Route path="/admin" element={<AdminView />} />
            </Routes>
          </Router>
         );
         }
        
**The new window**
![image](https://user-images.githubusercontent.com/114420500/199555201-d4d89484-2dcb-46a2-ab0e-df7e4e6e70de.png)

**Devtools console**
![image](https://user-images.githubusercontent.com/114420500/199554349-77cefa40-9d8f-45c3-b9c1-375a2e992510.png)

**VsCode console**

![image](https://user-images.githubusercontent.com/114420500/199555120-fc093a11-463d-42ba-950d-70f7771e11fe.png)

**Comment by alielmajdaoui** [comment]
Maybe try to follow this guide I made for multiple windows

https://medium.com/@alielmajdaoui/multiple-windows-in-electron-react-boilerplate-c6d763f38306

**Comment by amilajack** [comment]
unable to repro, please comment if you're still running into this
