### ISSUE TITLE
Can't import modules from release/app package.json

### ISSUE THREAD

**Issue by dimmil123** [electron-react-boilerplate/electron-react-boilerplate#3354]
All of my packages were initially in the root package.json, and things were working fine when I did `npm run start`. However, when I deleted my node_modules folder and tried to `npm install`, I got an error during `postinstall` that some of my packages are native dependencies and should be installed inside of the "./release/app" folder:

```
> postinstall
> ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts


 Webpack does not work with native dependencies.
ethers, keccak, secp256k1 are native dependencies and should be installed inside of the "./release/app" folder.
 First, uninstall the packages from "./package.json":
npm uninstall your-package
 Then, instead of installing the package to the root "./package.json":
npm install your-package
 Install the package to "./release/app/package.json"
cd ./release/app && npm install your-package
 Read more about native dependencies at:
https://electron-react-boilerplate.js.org/docs/adding-dependencies/#module-structure

npm ERR! code 1
npm ERR! path D:\Projects\myproject
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ts-node .erb/scripts/check-native-dep.js && electron-builder install-app-deps && cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.ts
```

When I uninstalled the packages and re-installed them in the release/app package.json, functions that required the moved packages did not work anymore. 

I tried deleting all node_modules folders and running `npm install` in both the root and ./release/app directories and then `npm run rebuild`, but it did not fix anything. The imported packages are still `undefined`.

**Comment by angelinimattia** [comment]
Usually, packages installed in ./release/app are used from the main applications.
I do not know your experience with electrons but in electron, you have the main that talks with the os and the web renderer(chromium).
For security reasons by default native packages are usable only in the main, if you want them in the render you have to use electron IPC (secure but tedious) or enable the native packages on the browser (less secure but easier).
In this topic, they talk about how to enable native modules on the renderer.

https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3340

**Comment by dimmil123** [comment]
> Usually, packages installed in ./release/app are used from the main applications. I do not know your experience with electrons but in electron, you have the main that talks with the os and the web renderer(chromium). For security reasons by default native packages are usable only in the main, if you want them in the render you have to use electron IPC (secure but tedious) or enable the native packages on the browser (less secure but easier). In this topic, they talk about how to enable native modules on the renderer.
> 
> #3340

Tried to enable the native modules on renderer but getting a new error related to it
```
PS D:\Projects\myproject> npm run start

> start
> ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer


> start:renderer
> cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts

[webpack-cli] Failed to load 'D:\Projects\myproject\.erb\configs\webpack.config.renderer.dev.ts' config
[webpack-cli] Error: Cannot find module 'ethers'
Require stack:
- D:\Projects\myproject\.erb\configs\webpack.config.base.ts        
- D:\Projects\myproject\.erb\configs\webpack.config.renderer.dev.ts
- D:\Projects\myproject\node_modules\webpack-cli\lib\webpack-cli.js
- D:\Projects\myproject\node_modules\webpack-cli\lib\bootstrap.js
- D:\Projects\myproject\node_modules\webpack-cli\bin\cli.js
- D:\Projects\myproject\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (D:\Projects\myproject\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (D:\Projects\myproject\.erb\configs\webpack.config.base.ts:49:23)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module.m._compile (D:\Projects\myproject\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .ts] (D:\Projects\myproject\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\myproject\\.erb\\configs\\webpack.config.base.ts',
    'D:\\Projects\\myproject\\.erb\\configs\\webpack.config.renderer.dev.ts',
    'D:\\Projects\\myproject\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'D:\\Projects\\myproject\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'D:\\Projects\\myproject\\node_modules\\webpack-cli\\bin\\cli.js',
    'D:\\Projects\\myproject\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
```

Here's my resolve object in webpack.config.base.ts:
```
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
    modules: [webpackPaths.srcPath, 'node_modules'],
    fallback: {
      ethers: require.resolve('ethers'),
      keccak: require.resolve('keccak'),
      secp256k1: require.resolve('secp256k1'),
    },
  },
```

My main package.json doesn't have the native modules anymore, they've been moved to the release/app package.json:
```
{
  "name": "myproject",
  "version": "1.0.0",
  "license": "MIT",
  "main": "./dist/main/main.js",
  "scripts": {
    "rebuild": "node -r ts-node/register ../../.erb/scripts/electron-rebuild.js",
    "postinstall": "npm run rebuild && npm run link-modules",
    "link-modules": "node -r ts-node/register ../../.erb/scripts/link-modules.ts"
  },
  "dependencies": {
    "ethers": "^5.7.2",
    "keccak": "^3.0.2",
    "secp256k1": "^4.0.3"
  },
  "devDependencies": {
    "@types/keccak": "^3.0.1",
    "@types/secp256k1": "^4.0.3"
  }
}
```

Not sure why the module can't be found. I tried `import { ethers } from 'ethers'` at the top of the webpack.config.base.ts file which doesn't work.

**Comment by colining** [comment]
same issue

although tags in browser window
···js
      nodeIntegration: true,
      contextIsolation: false,
···

it seem renderer /main process have diff env

main process __dirname is folder of project 
renderer process __dirname is folder of project folder \node_moduel\electron\asar

**Comment by amilajack** [comment]
I'm assuming this has been resolved by now. If it isn't, please comment and I'll reopen

**Comment by SantoshKumarRavi** [comment]
I tried  ipc solution for electron 22 and 23. it shows poly fill err for fs and path .and I am able to pass data and string only though IPC. can any one knw how to pass module from main to render

**Comment by glenne** [comment]
I was able to solve this by importing the native module into the top level package.json as a dev dependency.  This gives access to any available type information for import type checking but doesn't get the package involved in the build output except from release/app.
