### ISSUE TITLE
Tailwind: Not rewriting GET /index.html because the path includes a dot (.) character.

### ISSUE THREAD

**Issue by angel-luis** [electron-react-boilerplate/electron-react-boilerplate#3358]
I've cloned the boilerplate and followed this instructions: https://electron-react-boilerplate.js.org/docs/styling#custom-tailwind-config

I' reviewed every line of code 3 times, is exactly as the docs.

But when I do `npm start` I get the following error:

`Not rewriting GET /index.html because the path includes a dot (.) character.`

This happens when I put this on `webpack.config.renderer.dev.ts`:
```
{
        test: /\.s?css$/,
        use: [
          "style-loader",
          "css-loader",
          "sass-loader",
          {
            loader: "postcss-loader",
            options: {
              postcssOptions: {
                plugins: [require("tailwindcss"), require("autoprefixer")],
              },
            },
          },
        ],
        exclude: /\.module\.s?(c|a)ss$/,
      },
```

Also I've tried the **Without Custom Tailwind Config but Tailwind** doesn't loads.

Can anyone share a recent boilerplate with tailwindcss installed? Thank you.

**Comment by mlynch** [comment]
The solution for me was to remove this set of lines, otherwise even with the correct postcss-loader section I would get this error:

<img width="503" alt="image" src="https://github.com/user-attachments/assets/c54e62dc-0a7d-4bed-9faf-07cddd322636">
