### ISSUE TITLE
CDN workaround

### ISSUE THREAD

**Issue by angelinimattia** [electron-react-boilerplate/electron-react-boilerplate#3360]
Hi all, I'm trying to implement HLS streaming in my application, I'm using  "react-player": "^2.10.1" that expects to have the script  https://cdn.jsdelivr.net/npm/hls.js@1.0.9/dist/hls.min.js loaded in the browser object, the script should add the HLS object to the window. However, seem like with the current boilerplate the CDN is blocked so I'm trying to find a solution.

In detail I'm looking for one of the following options:
1. a solid solution that load the HLS script as a dependency: I tried to load the HLS npm package but nothing.
2. a way to manually add the script to the renderer.
3. a workaround that enables me to enable CDN scripts.

## Electron stuff:
    "electron": "19",
    "electron-builder": "^23.3.3",
    "electron-devtools-installer": "^3.2.0",
    "electron-notarize": "^1.2.1",
    "electron-rebuild": "^3.2.9",
    "electronmon": "^2.0.2",

**Comment by rnwelsh** [comment]
The problem is the  content-security-policy, it is set in src/renderer/index.ejs.  ERB sets it to be completely isolated to start with for security. You'll  need to update that for the source of your  videos as well
