### ISSUE TITLE
Many issues with eslint running "npm install" - How come?

### ISSUE THREAD

**Issue by stephyswe** [electron-react-boilerplate/electron-react-boilerplate#3363]
## Summary

I get Many issues with eslint running "npm install" - How come?
![image](https://user-images.githubusercontent.com/20955623/203263656-f46ee7e0-eecd-42f9-ae33-639557fdc568.png)

Also when starting 2 errors.

![image](https://user-images.githubusercontent.com/20955623/203264097-c0ba56d3-2870-4874-bf08-83a21796be2c.png)

**Comment by rnwelsh** [comment]
When installing, other dependencies are specifying an an older version of eslint than this package uses. These warnings are safe to ignore, it's just npm being quite verbose.

The runtime errors have to do with react devtools, there are unresolved issues with that extension (it's a chrome extension) so there's not much we can do about it here. I haven't had any problems with it other than the annoying errors every time I start the dev server.

**Comment by Apollinaire** [comment]
>  I haven't had any problems with it other than the annoying errors every time I start the dev server.

@rnwelsh Does the react-dev-tools extension work ? I just started on a fresh install and the "components" tab only says "Loading React Element Tree..."

**Comment by rnwelsh** [comment]
> > I haven't had any problems with it other than the annoying errors every time I start the dev server.
> 
> @rnwelsh Does the react-dev-tools extension work ? I just started on a fresh install and the "components" tab only says "Loading React Element Tree..."

Yeah, react-dev-tools worked ok. I ended up trying to build react-dev-tools from the latest source, which incorporated the manifest v3, but I could not get that to work at all. I just ended up removing react-dev-tools since I never actually end up using it. I'm sure it would be very helpful, I just always forget about it honestly

**Comment by PaulSzymanski** [comment]
https://github.com/electron-react-boilerplate/eslint-config-erb/issues/138

**Comment by amilajack** [comment]
I've just cut a new release for eslint-config-erb. this should be fixed
