### ISSUE TITLE
can not install ffi-napi in project

### ISSUE THREAD

**Issue by lfan3** [electron-react-boilerplate/electron-react-boilerplate#3364]
## summery
I try to install ffi-napi in the project. 
my node version is 16.13.0
and my IOS version is: 11.5.1
I use yarn add ffi-napi inside the release/app folder.
when I used yarn start to start the project: it show belowing error:
Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=107 uv=1 armv=8 libc=glibc node=16.15.0 electron=20.3.5
anyone has any idea how to solve this problem?

**Comment by amilajack** [comment]
unable to repro, please comment if you're still running into this
