### ISSUE TITLE
Use with yarn instead of npm

### ISSUE THREAD

**Issue by himat** [electron-react-boilerplate/electron-react-boilerplate#3367]
## Summary

Is there a reason why the repo switched to using npm when it originally used yarn?
I prefer using yarn so I'll be switching things to use yarn for myself, but I'm just curious if there was a real reason for the switch?

I see [here](https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2953) that one reason was that yarn still has bugs. But which bugs? npm has bugs as well right.

**Comment by JayyWalker** [comment]
> requiring yarn creates a barrier to entry for the boilerplate

If the aim of this project is to reach as wide an audience as possible and make building with Electron less hassle, moving to npm makes sense. It's the standard, and there's no hassle surrounding the different versions of yarn. For those who prefer yarn, like you and myself, it's easy enough to migrate over.
