### ISSUE TITLE
Github Actions Test fails

### ISSUE THREAD

**Issue by MarkRabey** [electron-react-boilerplate/electron-react-boilerplate#3372]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior
On a new project setup following the instructions in the README, all GitHub Actions should be successful.

## Current Behavior
All Test actions fail.
- `test (macos-latest)` and `test (windows-latest)` both fail with the message: `Error: The operation was canceled.` and no additional information.
- `test (ubuntu-latest)` fails with the message: `Error: node_modules/@types/node/globals.d.ts(72,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.`

## Steps to Reproduce

1. Follow installation instructions in README

2. Push the code to a new GitHub repository

## Your Environment

- Node version :
- electron-react-boilerplate version or branch :
- Operating System and version :
- Link to your project :

**Comment by amilajack** [comment]
unable to repro, please comment if you're still running into this
