### ISSUE TITLE
How to load .js scripts dynamically in ERB?

### ISSUE THREAD

**Issue by lucasrabiec** [electron-react-boilerplate/electron-react-boilerplate#3373]
## Summary

_Entire issue occurs on packed app (dev works)_

I'm working on an application that will provide the possibility to load and run a chosen script from the application's resources. I will use some of the chosen script's data to generate a form on the app's UI, etc. (It's some kind of a template).
> Please have in mind that I also want (in the future) to allow the user to import his own .js file which will be located anywhere on the user's disk e.g. from Documents.

I added `extra-data` dir with content at the root of the repo and add it to the `extraResources` in electron-builder. I also added some code that handles importing.
<img width="1421" alt="CleanShot 2022-12-09 at 17 39 55@2x" src="https://user-images.githubusercontent.com/9741188/206749758-15db9b46-e6cd-467b-ad8a-0b39c3335625.png">

Then I faced an error that said: `cannot find module /Applications/ElectronReact.app/Contents/Resources/extra-data/example-script.js`

I read the webpack is unable to handle a fully dynamic path (from variable): [more info here](https://webpack.js.org/api/module-methods/#:~:text=it%20is%20not%20possible%20to%20use%20a%20fully%20dynamic%20import%20statement%2C%20such%20as%20import(foo).%20because%20foo%20could%20potentially%20be%20any%20path%20to%20any%20file%20in%20your%20system%20or%20project.)
So I added `/* webpackIgnore: true */` and now it imports the script but there is another error which says it can't find the module which script uses

![CleanShot 2022-12-09 at 17 38 06@2x](https://user-images.githubusercontent.com/9741188/206749654-8b8fc2d4-4f6c-43cf-93c4-8c7d87bc0442.png)

My question: is there any possibility to allow the script to use packages from .asar (top level package.json's dependencies)? Maybe there is another way to do the whole thing?

Here is a branch with an example: [repro](https://github.com/lucasrabiec/electron-react-boilerplate/tree/erb/dynamic-import)

**Comment by amilajack** [comment]
see https://electron-react-boilerplate.js.org/docs/adding-assets#run-time-assets
