### ISSUE TITLE
Unable to npm install on Apple Silicon (M1 Max)

### ISSUE THREAD

**Issue by NRKirby** [electron-react-boilerplate/electron-react-boilerplate#3377]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

dependencies should install 

## Current Behavior

`npm install` fails with the following error on my M1 Max Monterey 12.5.1 (21G83) machine

```bash
$ npm install
npm WARN deprecated @types/terser-webpack-plugin@5.2.0: This is a stub types definition. terser-webpack-plugin provides its own type definitions, so you do not need this installed.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm ERR! code 1
npm ERR! path /Users/nick.kirby/nick/code/ecosunpi-desktop-client/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! RequestError: socket hang up
npm ERR!     at ClientRequest.<anonymous> (/Users/nick.kirby/nick/code/ecosunpi-desktop-client/node_modules/got/source/request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:640:26)
npm ERR!     at ClientRequest.emit (node:events:532:35)
npm ERR!     at ClientRequest.origin.emit (/Users/nick.kirby/nick/code/ecosunpi-desktop-client/node_modules/@szmarczak/http-timer/source/index.js:37:11)
npm ERR!     at TLSSocket.socketOnEnd (node:_http_client:466:9)
npm ERR!     at TLSSocket.emit (node:events:532:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1346:12)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nick.kirby/.npm/_logs/2022-12-16T12_25_41_170Z-debug-0.log
```

debug log can be found [here](https://gist.github.com/NRKirby/e6d973ad1d947963ed85b8bc44c2d237)

## Steps to Reproduce

1. clone repo

2. run `npm install`

## Context

I am trying to run a freshly cloned version from this repo

## Your Environment

- Node version :v16.14.0
- electron-react-boilerplate version or branch : main
- Operating System and version :  Monterey 12.5.1 (21G83) 
- Link to your project : this repo (2022-12-16)

**Comment by NRKirby** [comment]
This looked to be some kind of permissions issue on my machine around `node_modules`. I created the dir myself and everything installed fine.

Apologies if I wasted anyone's time with this

**Comment by muiux** [comment]
@NRKirby 
I am facing the same issue, What permissions did you change?
