### ISSUE TITLE
Using HTML file to call python script via pthon-shell library

### ISSUE THREAD

**Issue by alexandru-birtoiu** [electron-react-boilerplate/electron-react-boilerplate#3381]
## Summary

I am trying to create a new hidden renderer process that will be used as a way to process some data via a python script, which will return the result to the main process and after to the renderer React process. I have tried countless ways of making the python-shell package work in the html script, such as using import instead of require and even calling the script directly inside the react application. I have errors in all of the ways that I have tried. This is the `background.html` file that I am trying to use:

```
<script type="module">
  const {PythonShell} = require("python-shell")
  // when hidden renderer has been initialized properly, start function that will start python script
  window.electron.ipcRenderer.on("START_PROCESSING", (event, args) => {
    let pyshell = new PythonShell(path.join(__dirname, '../scripts/double.py'), {
      pythonPath: 'python3',
      args: [args.number]
    });

    // if python scripts sends back a good response
    pyshell.on('message', function(results) {
      window.electron.ipcRenderer.sendMessage('MESSAGE_FROM_BACKGROUND',[{ message: results }]);
    });
  });
  // tell main process that this hidden process is ready to work
  window.electron.ipcRenderer.sendMessage('BACKGROUND_READY', []);
</script>
```

And this is how I am creating the hidden window inside the main electron process:

```
ipcMain.on('START_BACKGROUND_VIA_MAIN', async (event, arg) => {
  const backgroundFileUrl = url.format({
    pathname: path.join(
      __dirname,
      `../background_tasks/background.html`
    ),
    protocol: 'file:',
    slashes: true,
  });
  hiddenWindow = new BrowserWindow({
    show: true,
    webPreferences: {
      nodeIntegration: true,
      preload: app.isPackaged
        ? path.join(__dirname, 'preload.js')
        : path.join(__dirname, '../../.erb/dll/preload.js'),
    },
  });

  hiddenWindow.loadURL(backgroundFileUrl);

  hiddenWindow.webContents.openDevTools();

  hiddenWindow.on('closed', () => {
    hiddenWindow = null;
  });
});
```

The error that I am getting is that require is not a function. However I have tried importing it using `import {PythonShell} from 'python-shell`, and setting the script type to 'module', and it gave me other errors regarding how ts-node compiles the modules. I can give more exact errors if needed, but I want to see what options you think would be viable.

Are there any other solutions I could try? I have thought about calling the python-shell directly from the main electron process with Promises etc. Would that work? Will it impact performance in any way in the main process?
I am open to any other ideas that could work. I think the main problem is how webpack transpiles the modules, however I do not have enough experience with it to solve it.

**Comment by amilajack** [comment]
I'm assuming this has been resolved by now. If it isn't, please comment and I'll reopen

**Comment by abhi-arya1** [comment]
@alexandru-birtoiu What ended up being the solution? I'm running into a similar issue myself but want to execute python within the JavaScript files.
