### ISSUE TITLE
how to use .well-known ? 

### ISSUE THREAD

**Issue by theyameen** [electron-react-boilerplate/electron-react-boilerplate#3388]
## Summary

I am using .well-known 

<link rel="assetlinks.json file" href="%PUBLIC_URL%/.well-known/assetlinks.json" />
<link rel="apple-app-site-association file" href="%PUBLIC_URL%/.well-known/apple-app-site-association" />
but after the npm run package does not show the folder and does not work

**Comment by amilajack** [comment]
please clarify your question
