### ISSUE TITLE
WebSerial API not working

### ISSUE THREAD

**Issue by siriwatknp** [electron-react-boilerplate/electron-react-boilerplate#3389]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

I followed the instruction for [WebSerial API](https://www.electronjs.org/docs/latest/tutorial/devices#web-serial-api), but always got errors in the renderer.

The callback in the `main` should be called.

**main.js**:
```js
mainWindow.webContents.session.on(
    'select-serial-port',
    (event, portList, webContents, callback) => {
      console.log(portList); // list of ports     
      ...the code in the official doc
    }
  );
```

## Current Behavior

The callback in the `main` is not called.

**main.js**:
```js
mainWindow.webContents.session.on(
    'select-serial-port',
    (event, portList, webContents, callback) => {
      console.log(portList); // No log called in the terminal
     
      ...the code in the official doc
    }
  );
```

## Steps to Reproduce

**Repo**: https://github.com/siriwatknp/electron-react-boilerplate-webserial

I believe that this is not a bug in electron but the boilerplate because I tried the same version with plain electron `20.0.2` and it works fine. See the [comparison](https://github.com/siriwatknp/electron-react-boilerplate-webserial/compare/main...plain-electron) (using plain script works fine).

1. Follow Electron React Boilerplate [installation](https://electron-react-boilerplate.js.org/docs/installation)

2. Add the code from [Electron WebSerial doc](https://www.electronjs.org/docs/latest/tutorial/devices#web-serial-api)

3. Connect a USB or a serial port to the computer

4. Add a console.log inside the callback of `mainWindow.webContents.session.on('select-serial-port', () => ...)`, the log should show

## Your Environment

- Node version :
- electron-react-boilerplate version or branch : `main`
- Operating System and version :
- Link to your project :

**Comment by amilajack** [comment]
it seems like loading a file instead of a url fixes it
