### ISSUE TITLE
npm update doesn't work

### ISSUE THREAD

**Issue by bystepii** [electron-react-boilerplate/electron-react-boilerplate#3396]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

`npm update` should work.

## Current Behavior

```
15:38 $ npm update
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from eslint-config-erb@4.0.4
npm ERR! node_modules/eslint-config-erb
npm ERR!   dev eslint-config-erb@"^4.0.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/stepii/.npm/_logs/2023-01-07T14_38_42_087Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/stepii/.npm/_logs/2023-01-07T14_38_42_087Z-debug-0.log
```

## Steps to Reproduce

1. `git clone --depth 1 --branch main https://github.com/electron-react-boilerplate/electron-react-boilerplate.git your-project-name &&
cd your-project-name &&
npm install`

2. `npm update`

## Your Environment

- Node version : v19.3.0
- npm version : 9.2.0
- electron-react-boilerplate version or branch : main
- Operating System and version : Ubuntu 22.04.1 LTS
- Link to your project :

**Comment by phyzixmusic** [comment]
Maybe try this

`npm i -g npm-check-updates
ncu -u
npm install`

**Comment by bystepii** [comment]
@phyzixmusic npm throws exactly the same error. I think it has something to do with [eslint-config-erb](https://github.com/electron-react-boilerplate/eslint-config-erb/blob/master/packages/eslint-config-erb/package.json#L39).

**Comment by mthorzen** [comment]
I am having the same issue, seems like eslint-config-erb needs an update.

**Comment by neth392** [comment]
same issue here

**Comment by MrTeferi** [comment]
Same issue here, tried @phyzixmusic solution and still failed.

**Comment by amilajack** [comment]
working on this right now

**Comment by amilajack** [comment]
fixed in https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3412
