### ISSUE TITLE
Jest runs tests in .erb/dll

### ISSUE THREAD

**Issue by aolsenjazz** [electron-react-boilerplate/electron-react-boilerplate#3400]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Jest runs all tests in src/\__tests__ and no others

## Current Behavior

Jest also runs all tsc-compiled tests in the .erb/dll directory

## Steps to Reproduce

1. clone, install, build, etc

2. npm exec tsc

3. npm run test

## Possible Solution (Not obligatory)

add .erb/dll to testPathIgnorePatterns in package.json. Will open a pr

## Context

This causes the test job in CI to fail if using relative paths within tests. Also probably just doesn't make sense to run all tests twice

## Your Environment

CI macosx latest

- Node version : 16
- electron-react-boilerplate version or branch : 19
- Operating System and version : macosx latest
- Link to your project : https://github.com/aolsenjazz/super-controller

**Comment by aolsenjazz** [comment]
pr #3401 added

**Comment by amilajack** [comment]
Merged!

**Comment by aolsenjazz** [comment]
thanks for all the work you do!
