### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sheril04** [electron-react-boilerplate/electron-react-boilerplate#3481]
## Summary

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\Sheril\git\node_modules\random\dist\random.module.js from C:\Users\Sheril\git\index.js not supported.
Instead change the require of random.module.js in C:\Users\Sheril\git\index.js to a dynamic import() which is available in all CommonJS modules.

**Comment by sheril04** [comment]
What to do in thisn

**Comment by sheril04** [comment]
![image](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/80672721/0256ec4d-ce59-4598-a015-9bb0b8000c12)

**Comment by amilajack** [comment]
ERB doesn't support native modules yet
