### ISSUE TITLE
Antivirus software blocking

### ISSUE THREAD

**Issue by xuffang** [electron-react-boilerplate/electron-react-boilerplate#3484]
![image](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/44192866/e972a4f4-8861-4213-a53d-ad6fab5c6c0c)

A virus prompt appears after Windows scans the exe file in the installation directory，the website is https://www.virustotal.com/

Is there a solution to avoid？？？ tks~

**Comment by amilajack** [comment]
#306
