### ISSUE TITLE
Illegal characters in path

### ISSUE THREAD

**Issue by rendomnet** [electron-react-boilerplate/electron-react-boilerplate#3501]
## Prerequisites

- [x] Using npm
- [x] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [x] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [x] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [x] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

succesfull build

## Current Behavior

1] [webpack-cli] Failed to load 'C:\dev\ultimate\newelectron\.erb\configs\webpack.config.renderer.prod.ts' config
[1] [webpack-cli] Error: Illegal characters in path.

## Steps to Reproduce

1. pnpm build

2. error

3.

4.

## Your Environment

- Node version : v18.16.0
- electron-react-boilerplate version or branch :latest
- Operating System and version : win 11
- Link to your project :

**Comment by codingedgar** [comment]
@rendomnet  Did you ever make it work?
