### ISSUE TITLE
What's the difference between build and package?

### ISSUE THREAD

**Issue by rohitkrishna094** [electron-react-boilerplate/electron-react-boilerplate#3506]
## Summary
What's the difference between `npm run build` and `npm run package`? Both are used for production right? so what's the difference then?

**Comment by shahul01** [comment]
maybe build is for react and package is for electron and after react is built

**Comment by lacymorrow** [comment]
@rohitkrishna094 @shahul01 A `build` compiles all of the JS/TS and Electron files required for a production build into a single directory with all and only the build assets, ready to be packaged into an ASAR archive.

`package` generates a system-specific runtime that allows users to install the app natively.

**Comment by rohitkrishna094** [comment]
Thanks that makes sense.
