### ISSUE TITLE
App not launching after packaging and installing 

### ISSUE THREAD

**Issue by salimdriai** [electron-react-boilerplate/electron-react-boilerplate#3517]
## Summary
I created an application and it works super fine in dev mode, but after packaging ( with `npm run package` ) and installing the app from the `ElectronReact Setup 4.6.0` in the `build` directory , i tried to launch the app but the window did not even appear, and in the windows task manager, i see 3 instances running . 

did i made something wrong while packaging and installing the app ? 
how can i get my app works after installation ?  

the build directory

![image](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/67127725/3e16ddc7-5b2b-4ebf-8762-29a99e0207b4)

in the task manager 

![image](https://github.com/electron-react-boilerplate/electron-react-boilerplate/assets/67127725/23cd59ac-88ad-4862-9a5d-2a8564121daa)

**Comment by Taha-daboussi** [comment]
Hello @salimdriai  Hope you found the solution 
and if you can share it please

**Comment by Taha-daboussi** [comment]
I get the same behavior on mac , 
am not sure if the solution is the same , 
but can you please share yours

**Comment by salimdriai** [comment]
Hi @Taha-daboussi , for me the problem was in the db file path, were the generated path in production was different from the dev mode path. Anyway, to log the problem you have you should launch the app from the terminal by navigating to the executable (dmg i guess in your case) file in your build and launch it . 
I hope this helps .
