### ISSUE TITLE
Does Electron and the boilerplate work on WSL environments?

### ISSUE THREAD

**Issue by parisosuch-dev** [electron-react-boilerplate/electron-react-boilerplate#3548]
## Summary

I was trying to run this in a WSL environment on windows (using Debian). Could not get it to work after installing the dependencies. 

Ran into this error:

```
/home/user/test/electron-react/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
[electronmon] app exited with code 127, waiting for change to restart it
[electronmon] waiting for a change to restart it
```

**Comment by DaviRJ** [comment]
Same here. WSL2 Ubuntu on Windows 11

**Comment by parisosuch-dev** [comment]
> Same here. WSL2 Ubuntu on Windows 11

it seems as if we are probably not going to get an answer to the issue here. Seeing too many issues that are aged quite a ways out. So far have not been able to get it working on WSL2 Debian or Ubuntu. You (@DaviRJ ) can however, get it working on regular windows. Sucks you can't develop in a WSL env though. I do recommend downloading GitBash for Windows if you do want Linux commands with a Windows binary. Good luck 🖖🏼
