### ISSUE TITLE
Build Electron-React-Boilerplate With Tailwindcss

### ISSUE THREAD

**Issue by SattyaP** [electron-react-boilerplate/electron-react-boilerplate#3590]
## Summary

Hello I am a new person using electron-react-boilerplate, I have a question when I want to build / package my project that includes tailwind postcss prefix etc, when the build is complete and I install the build results why does my app look like it doesn't use tailwindcss?

**Comment by ufilme** [comment]
How did you fix this? I get the same problem

**Comment by SattyaP** [comment]
> How did you fix this? I get the same problem

Integrate tailwindcss : https://github.com/amilajack/erb-tailwind-example
Original : https://electron-react-boilerplate.js.org/docs/installation

I use the electron boilerplate from this guy but in the original version, you can use that repository to get parts related to tailwindcss

**Why don't I just use the one that has been integrated with tailwind??** 

Because there are repo issues that cannot be used, from my experience you can check the issues yourself on the repository that has been integrated with Tailwind

But don't worry, you can still take parts related to tailwind

Clues 
.erb folder,
postfix.css,
tailwind config,
and some configuration on folder configs that includes with file name "webpack"

you just need to match it with the repo
