### ISSUE TITLE
Relaunch Electron App

### ISSUE THREAD

**Issue by SattyaP** [electron-react-boilerplate/electron-react-boilerplate#3591]
## Summary

How do we relaunch the app ? why it error on my code

`function appExit() {
  app.relaunch();
  app.exit();
}`

**Comment by dowmeister** [comment]
try

```
 app.relaunch();
app.quit();
          ```

**Comment by SattyaP** [comment]
> try
> 
> ```
> app.relaunch();
> app.quit();
> ```

thanks for the answer, I'll try it later, because I think I've already done that
