### ISSUE TITLE
Notarize question after commit

### ISSUE THREAD

**Issue by TrofinSorin** [electron-react-boilerplate/electron-react-boilerplate#3637]
Hello i've seen that  "afterSign": ".erb/scripts/notarize.js" has been removed and replaced with this:
   
   "mac": {
      "sign": ".erb/scripts/notarize.js",
      "notarize": false

Why? In this case I can't notarize anymore, if notarize is false it won't work, if notarize is true it will say it's not signed yet. @amilajack

**Comment by amilajack** [comment]
The afterSign script notarizes so it's not necessary

**Comment by TrofinSorin** [comment]
And if we want to notarize we need to bring back afterSign? @amilajack
