### ISSUE TITLE
PR: Migration from counter to todo list app

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#447]
I think this would be a good idea because its a pretty canonical way of getting developers to understand a stack. It demonstrates CRUD (create, read, update, delete) operations, which are essential to any kind of development.

Thoughts?

**Comment by jefffriesen** [comment]
I was pretty happy to see this repo not have the todo list app when I first came across it. Just minimal logic. Seems like the canonical todo list app is good if you're coming from another framework like Angular, Ember or Backbone and want to understand React and Redux. But IMHO this repo shouldn't be about teaching react and redux. It should be about getting all of the Electron + React + Webpack config taken care of (and through that teaching about those technologies). 

This is just my take on it. I rip out all of the redux stuff and use Mobx anyway, so maybe a more complex redux structure could be useful for people who are building redux apps. 

Btw @amilajack thanks for nurturing this project along so well.

**Comment by amilajack** [comment]
Thanks for the feedback. The motivation for this issue came from https://github.com/chentsulin/electron-react-boilerplate/issues/132. But I can see a lot of value in having just a minimal example.

**Comment by jefffriesen** [comment]
Interesting. I didn't see that comment before. Maybe documentation on what each webpack and electron config does would be cool. It's work but it could help others during refactors or to debug too.   I have set up quite a few webpack configs, and some of it I either don't know what it really does or I've forgotten. Electron is relatively new to me. For that matter, the redux part could be documented too.

We could have an optional script that strips out comments (npm run cleanup).

**Comment by amilajack** [comment]
> Maybe documentation on what each webpack and electron config does would be cool

Definitely agree with this. I'll try to make a PR with explanations some explanations sometime soon.

> We could have an optional script that strips out comments (npm run cleanup).

Yup! Here's the discussion on that: https://github.com/chentsulin/electron-react-boilerplate/pull/402#issuecomment-249093874

**Comment by vinnymac** [comment]
@amilajack I am pro the todo list app. Getting examples on common problems is really useful. I actually felt the example in this project was a bit light, and some things weren't setup out of box that users might expect to be.

**Comment by amilajack** [comment]
@vinnymac I wasnt even aware of that. What are some examples of things that weren't setup?

**Comment by amilajack** [comment]
@chentsulin @jhen0409 Would be great if you guys could weigh in

**Comment by chentsulin** [comment]
We should only care about how to demonstrate building a react app on top of electron, and keep it simple. Webpack configs and builder already so complex to a beginner. We'd not happy to see more issues such like #460, #461 to discuss react or redux stuff. But, if a todo example is helpful than a counter example for a beginner, It is fine with me.

**Comment by amilajack** [comment]
@chentsulin totally agree with keeping complexity to a minimum. Also do you know about the missing features that @vinnymac was talking about?

**Comment by vinnymac** [comment]
I agree, with both of you on simplicity. I like to follow [KISS](https://en.wikipedia.org/wiki/KISS_principle) as much as possible.

@amilajack I think what I was referring to was the usage of certain `stage-0` features. I think this project allows for syntactical sugar such as `async` and `await`. When it comes to the actual electron renderer code I don't think any is in use in the examples. I may have added a line such as `babel-polyfill` in my own projects to get it working. This might be taken care of now in this repo I am unsure. The examples are still lacking in that regard either way.

**Comment by jefffriesen** [comment]
@vinnymac async/await PRs are merged in (both from you and me)
https://github.com/chentsulin/electron-react-boilerplate/pull/378
https://github.com/chentsulin/electron-react-boilerplate/pull/358

It would be nice to show an example in the code. Even if it was something simple like async loading a text file that shows up on the home page (which also shows how to load files).
