### ISSUE TITLE
Question: disable/remove redux?

### ISSUE THREAD

**Issue by nolby** [electron-react-boilerplate/electron-react-boilerplate#745]
Is it possible to use this project without redux? Sorry if this is a simple question - I am inexperienced.

**Comment by amilajack** [comment]
It is possible but unfortunately you will have to strip it out on your own :( I personally think redux is overkill for a boilerplate. @dustintownsend, thoughts on this?

**Comment by movingelectrons** [comment]
https://github.com/removed-redux/electron-react-boilerplate  NOTE: I just forked this today (1/10/19) but I should have redux stripped out by tomorrow or day after.

**Comment by amilajack** [comment]
Awesome. Please PR our examples repo to add this as an example initially. We can experiment there and based on how that goes, we can merge those changes into ERB

**Comment by movingelectrons** [comment]
tried removing redux several times with no success..  I found this however: https://www.npmjs.com/package/electron-react-webpack-boilerplate

**Comment by hamidabdulmalik** [comment]
Anything on this yet people?
