### ISSUE TITLE
Discussion: Complementary Website 

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#800]
react-boilerplate, create-react-app, and other popular bootstrapping/boilerplate projects have websites that describe the features

What are thoughts on making a similar website for this boilerplate?

**Comment by Slapbox** [comment]
I think it's a great idea to make something simple at least, just to pin down the real estate. The site can always be made down the road, or it could be very simple, like simply being the readme.md from Github.

**Comment by shahzeb1** [comment]
I am willing to work on this! 😄

**Comment by amilajack** [comment]
@shahzeb1 I will definitely need some help on this. There's no way I can maintain this boilerplate, the website, and my other projects 😢

**Comment by shahzeb1** [comment]
@amilajack OK so, I have gone ahead and made a [repo](https://github.com/shahzeb1/electron-react-boilerplate-website) with a static website which is built using the [Google Web Starter Kit](https://github.com/google/web-starter-kit). The website is currently being served via Github Pages [over here](https://shahzeb1.github.io/electron-react-boilerplate-website/).

Please use the issue page on that repo to give me feedback / what you would like. That's just the first commit, to get things off the ground. Let me know what you think 😄 !

**Comment by amilajack** [comment]
Actually I was thinking of doing a design for the page first. I'll submit the design here.

**Comment by shahzeb1** [comment]
Awesome. Will keep an eye on it.

**Comment by shahzeb1** [comment]
@amilajack any update on your website requirements my dude?

**Comment by amilajack** [comment]
> my dude

😆 😆 😆 not yet. I'm running short on time this week. I think we should also fork react-boilerplate instead of google web starter kit, which isn't as opinionated.

**Comment by shahzeb1** [comment]
Awesome. Invite accepted.

**Comment by uppe-r** [comment]
Hey @amilajack, mind if I give a try to make a static website for the project? I'm saying this because it seems like this issue kind of died since more than a year ago and I also feel like this would be something awesome to have.

**Comment by amilajack** [comment]
Lets move the discussion there. The site is already in development: [electron-react-boilerplate.js.org](http://electron-react-boilerplate.js.org). Very early stages
