### ISSUE TITLE
IDEA: V8 Snapshot Integration

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/electron-react-boilerplate#932]
Would be nice if we could have support for v8 snapshots out of the box. [Inspired by this](http://blog.atom.io/2017/04/18/improving-startup-time.html?utm_source=nodeweekly&utm_medium=email)

See [this](https://github.com/atom/electron-link)

**Comment by erick2014** [comment]
👍 I've checked the article pretty cool feature to increase the performance
